### ISSUE TITLE
Internal server error (fission)

### ISSUE THREAD

**Issue by jedipunkz** [fission/fission#101]
I got this error "Internal server error (fission)".

I ran these command as follows.

```
docker-machine start default
minikube start
export FISSION_URL=http://$(minikube ip):31313
export FISSION_ROUTER=$(minikube ip):31314
fission env create --name nodejs --image fission/node-env
echo 'module.exports = function(context, callback) { callback(200, "Hello, world!\n"); }' > hello.js
fission function create --name hello --env nodejs --code hello.js
fission route create --method GET --url /hello --function hello
curl http://$FISSION_ROUTER/hello
Internal server error (fission)
```

Any idea?

**Comment by nouney** [comment]
Same here

**Comment by nouney** [comment]
@jedipunkz I finally found the solution. In my case, `echo 'module.exports = function(context, callback) { callback(200, "Hello, world!\n"); }' > hello.js` creates a malformed file. I had to manually write the function. Use `node hello.js` to check the file.

**Comment by Marak** [comment]
Service errors should be piped directly back to the client with an actual
error stack.

Getting back "Internal Server Error" message is unacceptable.

**Comment by soamvasani** [comment]
@jedipunkz Would you mind looking at poolmgr logs (`kubectl --namespace fission get pod poolmgr` to find the poolmgr pod.)?  There was a known issue #89 which you _may_ have hit. Or it could be the same thing that @nouney saw.

So in general, we have work to do in this area. I agree that users shouldn't be seeing hard-to-diagnose "Internal server errors".

#53 (Function logs) is tracking an easier way for users to get logs from functions.

More significantly, the environments v2 work (Documentation/wip/environments-v2.md) is tracking a function "compile"-time check to surface syntax errors while a function is registered, instead of letting syntax errors show up at runtime.

Also I'd like to update the README if these instructions are resulting in a malformed file.

**Comment by soamvasani** [comment]
I should point out that I disagree with @Marak's comment, though -- error stacks usually should _not_ be send to clients, unless it's in some sort of "development mode".  The HTTP error itself is right, in this case.

(The programmer of the function is the one interested in stack traces, not the user of the app the programmer is writing)

**Comment by jaxxstorm** [comment]
So I have this same problem, with a standard deploy. The error looks like like this:

router:
```
172.29.132.132 - - [06/Feb/2017:22:52:32 +0000] "GET /hello HTTP/1.1" 500 32
2017/02/06 22:52:32 Failed to get service for function (hello,7db6697d-8f11-4492-82e5-47c6d237e532): (Error 0) 500 Internal Server Error
2017/02/06 22:53:01 Not cached, getting new service for {hello 7db6697d-8f11-4492-82e5-47c6d237e532}
2017/02/06 22:53:01 Failed to get service for function (hello,7db6697d-8f11-4492-82e5-47c6d237e532): (Error 0) 500 Internal Server Error
172.29.132.132 - - [06/Feb/2017:22:53:01 +0000] "GET /hello HTTP/1.1" 500 32
```

poolmgr:

```
192.168.18.7 - - [06/Feb/2017:22:56:15 +0000] "POST /v1/getServiceForFunction HTTP/1.1" 500 15
2017/02/06 22:56:15 Error: 500: HTTP error 500
2017/02/06 22:57:30 [hello] Checking for cached function service
2017/02/06 22:57:30 [hello] No cached function service found, creating one
2017/02/06 22:57:30 [hello] getting environment for function
2017/02/06 22:57:30 [&{hello 56466500-d705-460e-8786-2d26c9c6a2c6}] getting function from controller
2017/02/06 22:57:30 [&{hello 56466500-d705-460e-8786-2d26c9c6a2c6}] getting env from controller
192.168.18.7 - - [06/Feb/2017:22:57:30 +0000] "POST /v1/getServiceForFunction HTTP/1.1" 500 15
2017/02/06 22:57:30 Error: 500: HTTP error 500
```

**Comment by soamvasani** [comment]
@jaxxstorm what do your function logs say?

```
kubectl --namespace fission-function get pods -l functionName=hello
kubectl --namespace fission-function logs <pod name> [python|nodejs]
```

**Comment by soamvasani** [comment]
Closing this; other bugs are tracking better logging/debuggability.
