### ISSUE TITLE
Precompiled CLI binaries for ARM

### ISSUE THREAD

**Issue by amentis** [fission/fission#1011]
I want to use the fission CLI on my pinebook, but I cannot find binaries precompiled for ARM and I could not find from reading the sourcecode how to compile just the cli.

**Comment by vishal-biyani** [comment]
@amentis For building the CLI you can cd to fission directory ( https://github.com/fission/fission/tree/master/fission) and run `go build` or `go install`. There you can pass parameters for building for ARM. (Like: `env GOOS=android GOARCH=arm64 go build`)
