### ISSUE TITLE
Cannot compile

### ISSUE THREAD

**Issue by amentis** [fission/fission#1016]
I've tried to compile the client for AMD64 and ARM64 both on AMD64 and ARM64 with GO 1.10 and 1.11, always doing glide install then cd fission then go install. Always have the following error:
# github.com/fission/fission/crd
../crd/client.go:70:58: cannot use config (type *"github.com/fission/fission/vendor/k8s.io/client-go/rest".Config) as type *"github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/client-go/rest".Config in argument to clientset.NewForConfig
../crd/crd.go:66:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:82:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:98:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:114:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:130:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:146:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:162:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:178:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:194:14: cannot use "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta literal (type "github.com/fission/fission/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta) as type "github.com/fission/fission/vendor/k8s.io/apiextensions-apiserver/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ObjectMeta in field value
../crd/crd.go:194:14: too many errors

I've tried both on master and v0.12.0 branches. My ultimate goal is to produce an executable for ARM64.

The go env for my latest attempt:
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/lib/go-1.10"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.10/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build789225792=/tmp/go-build -gno-record-gcc-switches"

**Comment by life1347** [comment]
Hi @amentis 
You can solve this by adding an extra flag to glide when installing dependencies.
```
glide install -v
```

**Comment by life1347** [comment]
close this for now. feel free to open it if it still not works.

**Comment by justinbuzzni** [comment]
@life1347  
I tried "glide install -v"
But, there is a  error "panic: runtime error: invalid memory address or nil pointer dereference"


[INFO]  Removing: /home/buzzni/work/src/github.com/fission/fission/vendor/github.com/coreos/etcd/vendor
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x6fdc82]


goroutine 1 [running]:
github.com/Masterminds/glide/path.StripVendor.func1(0xc4200906c0, 0x60, 0x0, 0x0, 0x8f3160, 0xc4205392c0, 0x0, 0x0)
        /home/vagrant/go/src/github.com/Masterminds/glide/path/strip.go:28 +0x42
path/filepath.walk(0xc42083e0c0, 0x55, 0x8fa0e0, 0xc420766410, 0xc4203b08c0, 0x0, 0x0)
        /usr/lib/go-1.10/src/path/filepath/path.go:377 +0x20d
path/filepath.walk(0xc4201e8af0, 0x4e, 0x8fa0e0, 0xc420814410, 0xc4203b08c0, 0x0, 0x0)
        /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc4201e8910, 0x49, 0x8fa0e0, 0xc420814340, 0xc4203b08c0, 0x0, 0x0)
        /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc4201e80a0, 0x42, 0x8fa0e0, 0xc42023e270, 0xc4203b08c0, 0x0, 0x0)
        /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.walk(0xc4202cb500, 0x37, 0x8fa0e0, 0xc420731040, 0xc4203b08c0, 0x0, 0x20)
        /usr/lib/go-1.10/src/path/filepath/path.go:381 +0x2c2
path/filepath.Walk(0xc4202cb500, 0x37, 0xc4203b08c0, 0xc420730f70, 0x0)
        /usr/lib/go-1.10/src/path/filepath/path.go:403 +0x106
github.com/Masterminds/glide/path.StripVendor(0x8b0354, 0x3b)
        /home/vagrant/go/src/github.com/Masterminds/glide/path/strip.go:22 +0x10a
github.com/Masterminds/glide/action.Install(0xc420085480, 0x89bc01)
        /home/vagrant/go/src/github.com/Masterminds/glide/action/install.go:62 +0x35b
main.commands.func12(0xc4200f0b00, 0x0, 0xc4200f0b00)
        /home/vagrant/go/src/github.com/Masterminds/glide/glide.go:510 +0x2bf
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.HandleAction(0x811280, 0x8ba950, 0xc4200f0b00, 0xc420032f00, 0x0)
        /home/vagrant/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:490 +0xc8
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.Command.Run(0x899e45, 0x7, 0x8984a0, 0x1, 0x0, 0x0, 0x0, 0x8a58b2, 0x20, 0x0, ...)
        /home/vagrant/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/command.go:210 +0xa36
github.com/Masterminds/glide/vendor/github.com/codegangsta/cli.(*App).Run(0xc420220000, 0xc42001e090, 0x3, 0x3, 0x0, 0x0)
        /home/vagrant/go/src/github.com/Masterminds/glide/vendor/github.com/codegangsta/cli/app.go:255 +0x6a0
main.main()
        /home/vagrant/go/src/github.com/Masterminds/glide/glide.go:104 +0x5a9
buzzni@IDC-83:~/work/src/github.com/fission/fission$ glide install

**Comment by justinbuzzni** [comment]
@life1347 I resolved the problem.
It's glide problem. ( https://github.com/Masterminds/glide/pull/990 )
When I upgrade glide to 0.13.2, I can compile without problem.
Thank you.

**Comment by life1347** [comment]
@justinbuzzni cool, good to hear that 👍
