### ISSUE TITLE
Configmap at environment level

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1021]
Currently in Fission one can attach the Configmap only to a function. There are scenarios where multiple functions of the same environment need the same configmap. It would be good to add support for configmaps ay environment level.

**Comment by msshroff** [comment]
This is something we are also looking for.

**Comment by paraspatidar** [comment]
Not Exactly like same , but something similar has been achieved like : 
Lets say , function needs some configuration or settings file to read during execution , thus if that is available at sourcepackage.zip then same can be read by function by reading file and serializing the json.

It is available in PR  https://github.com/fission/fission/pull/1001 
for dotnetcore 2.0 environment , but can be referred to achieve it for other environments.

here is exact commit for the same  : https://github.com/fission/fission/pull/1001/commits/c2c44ea2f0ee68b6dbb8fa79dff44d738b437bcc


```
 Source Package zip :
 --soruce.zip
	|--Func.cs
	|--nuget.txt
	|--exclude.txt
	|--mysetting.json
	|--....MiscFiles(optional)
	|--....MiscFiles(optional)
```
here is what *mysetting.json* looks like :
```
				{ 
				"name": "Alpha",
				"sendGridEndPoints": 
					[
						{ "port": 1002 },
						{ "port": 3004 } 
					]
				}
```
Note : This is for /v2/specialized endpoint only.

**Comment by life1347** [comment]
This now can be done with podSpec. Close it.
