### ISSUE TITLE
Ability to Delete the routes /trigger  via function name

### ISSUE THREAD

**Issue by paraspatidar** [fission/fission#1024]
Ability to Delete routes based on function name.

![image](https://user-images.githubusercontent.com/5575617/49989234-976a2900-ff9f-11e8-9f0b-a4455b836548.png)

Many time we want to cleanup the space , and we can iterate through list of function and delete them via some script , but 
for route , we need to delete them by route name which is random guid.
`fission route delete --name <routeguid>`

It will be a good idea to provide ability to delete route based on function name.
something like  : 

`fission route delete --fnname <functionname>`

It can also be used to find the routes associated with any function , like - 

`fission route list --fnname <functionname>`

Same goes for trigger , to be able to delete trigger based on function name.

**Comment by paraspatidar** [comment]
Currently here is how i ma doing with script : 

#cleanup envionrment 
```

$envpods=kubectl get pods -n fission-function
 $childenv=Get-ChildItem $envpods 
 $envpods.Length
 
 for($index=0; $index -lt $envpods.Length;)
    {
       $EnvName=$envpods[$index].Split('-')[0]
       Write-Host($EnvName)
       fission env delete --name $EnvName
        $index= $index+3
    }
	
```

#cleanup function
```
$fn=  fission fn list
  
   for($index=1; $index -lt $fn.Length;)
    {
       $fnline=$fn[$index]
       $fnname=$fnline.Split(' ')
       Write-Host($fnname)
       fission fn delete --name $fnname[0]
       $index++
    }
```

    #cleanup routes

```
$route=   fission route list
  
   for($index=1; $index -lt $route.Length;)
    {
       $rtline=$route[$index]
       $rtname=$rtline.Split(' ')
       Write-Host($rtname)
       fission route delete --name $rtname[0]
       $index++
    }

```

**Comment by swap357** [comment]
### cleanup.sh
> for r in $(fission route list|grep free| awk '{print $1}'); do fission route delete --name $r; done
