### ISSUE TITLE
Environments v2 

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#103]
This is an issue that's tracking the work around redesigning the environment interface.  This covers #24 but also various other issues, such as dependency resolution, better handling of compile-time errors, etc.

Current status: writing up requirements and user stories.  The doc is in Documentation/wip/environments-v2.md.

**Comment by soamvasani** [comment]
@ktrance @dgoujard you might be interested in this issue; I will update it as we progress. If you'd like to add anything to the requirements, from a C# and a PHP point of view, this is a good place to discuss it.

**Comment by ktrance** [comment]
Will do. 
Just looked at the AWS deployment package concept and for dotnet something like this would probably be the easiest to quickly get up and running. The developer is responsible for for packaging every component he needs which we wouldn't have to deal with open ports to get nuget packages etc. 

We could just:
1. dynamically load the main binary either from some specification or we would need  to scan all of them 
2. find a predefined interface/contract which we in essence have today in the dotnet env
3. execute the function

Nice and easy. I would be interested in doing a prototype of this.

**Comment by dgoujard** [comment]
@soamvasani For PHP env ideal workflow will be : 
1. Create a zip with multiples files (php and composer.json if needed) 
2. Function on /specialize phase will install composer.json package
3. Function will include "index.php" file on each request (and call handler if present)

This workflow did not allow to add php extension but it's more common to add package than extension (and i added many extension btw)

**Comment by soamvasani** [comment]
@ktrance So in this design, the user is responsible for doing the builds and creating a zip file, right?  It's a good idea -- it would allow us to get started with compiled language support without solving the bigger problem of builder containers too.  We still need to solve storage for these packages, but I will try to spec something out for that.

**Comment by soamvasani** [comment]
@dgoujard I'm sorry my knowledge of PHP isn't good enough to understand this... what is the difference between a package and an extension?

We're also trying to separate out the install steps from the runtime.  So basically we'd have a separate builder that would install dependencies, create some sort of package -- a zip file for example -- and then have the runtime load that when /specialize is called.

**Comment by dgoujard** [comment]
@soamvasani an extension need a compilation and loading at php startup. An package is just a library like you load in python with package.txt.

In this case the builder pod will download packages (composer.json) and the function pod will just execute code as today

**Comment by ktrance** [comment]
@soamvasani , yes that would be the general idea.

It would of course be a pain to go through if you only want to run a 5 line function but then you could still use the existing solution.

This wouldn't necessarily be the final solution but it would (likely) allow us to going very quickly and get some more experience.

**Comment by soamvasani** [comment]
@dgoujard thanks!  I agree that leaving out extension support is fine.  We can always tell users to rebuild the environment image -- that option will not go away.

> In this case the builder pod will download packages (composer.json) and the function pod will just execute code as today

👍 Makes sense.

**Comment by ktrance** [comment]
@soamvasani @dgoujard 

Ok, I have had the chance to read some code now and have an idea I would like to bounce of you all.

If we for a second says that we will go down the path of introducing a deployment concept which would simply mean that the code for a function isn't always a single text file but can also be a zipped archive of components. 
How these components are interpreted is up to the individual environment, in the case of dotnet it could be like we discussed above a complete package we load and execute dynamically. In java a jar or something similar, in php install composer.php etc.

This could be the first step before tackling a real build component, and in all likelihood a build component would also need the ability to be fed multiple files anyway so..

One way to this would be something along these lines:  

1. add --isdeployment switch to fission/main.go, and if it is set then the --code item should be a compressed archive
2. add IsDeployment bool to Function struct in types.go
3. add extra json property to fetcherRequest poolmgr/gp.go function specializePod line 258,
    the property should be based on IsDeployment from Function. maybe call it unpack.
4. add Unpack bool field to the FetchRequest struct in environments/fetcher/fetcher.go,
    consider renaming FileName to Destination as it will now work with both a file and a unzipped directory
5. add a check in handler in environments/fetcher/fetcher.go where if FetchRequest.Unpack is true it unzips to destination,
    something along the lines of http://blog.ralch.com/tutorial/golang-working-with-zip/
6. the enviroments then need to check for the presence of either a directory or a file during specialize post and take appropriate action

There is one caveat here and that is that the poolmgr does not, at this point in time, have any access to the Function struct.
The poolmgr only knows about the MetaData struct which does not contain information about whether or not, the Function is a Deployment or just a plain file. 
Neither do I believe that the MetaData struct should contain the deployment bool as it wouldn't make any sense on for example the Environment.
The API for accessing Function data is only available in the controller's API and using that would create a weird dependency.

Thoughts?

Todo: what to do about "fission fn get" in the case of a deployment and not plain file.

**Comment by soamvasani** [comment]
The [v2 environments doc](https://github.com/fission/fission/blob/master/Documentation/wip/environments-v2.md) has been updated, please take a look.  Still some more detail needed in various places (feel free to send PRs for this doc, btw :) ).

I also drew some diagrams, these are the slides we had in the dev hangout from Monday; note that there are slide notes too: https://docs.google.com/presentation/d/15BcRr_9Uf-aTrfYJNjwyN_jugwafQ6IlMmJOJ9qWesA/edit?usp=sharing

cc @ktrance @dgoujard

**Comment by soamvasani** [comment]
Thanks for the detailed sketch @ktrance, this was helpful.

> How these components are interpreted is up to the individual environment

Yup, makes total sense.

> add Unpack bool field to the FetchRequest

Alternatively we could have fetcher handle the Content-Type header.  If it's a zip, it should be uncompressed.  Packaging format should be environment-independent (say, zip for example.  All src/deployment packages can be wrapped in a zip that's handled by fetcher).

>  The API for accessing Function data is only available in the controller's API and using that would create a weird dependency.

I think this should be fine, poolmgr today already grabs the function object ([here](https://github.com/fission/fission/blob/master/poolmgr/api.go#L101)) when it needs to figure out which env a function belongs to, we can refactor a little bit and pass the function obj to the specialization code too.

**Comment by dgoujard** [comment]
@soamvasani How do you handle compile error feedback ? How the Buildmgr know the are errors ? And how to return this information to cli ?

Maybe the builder environement need to call Controller API to send the error message and the Controller API return the message to the cli (with websocket ?). I'm not realy fan of this idea

Or the builder environement create a special file "error.json" with error message and the Fetcher send the content of this file to the Controller API.

**Comment by soamvasani** [comment]
@dgoujard One way to do this is to have buildmgr capture stdout/stderr of the build command through the k8s API, and save the output into the function object by calling into the controller.

**Comment by dgoujard** [comment]
@soamvasani It seems like a good idea !

**Comment by awitherow** [comment]
Accessing storage is a nice feature that is mentioned in the v2 docs. Currently using Google Cloud Platform, serving a single page app via this method is not recommended as only http is supported, not https. Any ways that fission could help alleviate this problem or is it beyond the scope/control of this project?

**Comment by Disturbing** [comment]
Where are we at this with one?

**Comment by soamvasani** [comment]
This has been implemented a few releases ago.
