### ISSUE TITLE
Go function failed to execute after upgrading go version of runtime image

### ISSUE THREAD

**Issue by life1347** [fission/fission#1030]
This isn't an issue just a reminder for people who encounter the same problem.

After some experiment, looks like go only allows to load a plugin that built with the same go version of the application, which means you cannot load a plugin built with old go version and load it in newer go version, and vice versa.

To prevent such compatibility problem, it better to make sure that both runtime image and builder image are using the same go version or using same fission release of go-env and go-builder.

reference: https://github.com/whiteboxio/flow/issues/3

**Comment by soamvasani** [comment]
@life1347 any code changes you're thinking of here?  Or is this just for documentation?  If so we can add something to the docs and close this issue.
