### ISSUE TITLE
README and Documentation Divergence

### ISSUE THREAD

**Issue by gravypod** [fission/fission#1038]
Hello. I've been looking into using fission. I found that the README.md states 

> A trigger is something that maps an event to a function; Fission supports HTTP routes as triggers today, with upcoming support for other types of event triggers, such as timers and Kubernetes events.

Is this accurate? The documentation contains [instructions for creating a timed trigger.](https://docs.fission.io/usage/trigger/#create-a-time-trigger)

**Comment by gravypod** [comment]
Yeah I'll do that when I get home from work. Thanks for your time! Should I
@ you in the PR?

**Comment by vishal-biyani** [comment]
Closed by https://github.com/fission/fission/pull/1043
