### ISSUE TITLE
Ruby support

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#104]
Issue for tracking Ruby support.  We will work on this based on interest; of course, contributions are always welcome.  Please 👍 this issue if you're interested in Ruby support.

If anyone's interested in helping out with this, the [Python environment](https://github.com/fission/fission/tree/master/environments/python3) is a good place to learn how to add language support to Fission.

**Comment by lfundaro** [comment]
I'll check the *Python environment* and see if I can make the support for ruby.

**Comment by soamvasani** [comment]
Nice, thanks! Don't hesitate to reach out if you have any questions.

**Comment by sbfaulkner** [comment]
I think this can be closed now
