### ISSUE TITLE
Ingress TLS termination

### ISSUE THREAD

**Issue by jleavers** [fission/fission#1046]
As mentioned on Slack (https://fissionio.slack.com/archives/C3LUX6BBP/p1546510527020000):

I have been using `fission httptrigger` _without_ `--createingress` as our normal configuration is to terminate SSL at the ingress controller, e.g.

    tls:
    - hosts:
      - host.mydomain.local
      secretName: mydomain-wildcard

Would it be feasible for `--createingress` to optionally add TLS termination to the ingress rule that it creates, e.g. with a flag of `--tls` and another flag of `--tlssecret` to specify the secret name?

Alternatively, would it be feasible to configure a tls secret and use HTTPS with the router directly instead of HTTP?

**Comment by jayunit100** [comment]
That might be a little tricky since, some ingress controllers might not properly implement the tls termination, and then you’d have a less platform neutral TLS
