### ISSUE TITLE
Question on scaling up fission components

### ISSUE THREAD

**Issue by danielwhatmuff** [fission/fission#1072]
I wondered if it's possible to autoscale the fission components themselves e.g. redis/influxdb/controller API etc. Are there any docs relating to advanced deployment? Has it been deployed at a scale requiring that before? I noticed all the Kubernetes `Deployments` have replicas set staticly to 1 in the deployment YAML - which I'm guessing would become an issue when running fission in a multi-tenant setup at scale..?

**Comment by life1347** [comment]
Hi @danielwhatmuff , most of the fission components are not able to scale up except the router. You can manually scale up the router to replicas as you want, or you can set HPA for router based on CPU/Memory let kubernetes scales it automatically.

**Comment by life1347** [comment]
Close due to inactivity. Here is [Advanced Setup Guide](https://docs.fission.io/installation/advanced-setup/) for anyone who is interesting in this topic.
