### ISSUE TITLE
Fission Api client? Rest api? and sdks?

### ISSUE THREAD

**Issue by unikzforce** [fission/fission#1073]
Hello dear fission team.
i'm currently working on a project written in java spring boot.
from this project i want to connect to fission and submit some functions and workflows. is it possible?
is there any rest api i can call to submit a function in environment?
is there any rest api i can call to get the last state of a workflow instance?
i don't know if REST is the right way to interact and control fission in kubernetes .. so excuse me for my insufficient knowledge level.

would you please help me with these questions?
thanks a lot.

**Comment by erwinvaneyk** [comment]
It is no where explicitly documented, but the REST API consists out of two services: the controller and the router
- for the controller: https://github.com/fission/fission/blob/master/controller/api.go#L194
- for the router: is basically custom http triggers. By default you can trigger your function `$ROUTER_URL/fission-function/<function-name>`
