### ISSUE TITLE
Autoscaling Isuue

### ISSUE THREAD

**Issue by white-cloud** [fission/fission#1088]
Hello, 

I wonder why the autoscaling is not working for me. 
I create the function with the following command and i configured it with few resources and 20% in purpuse to see the autiscaling for this function but its always create only when pod even if i increase my load.
 fission function  create --name hello --env python  --code hello.py     --minmemory 64 --maxmemory 128 --minscale 0 --maxscale 6  --targetcpu 20 --executortype newdeploy .

PS: im using Fission 1.0-rc1. 

Thank you.

**Comment by soamvasani** [comment]
Hi @white-cloud , could you take this to the Slack please?  Usually this is some sort of setup issue with the metrics server.
