### ISSUE TITLE
Reading ConfigMaps or Secrets that have been created via files does not work

### ISSUE THREAD

**Issue by CamelCaseNotation** [fission/fission#1089]
https://docs.fission.io/usage/access-secret-cfgmap-in-function/ This documentation says we can read the files mounted in our functions. This only works when the secret/configmap has been created via `--from-literal`. Continually getting file not found exceptions otherwise

**Comment by bhavin192** [comment]
@CamelCaseNotation can you please share the way you are using to access the file?
When we create a secret/configMap using `--from-file`like
```
$ kubectl create secret generic secret-name --from-file=my-file.txt
```
The file name is the key in the secret.
It should be accessible at: `/configs/default/secret-name/my-file.txt`

**Comment by soamvasani** [comment]
@CamelCaseNotation please reopen if this is not solved by @bhavin192 's comment
