### ISSUE TITLE
Spec should rebuild failed package if apply spec files again

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#1092]
Deploying the go example from scratch results in an error:
```
$ fission spec apply --wait
1 environment created: go
1 package created: hello-go-pkg
1 function created: hello-go
--- Build FAILED: ---
Build timeout due to environment builder not ready
------
```
This is due to spec not awaiting creation environment before trying to create the function.

Subsequent `spec apply` fail too:
```
$ fission spec apply --wait
Everything up to date.
--- Build FAILED: ---
Build timeout due to environment builder not ready
------
```
The reason for this is that the failed function is not being retried/rebuild. 

Currently to workaround this, you need to manually force a rebuild of the failed pkg: `fission pkg rebuild --name <go-pkg-name>`. 

We should fix this to be more developer-friendly / intuitive.

**Comment by JannikZed** [comment]
we are running into the same issue

**Comment by mstrYoda** [comment]
I have faced with the same issue

**Comment by holyketzer** [comment]
Any updates on it?

**Comment by life1347** [comment]
@holyketzer I just scheduled this issue in next milestone.
