### ISSUE TITLE
Add (and sort by) timestamps to pkg list

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#1093]
Currently the `pkg list` command does not contain a timestamp. This is in my opinion pretty useful, because you typically want to find one of the most recent package that failed. (Optionally) sorting the list by that timestamp would be helpful too.
```
$ fission pkg list
NAME                      BUILD_STATUS ENV
fortune-sh-ljcr           succeeded    binary
fortunewhale-wf-yaml-btrh succeeded    workflow
hello-go-pkg              succeeded    go
hello-js-idsl             failed       nodejs
hello-js-n8dw             succeeded    nodejs
hello-wf-yaml-4jor        failed       workflows
hello-wf-yaml-b8uy        succeeded    workflow
...
```

**Comment by viveksinghggits** [comment]
I am planning to work on this issue.

**Comment by viveksinghggits** [comment]
Hi @life1347 
we should sort the list by timestamp by default or there should be a flag that should be provided while calling the function to get the sorted list.
cc @erwinvaneyk

**Comment by viveksinghggits** [comment]
I was planning to sort that by `creationTimestamp` initially but `lastUpdateTime` is perfect.

**Comment by viveksinghggits** [comment]
Hi @life1347 
I just implemented to get the package list sorted, are you expecting that `--status` thing as part of this change?

ps. 
I was bit involved with other things thats was not able to work on this.

**Comment by life1347** [comment]
@viveksinghggits Let's leave the `--status` thing in another PR. I will open an issue to track that. Thanks for your contribution to PR1334.
