### ISSUE TITLE
updating function resources while the function is running?`

### ISSUE THREAD

**Issue by prp20** [fission/fission#1099]
HI All, 

would like to know if there is a mechanism/ API call where we can update the memory resources of a function while the function is running? something similar to the "Kubectl patch" command in Kubernetes. Would be great if someone can provide and example regarding this.

**Comment by vishal-biyani** [comment]
Hi @prp20 ATM it is not possible to increase the memory of a running function. In fact, Kubernetes also does not completely support in place memory update yet (There are efforts like https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler which will require pod restart).

Is there a specific use case that you are trying to solve?

**Comment by life1347** [comment]
Close. Feel free to reopen it.
