### ISSUE TITLE
Support Kubernetes contexts

### ISSUE THREAD

**Issue by TimJones** [fission/fission#1102]
I manage several clusters and would love to see support for a `--kube-context` parameter that allows me to run fission without having to `kubectl config use-context xxx` between each call.

**Comment by a8uhnf** [comment]
I would like to help with this issue

**Comment by life1347** [comment]
@a8uhnf that would be awesome! Feel free to ping me on Slack if you need any help.

**Comment by philomory** [comment]
Is there any chance the PR for this could get merged?

**Comment by vishal-biyani** [comment]
Hi, @philomory I don't think the PR linked above actually does anything at this point and it seems some work is pending. 

Hey @a8uhnf - will you be able to take this up further and close the WIP from PR?

**Comment by vishal-biyani** [comment]
This has been addressed in PR #1595 hence closing.
