### ISSUE TITLE
Allow creating environments with the newdeploy executor type

### ISSUE THREAD

**Issue by TimJones** [fission/fission#1104]
I have a workflow where latency isn't important but resource use is, so all my functions are declared with `--executortype newdeploy --minscale 0`.
When starting my fission project I had to create the environment which by default is a `poolmgr` which is unneeded in this use case and wastes resources.

I would like to see setting up of the environment allowing a selection for the executor type.

**Comment by vishal-biyani** [comment]
Set version of env to 3 if poolsize is specified by user
