### ISSUE TITLE
Multiple pods behind function service when using Istio

### ISSUE THREAD

**Issue by grounded042** [fission/fission#1108]
When using Fission with Istio and a pool manager for my function I've run into a problem. When the executor gets a call from the router to find where a service lives it first looks in the service cache. If the cache doesn't satisfy the needs, the executor creates a service for the function which for Istio will delete any pods currently labeled for the function. Since the function has been run before, but is not longer valid in the cache, it is marked to be deleted and a new pod is chosen and labeled. This is where the main problem happens - the pod that's marked for deleted does not seem to be in a non `Running` status phase and thus is still able to back the service. But since the pod has already been specialized it bombs out.

There are two main problems here:
1) The validity of a service in the executor cache is determined on address which means that the istio service will NEVER be valid as it has a url and not the ip of a pod.
2) We don't wait for the new labeled pod to be the only pod that could back the function service

I've looked at one solution where when using Istio the executor actually waits for only one pod to match the labels for backing a service, but I ran into problems where it seems like querying the cluster from inside of the pod lagged behind on actual status compared to my local kubectl calls.

Another solution was to add a specialization id to the pod labels and then update the k8s service entry  selector with the specialization id so it only gets that specific pod. However, while I can see the updated selector via kubectl on the service, it still seems to be routing traffic to the old pod. 

To reproduce this, you can do the following: 
1. Clone the repo that contains the needed files: https://github.com/grounded042/fission-istio-problem
2. start up minikube `$ minikube start --cpus 4 --memory 8192 --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/minikube/certs/ca.crt" --extra-config=controller-manager.cluster-signing-key-file="/var/lib/minikube/certs/ca.key"`
3. Apply Istio CRDs `$ kubectl apply -f istio-1.0.6/install/kubernetes/helm/istio/templates/crds.yaml`
4. Apply non mTLS Istio `$ kubectl apply -f istio-1.0.6/install/kubernetes/istio-demo.yaml`
5. Make sure the Istio services are created `$ kubectl get svc -n istio-system`
6. Make sure all Istio pods are running `$ kubectl get pods -n istio-system`
7. Apply Fission `$ kubectl apply -f fission/fission-all.yaml`
8. Make sure all Fission pods are running `$ kubectl get pods -n fission`
9. Create a go env `$ fission environment create --name go --image fission/go-env --builder fission/go-builder`
10. Create a function `$ fission fn create --name helloworld --env go --src fission-test.go --entrypoint Handler`
11. Make sure it finished building `$ fission pkg info --name <name-from-last-command>`
12. Run the function `$ fission fn test --name helloworld`
13. Find the name of the pod it ran the function on `$ kubectl logs <executor pod name> -n fission executor` look for the line that says something like `2019/02/26 23:42:08 Chosen pod: poolmgr-go-default-q4ezjznl-74dddc4dfc-wcmhp (in 26.586983ms)`
14. Get the logs of that pod just to see that it ran on there `$ kubectl logs <pod name from last step> -n fission-function fetcher`
15. Wait 65 seconds so the router will have to call the executor
16. Run the function again `$ fission fn test --name helloworld` and watch it fail.
17. Find the name of the pod it supposedly ran the function on `$ kubectl logs <executor pod name> -n fission executor`
18. Check the logs of that pod and notice that it did not run `$ kubectl logs <pod name from last step> -n fission-function fetcher` as all it says is `2019/02/26 23:40:02 Fetcher ready to receive requests`
19. Check the logs from the pod found in step 13 and notice that it tried to run it against this pod as there are lots of fetch requests `$ kubectl logs <pod name from step 13> -n fission-function fetcher`

**Comment by life1347** [comment]
Thanks for providing the details, I will take a look!
