### ISSUE TITLE
Github Actions 

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1113]
Explore usage of Github actions for CI/CD workflow of Fission functions

**Comment by vishal-biyani** [comment]
Fission GitHub action is available in marketplace [here](https://github.com/marketplace/actions/fission-action) and code is [here](https://github.com/fission/action)

**Comment by soamvasani** [comment]
Anything still left to track here, @vishal-biyani ?

**Comment by vishal-biyani** [comment]
Closing this for now - and we can create a new one for any future needs.
