### ISSUE TITLE
Fission 1.0.0 client doesn't work with Fission Service <1.0.0

### ISSUE THREAD

**Issue by freeqaz** [fission/fission#1114]
# Summary
Fission client versions are not pinned to server versions in any way. This produces strange edge cases where many issues arise, often subtly. From the investigation done for `fission-workflows` [here](https://github.com/fission/fission-workflows/issues/249), this can make it difficult to diagnose the problem.

## Core Issue
Fission 1.0.0 client doesn't work with Fission Service <1.0.0

## Easy Fix
Warn users when the server version of fission doesn't match the client version.

### Better Fix
Make clients backwards compatible and/or provide a way to swap which client is being used easily (think `nvm` for Node or, to a lesser extent, `virtualenv` for Python).

Hopefully this makes sense. Let me know if you have any questions or concerns. Wanted to make sure this wasn't lost, because this issue was pretty painful to debug and I'm sure I won't be alone!

**Comment by relaxxpls** [comment]
Hey! I'm a little new to Open Source but id like to help! Could you tell me where to get started!?

**Comment by vishal-biyani** [comment]
Hey @relaxxpls This is a bit stale issue and not relevant anymore, could you search for another issue in the repo.
