### ISSUE TITLE
Trying to create an existing function results in a 500 error

### ISSUE THREAD

**Issue by tobias** [fission/fission#112]
If you create a function:
    
    fission fn create --name foo --env nodejs --code foo.js

then try to use the same name again:

    fission fn create --name foo --env nodejs --code foo2.js

You get:

    ERRO[0000] Failed to create function                     err="(Error 0) HTTP error 500" name=hello
    Failed to create function: (Error 0) HTTP error 500
    
I think the controller API could be improved a bit to give a better status code and message in this case (and probably others). I'm happy to take a look at doing that if there is interest.

**Comment by soamvasani** [comment]
> I think the controller API could be improved a bit to give a better status code and message in this case (and probably others). I'm happy to take a look at doing that if there is interest.

Yes, agreed and thanks for offering to help!

The function API is implemented in controller/functionApi.go; that's a good place for this particular check.
