### ISSUE TITLE
Fission workflows - return HTTP code failing function

### ISSUE THREAD

**Issue by yannickstruyf** [fission/fission#1131]
When creating a fission workflow it should be possible to return the exit code of a failing function to the end-user. 

To give an example. When I create an authentication function, I want to throw 401 in case the user was not authenticated. Currently the user retrieves 500 internal server error because the workflow fails (a function retrieved HTTP status code > 200).

**Comment by life1347** [comment]
@erwinvaneyk any idea?

**Comment by erwinvaneyk** [comment]
This is currently not supported. We need to add the status code to the error object in the workflow invocation and propagate it up to the workflow runtime.

**Comment by soamvasani** [comment]
Please track it in the workflows repo if it isn't already -- https://github.com/fission/fission-workflows
