### ISSUE TITLE
Fission upgrade with Istio fails

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1144]
If you have a cluster with no Istio enabled and then you upgrade with `enableIstio` - then upgrade fails. Also a fresh install with Fission and Istio enabled fails to upgrade. The Helm upgrade waits on the job to complete as seen from Tiller logs and status of the job:

```
[tiller] 2019/04/02 18:18:17 warning: Release fission pre-upgrade fission-all/templates/pre-upgrade-job.yaml could not complete: timed out waiting for the condition
```

```
status:
  active: 1
  startTime: 2019-04-02T18:13:17Z
```

Now if you look at job logs:

```
$ kubectl logs fission-fission-all-1.1.0-484-nxk4n -c pre-upgrade-job
{"level":"info","ts":1554228806.7490427,"caller":"preupgradechecks/main.go:65","msg":"nothing to do since CRDs are not present on the cluster"}
```

But if we look at relevant code, the job returns right after above statement:

```

	if !crdBackedClient.IsFissionReInstall() {
		logger.Info("nothing to do since CRDs are not present on the cluster")
		return
	}
```

This happens because the Istio sidecar never returns even after the job is done (https://github.com/istio/istio/issues/6324). Probably we should add an annotation to avoid auto-inject for the pre-upgrade job (Not sure if that is possible!)

**Comment by vishal-biyani** [comment]
Quick update, I tried adding inject = false annotation on pre-upgrade job and it did not help AFAIT:

```
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded
    "sidecar.istio.io/inject": false
``` 

& still:

```
[tiller] 2019/04/02 18:35:24 warning: Release fission pre-upgrade fission-all/templates/pre-upgrade-job.yaml could not complete: timed out waiting for the condition
```

**Comment by bopm** [comment]
So contributors, it's safe to say that it's no longer possible to use Fission with Istio. Same problems appear with both upgrade or fresh install. Is it's going to be addressed, or it's simpler to say that fission is no longer usable in istio enabled envs?

**Comment by soamvasani** [comment]
@bopm Fresh installs do work, so no, it is not correct to say that.  You encounter this bug only when you try to upgrade.  

And to your other question, we certainly plan to address this.

In fact, there's a work around -- you could upgrade with `--no-hooks` and helm will just skip the pre-upgrade job.  Or you could use the yaml to install and upgrade.

**Comment by bopm** [comment]
@soamvasani I'd really appreciate if it was the case. But unfortunately, it's same way as this [error](https://github.com/fission/fission/issues/1143):
```
{"level":"info","ts":1557146106.9801953,"caller":"fission-bundle/main.go:106","msg":"skipping trace exporter registration"}
{"level":"fatal","ts":1557146110.6808698,"caller":"messageQueue/messageQueue.go:99","msg":"failed to connect to remote message queue server","error":"read tcp 10.1.0.80:46126->10.107.194.127:4222: i/o timeout","stacktrace":"github.com/fission/fission/mqtrigger/messageQueue.MakeMessageQueueTriggerManager\n\t/go/src/github.com/fission/fission/mqtrigger/messageQueue/messageQueue.go:99\ngithub.com/fission/fission/mqtrigger.Start\n\t/go/src/github.com/fission/fission/mqtrigger/main.go:47\nmain.runMessageQueueMgr\n\tsrc/github.com/fission/fission/fission-bundle/main.go:58\nmain.main\n\tsrc/github.com/fission/fission/fission-bundle/main.go:252\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:198"}
```

**Comment by vishal-biyani** [comment]
Hi @bopm Are you actively using NATS as a MqTrigger in the setup?

**Comment by bopm** [comment]
@vishal-biyani I am just following installation instructions. It's working without istio, but not working with it. Here is commands I am using:
```
export FISSION_NAMESPACE=fission
kubectl create namespace $FISSION_NAMESPACE
kubectl label namespace $FISSION_NAMESPACE istio-injection=enabled
helm install --name fission --namespace fission --set enableIstio=true https://github.com/fission/fission/releases/download/1.1.0/fission-all-1.1.0.tgz
```

**Comment by vishal-biyani** [comment]
@bopm On a fresh install even with Istio, only one pod/component that should fail is `mqtrigger-nats-streaming` - which does not prevent you from using rest of Fission's functionality. If you don't plan on using NATS as an MQ then you can also disable it in values.yaml and you will be fine.

```
nats:
  enabled: false
```
So even with Istio installed - most of Fission works without any issues. Please ping me on slack if you run into any issues and I am happy to take a look!

**Comment by bopm** [comment]
I'll try to disable it there but for now it's looking like that:
```
NAME                                                     READY     STATUS             RESTARTS   AGE
buildermgr-86858f4f6c-2c66n                              0/2       Pending            0          2d
controller-78cbdfc4fb-stswm                              2/2       Running            1          2d
executor-97c7fc96d-24b6w                                 0/2       Pending            0          2d
fission-prometheus-alertmanager-5c96f6d569-gj9sm         0/3       Pending            0          2d
fission-prometheus-kube-state-metrics-7d8dc547b6-zc87k   2/2       Running            1          2d
fission-prometheus-node-exporter-wqwjf                   1/1       Running            0          2d
fission-prometheus-pushgateway-74678f8d6c-8cl5b          2/2       Running            0          2d
fission-prometheus-server-57bdb98766-lfwz7               3/3       Running            1          2d
influxdb-5668d995f9-qg969                                2/2       Running            0          2d
kubewatcher-5896f96f59-6fmpp                             2/2       Running            1          2d
logger-k5lg9                                             3/3       Running            0          2d
mqtrigger-nats-streaming-677549b5cf-rnmjg                1/2       CrashLoopBackOff   34         2d
nats-streaming-7686cd7ff4-49thk                          2/2       Running            0          2d
redis-0                                                  2/2       Running            0          2d
router-6c8f6b7c8d-5sdtj                                  2/2       Running            1          2d
storagesvc-b45d8b5cf-sr79t                               0/2       Pending            0          2d
timer-79667dbf9c-mrr4p                                   2/2       Running            1          2d```
So failing pod leading to pending pods if I understand situation correctly.

**Comment by bopm** [comment]
Update: `helm install --name fission --namespace fission --set enableIstio=true,nats.enabled=false https://github.com/fission/fission/releases/download/1.2.0/fission-all-1.2.0.tgz` works for me.

**Comment by soamvasani** [comment]
Thanks for the update, @bopm!

**Comment by bopm** [comment]
I am still struggling with routing/istio on next step, but it's a little bit different story. Probably will collect all as PR for documentation update later if succeed.

**Comment by bopm** [comment]
But nope, was too fast on that one: `router-7f469fb884-9dljf                                  0/2       Pending   0          26m`

**Comment by bopm** [comment]
After some more experiments, I found out that it was all because of out of memory error. After adding some more memory to docker desktop it all works.

**Comment by munjalpatel** [comment]
@vishal-biyani we are planning to use NATS with `istio` enabled. I just tried the following and the `mqtrigger-nats-streaming` pod still fails.

```
kubectl create ns fission
kubectl label namespace fission istio-injection=enabled

helm install --namespace fission --name-template fission \
  --set routerServiceType=ClusterIP,enableIstio=true,router.displayAccessLog=true,persistence.storageType=local,persistence.storageClass=local-path,analytics=false,canaryDeployment.enabled=false \
  https://github.com/fission/fission/releases/download/1.12.0/fission-all-1.12.0.tgz
```

Are there any plans to fix this in near future? It would be great if we can use Fission for both synchronous and asynchronous workloads.
