### ISSUE TITLE
Is it possible to define middleware functions for router?

### ISSUE THREAD

**Issue by purplemana** [fission/fission#1146]
# This is a feature question, not a bug report.
With http triggers, is it possible to define a series of middleware functions to be executed? This is to make DRY authentication and authorization (and other context building functionality) a possibility.

Workflows look to be a way, but would require creating the entire middleware chain in every function spec. It'd be great if fission provides some concept of middleware ootb.

Thanks

**Comment by vishal-biyani** [comment]
Hi @purplemana - ATM we don't have support for trigger middleware. For authentication and authorization - would an Ingress controller not satisfy your needs (Curious). And it would be best to ask queries on Slack: http://slack.fission.io. I will close the bug here and we can chat on Slack.
