### ISSUE TITLE
request full url path in function context

### ISSUE THREAD

**Issue by GIG0i** [fission/fission#1153]
It would be very useful if from within the function we could retrieve the request full url path so that a single function, with a single deployment, can be used for multiple routes. This would still require some logic on the application side to map url paths to specific entry points/controllers.

Currently, for example using the Python environment (which comes pre-loaded with Flask), I haven't found any way to retrieve the request full url path. The Flask request object will return only the base domain and there are no headers that expose the full path.

**Assumptions:**
- I know that the current guideline is to create a new function (using the same codebase) for each route so that different entry points can be configured.
- Currently it is possible to retrieve the url params, but not the full url path:
https://github.com/fission/fission/issues/158

**Comment by soamvasani** [comment]
Yeah this is a reasonable thing to add as a header, shouldn't be too difficult.
