### ISSUE TITLE
Setting affinity/tolerations on fission core deployments

### ISSUE THREAD

**Issue by davidsmf** [fission/fission#1155]
There's already issues (#604, #644) for adding affinity and tolerations on the functions.
However, we'd be interested in all of the core-functionality from fission having affinity support. That way we can run it on a node without so much load.

Would people want it to be configured once for all of the deployments, or separately for each so you could have separate tolerations or affinity for the executor and the controller?

**Comment by vishal-biyani** [comment]
Closed by https://github.com/fission/fission/pull/1170
