### ISSUE TITLE
Need a way to change Kafka Connection details

### ISSUE THREAD

**Issue by msshroff** [fission/fission#1157]
We are using fission-all helm chart to install the fission.
We download fission-all chart, edit values.yaml in it and put below details pointing to our kafka installation:

`## Kafka: enable and configure the details`
`kafka:`
`  enabled: true`
`  brokers: '10.236.196.20:9092'`

Now post fission installation, we want to start using a new Kafka installation.
What is the best way to change this connection detail on running environment?

**Comment by vishal-biyani** [comment]
Hi, As with any Helm chart upgrade, the way to do this would be to change the values in the values.yaml and run a `helm upgrade --values newValueFiles` command. It is recommended to keep the values.yaml in some sort of version control so these changes can be tracked. Please let me know if this does not solve the upgrade, I will close the issue for now.
