### ISSUE TITLE
Fission fn create does not validate the provided functionName

### ISSUE THREAD

**Issue by hd40910** [fission/fission#1160]
While creating a fission function if we can pass a invalid function name as given below.
This should not be allowed. The spec gets applied without any issue and then the issue gets logged only in the var logs.

Invalid function name : some-name (Here - is not allowed) but there is no error

The function gets created and when the function is called it only return internal server error 500 or 504.

In below given example the provided values sqs-publisher is invalid.

API Response:

![image](https://user-images.githubusercontent.com/17830882/55968706-2a8b4500-5c9a-11e9-8353-cfce12bf27cc.png)

Spec file : 

![image](https://user-images.githubusercontent.com/17830882/55968985-adac9b00-5c9a-11e9-9b0d-b7ad510265d1.png)

Logs : 

Apr 11 17:25:36 ilgss0166 journal: [2019-04-11 14:25:36,663] ERROR in app: Exception on /v2/specialize [POST]
Apr 11 17:25:36 ilgss0166 journal: Traceback (most recent call last):
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
Apr 11 17:25:36 ilgss0166 journal:    response = self.full_dispatch_request()
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
Apr 11 17:25:36 ilgss0166 journal:    rv = self.handle_user_exception(e)
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
Apr 11 17:25:36 ilgss0166 journal:    reraise(exc_type, exc_value, tb)
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/site-packages/flask/_compat.py", line 33, in reraise
Apr 11 17:25:36 ilgss0166 journal:    raise value
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
Apr 11 17:25:36 ilgss0166 journal:    rv = self.dispatch_request()
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
Apr 11 17:25:36 ilgss0166 journal:    return self.view_functions[rule.endpoint](**req.view_args)
Apr 11 17:25:36 ilgss0166 journal:  File "server.py", line 57, in loadv2
Apr 11 17:25:36 ilgss0166 journal:    f, path, desc = imp.find_module(moduleName, [filepath])
Apr 11 17:25:36 ilgss0166 journal:  File "/usr/lib/python3.5/imp.py", line 297, in find_module
Apr 11 17:25:36 ilgss0166 journal:    raise ImportError(_ERR_MSG.format(name), name=name)
Apr 11 17:25:36 ilgss0166 journal: ImportError: No module named 'sqs-publisher'

**Comment by hd40910** [comment]
Please Note : The same issue occurs when used via spec

**Comment by vishal-biyani** [comment]
Hey @hd40910 - can you please update the description as it does not match the title. I think this is a copy paste issue.

**Comment by hd40910** [comment]
@vishal-biyani  @mehuls When we create a function ( Using CLI or spec) , the provided config maps or secrets are not validated to be available. The function then fails on api invocation.
Raised this issue to understand is some validation can be added for this , maybe an optional indicator with default as false

**Comment by hd40910** [comment]
@vishal-biyani  Upadated

**Comment by parauliya** [comment]
Hi All,
This issue occurred in python environment but in almost every language and environment the function naming rules are the same. For e.g. Function names should have alphanumeric characters and '_' as a special character only. Therefore we should have a generic check for validation of function name irrespective of the environment. And in case function name is not valid, an error should be returned telling that function name provided is not valid or can only have alphanumeric characters and '_'.
Please let me know your views for the same.

**Comment by soamvasani** [comment]
>  Therefore we should have a generic check for validation of function name in the process of function creation itself irrespective of the environment. 

I think it makes sense to add this, yeah.  

The only potential problem is that existing users might have specs that worked before but don't work after we add validation.  But  maybe this is only a theoretical concern, because I can't think of any examples where a name that doesn't validate would actually work.

**Comment by life1347** [comment]
In #1042 , we switched the library from `imp` to `importlib` for importing user functions. And I can confirm this problem is no longer exists. Close.

Reference: https://stackoverflow.com/a/24659400
