### ISSUE TITLE
Support for Kafka Triggers with SASL enabled kafka cluster 

### ISSUE THREAD

**Issue by rakeshbshukla** [fission/fission#1162]
Does fission provide support for creating kafka triggers for SASL enabled kafka cluster.
Is there a way to configure the kafka triggers [MQT's] for authentication using SASL for kafka cluster.
Will fission MQ trigger be able to subscribe a secured kafka cluster using SASL auth enabled.

**Comment by vishal-biyani** [comment]
This can be potentially be closed since https://github.com/fission/fission/pull/1300 is merged.

**Comment by justinfx** [comment]
We currently have a Kafka cluster deployed using Sasl SCRAM. It seems none of the faas platform Kafka agents ever expose the "mechanism" configuration to provide SCRAM. I'm trying to get our Kafka deployment to switch to something else but I wonder if this is something that should be exposed?

**Comment by vishal-biyani** [comment]
Hi @justinfx Once we have this PR ready https://github.com/fission/fission/issues/1565 - we should be able to support SCRAM too as documented here: https://keda.sh/docs/1.4/scalers/apache-kafka/#authentication-parameters

**Comment by vishal-biyani** [comment]
Fission now can supports SASL, SCRAM based on the new Keda based MQTrigger. The PR is https://github.com/fission/fission/pull/1657 and blog details out working here: https://blog.fission.io/posts/event-driven-scaling-fission-function-using-keda/
