### ISSUE TITLE
Update secret/configmaps in function pod if source changed

### ISSUE THREAD

**Issue by life1347** [fission/fission#1164]
It would be helpful for fetcher to check and pull changes of secrets/configmaps periodically.
#1161

**Comment by soamvasani** [comment]
We'd have to be careful not to race with user code that's reading the config or secret.

**Comment by vishal-biyani** [comment]
Just updating the conversation I had with Soam here - we should do something similar to PR https://github.com/fission/fission/pull/1116 which updates a function when an image in the environment changes. We can watch all secrets & configmaps which are related to a function (Do we use labels to identify configmaps related to a function?) and then update function if there is a change in configmap/secret.

**Comment by hd40910** [comment]
@mehuls #1159 is related .
@vishal-biyani  Do we have release date planned for 1.3 ?
