### ISSUE TITLE
poolmgr function update behaviour on env update

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#1169]
After #1116, functions using the newdeploy executor are updated after an environment change.  But functions using poolmgr do not notice the change.  This is less of a problem since poolmgr functions usually become idle at some point and get killed anyway; but depending on the use case this could take a while.  

We should make the poolmgr behaviour consistent with the newdeploy behaviour and treat env updates the same as function updates.

**Comment by vishal-biyani** [comment]
Pasting the conversation with @airhorns 

Zero downtime environment deploys. Two sub issues here:

2a - Right now, when you change the docker image for a poolmgr Environment CRD, fission does a good job of recreating the deployment for the pool of unspecialized pods and will specialize new pods out of that new pool. But, I think there's a brief window where during this deploy, the old pool is terminated and the new pool is not yet ready such that specializations fail while the new pods start. Note that I don't mean zero downtime function deploys, this is about changing the environment that many functions are running in while serving continuous traffic to all the functions, specialized or not.

2b - After a new poolmgr environment CRD has been recreated, there can still be a bunch of pods that were specialized using the previous environment version. these pods were specialized before so they are still running whatever function on top of the old environment code. It'd be amazing to eventually stop routing traffic to these functions and re-specialize them on the new environment version so the amount of time the old environment is running is bounded. Right now, if a function is getting continuous traffic before going cold and the pod being reaped, nothing ever shuts it down despite there being a new environment version that it "should" be running

**Comment by sanketsudake** [comment]
Related PRs 

https://github.com/fission/fission/pull/2161
https://github.com/fission/fission/pull/2166
https://github.com/fission/fission/pull/2184
