### ISSUE TITLE
Dotnet arguments example fails 

### ISSUE THREAD

**Issue by CanerPatir** [fission/fission#1174]
syntax error on https://github.com/fission/fission/blob/master/examples/dotnet/arguments.cs

**Comment by vishal-biyani** [comment]
Hi, @CanerPatir Thanks - can you please paste the error?

**Comment by CanerPatir** [comment]
Fatal error: Failed to execute HTTP request: Get http://127.0.0.1:52850/fission-function/hello2: context deadline exceeded

**Comment by life1347** [comment]
Fix by #1175
