### ISSUE TITLE
Configmap mount directory was changed which breaks functions

### ISSUE THREAD

**Issue by mattroark** [fission/fission#1176]
The configmap mount directory was changed in 1.2.0 which will break any functions that rely on the old path. Instead of `/configs`, it is now `/configmaps`.

```yaml
        - mountPath: /configmaps
          name: configmaps

```

**Comment by soamvasani** [comment]
Thanks for filing this @mattroark .

I've marked 1.2 as a pre-release with a note about this bug, @vishal-biyani let's do a 1.2.1 with just the fix for this since this is pretty critical.

Also, looks like test_secret_cfgmap is passing when it should be broken :confused:

**Comment by vishal-biyani** [comment]
Sorry about that - this is totally my bad. I did notice that the test was not working but I felt the `/configmap` was better than `/configs` and changed both which introduced breaking change.
