### ISSUE TITLE
[Feature] Fission CLI check

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1183]
Inspired by Linkerd CLI, I propose we add a check command to Fission CLI which can act in two scenarios:

1) Before installing Fission into the cluster - the user should be able to do a "pre-check" and see what exists or does not in the cluster for Fission to work properly. Potentially it can also emit YAMLs and install from CLI itself

```
$ fission check --pre
kubernetes
--------------
√ kubernetes version is compatible

storage
------------------
√ cluster can provision a disk

```

2) After Fission is installed in the cluster - a check everything is healthy!

```
$ fission check
fission
--------------
√ all fission controllers running fine

storage
------------------
√ cluster can provision a disk

fission-version
---------------
√ can determine the latest version
√ cli is up-to-date
```

**Comment by sparkingdark** [comment]
Are you want to add a check command to get more information>

**Comment by sanketsudake** [comment]
Noting reference of slack conversation around this issue https://fissionio.slack.com/archives/C7T2HDYTG/p1643538704290109
