### ISSUE TITLE
Function level timeout

### ISSUE THREAD

**Issue by msshroff** [fission/fission#1229]
Currently we do not have any mechanism to setup timeout to limit fictions runtime in fission. 
We are using ingress to route the traffic and using ingress level timeout for this. 

But ingress solution allows single timeout for all the fictions. 
Can there be a mechanism to set "fission environment level" or "fission function level" timeout? 

**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    gitcommit: 898d1271e21c19a421687ec04ae22a2b399fa11c
    builddate: 2019-02-13T15:57:47Z
    version: 1.0.0
server:
  fission/core:
    gitcommit: 898d1271e21c19a421687ec04ae22a2b399fa11c
    builddate: 2019-02-13T15:57:47Z
    version: 1.0.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Comment by parauliya** [comment]
I think we can add a new parameter in function creation cli ( --function-timeout ) in which we can pass the default time within which the function should complete its execution and return.

**Comment by life1347** [comment]
Solved by #1284
