### ISSUE TITLE
Status for fission resource

### ISSUE THREAD

**Issue by life1347** [fission/fission#1234]
Currently, only `canary-config` and `pkg` provides STATUS field for users to know what exactly happened. Due to lack of status fields for other resources, users have to check logs of fission components instead of resource status/logs which is not so friendly for people who are not that much familiar with kubernetes.

**Comment by life1347** [comment]
duplicate of https://github.com/fission/fission/issues/1077

**Comment by RealHarshThakur** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Status of Fission resources](https://trello.com/c/aczCEqNL/7-status-of-fission-resources)
