### ISSUE TITLE
controller in CrashLoopBackOff in OpenShift environment

### ISSUE THREAD

**Issue by msshroff** [fission/fission#1248]
Hi 

We are installing Fission 1.2.1 on OpenShift 3.9 
Controller is not coming failing on readiness probe with below error:

<pre>
Readiness probe failed: Get http://172.17.0.20:8888/healthz: dial tcp 172.17.0.20:8888: getsockopt: connection refused
</pre>

Using below to install 
<pre>
# helm install --name fission --namespace fission --set serviceType=NodePort,routerServiceType=NodePort  ./fission-all-1.2.1.tgz
</pre>

Controller pod is stuck in CrashLoopBackOff
<pre>
# oc get pods -n fission | grep controller
controller-6c4787cd6b-x6mts                              0/1       CrashLoopBackOff        9          16m
</pre>

<pre>
# oc events pods controller-6c4787cd6b-x6mts -n fission
-- output skipped --- 
Events:
  Type     Reason                 Age                 From                Message
  ----     ------                 ----                ----                -------
  Normal   Scheduled              21m                 default-scheduler   Successfully assigned controller-6c4787cd6b-x6mts to localhost
  Normal   SuccessfulMountVolume  21m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "config-volume"
  Normal   SuccessfulMountVolume  21m                 kubelet, localhost  MountVolume.SetUp succeeded for volume "fission-svc-token-7cwvq"
  Normal   Pulled                 21m                 kubelet, localhost  Container image "index.docker.io/fission/fission-bundle:1.2.1" already present on machine
  Normal   Created                21m                 kubelet, localhost  Created container
  Normal   Started                21m                 kubelet, localhost  Started container
  Warning  Unhealthy              6m (x349 over 21m)  kubelet, localhost  Readiness probe failed: Get http://172.17.0.20:8888/healthz: dial tcp 172.17.0.20:8888: getsockopt: connection refused
  Warning  BackOff                1m (x64 over 17m)   kubelet, localhost  Back-off restarting failed container
</pre>

Seeing below errors in /var/log/messages

 <pre>
Jul 25 13:46:16 ilgss0225 journal: I0725 10:46:16.701790   14037 kuberuntime_manager.go:514] Container {Name:controller Image:index.docker.io/fission/fission-bundle:1.2.1 Command:[/fission-bundle] Args:[--controllerPort 8888 --collectorEndpoint ] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:FISSION_FUNCTION_NAMESPACE Value:fission-function ValueFrom:nil} {Name:TRACING_SAMPLING_RATE Value:0.5 ValueFrom:nil} {Name:POD_NAMESPACE Value: ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:metadata.namespace,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,}}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:config-volume ReadOnly:false MountPath:/etc/config/config.yaml SubPath:config.yaml MountPropagation:<nil>} {Name:fission-svc-token-7cwvq ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:8888,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:35,TimeoutSeconds:1,PeriodSeconds:5,SuccessThreshold:1,FailureThreshold:3,} ReadinessProbe:&Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:8888,Host:,Scheme:HTTP,HTTPHeaders:[],},TCPSocket:nil,},InitialDelaySeconds:1,TimeoutSeconds:1,PeriodSeconds:1,SuccessThreshold:1,FailureThreshold:30,} Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:&Capabilities{Add:[],Drop:[KILL MKNOD SETGID SETUID],},Privileged:nil,SELinuxOptions:nil,RunAsUser:*1000120000,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jul 25 13:46:16 ilgss0225 journal: I0725 10:46:16.701925   14037 kuberuntime_manager.go:758] checking backoff for container "controller" in pod "controller-6c4787cd6b-x6mts_fission(f4e12357-aec5-11e9-b7e5-005056afbf4a)"
Jul 25 13:46:16 ilgss0225 journal: I0725 10:46:16.702052   14037 kuberuntime_manager.go:768] Back-off 5m0s restarting failed container=controller pod=controller-6c4787cd6b-x6mts_fission(f4e12357-aec5-11e9-b7e5-005056afbf4a)
Jul 25 13:46:16 ilgss0225 journal: E0725 10:46:16.702081   14037 pod_workers.go:186] Error syncing pod f4e12357-aec5-11e9-b7e5-005056afbf4a ("controller-6c4787cd6b-x6mts_fission(f4e12357-aec5-11e9-b7e5-005056afbf4a)"), skipping: failed to "StartContainer" for "controller" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=controller pod=controller-6c4787cd6b-x6mts_fission(f4e12357-aec5-11e9-b7e5-005056afbf4a)"

</pre> 

<pre>
# fission support dump
Start dumping process...
Fatal error: Error forwarding to port 52073: error upgrading connection: the object provided is unrecognized (must be of type Pod): couldn't get version/kind; json parse error: unexpected end of JSON input (<empty>)
</pre>

**Comment by vishal-biyani** [comment]
Hi @msshroff Can you please share the logs of the pod which are crashing?

**Comment by life1347** [comment]
The reason for `fission support dump` failed is that the controller doesn't create CRD resources yet. You need to use `kubectl -n <fission-ns> logs -f <controller-pod>` to get pod log before it crashes.

**Comment by msshroff** [comment]
Please see the pods logs below 
<pre>
# oc logs controller-6c4787cd6b-6vp88 -n fission
{"level":"info","ts":1564072765.9291146,"caller":"fission-bundle/main.go:106","msg":"skipping trace exporter registration"}
goroutine 6 [running]:
runtime/debug.Stack(0xc0000a6008, 0xc0004f77b8, 0x1)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/fission/fission.SetupStackTraceHandler.func1(0xc0004ba1e0)
        /go/src/github.com/fission/fission/common.go:57 +0x7d
created by github.com/fission/fission.SetupStackTraceHandler
        /go/src/github.com/fission/fission/common.go:54 +0xab
Received SIGTERM : Dumping stack trace

</pre>

**Comment by life1347** [comment]
I guess this problem may be related to this PR https://github.com/fission/fission/commit/56fa8fe7665a50d3148126b4ea98abd168e481c3
Could you try to test against with 1.3.0?

**Comment by vishal-biyani** [comment]
@ta-ching Mehul is testing this on 1.2.1 version

**Comment by life1347** [comment]
@vishal-biyani I know. But the issue I mentioned got fixed in 1.3.0.

**Comment by vishal-biyani** [comment]
Oh ok, sorry I did not see the change you mentioned earlier. Thanks for pointers - I will try 1.3 with the OpenShift

**Comment by msshroff** [comment]
Thanks @life1347 !
It worked with 1.3

**Comment by life1347** [comment]
Glad it works now :) Close.
