### ISSUE TITLE
Spec API version changed....

### ISSUE THREAD

**Issue by davidsmf** [fission/fission#1251]
In latest HEAD, in https://github.com/fission/fission/blob/master/pkg/fission-cli/spec.go#L47

```
const SPEC_API_VERSION = "fv1.io/v1"
```

I think this should still be 
```
const SPEC_API_VERSION = "fission.io/v1"
```

The CRDs are all still using the `fission.io` names.

**Comment by davidsmf** [comment]
Also in `pkg/crd/crd_test.go`, all the `APIVersion` values have also been replaced.

**Comment by life1347** [comment]
@davidsmf thanks a lot for point this out. I definitely need to check the codebase again after the PR of moving them to pkg directory.

**Comment by life1347** [comment]
The thing interesting here is that it didn't break the spec command. Looks like we also need to add some extra validation for API version.
