### ISSUE TITLE
Get error response after switching function executor type from poolmanager to newdeploy

### ISSUE THREAD

**Issue by UmamaheshMaxwell** [fission/fission#1252]
**_Fission version_**
client:
  fission/core:
    gitcommit: cb8605cf60f5b6c7014ba45b68f055a57ed0e150
    builddate: "2019-06-03T10:28:00Z"
    version: 1.3.0
server:
  fission/core:
    gitcommit: cb8605cf60f5b6c7014ba45b68f055a57ed0e150
    builddate: "2019-06-03T10:28:00Z"
    version: 1.3.0

**Kubectl version**

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}

Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Bug**

  We see this error when ever we change the `--executortype` to `newdeploy `from `poolmgr` to our function. Instead of using default image (fission/node-env) we have used our own image which is working fine with `poolmgr`. But errors pops up only when we change it to `newdeploy`

checked the logs using below commands and we don't see any errors in logs

`kubectl --namespace orchard-server get pods -l functionName=create-login` 
`kubectl --namespace orchard-server logs newdeploy-update-password-some-server-nba4ghi2-65556d4f6jqc4 create-login`

**Fission ENV**
fission env create --spec --name some-env --envNamespace some-server --image some--image:latest --builder fission/node-builder  --mincpu 40 --maxcpu 80 --minmemory 64 --maxmemory 128 --poolsize 1

**Works**
fission function create --spec --name create-login --env some-env --envNamespace some-server --fnNamespace some-server --src . --entrypoint "api/user_profile.login"

fission route create --spec  --name create-login  --method POST --url /v1/login --function login --fnNamespace some-server

**Fails**
fission function create --spec --name create-login --env some-env --envNamespace some-server --fnNamespace some-server --src . --entrypoint "api/user_profile.login" --executortye newdeploy

fission route create --spec  --name create-login  --method POST --url /v1/login --function login --fnNamespace some-server

**Expected result:** 
Should create login with token

**Actual Result**
`error updating service address entry for function create-login_orchard-server: Internal error - [create-login] error creating service for function: error creating deployment newdeploy-create-login-orchard-server-qxyqvjb4: failed to create deployment within timeout window`

If we have to think like there is an issue with image it is working fine when executortype  `poolmgr` so we are wondering if this is something to do with `newdeploy
<img width="1680" alt="Screenshot 2019-07-26 at 5 04 01 PM" src="https://user-images.githubusercontent.com/14071278/61949265-dcd7e580-afc7-11e9-8578-9abfe6d29751.png">
<img width="1422" alt="Screenshot 2019-07-26 at 5 04 36 PM" src="https://user-images.githubusercontent.com/14071278/61949267-de091280-afc7-11e9-9938-c13204e210ae.png">

`

**Comment by vishal-biyani** [comment]
Hi @UmamaheshMaxwell I tried to reproduce this and at least with sample code I used I was not able to reproduce this as shown below. Can you please help us a little more here? Ideally, if you can reproduce in your environment and get logs or debug together?

```
$ fission env create --spec --name node --envNamespace test --image fission/node-env --mincpu 40 --maxcpu 80 --minmemory 64 --maxmemory 128 --poolsize 1

$ fission function create --spec --name hello --env node --envNamespace test --fnNamespace test --code hello.js

$ fission function create --spec --name hellond --env node --envNamespace test --fnNamespace test --code hello.js --executortype newdeploy

$ fission route create --spec --name hellond --method GET --url /v1/login --function hellond --fnNamespace test

$ fission spec apply
1 package created: hello-js-phqv
1 function created: hello
1 function created: hellond
1 environment created: node
1 HTTPTrigger created: hellond

$ curl http://xx.xxx.xxx.xxx/v1/login
hello, world!
```

**Comment by life1347** [comment]
Close. Feel free to reopen it.
