### ISSUE TITLE
Error when run fission fn update

### ISSUE THREAD

**Issue by mstrYoda** [fission/fission#1262]
I am trying the given go example. When I execute the following command : 

fission fn update --name hello-go --code hello.go

it gives me the error below:

package 'hello-go-pkg' updated 
Fatal error: Failed to update function: Invalid fission Function object: * ExecutionStrategy.ExecutorType: Unsupported type: : [not a valid executor type]

After when I run :

fission spec apply --wait

output is : 

1 package updated: hello-go-pkg
1 function updated: hello-go
--- Build SUCCEEDED ---
Building file /packages/hello-go-pkg-dnzwpj in /tmp/hello-go-pkg-dnzwpj

------

**Comment by vadasambar** [comment]
Thanks for raising an issue! Let me check :)

**Comment by vadasambar** [comment]
I can reproduce this issue. I ran into a related issue #1092 while trying to reproduce this issue.

**Comment by vadasambar** [comment]
This issue seems to occur because ExecutorType is empty ("").

Output for my function's yaml

```
apiVersion: fission.io/v1
kind: Function
metadata:
  annotations:
    fission-name: hello-go
    fission-uid: a8cdb63c-9be8-4a59-9427-89051afecd7b
  creationTimestamp: "2019-08-08T05:53:18Z"
  generation: 5
  name: hello-go
  namespace: default
  resourceVersion: "45395"
  selfLink: /apis/fission.io/v1/namespaces/default/functions/hello-go
  uid: 0368211f-f219-47f6-9f61-c70969e9ce99
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: ""
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 0
      TargetCPUPercent: 0
    StrategyType: ""
  configmaps: null
  environment:
    name: go
    namespace: default
  package:
    functionName: Handler
    packageref:
      name: hello-go-pkg
      namespace: default
      resourceversion: "44020"
  resources: {}
  secrets: null
```
@mstrYoda, please check the output for 
```
$ kubectl get function hello-go -o yaml -n fission
```

**Comment by mstrYoda** [comment]
I'll check it out as soon as I become available

**Comment by life1347** [comment]
@mstrYoda What fission version you tested against with?
I tested with latest release 1.4.1 with following steps and get non-empty ExecutorType.
```
$ fission spec init
$ fission fn create --name py12 --env python --code hello.py --spec
$ cat specs/function-py12.yaml
apiVersion: fission.io/v1
...
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
...
```
A workaround is to assign executor type explicitly
```
fission fn update --name <fn> --executortype poolmgr
```

**Comment by life1347** [comment]
Close. Feel free to reopen it.
