### ISSUE TITLE
Error 502 bad gateway on microk8s

### ISSUE THREAD

**Issue by spiogit** [fission/fission#1264]
**Fission/Kubernetes version**

$ fission --version
client:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T17:09:13Z", GoVersion:"go1.12.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:15:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Kubernetes platform (e.g. Google Kubernetes Engine)**

microk8s v1.15.2

**Describe the bug**

Following the getting started example of NodeJS works fine for the first three lines, but the actual invocation of the hello world function fails. The error message is: 
Error calling function hello: 502; Please try again or fix the error: Fatal error: Error querying logs: Internal error - 502 Bad Gateway

It does not inform about which logs it tries to query.

$ fission function list
NAME  UID                                  ENV    EXECUTORTYPE MINSCALE MAXSCALE MINCPU MAXCPU MINMEMORY MAXMEMORY TARGETCPU
hello 74af9468-b28c-45b4-917e-196a289dc6db nodejs poolmgr      0        0        0      0      0         0         0

**To Reproduce**

Reproducible on a plain Ubuntu 19.04 installation:

for snap in kubectl microk8s helm; do sudo snap install $snap --classic; done
helm init
# wait half a minute until tiller pod ready...
helm install --name fission --namespace fission https://github.com/fission/fission/releases/download/1.4.1/fission-all-1.4.1.tgz
curl -Lo fission https://github.com/fission/fission/releases/download/1.4.1/fission-cli-linux && chmod +x fission && sudo mv fission /usr/local/bin/
mkdir -p ~/.kube && microk8s.config > ~/.kube/config
fission env create --name nodejs --image fission/node-env
curl -LO https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js
fission function create --name hello --env nodejs --code hello.js
fission function test --name hello

**Expected result**

Hello, world!

**Actual result**

Error calling function hello: 502; Please try again or fix the error: Fatal error: Error querying logs: Internal error - 502 Bad Gateway

**Screenshots/Dump file**

[fission-dump_1565343269.zip](https://github.com/fission/fission/files/3485707/fission-dump_1565343269.zip)

**Comment by ewrogers** [comment]
I'm getting this issue too, but only on some packages. I can't quite figure out why my existing Hello World examples work but this nodejs-builder one does not.

**Comment by life1347** [comment]
@spiogit  From router log in the dump file attached
```
{"level":"error","ts":1565343202.641367,"logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:587","msg":"error updating service address entry for function","error":"error posting to getting service for function: Post http://executor.fission/v2/getServiceForFunction: dial tcp: lookup executor.fission on 127.0.0.53:53: read udp 127.0.0.1:59676->127.0.0.53:53: read: connection refused","errorVerbose":"Post http://executor.fission/v2/getServiceForFunction: dial tcp: lookup executor.fission on 127.0.0.53:53: read udp 127.0.0.1:59676->127.0.0.53:53: read: connection refused\nerror posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction\n\t/go/src/github.com/fission/fission/pkg/executor/client/client.go:70\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntryFromExecutor\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:628\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry.func1\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:560\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\t/go/src/github.com/fission/fission/pkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/router.(*functionHandler).getServiceEntry\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:552\ngithub.com/fission/fission/pkg/router.RetryingRoundTripper.RoundTrip\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:234\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\t<autogenerated>:1\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:232\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:454\ngithub.com/fission/fission/pkg/router.functionHandler.handler-fm\n\t/go/src/github.com/fission/fission/pkg/router/httpTriggers.go:180\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\t/go/src/github.com/fission/fission/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.18.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1333","function_name":"hello","function_namespace":"default"}
```
It shows 
```
udp 127.0.0.1:59676->127.0.0.53:53:
```

It related to DNS lookup problem, you have to check whether in-cluster NDS works correctly.
@ewrogers I'm not sure if you are experiencing the same problem, but it worth to take a look.

**Comment by ewrogers** [comment]
What's interesting is that I don't get this issue when using the standard `nodejs` env (no builder). I can run the `hello.js` example no problem.

But trying to create a similar example using the node-builder instead I get the 502 errors. So I don't think it's the DNS issue or I'd expect both of them to fail similarly.

The router log for **hello** invocation, followed by a similar test with the **crypto** invocation:
```
{"level":"info","ts":1565623643.920332,"logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:568","msg":"assigning service url for function","url":"http://100.99.2.135:8888","function_name":"hello"}
```
{"level":"info","ts":1565623661.4693346,"logger":"triggerset.http_trigger_set.crypto","caller":"router/functionHandler.go:568","msg":"assigning service url for function","url":"http://100.99.1.250:8888","function_name":"crypto"}
2019/08/12 15:28:07 http: proxy error: error sending request to function crypto: context canceled

**Comment by life1347** [comment]
@ewrogers 
Just wondering does the `crypto` is a file or a package?
If it a file then you may not need a builder. If you add a builder image to an environment, you have to set the entrypoint for envrionment to load function. See https://docs.fission.io/languages/nodejs/#using-fission-nodejs-builder-image

**Comment by ewrogers** [comment]
It's a package and deployed with the proper nodejs builder. I've done it the same way for other packages and they work. I have triple-checked everything I can and don't see a reason why this one doesn't work.

The entrypoint and everything are there, I've looked into the ZIP file and it's good there too. It's just a tad frustrating because I have no way to debug further as to what isn't wired up.

**Comment by life1347** [comment]
Since it looks like a different problem than the original one, would you mind reproduce the issue and then running
```
$ fission support dump
```
then share the dump file, so that I can help you to find out the problem.

>  It's just a tad frustrating because I have no way to debug further as to what isn't wired up.

You can dump function log and component log by following commands
```
# function log
kubectl -n fission-function get pod -l functionName=<fn>
kubectl -n fission-function logs -f -c <container> <pod> 

# component log
kubectl -n fission logs -f <pod>
```

Also, could you also check whether its the same problem mentioned in PR #1272 ? Thanks

**Comment by life1347** [comment]
Close. Feel free to reopen it.
