### ISSUE TITLE
cmd "fission fn test --name somefunc" return 502 after reinstall fission

### ISSUE THREAD

**Issue by cocoifly10** [fission/fission#1268]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    gitcommit: 518ab3b90d6d4085e653ef36feb6b34500940823
    builddate: "2019-05-09T08:24:19Z"
    version: 1.2.1
server:
  fission/core:
    gitcommit: 94b157137d45f311dba9affa1ad6ee79b56a73cb
    builddate: "2019-07-29T08:21:45Z"
    version: 1.4.1
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**bug:**
function created before can't run after update fission:
<pre>
Error calling function 2sai7mfk0fkc9v7qagv-hello: 502; Please try again or fix the error:
</pre>

**To Reproduce**

1. create a function "hello", print "hello"
2. run "fission fn test --name hello" to make sure everything goes well
3, delete fission and install another version
4. run "fission fn test --name hello"

**Expected result**
print "hello" 

**Actual result**
Error calling function 2sai7mfk0fkc9v7qagv-hello: 502; Please try again or fix the error:

**Comment by life1347** [comment]
@cocoifly10 What fission version you installed before reinstalling fission?

**Comment by cocoifly10** [comment]
@life1347 yes, 1.2.1

**Comment by life1347** [comment]
Hi @cocoifly10 I am not able to reproduce the problem. Would you mind following the same steps to reproduce the problem, running `fission support dump` and share the dump file for troubleshooting? Thanks

**Comment by life1347** [comment]
Close. Feel free to reopen it.
