### ISSUE TITLE
Kafka mqtrigger consumer function is not getting called

### ISSUE THREAD

**Issue by vadasambar** [fission/fission#1279]
**Fission/Kubernetes version**
Fission version: 9c63975497d83c09809e1050dd140bd7e9008417
Kubernetes version: v1.15.0

<pre>
$ fission --version (I have used 9c63975497 to build fission)
client:
  fission/core:
    gitcommit: ""
    builddate: ""
    version: ""
server:
  fission/core:
    gitcommit: unknown
    builddate: unknown
    version: unknown
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:32:14Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Minikube
**Describe the bug**
I am following https://docs.fission.io/usage/kafka-trigger-tutorial/ to create a mqtrigger using kafka. 

When I do
```
$ fission function test --name producerfunc
```

**To Reproduce**

Just follow the tutorial and test it using `fission function test --name producerfunc`. Producer func gets called but consumer is not called. Message is logged in the kafka queue on the topic provided in mqtrigger.

**Expected result**
MQtrigger should have called consumerfunc. It is not being called.

**Actual result**
I get no error. My handler for consumer is not called. 

https://github.com/fission/fission/blob/9c63975497d83c09809e1050dd140bd7e9008417/pkg/mqtrigger/messageQueue/kafka.go#L118

**Comment by life1347** [comment]
Could you share the log of kafka message queue trigger pod? It should contain some clues.

**Comment by vadasambar** [comment]
Logs for the mqtrigger-kafka pod

```
{"level":"info","ts":1566371344.654092,"logger":"kafka","caller":"messageQueue/kafka.go:75","msg":"inside kakfa subscribe","trigger":"&TypeMeta{Kind:MessageQueueTrigger,APIVersion:fission.io/v1,}"}
{"level":"info","ts":1566371344.654533,"logger":"kafka","caller":"messageQueue/kafka.go:76","msg":"brokers set","brokers":["my-cluster-kafka-brokers.kafka.svc.cluster.local:9092"]}
{"level":"info","ts":1566371344.6624277,"logger":"kafka","caller":"messageQueue/kafka.go:84","msg":"created a new consumer","consumer":{}}
{"level":"info","ts":1566371344.668024,"logger":"kafka","caller":"messageQueue/kafka.go:96","msg":"created a new producer","producer":{}}
{"level":"info","ts":1566371344.6692178,"logger":"message_queue_trigger_manager","caller":"messageQueue/messageQueue.go:210","msg":"message queue trigger created","trigger_name":"kafkatest"}
{"level":"info","ts":1566371344.766645,"logger":"kafka","caller":"messageQueue/kafka.go:111","msg":"consumer notification","notification":{"Type":1,"Claimed":null,"Released":null,"Current":{}}}
{"level":"info","ts":1566371347.7900126,"logger":"kafka","caller":"messageQueue/kafka.go:111","msg":"consumer notification","notification":{"Type":2,"Claimed":{"input":[0]},"Released":{},"Current":{"input":[0]}}}
{"level":"warn","ts":1566371418.0806932,"logger":"kafka","caller":"messageQueue/kafka.go:168","msg":"headers are not supported by current Kafka version, needs v0.11+: no record headers to add in HTTP request","current_version":"0.8.2.0"}
{"level":"warn","ts":1566371419.7354107,"logger":"kafka","caller":"messageQueue/kafka.go:232","msg":"headers are not supported by current Kafka version, needs v0.11+: no record headers to add in HTTP request","current_version":"0.8.2.0"}
```

Log for the kafka pod

```
{"name": "value 2019-08-21T07:10:18Z "}
```

**Comment by vadasambar** [comment]
I tried out the tarball for an older version of fission ([1.0.0](https://github.com/fission/fission/releases/tag/1.0.0)) and it works fine with the same kafka cluster as I have above.

**Comment by vadasambar** [comment]
I tried out the last release of fission ([1.4.1](https://github.com/fission/fission/releases/tag/1.4.1)). I am facing the same issue here as well.

**Comment by life1347** [comment]
Would you mind trying other old versions between 1.0.0 and 1.4.1? In this way, we can locate the problem more easily.

**Comment by vadasambar** [comment]
It works for 1.3.0. Does not work for 1.4.1. I could not check 1.4.0 (the release has issues with yaml file).

**Comment by vishal-biyani** [comment]
That's strange!:

From version 1.3.0:
https://github.com/fission/fission/blob/4bc5d497926e1b1874a6629b5ed05bce28579492/go.mod#L7-L10

From version 1.4.0:
https://github.com/fission/fission/blob/b9997b2eceb1515adf84d28b5985efa954402f54/go.mod#L7-L10

**Comment by vadasambar** [comment]
Thank @vishal-biyani ! I diff'ed 1.3.0 and 1.4.0. There doesn't seem to be a big change between 1.3.0 and 1.4.0 in kafka.go or messageQueue.go. 

I think I am missing something silly. I will retry building with the latest commit once again and see how it goes.

**Comment by vadasambar** [comment]
Turns out the output is not being logged in the mqtrigger-kafka pod in releases after 1.3.0. This is because zap by default logs at `Info` level but the log for consumer func was changed to `Debug`. Changing it back to `Info` shows the output in mqtrigger-kafka pod. 

https://github.com/fission/fission/blob/9c3195a84ea20617a88acfc5b432bdd44902e73c/pkg/mqtrigger/messageQueue/kafka.go#L208

This is confusing because the docs show output like this
```
time="2018-10-29T10:46:12Z" level=info msg="Calling message handler with value {"name": "value 2018-10-29T10:46:12Z "}" 
time="2018-10-29T10:46:12Z" level=info msg="Making HTTP request to http://router.fission/fission-function/consumer-func" 
time="2018-10-29T10:46:12Z" level=info msg="Got response Hello {"name":"value 2018-10-29T10:46:12Z "}" 
```

Maybe we should fix the logs shown in the docs or revert the response body to `Info` instead of `Debug` because it is a little difficult to see if the consumer func was actually called unless you use a third party tool like Pixy.

**Comment by life1347** [comment]
You can adjust the log level by setting 
https://github.com/fission/fission/blob/97b9350651a685477b4e2f7d35ea18bb2280d2c9/charts/fission-all/templates/deployment.yaml#L681-L682
It's intentional to set the log level to `Debug` to prevent performance issue if we're under heavy workloads.

BTW, the log level adjustment is mentioned in the [release highlight](https://docs.fission.io/releases/1.4.1/#log-level-through-environment-variable).

**Comment by life1347** [comment]
Also, I think you should check function log instead of mqtriger to see if a function was invoked.
