### ISSUE TITLE
Use Kubernetes ThirdPartyResources for storing state

### ISSUE THREAD

**Issue by kfox1111** [fission/fission#129]
Kubernetes has a 3rd party resource type that allows extending the kubernetes api by 3rd parties.

It would be very interesting to add support for this in fission. The user could then upload an environment description as a 3rd party object, and the script file itself as a 3rd party object.

This even would allow the user to deploy those objects in helm charts along with other k8s objects.

**Comment by soamvasani** [comment]
Closing, we've switched to TPRs a while ago (and will be switching to CRDs soon).
