### ISSUE TITLE
Fission will not install due to "extensions/v1beta1" Deployment deprecation

### ISSUE THREAD

**Issue by GIG0i** [fission/fission#1329]
**Fission/Kubernetes version**

Fission version: 1.5.0 or 1.4.1
Kubernetes version: 1.16.0

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Minikube

**Describe the bug**
I'm having an issue installing Fission from scratch on a local Minikube fresh installation and apparently running into this issue where Fission will not install either with Helm or directly by giving the following error:
```
error: unable to recognize "deployment": no matches for kind "Deployment" in version "extensions/v1beta1"
```

Which I think is because this has just been deprecated in the latest Kubernetes version (see section "Significant Changes to the Kubernetes API"):
https://kubernetes.io/blog/2019/09/18/kubernetes-1-16-release-announcement

**To Reproduce**
Install Fission through Helm or without Helm.

**Expected result**
Fission installs correctly.

**Actual result**
Fission fails installing with the following error:
```
error: unable to recognize "deployment": no matches for kind "Deployment" in version "extensions/v1beta1"
```

**Comment by GIG0i** [comment]
For additional context the same issue is affecting Helm itself https://github.com/helm/helm/issues/6374

**Comment by TaylorMonacelli** [comment]
```minikube start --kubernetes-version v1.15.4``` works around this for me for now.
