### ISSUE TITLE
Move Ingress to networking.k8s.io/v1beta1 before 1.18 release

### ISSUE THREAD

**Issue by life1347** [fission/fission#1330]
According to this is PR (https://github.com/kubernetes/kubernetes/pull/74057), Ingress is moving to `networking.k8s.io/v1beta1`. `extensions/v1beta1` objects will be deprecated in 1.18. We should update ingress related functions and bump minimum requirement kubernetes version to 1.14 in order to make sure fission works as expected. For now, we can stick to `extensions/v1beta1` and upgrade to `networking.k8s.io/v1beta1` when 1.18 is out.

**Comment by sanketsudake** [comment]
This is now fixed, would be available in the upcoming 1.14 release.
