### ISSUE TITLE
Ability to update secret&configmap with fn update

### ISSUE THREAD

**Issue by life1347** [fission/fission#1357]
We should be able to update the secret&configmap through `fn update`
```
fission fn update --name xxx --secret yyy
```

**Comment by viveksinghggits** [comment]
Hi @life1347 ,
I have started working on this.

**Comment by viveksinghggits** [comment]
Hi @life1347 
If the function is already created with n secrets and we run below command 
```
fission fn update --name <fn-name> --secret <secret-name>
```
the function should get update with one secrets <secret-name> or the should now have `n+1` secrets.

**Comment by life1347** [comment]
I would suggest replacing the entire existing list of secrets/configmaps with new list provided by the user. And so you may need to emphasize the "replace" instead of "append" nor "merge" operation at flag usage.

**Comment by viveksinghggits** [comment]
I agree, if they want to merge new secrets it better that they remember the secrets/configmaps they created the function with.

**Comment by life1347** [comment]
Hmm, it's related to CLI UX. Could you also update the `fission fn list` to show the list of secrets/configmaps? so that they don't need to remember all of them.

**Comment by viveksinghggits** [comment]
Hi @life1347,
I can do that, do you want me to do that as part of same PR.

**Comment by life1347** [comment]
That would be great if we can ship them in the same PR.

**Comment by viveksinghggits** [comment]
Changing output of `fission fn list ` in such a way that it will show functions in below format
```
NAME UID                                  ENV    EXECUTORTYPE MINSCALE MAXSCALE MINCPU MAXCPU MINMEMORY MAXMEMORY TARGETCPU
hi   9f123d02-f318-11e9-9a0b-08002766cde0 python poolmgr      0        0        0      0      0         0         0

```

**Comment by life1347** [comment]
yeap, let's go this way!
