### ISSUE TITLE
How to import a WebAssembly file from a Node.js package?

### ISSUE THREAD

**Issue by robinvanemden** [fission/fission#1384]
I am trying to load a WebAssembly module.wasm file from a main Node.js index file, like so:

```
...
fetch('module.wasm').then(response =>
  response.arrayBuffer()
...
```

The code works perfectly when I run it locally, using

`node index.js`

But when I try to run it as an function (both files zipped, and following the instructions) I receive:

`Fatal error: Failed to execute HTTP request: Get http://127.0.0.1:40073/fission-function/lll: context deadline exceeded`

I have the idea the index.js might not be able to load or find the module.wasm - could that be the case? Do I need to make it available through package.json in some way? Or custom build the package?

**Comment by life1347** [comment]
You can use following commands to see what's happening in the function pod.
```
# get pod that runs the function
$ kubectl -n fission-function get pod -l functionName=<fn-name> 

# show container log
$ kubectl -n fission-function logs -f -c <container> <pod-name>
```

Not sure whether Node supports to get the real path of loading file. But if the failure reason in log is that the node cannot find the wasm, you may be able to load the wasm at the path `/userfunc/xxx/yyy.wasm`.

```
/ # tree -L 2 /userfunc
/userfunc
├── some-random-string
│   ├── README.md
│   ├── README_V1.md
│   └── hello-callback.js
└─── xxxxx.wasm
```

**Comment by robinvanemden** [comment]
Thank you! Very useful. By being able to see what was happening within the function pod, I could establish that the WASM file loaded just fine, but that I messed up my promises.

**Comment by life1347** [comment]
For reference, once PR #1529 is merged, people will be able to find their file in real path `/userfunc/deployarchive`.
