### ISSUE TITLE
Resource create should return a Location header

### ISSUE THREAD

**Issue by RobertHerhold** [fission/fission#143]
![image](https://cloud.githubusercontent.com/assets/8069753/23656841/4fc90a88-0309-11e7-855b-ade7370c37c1.png)

Deleting a non-existant resource throws a 500, but I would think it would make more sense as a 404. There are also other status code discrepancies; creating a resource returns 200 instead of 201

**Comment by soamvasani** [comment]
The non-existent resources error code is already fixed by @tobias in #121.

**Comment by soamvasani** [comment]
Didn't mean to close it; the location header still needs to be added.
