### ISSUE TITLE
Fission function calls failing when the pod goes in terminating state instead of warming up a new pod to handle the request it give server error.

### ISSUE THREAD

**Issue by rakeshbshukla** [fission/fission#1463]
We are seeing a strange issue with the fission function execution. When we hit the function a new pod is warmed up executes and gives the output as requested. But after sometime when the pod goes to terminating state and a request comes in the router throws the below error 

{"level":"info","ts":1575577817.4312112,"logger":"executor_client","caller":"client/client.go:103","msg":"tapped services in batch","service_count":1}
{"level":"error","ts":1575577817.9926271,"logger":"triggerset.http_trigger_set.2ed7f0a8-a678-4296-ac24-0c1e108b67b7.roundtripper","caller":"router/functionHandler.go:332","msg":"request errored out - removing function from router's cache and requesting a new service for function","**url":"10.244.0.210:8888","function_name":"csv-to-**json","stacktrace":"github.com/fission/fission/router.RetryingRoundTripper.RoundTrip\n\t/go/src/github.com/fission/fission/router/functionHandler.go:332\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:232\ngithub.com/fission/fission/router.functionHandler.handler\n\t/go/src/github.com/fission/fission/router/functionHandler.go:443\ngithub.com/fission/fission/router.functionHandler.handler-fm\n\t/go/src/github.com/fission/fission/router/httpTriggers.go:179\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1964\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission/router.(*mutableRouter).ServeHTTP\n\t/go/src/github.com/fission/fission/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.18.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2741\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1847"}

which i think is expected behavior and it tries to warm a new pod.
But as i see from the logs the router gives the same service url as previous terminating pod
{"level":"info","ts":1575577817.9928656,"logger":"triggerset.http_trigger_set.2ed7f0a8-a678-4296-ac24-0c1e108b67b7","caller":"router/functionHandler.go:544","msg":"calling getServiceForFunction","function_name":"csv-to-json"}
{"level":"info","ts":1575577817.9967723,"logger":"triggerset.http_trigger_set.2ed7f0a8-a678-4296-ac24-0c1e108b67b7","caller":"router/functionHandler.go:554","msg":"assigning service url for function","url":"**http://10.244.0.210:8888"**,"function_name":"csv-to-json"}

**Now as the service url is same of terminating pod the request fails with server error.**

{"level":"info","ts":1575577817.9977643,"logger":"triggerset.http_trigger_set.2ed7f0a8-a678-4296-ac24-0c1e108b67b7.roundtripper","caller":"router/functionHandler.go:320","msg":"request errored out - backing off before retrying","url":"10.244.0.210:8888","backoff_timeout":3.2}
{"level":"info","ts":1575577821.1984746,"logger":"triggerset.http_trigger_set.2ed7f0a8-a678-4296-ac24-0c1e108b67b7.roundtripper","caller":"router/functionHandler.go:320","msg":"request errored out - backing off before retrying","url":"10.244.0.210:8888","backoff_timeout":6.4}
{"level":"info","ts":1575577822.4312384,"logger":"executor_client","caller":"client/client.go:103","msg":"tapped services in batch","service_count":1}
{"level":"info","ts":1575577827.598934,"logger":"triggerset.http_trigger_set.2ed7f0a8-a678-4296-ac24-0c1e108b67b7.roundtripper","caller":"router/functionHandler.go:320","msg":"request errored out - backing off before retrying","url":"10.244.0.210:8888","backoff_timeout":12.8}

**Now If once the pod in terminating state is terminated and we make a new request it again works as expected by warming a new pod.**

We are using custom python environment for execution of function. 
**Bare Metal K8s Cluster**
**Fission version:** 1.2.1
**kubernetes :** Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"**v1.12.3**", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

If you need we can provide the fission support dump as well.
Please help us figure out if there is any configuration missing from our end.

**Comment by life1347** [comment]
@rakeshbshukla thanks for the report. I suspect it's because of the check pass and so executor returns the same address.

https://github.com/fission/fission/blob/f28b58c3990ab70e38a391282ed25f84afcc22e3/executor/poolmgr/gpm.go#L297-L308

Does this problem occur very often? Is it able to reproduce the problem by manually delete the function pod?

I can try to reproduce the problem, but it will be faster if you can reproduce the problem and share the fission dump. You can ping me and share the dump file on Slack if you don't want to make it public.

btw, is it able to reproduce the same problem with 1.7.1? because 1.2.1 is a little bit old for us and may take us a long time to trace this issue in the old version.

**Comment by rakeshbshukla** [comment]
its for 1.2 i saw now not tested on 1.7.
I will share the dump


                                                      With Regards
                                                    Rakesh Shukla

**Comment by rakeshbshukla** [comment]
Fission Dump Attached .
[fission-dump_Executor_Issue.zip](https://github.com/fission/fission/files/3954676/fission-dump_Executor_Issue.zip)

**Comment by life1347** [comment]
1. Could you provide the dump that when the error occurred? Otherwise, no useful clues in the dump logs. 
2. Could you also try to test against 1.7.1? Thanks.

**Comment by vishal-biyani** [comment]
Closing due to lack of response. Please reopen if still an issue.
