### ISSUE TITLE
MQT trigger does not fire despite being properly registered

### ISSUE THREAD

**Issue by LemurPwned** [fission/fission#1466]
**Fission/Kubernetes version**
```
Fission
client:    Version: 1.7.1
server:  Version: 1.7.0
```
```
Kubernetes Version 1.15.6
```

**Kubernetes platform (e.g. Google Kubernetes Engine)**
microk8s

**Describe the bug**
The function is not invoked despite mqt trigger being successfully registered and despite nats-streaming service operating properly.
The function has been created using:
```bash
fission fn create --name foobar --env go --src foobar.go --entrypoint Handler
```
**To Reproduce**
I built a function in .go which contains just a `Handler` function. The function is called `foobar`
Another fission function publishes onto a specific topic `foo`. I expect that if I do:
```bash
fission mqtrigger create --name new-trigger --function foobar --topic foo
```
then whenever I publish a message to the `foo` queue, the `foobar` function will be invoked.

I tested publishing and consuming separately and it works well with the `nats-streaming` service provided with the fission deployment. 

**Expected result**
The function is invoked after I publish to the topic. 

**Actual result**
There is no trace of trigger in the function logs. The function mqt trigger is registered which can be observed in the logs of the `mqtrigger-nats-streaming` pod.

If possible, could anyone direct me to an example please? I'm not sure if there should be some default endpoint for the function. I looked at the code in `fission/pkg/mqtrigger/messageQueue/nats.go` and there's this line:
```go
url := nats.routerUrl + "/" + strings.TrimPrefix(utils.UrlForFunction(trigger.Spec.FunctionReference.Name, trigger.Metadata.Namespace), "/")
```
I'm not really sure if I should create this or it's managed somewhere else.

**Comment by life1347** [comment]
HI @LemurPwned 

May I ask how you do the `publishing and consuming` cause so far I cannot think of any reasons that will fail to invocation?

Also, would you provide the logs of `mqtrigger-nats-streaming` pod? Thanks

**Comment by LemurPwned** [comment]
@life1347 thanks for your answer.
I turned on the DEBUG in the deployment env and here are the logs from the `mqtrigger-nats-streaming` pod (this is after I've sent the test messages onto the queue). 
```bash
2019-12-18T14:21:38.466Z        INFO    fission-bundle/main.go:123      skipping trace exporter registration
2019-12-18T14:21:38.988Z        INFO    message_queue_trigger_manager   messageQueue/messageQueue.go:210        message queue trigger created   {"trigger_name": "model-updated"}
2019-12-18T14:25:00.224Z        INFO    message_queue_trigger_manager   messageQueue/messageQueue.go:210        message queue trigger created   {"trigger_name": "model-updates"}
```
I registered two mqt triggers and here are the corresponding trigger lists:
```
NAME          FUNCTION_NAME     MESSAGE_QUEUE_TYPE TOPIC         RESPONSE_TOPIC ERROR_TOPIC MAX_RETRIES PUB_MSG_CONTENT_TYPE
model-updated download-function nats-streaming     model-updates                            0           application/json
model-updates download-function nats-streaming     model-updates                            0           application/json
```
These are connected to the same function.  
#### How I tested this?
I have created a consumer that listens on the same topic: in this case: `model-updates` (coincidentally, the second trigger name is the same). The dummy consumer correctly receives the message when I publish to that topic, so I know that the message actually reaches the queue. I'd expect that if I send a message to the topic, then I will see it logged in the `mqtrigger-nats-streaming`, even if the resulting message does not eventually trigger the function associated with the queue. I connect to the queue using the following address `nats://defaultFissionAuthToken@nats_pod_IP:4222` in the dummy consumer and in the publishing pod I do `nats://defaultFissionAuthToken@nats-streaming.fission:4222`. Maybe that's a problem with the internal recognition of the pod's qualified name?

**Comment by life1347** [comment]
The only strange thing I saw is that `mqtrigger-nats-streaming` doesn't print any log when receiving messages. And `nats://defaultFissionAuthToken@nats-streaming.fission:4222 looks fine for me. So I cannot really figure out where is the problem.

Would you mind to join the Slack, so that we can have a discussion for the problem?

**Comment by LemurPwned** [comment]
Ok, @life1347 helped me solve the issue.
The key is to use `nats-streaming` instead of pure `nats`. 

An example for connecting, courtesy @life1347: 
```go
import uuid "github.com/satori/go.uuid"
import nats  "github.com/nats-io/stan.go"
addr := "nats://defaultFissionAuthToken@nats-streaming.fission:4222"
nc, err := nats.Connect("fissionMQTrigger", uuid.NewV4().String(), nats.NatsURL(addr))
```
