### ISSUE TITLE
Fission using only one k8s pod

### ISSUE THREAD

**Issue by brunomanzo** [fission/fission#1494]
**Fission/Kubernetes version**

<pre>
% fission version  
client:
  fission/core:
    BuildDate: "2019-12-09T03:58:10Z"
    GitCommit: 9401c1ee8559975ffe97db27d8b3572af9f17eda
    Version: 1.7.1
server:
  fission/core:
    BuildDate: "2019-12-09T03:58:10Z"
    GitCommit: 9401c1ee8559975ffe97db27d8b3572af9f17eda
    Version: 1.7.1

 % kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
DigitalOcean k8s

**Describe the bug**

Requests are being forwarded to only one pod

**To Reproduce**

I just create a env with 3 pods, a function, a http trigger and started triggering it.
It seens requests are always on the same pod.

**Expected result**

Some requests balancing?

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by life1347** [comment]
Hi @brunomanzo, you can set executor type to newdeploy in order to have more pods for the functions. Please visit the doc site to see more details: http://127.0.0.1:1313/docs/concepts/components/core/executor/#new-deployment

**Comment by brunomanzo** [comment]
@life1347 thanks
