### ISSUE TITLE
CRD informer won't stop

### ISSUE THREAD

**Issue by life1347** [fission/fission#1495]
This is the ticket to track the issue about CRD informer won't stop.
ref: https://github.com/kubernetes/kubernetes/issues/79610

**Comment by sanketsudake** [comment]
We have moved to typed Share index informers now, so assuming this issue won't affect us. 
Need validation though with the latest upcoming release 1.14.

**Comment by soharab-ic** [comment]
Please try latest fission `v1.20.5` and re-open if issue remains.
