### ISSUE TITLE
Can't change environment gracetime 

### ISSUE THREAD

**Issue by brunomanzo** [fission/fission#1496]
**Fission/Kubernetes version**

<pre>
% fission version  
client:
  fission/core:
    BuildDate: "2019-12-09T03:58:10Z"
    GitCommit: 9401c1ee8559975ffe97db27d8b3572af9f17eda
    Version: 1.7.1
server:
  fission/core:
    BuildDate: "2019-12-09T03:58:10Z"
    GitCommit: 9401c1ee8559975ffe97db27d8b3572af9f17eda
    Version: 1.7.1

 % kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:18:23Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
DigitalOcean k8s

**Describe the bug**

I cant control gracetime of the function

**To Reproduce**

I am not being able to change the grace time of a env in fission cli.
The default is way higher than I need. By now I edited the deployment of the function to lower it but I want to make it work the right way.

**Expected result**

Lower grace time

**Actual result**
```
bruno ~/Dev/fission(master|✚1) % fission environment update --name python3 --image brunomanzo/fission-python-3.6:work --poolsize 0 --period 5
environment 'python3' updated
bruno ~/Dev/fission(master|✚1) % fission env list                                                                                            
NAME    IMAGE                              BUILDER_IMAGE POOLSIZE MINCPU MAXCPU MINMEMORY MAXMEMORY EXTNET GRACETIME
python3 brunomanzo/fission-python-3.6:work               0        0      0      0         0         false  0
bruno ~/Dev/fission(master|✚1) % fission environment update --name python3 --image brunomanzo/fission-python-3.6:work --poolsize 0 --graceperiod 5
environment 'python3' updated
bruno ~/Dev/fission(master|✚1) % fission env list                                                                                                 
NAME    IMAGE                              BUILDER_IMAGE POOLSIZE MINCPU MAXCPU MINMEMORY MAXMEMORY EXTNET GRACETIME
python3 brunomanzo/fission-python-3.6:work               0        0      0      0         0         false  0
```
**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by life1347** [comment]
This issue has been fixed in PR https://github.com/fission/fission/pull/1476 and will be contained in 1.8.0 which should come out at end of Jan.

**Comment by brunomanzo** [comment]
@life1347 thanks for the response (again)! really enjoying fission so far
