### ISSUE TITLE
Java function not  supporting XML post request.

### ISSUE THREAD

**Issue by AshishJainRadicle** [fission/fission#1505]
fission 1.7.1

Xml post request support in java function 
 
In context of Java env, we are trying to create a function which accpets a xml request. While testing it, we run into an issue where we found that 
fission function in java seems to accept only json request. In fission\environments\jvm\src\main\java\io\fission\Server.java post mappings are defined as
@PostMapping(path = "/v2/specialize", consumes = "application/json"). 

We tried to change it as well and created a new enviroment but seems like that is not the only place where media type
pplication/json is hard coded. 

What actually we need is a capability to be able to define the media type of the request in the function it self.

Java function error with xml request:-
{
    "timestamp": "2020-01-22T09:33:33.962+0000",
    "status": 415,
    "error": "Unsupported Media Type",
    "message": "Content type 'application/xml;charset=UTF-8' not supported",
    "path": "/"
}

**Comment by AshishJainRadicle** [comment]
Hi,
I have made new image "ajain1234/xmljvm" on docker hub after added new dependency in pom.xml file which is present in (..enviroments/

**Comment by vishal-biyani** [comment]
As discussed with Saurabh and Ashish - the XML parsing loses some data. @AshishJainRadicle  - can you please paste a sample XML?

**Comment by AshishJainRadicle** [comment]
@vishal-biyani 
If post following xml in body

<Book>
	<name>Ashish</name>
	<subject>
		 <name>Math</name>
		 <name>Hindi</name>
	</subject>
</Book>

Got following in req.getBody() 

{name=Ashish, subject={name=Hindi}}

So not able de-serializing xml correctly.

**Comment by sahil-lakhwani** [comment]
I tested the above XML data, works fine for me.
I think the confusion is how the XML parsing the data inside the function. Fission will only deliver the data to the correct function, rest should be managed by the function.

Let me know what exact data loss you see.

**Comment by AshishJainRadicle** [comment]
I did not tried with above xml. I tried with following

**Comment by sahil-lakhwani** [comment]
@AshishJainRadicle Yes, that's how mapping in `RequestEntity`  from Spring Boot, used by Fission, works. If you try to map this to a Book POJO, it'll work correctly.
You can try it with a standalone Spring Boot server.
I'll let you know if I find some workaround.

**Comment by AshishJainRadicle** [comment]
Hi @sahil-lakhwani @vishal-biyani 

I am not able to map my xml request to Book POJO class
Book.java class code as following:-
   
    public class Book {
	
		private String name;
		private Subject subject;

		public String getName() {
			return name;
		}
		public void setName(String name) {
			this.name = name;
		}
		public Subject getSubject() {
			return subject;
		}
		public void setSubject(Subject subject) {
			this.subject = subject;
		}
	
    } 
 
  Subject.java  class code as following:- 
  
    public class Subject {

		private List<String> name;

		public List<String> getName() {
			return name;
		}
		public void setName(List<String> name) {
			this.name = name;
		}
    }
	
   
 1- Get method code producing Book object as a APPLICATION_XML response type header
   
   
    @Override
	public ResponseEntity call(RequestEntity req, Context context) {
		final HttpHeaders httpHeaders =  new  HttpHeaders();
		try {
				
			  Book book = new Book();
			  book.setName("Ashish");
			 
			  Subject subject = new Subject(); 
			  List<String> subjects = new ArrayList<>();
			  subjects.add("hindi"); 
			  subjects.add("math"); 
			  subject.setName(subjects);
			  
			  book.setSubject(subject);
			 		
			  httpHeaders.setContentType(MediaType.APPLICATION_XML);
			  return new ResponseEntity(book, httpHeaders, HttpStatus.OK);
		}catch(Exception e) {
			LOG.error("e",e.getMessage());
			final StringBuffer sb= new StringBuffer();
			sb.append(e.getMessage());
			httpHeaders.setContentType(MediaType.TEXT_PLAIN);
			return new ResponseEntity<>(sb, httpHeaders, HttpStatus.OK);
		}
	}

    getting resopnse as following:-
	
	<Book><name>Ashish</name><subject><name><name>hindi</name><name>math</name></name></subject></Book>
	     but It should be as following
	<Book><name>Ashish</name><subject><name>hindi</name><name>math</name></subject></Book>
	
2- 	Post method code which producing Book object as a APPLICATION_XML response type header

    @Override
	public ResponseEntity call(RequestEntity req, Context context) {
		final HttpHeaders httpHeaders =  new  HttpHeaders();
		try {
			ObjectMapper mapper =  new ObjectMapper();
			Book book = mapper.convertValue(req.getBody(), Book.class);
			httpHeaders.setContentType(MediaType.APPLICATION_XML);
			return new ResponseEntity(book, httpHeaders, HttpStatus.OK);
		}catch(Exception e) {
			LOG.error("e",e.getMessage());
			final StringBuffer sb= new StringBuffer();
			sb.append(e.getMessage());
			httpHeaders.setContentType(MediaType.TEXT_PLAIN);
			return new ResponseEntity<>(sb, httpHeaders, HttpStatus.OK);
		}
	}    
 
    -When i am post request with body  "<Book><name>Ashish</name><subject><name><name>hindi</name><name>math</name></name></subject></Book>" it is giving response as
	    "Cannot deserialize instance of `java.lang.String` out of START_OBJECT token" 
		
	-When i am post request with body  "<Book><name>Ashish</name><subject><name>hindi</name><name>math</name></subject></Book>" it is giving response as
	   <Book><name>Ashish</name><subject><name><name>math</name></name></subject></Book>
	   
	Here,you can clearly see data has been lost in out put.

I have also tried with @XmlAttribute and @XmlElement but did not work.

**Comment by vishal-biyani** [comment]
As per comment here: https://github.com/fission/fission/pull/1541#issuecomment-626806287 closing this for now.

**Comment by vishal-biyani** [comment]
With https://github.com/fission/fission/pull/1677 merged - XML now works with new JVM environment.
