### ISSUE TITLE
Prometheus defaults to deployed in `-core` against documentation

### ISSUE THREAD

**Issue by davidsmf** [fission/fission#1510]
**Fission/Kubernetes version**

1.7.1, helm charts

**Describe the bug**

Documentation at https://github.com/fission/fission/blob/master/charts/README.md says "prometheus.enabled=false" for `fission-core`.

https://github.com/fission/fission/blob/master/charts/fission-core/values.yaml says `enabled: true`

Looks like the mistake was in copy/paste in this commit: 

https://github.com/fission/fission/commit/b5c8ea0e1398c5df510297145232d4dea9f6bac8#diff-53cb7a10c38d04eb63bcf14cc9290639

**Comment by life1347** [comment]
oops, thanks for your feedback!
