### ISSUE TITLE
Add timer trigger API and client

### ISSUE THREAD

**Issue by yqf3139** [fission/fission#153]
Timer trigger is quite useful. It invokes the target function like cron.

Related actions:
- List: return the timer uid, function metadata, cron variables and status
- Create: create a stopped timer trigger by sending a timer trigger metadata (uid, name optional for description ), a function metadata, cron variables in a string and status(running, stopped)
- Delete: by sending a timer metadata
- Update: by sending a timer metadata, cron variables and status

Features nice to have: parameter binding, history

**Comment by tobilarscheid** [comment]
How would that interface with kubernetes cron jobs?

**Comment by yqf3139** [comment]
@tobilarscheid It is a separated implementation and does not interfere with kubernetes cron jobs.

**Comment by soamvasani** [comment]
Fixed by #161
