### ISSUE TITLE
HTTPS for deployment file and CLI binaries

### ISSUE THREAD

**Issue by abglassman** [fission/fission#154]
If possible, it would be great to have HTTPS for the deployment YAML files and the CLI binaries in the getting started/installation instructions. I'm sure I'm not the only one whose spine goes a-tingle downloading and running binaries over insecure connections. Thanks in advance.

**Comment by soamvasani** [comment]
Yeah, I hear you.  We'll move to github releases to host those files from the next release, which should be pretty soon.

**Comment by soamvasani** [comment]
Switched to github releases now, all install instructions are updated too.
