### ISSUE TITLE
Fission function pod timing out after 500 secs

### ISSUE THREAD

**Issue by rakeshbshukla** [fission/fission#1546]
Facing issue with fission function pod. After 500 secs the pod terminates even if the function is still running.
" http: proxy error: error sending request to function fire-unix-command: EOF"
I can see the below error in logs

Feb 27 03:42:47 xxx journal: 27-02-2020 09:42:47[ERROR][user print]:   InsecureRequestWarning)
Feb 27 03:42:47 xxxx kubelet: W0227 03:42:47.784507   25194 prober.go:104] No ref for container "docker://ccfaaf4d6cf19e2b266956480c1bb43cab3746045b9cf
876a9926418a19a7e2b" (poolmgr-atomiq-py-security-fission-function-mr2famkk-545ffljj2w_fission-function(7d7d58c4-ace6-4399-b75d-c4d174df7212):fetcher)
Feb 27 03:42:47 xxxx journal: 27-02-2020 09:42:47[INFO ][fire-unix-command:<received empty from SNOW> and populated by NiFi]: [user print]: 545
Feb 27 03:42:47 x kuxxxxbelet: W0227 03:42:47.920754   25194 prober.go:104] No ref for container "docker://b2270424231a004637d832ca265eec1be087d95b5d34b
345c16cd46dcd71f83e" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c957bcm7_fission-function(adefd5bf-1f0c-4a53-9b74-96693df16350):fetcher)
Feb 27 03:42:48 x kubelexxt: W0227 03:42:48.114187   25194 prober.go:104] No ref for container "docker://38c1c1c32c2acc3303c0a29766e55453f9ab483d99b59
118c3f6a5604fd65c1a" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c955csbk_fission-function(3af5bb57-cd00-4fa5-9360-6126d7545677):fetcher)
Feb 27 03:42:48 cmildev171 kubelet: W0227 03:42:48.255731   25194 prober.go:104] No ref for container "docker://a7c93c8c1d6acc18b34cc87102c70378da98aed644300
52d30933928fd180573" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c95jvj54_fission-function(bcc60c01-da42-447f-8972-6083eb0430c3):fetcher)
Feb 27 03:42:48 cmildev171 kubelet: W0227 03:42:48.261514   25194 prober.go:104] No ref for container "docker://36d3684e02bea070a26d21e9b87ff127e5a68b265e1a2
50eafec478c56d83261" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c95qmzbq_fission-function(a939715e-5415-4d34-a2a7-4b727e024339):fetcher)
Feb 27 03:42:48 cmildev171 kubelet: W0227 03:42:48.299585   25194 prober.go:104] No ref for container "docker://38c1c1c32c2acc3303c0a29766e55453f9ab483d99b59
118c3f6a5604fd65c1a" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c955csbk_fission-function(3af5bb57-cd00-4fa5-9360-6126d7545677):fetcher)
Feb 27 03:42:48 cmildev171 kubelet: W0227 03:42:48.390598   25194 prober.go:104] No ref for container "docker://7e6bb9a1b00bb5345e7962a9ec215d782323f1afb8fc9
35cdca67c1bb5d0735b" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c95x6m2d_fission-function(add7d2c4-3c09-483d-b742-3ef0bae700ec):fetcher)
Feb 27 03:42:48 xxxxx kubelet: W0227 03:42:48.467440   25194 prober.go:104] No ref for container "docker://592d6ff44c6ae765fb00c6dfdb7d3d52fdd7387dff5cd
9273f39a6cce63ba925" (poolmgr-atomiq-py-ssh-fission-function-cdh9lufh-684f898c95ccgd8_fission-function(10c4b83b-2918-40bc-925d-e56458b51e78):fetcher)
Feb 27 03:42:48 xxxxx dockerd-current: time="2020-02-27T03:42:48.492511701-06:00" level=info msg="Container 9fb67a1880bc036d68e5ab548df66c2fb4aefb5f2724
e125da7e8e5dae123e30 failed to exit within 2 seconds of signal 15 - using the force"
Feb 27 03:42:48 xxxxxx dockerd-current: time="2020-02-27T03:42:48.507837995-06:00" level=info msg="Container c42ed7f6944359617e075ae22f3bd46ef59cebcff2c0
c4681953208bd69daf2b failed to exit within 2 seconds of signal 15 - using the force"
Feb 27 03:42:48 xxxx journal: 2020/02/27 09:42:48 **http: proxy error: error sending request to function fire-unix-command: EOF**
Feb 27 03:42:48 xxxx journal: 10.78.50.200 - [10.78.50.200] - - [27/Feb/2020:09:42:48 +0000] "POST /default/atomiq_py_ssh/fire_unix_command HTTP/2.0" 5
02 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36" 1119 546.257 [fission-router-8
0] 10.244.0.103:8888 0 546.246 502 3ea1cb26983347c06ffb871abed0e357

<pre>
=================Fission: =========================
client:
  fission/core:
    gitcommit: 518ab3b90d6d4085e653ef36feb6b34500940823
    builddate: "2019-05-09T08:24:19Z"
    version: 1.2.1
server:
  fission/core:
    gitcommit: 518ab3b90d6d4085e653ef36feb6b34500940823
    builddate: "2019-05-09T08:24:19Z"
    version: 1.2.1
================================================
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:09:21Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

===================================================
</pre>

*Created a python function with a for loop for 900 and having just a sleeping and printing value of variable i. Ingress timeout is already increased to 3600

**Comment by vishal-biyani** [comment]
Hey @rakeshbshukla We have added function timeout and also there are quite a few router tunable parameters in later releases were added:  

https://github.com/fission/fission/blob/master/charts/fission-all/values.yaml#L114-L141

Will you be able to install the latest release and see if you can reprod=uce this, please?

**Comment by rakeshbshukla** [comment]
Sure @vishal-biyani  thanks will do the testing and get back to you.

**Comment by vishal-biyani** [comment]
Hi @rakeshbshukla Closing this for now as we have not seen further updates. Please reopen/create a new issue if needed.
