### ISSUE TITLE
Nats streaming integration cluster ID is hardcoded

### ISSUE THREAD

**Issue by samoscybercraig** [fission/fission#1549]
**Fission/Kubernetes version**

<pre>
Fission client: v1.8.0
Fission server: v1.8.0
</pre>

<pre>
Kubernetes Client Version: v1.17.3
Kubernetes Server Version: v1.17.3
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

Minikube

**Describe the bug**

When using an "external" nats streaming cluster with fission, it is not possible as the cluster id required is hardcoded in the mqtrigger container which communicates with the nats-streaming element [CODE](https://github.com/fission/fission/blob/e7c0ff7d41b9ef93b60827314ff255c5b685134e/pkg/mqtrigger/messageQueue/nats.go#L35). Also the boolean in values.yaml for nats controls both nats-streaming and mqtrigger, one can't choose false to create their own nats streaming but true for mqtrigger and pass url,port,authentication and cluster id. This however can be achieved by manually adjusting the helm charts, however the main bug exists that setting cluster id is not used in the mqtrigger. 

Cluster IDs in generic clusters should be configurable, this cannot be tested with the nats-streaming operator as it uses the hostname from the FQDN as the cluster. On validation the operator errors if using the "default" fission cluster id, as it is mixed case which is not valid for a hostname. 

**To Reproduce**
Create an external nats-streaming cluster: 

>`$ kubectl apply -f https://github.com/nats-io/nats-operator/releases/download/v0.5.0/00-prereqs.yaml`

>`$ kubectl apply -f https://github.com/nats-io/nats-operator/releases/download/v0.5.0/10-deployment.yaml`

>`$ kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-streaming-operator/master/deploy/default-rbac.yaml`

>`$ kubectl apply -f https://raw.githubusercontent.com/nats-io/nats-streaming-operator/master/deploy/deployment.yaml`

Deploy a cluster using the operator 

<pre>
echo '
---
apiVersion: "nats.io/v1alpha2"
kind: "NatsCluster"
metadata:
  name: "example-nats"
spec:
  size: 3
' | kubectl apply -f -
</pre>

<pre>
echo '
---
apiVersion: "streaming.nats.io/v1alpha1"
kind: "NatsStreamingCluster"
metadata:
  name: "example-stan"
spec:
  size: 3
  natsSvc: "example-nats"
' | kubectl apply -f -
</pre>

Now edit the fission nats streamings configuration as described in the [docs](https://docs.fission.io/docs/triggers/message-queue-trigger/nats-streaming/)

>`$ kubectl -n fission edit deployment mqtrigger-nats-streaming`

The URL for the external cluster would be 

`nats://example-nats.default:4222` with a cluster id of `example-stan`

mqtrigger container will error with 

```
2020-03-03T18:22:32.705Z	INFO	fission-bundle/main.go:123	skipping trace exporter registration
2020-03-03T18:22:32.715Z	FATAL	messageQueue/messageQueue.go:99	failed to connect to remote message queue server	{"error": "nats: no servers available for connection"}
github.com/fission/fission/pkg/mqtrigger/messageQueue.MakeMessageQueueTriggerManager
	/go/src/pkg/mqtrigger/messageQueue/messageQueue.go:99
```

**Expected result**

mqtrigger can connect to external cluster  

**Actual result**

mqtrigger can't connect to external cluster 

**Additional context**

+ mqtrigger should use cluster ID and other settings from environment or passed via args. 

+ helm charts should have `values.yaml` options to have nats enabled but an external cluster with a define auth, name, port and clusterID which is passed into mqtrigger.

**Comment by vishal-biyani** [comment]
Closed by https://github.com/fission/fission/pull/1554
