### ISSUE TITLE
Fission chart feature toggles

### ISSUE THREAD

**Issue by delucca** [fission/fission#1551]
## 🧐 The problem

In our installation of Fission we have a shell script that uses `sed` to remove a bunch of unwanted features (like logger, and so on).

## 💡 What solution do I want

It would be great if we could have a feature toggle for every non-required feature on `fission-all` chart (like logger, nats, etc). By doing so we could be also able to remove `fission-core` at all and use the feature toggles to handle it.

## 😰 What have I tried to do already

Right now, we have a script with a bunch of `sed` commands removing the unwanted resources.

## 🍪 Further details

After talking with @life1347 I've told him that we're going to try to implement this, and open a PR soon.

**Comment by hacky1997** [comment]
@vishal-biyani was it assigned to anybody?

**Comment by vishal-biyani** [comment]
@hacky1997 Not yet, do you want to give it a shot?

**Comment by sanketsudake** [comment]
We have recently merged `fission-core` and `fission-all` charts. 

More details are in 1.15 rc2 release notes.
https://fission.io/docs/releases/v1.15.0-rc2/

With merged PR, goals in this issue are achieved.
https://github.com/fission/fission/pull/2224

We have flags to enable/disable specific components.

@hacky1997 if you observe any further enhancements needed on top of the 1.15 rc2 release. Feel free to raise the issue with more flags needed.

🎉
