### ISSUE TITLE
Question: already have clusterscoped nats streaming

### ISSUE THREAD

**Issue by shaunc** [fission/fission#1553]
Newbie question (/doc request): I have a cluster with clusterscoped nats streaming, used for another purpose. I would like to try out fission. How can I set it up to use existing nats streaming cluster?

**Comment by life1347** [comment]
You can change the NATS streaming url to the existing NATS streaming service.

https://github.com/fission/fission/blob/4fb1a8fbe8e52c0b0bf4ef3f19b02a79d8639a25/charts/fission-all/templates/deployment.yaml#L588-L589

**Comment by shaunc** [comment]
ok ... hmm... so I have to patch the chart (or role my own) -- would you accept a PR to add a variable to the chart for `nats-streaming` service name?

**Comment by samoscybercraig** [comment]
So you have to have the Cluster ID named to match the one fission expects - see #1549 for some more details on it.

**Comment by shaunc** [comment]
They will be in different namespaces ... (unless there is a way to use an "externalName" service to forward? Never tried that before...) ... so I'd want url with host like -- e.g. -- `nats-streaming.nats-io.service.cluster.local`

**Comment by vishal-biyani** [comment]
Thanks for raising the issue and PR @shaunc I think this can be closed now.
