### ISSUE TITLE
Function responding 504 (Request Time out) when trying with curl request.

### ISSUE THREAD

**Issue by AshishJainRadicle** [fission/fission#1555]
@vishal-biyani 

Hi I have a function which gives response after 1-2 mins, when tested it from Fission CLI (fn test command) it runs successfully but giving Request Time out error (504) when trying with curl request.

I have set the nginx proxy-read-timeout to 15 min. but it is still giving same 504 time out. 

1- We have created function "sleeptime" which can take sleeptime in query parameter (default is 
     30s).Url as following
   `https://fission.lingkcore.com/sleeptime?sleeptime=60`
2- I used below command to create this function :-
 ` fission-cli-windows.exe fn create --name sleeptime --pkg  fission-zip-wajb --env java-xml --entrypoint  com.lingk.fission.api.HelloWorld --fntimeout 1200`
   You can see that we are giving --fntimeout value to 20 mins.  Without this, the default values is 60s. If we provide a sleeptime value more than 50s without specifying --fntimeout then
   will get timeout error in fission test command as well.(Error calling function sleeptime: 504; Please try again or fix the error: function not responses before the timeout)
3- Without switch --timeout in test function command we get exception this "context deadline exceeded" even though -fntimeout 1200  was defined.
   `fission-cli-windows fn test --name=sleeptime -q sleeptime=120 --timeout=1200s`
   Execution successful
  ` fission-cli-windows fn test --name=sleeptime -q sleeptime=120`
   Result into error "context deadline exceeded"
4- In any kind of time out, the function is still executing and completes execution, this is evident from function log.
5- While calling from Postman, even after having 1200s as the fntime, ingress timeout of 15min, we are still getting a 504 timeout after 60 sec (https://fission.lingkcore.com/sleeptime?sleeptime=60). (edited)

**Comment by AshishJainRadicle** [comment]
@vishal-biyani ,
Any update on this...

**Comment by vishal-biyani** [comment]
Hey @AshishJainRadicle Looking into the issue, will update shortly.

**Comment by hd40910** [comment]
Hi @vishal-biyani ,

Any update on this. The same is happening for us. 
We could find the following in the fission router logs.

{
    "level": "error",
    "ts": 1594395554.2920804,
    "logger": "triggerset.http_trigger_set.nft-ba-sstest-11-atom-1",
    "caller": "router/functionHandler.go:650",
    **"msg": "error sending request to function",
    "error": " - error updating service address entry for function nft-ba-sstest-11-atom-1_default: error posting to getting service for function: context deadline exceeded",**
    "function": {
        "metadata": {
            "name": "nft-ba-sstest-11-atom-1",
            "namespace": "default",
            "selfLink": "/apis/fission.io/v1/namespaces/default/functions/nft-ba-sstest-11-atom-1",
            "uid": "116115d2-35e9-45cf-ad5a-6c11c2d28b31",
            "resourceVersion": "607752",
            "generation": 1,
            "creationTimestamp": "2020-07-10T15:03:53Z",
            "annotations": {
                "fission-name": "nft-ba-sstest-11-atom-1",
                "fission-uid": "default-test-py-database-nft-ba-sstest-11-atom-1"
            }
        },
        "spec": {
            "environment": {
                "namespace": "fission-function",
                "name": "test-py-database"
            },
            "package": {
                "packageref": {
                    "namespace": "default",
                    "name": "nft-ba-sstest-11-atom-1",
                    "resourceversion": "607747"
                }
            },
            "secrets": null,
            "configmaps": [
                {
                    "namespace": "default",
                    "name": "account-configmap"
                }
            ],
            "resources": {},
            "InvokeStrategy": {
                "ExecutionStrategy": {
                    "ExecutorType": "poolmgr",
                    "MinScale": 0,
                    "MaxScale": 0,
                    "TargetCPUPercent": 0,
                    **"SpecializationTimeout": 120**
                },
                "StrategyType": "execution"
            },
            **"functionTimeout": 540,
            "idletimeout": 540**
        }
    },
    "request_header": {
        "Accept": ["text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2"],
        "Authorization": ["Basic Zmlzc2lvbjpmaXNzaW9u"],
        "Cache-Control": ["no-cache"],
        "Content-Length": ["385"],
        "Content-Type": ["application/json"],
        "Pragma": ["no-cache"],
        "Uber-Trace-Id": ["91b88eb42a6b4331b5b3f8cc9a88867c:8993dae099d8c4aa:0:3"],
        "User-Agent": ["JESI9.9sp14"],
        "X-Fission-Full-Url": ["/default/test_py_database/nft_ba_sstest_11_atom_1"],
        "X-Fission-Function-Name": ["nft-ba-sstest-11-atom-1"],
        "X-Fission-Function-Namespace": ["default"],
        "X-Fission-Function-Resourceversion": ["607752"],
        "X-Fission-Function-Uid": ["116115d2-35e9-45cf-ad5a-6c11c2d28b31"],
        "X-Forwarded-For": ["10.244.0.66, 10.244.0.241"],
        "X-Forwarded-Host": ["nginx-ingress-controller.kube-system.svc.cluster.local"],
        "X-Forwarded-Port": ["443"],
        "X-Forwarded-Proto": ["https"],
        "X-Real-Ip": ["10.244.0.66"],
        "X-Request-Id": ["0212977ee46b1aca497c3367cd01092b"],
        "X-Scheme": ["https"]
    }
}

**Comment by vishal-biyani** [comment]
This has been closed as described in the issues links in the previous comment.
