### ISSUE TITLE
How to use istio for authorization, circuit breaking...

### ISSUE THREAD

**Issue by toonsevrin** [fission/fission#1558]
Hi, I think the istio integration is great :tada:, I am wondering: How can we use it for more then just monitoring? Is there a way to specify istio policies on a per-function basis? If so, can you provide some examples of the following:
- Authorize only specific functions to call a function
- Add [a circuit breaker](https://istio.io/docs/tasks/traffic-management/circuit-breaking/) to a function

I assume this is relatively simple with the New-Deployment [executor](https://docs.fission.io/docs/concepts/components/core/executor/) but is there a best practice for the PoolManager executor?

Should we simply add our destination policies to the router service?

Should we create a virtual service for each function that points to the router, and add our logic to the virtual service?

EDIT: I am assuming the virtual service option is the way for this, can anyone confirm?

**If someone can provide the best practices for this, I'll update the documentation**

**Comment by vishal-biyani** [comment]
Hi @toonsevrin I haven't tried Istio for internal function routing policies. I think virtual service for the function's URL should do it but I am not 100% sure. If you are going to try it - would you mind sharing your findings and we can have a blog/doc update for it.

**Comment by toonsevrin** [comment]
@vishal-biyani I see but sadly enough I won't be able to give you our insights in the near future. It appears like we're moving more and more towards everything as a gRPC service and as I don't think Fission allows for gRPC interfaces, we are not adopting fission just yet :(

**Comment by vishal-biyani** [comment]
Thanks for update @toonsevrin Yes GRPC support is not there yet. I will loop you in when we add GRPC support.

**Comment by toonsevrin** [comment]
Awesome, I'm really looking forward to that. 

Once released, we'll definitely deploy some less critical production services with it (and experiment with the combination of istio), so please do keep me in the loop :)
