### ISSUE TITLE
Use fission api

### ISSUE THREAD

**Issue by JieWaZi** [fission/fission#1559]
I want to use fission in my application.How can i use fission api to deploy a function or an environment?
I don't want to use fission cli to control fission.I want to use rest api to control。what should i do？

**Comment by life1347** [comment]
Hi @JieWaZi you can follow the openAPI spec to connect to fission controller, see https://docs.fission.io/docs/releases/1.5.0/#openapi-2-0-swagger-api-doc for details.

**Comment by JieWaZi** [comment]
thank you!

**Comment by JieWaZi** [comment]
can you give an example to use api. I see the api-doc but don't know the url i can use.for example i want to get the environment.the url is localhost:8001/..... ? i can't understand

**Comment by JieWaZi** [comment]
@life1347 can you help me？ i don't know the real url

**Comment by life1347** [comment]
solved at Slack. Close it
