### ISSUE TITLE
Fission integration with KEDA

### ISSUE THREAD

**Issue by salluvada** [fission/fission#1565]
Given that KEDA (https://keda.sh/) is supporting various scalers, can they be used with Fission to provide pro-active horizontal pod autoscaling so that Fission functions can autoscale proactively based on the incoming demand rather than reactively using CPU that it currently does?

**Comment by vishal-biyani** [comment]
Hey, @salluvada Thanks for raising the issue. Although I am not super familiar with Keda in detail - at first glance, it looks like this could be super useful. Do you want to take this up? I can guide you on the Fission side of code.

**Comment by salluvada** [comment]
Sure @vishal-biyani  I am still getting warmed up to the implementation details of both Fission and Keda. It should be an interesting item to take up. Please provide me the necessary details on the Fission side.

**Comment by salluvada** [comment]
Based on the initial analysis, the integration looks straight forward. When a function is created using the newdeploy executor type, the newdeploymgr should emit a KEDA ScaledObject (https://keda.sh/docs/concepts/scaling-deployments/) instead of a FunctionHPA and let KEDA control the deployment scaling. The KEDA scaling trigger spec can be accepted as an input file by the fission cli and passed to the newdeploymgr so that the trigger spec would be used in constructing the spec for KEDA ScaledObject.

**Comment by vishal-biyani** [comment]
Hey, @salluvada Thanks for details and a brief. I had a look at Keda project and here are my thoughts:

- Current HPA and scaling of function are purely based on CPU of a given function and when we adopt HPA V2 - potentially other parameters such as memory, etc. This scaling is still useful for many use cases and it would be good to have it.

- Project Keda's majority of current scalars are MQ/DB based except some which are Monitoring systems such as Prometheus based. 

I think in terms of integrating Keda with Fission I see two things, one immediate term, and one slightly longer term

- [Short/Immediate Term] I think Keda would be a great fit for abstracting our queue-based trigger implementations (Kafka, Azure Storage Queue, etc.) and making those integrations more dynamic - such that the integration pods are created by Keda when there is actual messages in any queue. We can define scalars for all the queue types in one pod of Keda. This is different than the current model of creating one pod for each integration. If you are interested, we can work on designing this and get this in Fission.

- [Long term] We could use Keda's monitoring metrics to autoscale. Although this is a much bigger and impacts the core parts so we would have to do a detailed design and understand the impact.

**Comment by salluvada** [comment]
@vishal-biyani  that is interesting. Let's work on designing for the short term needs and making it happen.

**Comment by vishal-biyani** [comment]
Fixes: https://github.com/fission/fission/issues/1162

**Comment by vishal-biyani** [comment]
Hey @salluvada The keda integration is ready to be merged with Kafka as an initial connector (https://github.com/fission/fission/pull/1657). We are also working on other connectors such as RabbitMQ and NATS. Do you need any other connectors and would like to contribute? Please free to pick up any connector from the issue: https://github.com/fission/fission/issues/1663

**Comment by vishal-biyani** [comment]
We will close this issue and track connectors development in #1663
