### ISSUE TITLE
General release for fission-java-core ?

### ISSUE THREAD

**Issue by PraveenGNair** [fission/fission#1579]
We are accessing fission, so that we can use in our jvm environment But found that fission-java-core module is still in SNAPSHOT version, and that cannot be used as per company policies. Is there any ETA for a release version ?

**Comment by vishal-biyani** [comment]
Hi @PraveenGNair With the new JVM jersey merged and new version of the dependency is also available now here: https://search.maven.org/artifact/io.fission/fission-jvm-jersey/0.0.1/jar 

I will close this issue for now but please reopen another one if you find something when trying the new environment. We will also update the blog & docs as part of the release next week.
