### ISSUE TITLE
Retrieve URL params in functions

### ISSUE THREAD

**Issue by nouney** [fission/fission#158]
We can use `gorilla/mux` URL params when defining a route but we can't retrieve them in functions. 

Maybe could we add them in the query string or HTTP headers?

**Comment by yqf3139** [comment]
I think add them in the headers is a good idea.
For example, X-Fission-Params-${key}: ${value}.

**Comment by sbfaulkner** [comment]
alternate approaches could be...

(all examples below use a route of `/path/{x}/{y}` and path of `/path/1/2`)

1. url encoding the key value pairs into a single X-Fission-Params header

    eg.  the resulting header could be `X-Fission-Params: x=1&y=2`

2. adding params to the query string with a prefix

    eg.  the resulting request_uri could be `/?_fission_x=1&_fission_y=2`

3. adding params to the query string using "nested" params

    eg.  the resulting request_uri could be `/?_fission[x]=1&_fission[y]=2`

**Comment by sbfaulkner** [comment]
thoughts @soamvasani ?

**Comment by soamvasani** [comment]
I think the first option of using one header per param is the most obvious thing to do.  (The only catch is, since the path can contain `:`s, we'd need to escape them in the header.)

Looks like @yqf3139 already has a fix in progress.

**Comment by yqf3139** [comment]
@soamvasani 
I just made some test for the `:`. The original fix works well.
