### ISSUE TITLE
Custom metric for HPA for fission function based on outstanding messages in Kafka

### ISSUE THREAD

**Issue by msshroff** [fission/fission#1582]
This is "new feature request" not issue.

Currently we are using Fission Functions and Kafka MQT. 
For the fission functions deployed in newDeploy, we want to use HPA. 

Currently we can use CPU  utilization as HPA metrics, using --targetcpu while creating fission function. 

We think outstanding messages in kafka topic can be a better metric autoscale the PODs. 

Please consider the request. 

Thanks
Mehul S.

**Comment by vishal-biyani** [comment]
Hi, @msshroff This essentially is a feature request for enabling custom metrics. Once that is possible then the user can actually create a trigger with any custom metric (including number of messages in queue). We are tracking this request. here: https://github.com/fission/fission/issues/854 so I will close this issue for now.
