### ISSUE TITLE
Fission Pods stuck at Terminating state when autoscaling with metrics server is enabled

### ISSUE THREAD

**Issue by rakeshbshukla** [fission/fission#1583]
Bare metal 3 node cluster with 2 worker nodes.
We have seen this issue when the metrics server is enabled auto sclaing feature works fine but when it comes to scale down. The pod is stuck in terminating state. I see controller events SuccessfulCreate and SuccessfulDelete entry in events but the pod is still stuck in terminating state for more than 30 mins.

Kubernetes Version:
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Fission : 1.8.0

 No ref for container "docker://e5d63817a394395317209c2369449f65c746ca402b67623b42997a824c006c5d" (newdeploy-router-default-9ac4-a9f6281f13f3-6895566f
go:108] No ref for container "docker://d49c737d60199b50715f070eb0a0642ab88626cfeddbb26b7fb7433acb937875" (newdeploy-metric-processing-fission-function-9f96-4
go:108] No ref for container "docker://c6234fb710cf26542404501f2e33b908488f2091f9667b593101eade48416f5d" (newdeploy-collect-jesi-raw-metrics-default-8051-943
go:108] No ref for container "docker://f66f765f27baae707c4b302c51f03a1dc7fb17d4cfe0dd76722e83c33e72d71d" (newdeploy-metrics-check-fission-function-b458-28d6d
go:108] No ref for container "docker://a8e491871b8904785e033138a873cd04c5717dbc4c918b63fda63e8944c73a5b" (newdeploy-metric-processing-fission-function-9f96-4
runtime.go:351] ExecSync 929b39ba9e84ef26eb0206a18061377cf49b7af74c3545144bffc5fd757e002e 'pgrep .*ndm' from runtime service failed: rpc error: code = Deadli

**Comment by vishal-biyani** [comment]
Hi @rakeshbshukla Closing this as there are no further updates. Please reopen/create a new one if needed
