### ISSUE TITLE
Prometheus pod won't start

### ISSUE THREAD

**Issue by brandoncollins7** [fission/fission#1584]
**Fission/Kubernetes version**

fission: 1.8.0
kube: 1.8.0

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

I pushed fission to a brand new minikube cluster yesterday. All seemed to be working fine. Today I simply restarted the same cluster and prometheus pod is failing to start with the following error:
`level=info ts=2020-04-27T13:52:47.259Z caller=main.go:332 msg="Starting Prometheus" version="(version=2.13.1, branch=HEAD, revision=6f92ce56053866194ae5937012c1bec40f1dd1d9)"
level=info ts=2020-04-27T13:52:47.259Z caller=main.go:333 build_context="(go=go1.13.1, user=root@88e419aa1676, date=20191017-13:15:01)"
level=info ts=2020-04-27T13:52:47.259Z caller=main.go:334 host_details="(Linux 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 fission-prometheus-server-649849cdd8-c7k6s (none))"
level=info ts=2020-04-27T13:52:47.260Z caller=main.go:335 fd_limits="(soft=1048576, hard=1048576)"
level=info ts=2020-04-27T13:52:47.260Z caller=main.go:336 vm_limits="(soft=unlimited, hard=unlimited)"
level=error ts=2020-04-27T13:52:47.260Z caller=query_logger.go:85 component=activeQueryTracker msg="Error opening query log file" file=/data/queries.active err="open /data/queries.active: permission denied"
panic: Unable to create mmap-ed active query log
goroutine 1 [running]:
github.com/prometheus/prometheus/promql.NewActiveQueryTracker(0x7ffe9687528f, 0x5, 0x14, 0x29db1e0, 0xc00014da10, 0x29db1e0)
	/app/promql/query_logger.go:115 +0x48c
main.main()
	/app/cmd/prometheus/main.go:364 +0x5229`
fission --version
[fission-dump_1587995755.zip](https://github.com/fission/fission/files/4540062/fission-dump_1587995755.zip)

**Additional context**
attached

**Comment by vishal-biyani** [comment]
Hi @brandoncollins7 This looks like more of an issue with Prometheus not finding a config file due to related permission on config file as reported here: https://github.com/prometheus/prometheus/issues/5976 Can you please take a look at that thread and see if anything is similar in your case?

**Comment by brandoncollins7** [comment]
It could be but I am not sure what I would do to change it, given I installed fission via helm onto a fresh cluster and made no other modifications?

**Comment by brandoncollins7** [comment]
Looks like I got it to work by setting the initContainer securityContext:

initContainers:
        - name: app-data-permission-fix
          image: busybox
          command:
            - /bin/chmod
            - '-R'
            - '777'
            - /appdata
          resources: {}
          volumeMounts:
            - name: storage-volume
              mountPath: /appdata
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            runAsNonRoot: false

**Comment by vishal-biyani** [comment]
Hey @brandoncollins7 This looks like an issue on Prometheus side and do you know if a newer version there changed the behavior? Please reopen if this is still an issue.
