### ISSUE TITLE
sh: ./fission: not found on alpine docker image

### ISSUE THREAD

**Issue by manish2v** [fission/fission#1592]
**Fission/Kubernetes version**
fission: 1.8.0
k8s: 1.15

<pre>
$ fission --version : command not working , sh: ./fission: not found
$ kubectl version : v1.18.2
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
EKS : AWS
**Describe the bug**
This is with a docker alpine docker image
(1)     kubectl -n fission apply -f https://github.com/fission/fission/releases/download/1.8.0/fission-all-1.8.0.yaml
(2) curl -Lo fission https://github.com/fission/fission/releases/download/1.8.0/fission-cli-linux \
    && chmod +x fission && sudo mv fission /usr/local/bin/
(3) fission : sh: fission: not found

**To Reproduce**

(1)     kubectl -n fission apply -f https://github.com/fission/fission/releases/download/1.8.0/fission-all-1.8.0.yaml
(2) curl -Lo fission https://github.com/fission/fission/releases/download/1.8.0/fission-cli-linux \
    && chmod +x fission && sudo mv fission /usr/local/bin/
(3) fission : sh: fission: not found

**Expected result**
fission command should work

**Actual result**
sh: fission: not found

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by vishal-biyani** [comment]
Hey @manish2v Are you trying to execute the Fission CLI inside an alpine docker image or what do you mean?

**Comment by manish2v** [comment]
yes, its inside a alpine docker image
![2020-05-07_153115](https://user-images.githubusercontent.com/59185197/81257909-d3f86200-9077-11ea-90aa-260627ca5ebb.png)

**Comment by manish2v** [comment]
RUN curl -Lo fission https://github.com/fission/fission/releases/download/1.8.0/fission-cli-linux 
RUN chmod +x fission 
RUN mv ./fission bin/

These are commands in Dockerfile for installing CLI

**Comment by vishal-biyani** [comment]
So the Fission CLI is not compiled for Alpine. You should get an error similar to `standard_init_linux.go:211: exec user process caused "no such file or directory"`

You will have to compile the Fission CLI for Alpine or use a Linux image for running Fission CLI.

**Comment by manish2v** [comment]
Thanks! Vishal
