### ISSUE TITLE
Request Body Size: HTTP 413

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1594]
On Slack conversation, Ashish Jain mentioned that when using a body greater than 1MB for a function call was throwing `413 Request Entity Too Large` error. This issue is for tracking and fixing the problem.

**Comment by LittleFox94** [comment]
Educated guess without looking at anything: Ingress involved and not set correctly?

**Comment by vishal-biyani** [comment]
Hey, @LittleFox94 this is a problem specific to the NodeJS environment. Express/Body-parser package by default limits body size to 100KB (https://www.npmjs.com/package/body-parser#limit). 

We bumped it up to 1MB but some users need bigger limits:

https://github.com/fission/fission/blob/aa8c27fd5d9a1b92062d87e73a0e96f1c9b7ba7a/environments/nodejs/server.js#L102-L105

**Comment by vishal-biyani** [comment]
Closed by #1618
