### ISSUE TITLE
Proposal: Possibility to disable "enableServiceLinks" environment variables for functions/environments

### ISSUE THREAD

**Issue by darkworon** [fission/fission#1599]
Kubernetes injects environment variables to each Pod with the IP and port of ever other service in the cluster's namespace and for the Kubernetes API Server. And those variables are not desirable in functions environment.

```
➜  ~ fission function test --name hellogo --timeout=10s --fns test1                                                                                              
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME = poolmgr-go-default-24404-7b6d66fdf7-wrbth
KUBERNETES_PORT_443_TCP = tcp://172.19.0.1:443
KUBERNETES_PORT_443_TCP_PROTO = tcp
KUBERNETES_PORT_443_TCP_PORT = 443
KUBERNETES_PORT_443_TCP_ADDR = 172.19.0.1
KUBERNETES_SERVICE_HOST = 172.19.0.1
KUBERNETES_SERVICE_PORT = 443
KUBERNETES_SERVICE_PORT_HTTPS = 443
KUBERNETES_PORT = tcp://172.19.0.1:443
HOME = /root
```

More information here: https://kubernetes.io/docs/concepts/services-networking/service/#discovering-services

Having dug into the Kubelet codebase, looking for a global flag, I didn't find one, but found an override in the PodSpec which seems reasonable to set as a default for all users.

https://github.com/kubernetes/kubernetes/blob/21d4d13d98219b2d6e04ba7d1a634fbd62f9a256/pkg/kubelet/kubelet_pods.go#L555

Simply set: pod.spec.enableServiceLinks to false.

https://kubernetes.io/docs/concepts/services-networking/connect-applications-service/#accessing-the-service

**Comment by vishal-biyani** [comment]
Hi, @darkworon What is the use case you are trying to solve by disabling the Kubernetes injected environment variables?

**Comment by darkworon** [comment]
@vishal-biyani we have multiple customers deploying functions and we'd like to avoid to leak information about other functions and/or Kubernetes environment through DNS or environment variables.

**Comment by vishal-biyani** [comment]
@darkworon Thanks - that makes sense. Since the field is available in PodSpec - we can enable in PodSpec. Currently, the mergePodSpec does not pick it up (https://github.com/fission/fission/blob/master/pkg/executor/util/merge.go#L57). Would you like to send a PR - as this is a relatively small change.
