### ISSUE TITLE
Github Action for CI/CD

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1603]
GitHub Actions can be used for CI and will solve a few problems potentially:

- [x] PRs from external contributors can be tested without additional work
- [x] Within CI Kind can be used or cluster can be created as a separate step
- [x] Testing Fission against 3/4 different versions of Kubernetes (Using Kind?)
- [x] A separate action can also be used for releasing Fission

**Comment by nanotkarashish** [comment]
Can use this to run tests locally in dev env as well.
https://github.com/nektos/act

**Comment by rajalokan** [comment]
If anyone has not started work on this, i would like to take on this. Also I've one task in hand so will be start work on this after 2-3 days. 

I've experience with github actions should be able to pick on fast.

**Comment by vishal-biyani** [comment]
@rajalokan Thank you - go ahead. You might want to tackle one item at a time. I am also doing some work around Skaffold + Kind for local dev - which can be used in the action workflow too. This is what I have in mind as part of this one:

1. Locally test Fission wit Skaffold and Kind - ideal case is we should be able to run the entire test suite end to end. There are some issues ATM - I will send an update to docs repo soon with an update.
2. Once (1) works - moving that to a Github Action workflow. Let's not kick this off for the master branch merge process yet.
3. Moving current Travis build to a Github action and making it create a GKE cluster on the fly instead of using a static cluster.
  - There is also an upgrade job within the same Travis job (fission_upgrade_test.sh) which is called once a day. Same should be a sub/separate action
4. We can use (2) for every PR merge and (3) as a once a day job
5. We can use action (2) for testing against 3/4 different versions of Kubernetes - maybe once a day or so.
6. Another action for Fission release (release.sh)

The following will be possible once this is done, but just need to validate by testing:

- PRs from external contributors can be tested without additional work (Which should be possible once previous items are done anyway)

**Comment by bhavin192** [comment]
I was wondering if we can give KUTTL a try and see if we can replace current e2e test suite with a KUTTL test suite. 

https://github.com/kudobuilder/kuttl
https://kuttl.dev/docs/kuttl-test-harness.html#writing-your-first-test

- It's possible to run commands as test steps in KUTTL

**Comment by vishal-biyani** [comment]
Reference for Skaffold and Kind is updated in the contributing docs now: https://docs.fission.io/docs/contributing/

**Comment by vishal-biyani** [comment]
Thanks, @bhavin192 for the suggestion - there is definitely room for better E2E tests. This issue is the first step in that direction. Once we have done 1-4/5 in the above list, this would be a logical step. I am adding this as an item just for reference.

**Comment by sanketsudake** [comment]
@suramya-shah please consider this issue for release flow you are working on.

**Comment by soharab-ic** [comment]
Closing as all goals achieved.
