### ISSUE TITLE
Need a better solution for environments whose functions are in binary

### ISSUE THREAD

**Issue by yqf3139** [fission/fission#162]
Commit 1665235 makes Golang env possible. It uses the code field in the function struct.

That needs enhancement because the code field is used as text type and will be encoded in base64. 

And also in fission-ui, we cannot distinguish whether the code is text or binary in order to display the code or not. `fission function edit` also will fail in this case.

A simple solution is to use a different field to store the binary file. Furthermore, We can use an object storage instead of encoding the binary file into an json file.
Environment V2 #103 seems to be a well-thought solution. Maybe it is time to migrate to environment v2.

**Comment by soamvasani** [comment]
Hey @yqf3139, yes, Env v2 is the right way to fix these issues.  Agree on the UI and CLI edit workflows.  

We're already tracking Env v2 work in #103, so there is nothing new to track here.  I'd like to keep the discussion in that issue itself.
