### ISSUE TITLE
Nodejs environments are out of date

### ISSUE THREAD

**Issue by ggilley** [fission/fission#1620]
The nodejs environments are using Node 8. Node 8 was end-of-lifed in December 2019. There have been no security updates since then. Need to update to a more recent version of nodejs. Looking at the support timelines, 12.x would seem like the best choice at the moment.

[Nodejs Releases](https://github.com/nodejs/Release)

**Comment by vishal-biyani** [comment]
Thanks for filing this issue @ggilley - a definitely important one. We will get this prioritized in one of the upcoming releases.

**Comment by vishal-biyani** [comment]
Closed by https://github.com/fission/fission/pull/1683
