### ISSUE TITLE
Connection errors after trying to deploy a java function with executortype newdeploy 

### ISSUE THREAD

**Issue by dennisMKI** [fission/fission#1626]
**Fission/Kubernetes version**

<pre>
$ fission --version
Error forwarding to port 55040: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: i/o timeout
</pre>

Running fission version with a clean installation:
<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2020-02-03T08:40:57Z"
    GitCommit: bda974a72c9093e241c1dae6a7fc1a2d16e28b02
    Version: 1.8.0
server:
  fission/core:
    BuildDate: "2020-05-10T16:11:44Z"
    GitCommit: 8a4d2c8ecc821e896d87f074660685565156aff1
    Version: 1.9.0
</pre>

kubectl for minikube:
<pre>
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
</pre>

kubectl for aks:
<pre>
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.1", GitCommit:"d224476cd0730baca2b6e357d144171ed74192d6", GitTreeState:"clean", BuildDate:"2020-01-14T21:04:32Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.7", GitCommit:"e2d9f8479783020904aba3de7499a49be6c75ebd", GitTreeState:"clean", BuildDate:"2020-04-09T02:31:15Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Azure Kubernetes Service (AKS) and minikube

**Describe the bug**

Connection error to Kubernetes/Fission service (??) after deployment a simple hello world java function with executortype newdeploy and min- and maxscale = 5.

Important information: Problem only occurs with executortype newdeploy. Running function with default config works like a charm:
<pre>
$ fission fn create --name hello --pkg java-hello-world-zip-jnek --env java --entrypoint io.fission.HelloWorld
function 'hello' created

$ fission fn test --name hello
Hello world!
</pre>

**To Reproduce**
Download https://github.com/fission/fission/tree/master/examples/jvm/java and zip as "java-hello-world.zip"

<pre>
$ fission env create --name java --image fission/jvm-env --version 2 --keeparchive --builder fission/jvm-builder

$ fission package create --sourcearchive java-hello-world.zip --env java
Package 'java-hello-world-zip-ule6' created

$ fission package info --name java-hello-world-zip-ule6
Name:        java-hello-world-zip-ule6
Environment: java2
Status:      succeeded
Build Logs:
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------------< io.fission:hello-world >-----------------------
[INFO] Building hello-world 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-clean-plugin/2.5/maven-clean-plugin-2.5.pom
[...]
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/plexus/plexus-utils/2.0.1/plexus-utils-2.0.1.jar (222 kB at 461 kB/s)
[INFO] Building jar: /packages/java-hello-world-zip-ule6-eug8to/target/hello-world-1.0-SNAPSHOT-jar-with-dependencies.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:08 min
[INFO] Finished at: 2020-05-28T14:16:07Z
[INFO] ------------------------------------------------------------------------
$ fission fn create --name hellonewdeploy --env java --entrypoint io.fission.HelloWorld --pkg java-hello-world-zip-ule6 --executortype newdeploy --minscale 5 --maxscale 5
</pre>

**Expected result**

Five running pods and a successful response like
<pre>
$ fission fn test --name hellonewdeploy
Hello world!
</pre>

**Actual result**
_Minikube:_

<pre>
$ kubectl get all -n fission-function
NAME                                                                  READY   STATUS              RESTARTS   AGE
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-577d6c6949tm   2/2     Terminating         0          2m4s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-577d6c6fpcnh   2/2     Terminating         0          2m4s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-577d6c6k84mr   2/2     Terminating         0          2m4s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-577d6c6kqxds   2/2     Terminating         0          2m4s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-577d6c6mkrv7   2/2     Terminating         0          2m4s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-65fd8854pp8j   0/2     ContainerCreating   0          21s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-65fd88575pcl   0/2     ContainerCreating   0          21s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-65fd885tdr5g   0/2     ContainerCreating   0          21s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-65fd885vk2j7   0/2     ContainerCreating   0          21s
pod/newdeploy-hellonewdeploy-default-8802-eddeb0f69b3a-65fd885vqjbb   0/2     ContainerCreating   0          22s
pod/poolmgr-java-default-4315-5495dd5b59-9zpzw                       0/2     ContainerCreating   0          22s
pod/poolmgr-java-default-4315-5495dd5b59-r68hj                       0/2     ContainerCreating   0          22s
pod/poolmgr-java-default-4315-5495dd5b59-thvmt                       0/2     ContainerCreating   0          22s
pod/poolmgr-java-default-4315-78bdd7f786-4tq9k                       2/2     Terminating         0          7m41s
pod/poolmgr-java-default-4315-78bdd7f786-jw6mm                       2/2     Terminating         0          7m41s
pod/poolmgr-java-default-4315-78bdd7f786-pn57n                       2/2     Terminating         0          7m41s
Error from server: rpc error: code = Unavailable desc = transport is closing
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get deployments.apps)
Unable to connect to the server: unexpected EOF
Unable to connect to the server: dial tcp 192.168.99.105:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 192.168.99.105:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 192.168.99.105:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 192.168.99.105:8443: connectex: No connection could be made because the target machine actively refused it.
</pre>

After some minutes the pods are gone:
<pre>
$ kubectl get pods -n fission-function
NAMESPACE          NAME                                                        READY   STATUS             RESTARTS   AGE

fission-function   pod/poolmgr-java-default-4315-5495dd5b59-d8wlv             2/2     Running            0          46m
fission-function   pod/poolmgr-java-default-4315-5495dd5b59-kgcfb             2/2     Running            0          46m
fission-function   pod/poolmgr-java-default-4315-5495dd5b59-mfcp9             2/2     Running            0          46m
</pre>

Running function:
<pre>
$ fission fn test --name hellonewdeploy
Error forwarding to port 56624: error getting pod for port-forwarding with label selector application=fission-api: etcdserver: request timed out
</pre>

Few minutes later I got this message:
<pre>
$ fission fn test --name hellonewdeploy

Options:
  --name=''                        Function name
  --method='GET'                   HTTP Method: GET|POST|PUT|DELETE|HEAD
  --header=[] (-H)                 Request headers
  --body='' (-b)                   Request body
  --query=[] (-q)                  Request query parameters: -q key1=value1 -q key2=value2
  --timeout=30s (-t)               Length of time to wait for the response. If set to zero or negative
                                   number, no timeout is set
  --fnNamespace='default' (--fns)  Namespace for function object
  --dbtype='influxdb'              Log database type, e.g. influxdb (currently only influxdb is
                                   supported)

Global Options:
  --server=''         Server URL
  --verbosity=1 (-v)  CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)

Usage:
  fission function test [options]

[31mError[0m: error executing HTTP request: Get http://127.0.0.1:57083/fission-function/hellonewdeploy: context deadline exceeded
</pre>

And later:
<pre>
$ fission fn test --name hellonewdeploy
Error forwarding to port 53516: error upgrading connection: the server does not allow this method on the requested resource
</pre>

_AKS:_
Behave very similar to minikube.

<pre>
$ kubectl get all --all-namespaces
NAMESPACE          NAME                                                                  READY   STATUS              RESTARTS   AGE
fission-builder    pod/java-3217-66458fbfdc-9279q                                        2/2     Running             7          4d20h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-67mkgf   1/2     Terminating         2          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6bnhwv   1/2     Terminating         2          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6jr9pz   0/2     ContainerCreating   0          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6m69km   1/2     Terminating         2          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6n7kw7   0/2     ContainerCreating   0          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6pwgn4   0/2     ContainerCreating   0          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6rc8k4   0/2     ContainerCreating   0          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6rw6lp   1/2     Terminating         2          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6vdmwr   1/2     Terminating         1          9h
fission-function   pod/newdeploy-hello-java-five-repl-default-889c-7604b2233f2b-6vmxz7   0/2     ContainerCreating   0          9h
</pre>

<pre>
$ fission fn test --name newdeploy-hello-java-five-repl
Error forwarding to port 53687: error upgrading connection: error dialing backend: dial tcp 10.240.0.4:10250: i/o timeout
</pre>

**Comment by vishal-biyani** [comment]
Hi @dennisMKI Thanks for filling the issue. This looks strange, will take a look my morning and update

**Comment by dennisMKI** [comment]
Hi @vishal-biyani , thank you for your answer. I'm looking forward to further information.
If you need further information from my side, please contact me.

**Comment by vishal-biyani** [comment]
Hi @dennisMKI Sorry, I was a bit caught up and hence the delay. I was able to try on AKS and could not reproduce the issue:

```
$ fission env create --name java --image fission/jvm-env --version 2 --keeparchive --builder fission/jvm-builder
$ fission package create --sourcearchive java.zip --env java
$ fission fn create --name hellojava --env java --entrypoint io.fission.HelloWorld --pkg java-zip-jfog --executortype newdeploy --minscale 5 --maxscale 5
function 'hellojava' created

$ fission fn test --name hellojava
Hello World!

$kubectl get pods -nfission-function
NAME                                                             READY   STATUS    RESTARTS   AGE
newdeploy-hellojava-default-81a5-9e87950e3fb8-6d59d5c5d9-59vck   2/2     Running   0          17s
newdeploy-hellojava-default-81a5-9e87950e3fb8-6d59d5c5d9-5mffr   2/2     Running   0          17s
newdeploy-hellojava-default-81a5-9e87950e3fb8-6d59d5c5d9-c69fw   2/2     Running   0          17s
newdeploy-hellojava-default-81a5-9e87950e3fb8-6d59d5c5d9-dddc9   2/2     Running   0          17s
newdeploy-hellojava-default-81a5-9e87950e3fb8-6d59d5c5d9-vgghq   2/2     Running   0          17s
poolmgr-java-default-273974-56f86df5cf-2x6pb                     2/2     Running   0          14m
poolmgr-java-default-273974-56f86df5cf-6z5cc                     2/2     Running   0          14m
poolmgr-java-default-273974-56f86df5cf-gwjmk                     2/2     Running   0          14m
```

I will leave it running for some time to test it more but does not look like an issue. Can you confirm if your Minikube/AKS clusters are not running low on resources?

**Comment by dennisMKI** [comment]
Hi @vishal-biyani Thanks. I will check this and answer you afterwards.

**Comment by dennisMKI** [comment]
Hi @vishal-biyani thank you for your help and sorry for the late response. Unfortunately, I cannot explain this issue to myself. When I retested it a few days ago, it suddenly worked without problems.
