### ISSUE TITLE
Fission shows 'error sending request to function' on specific function

### ISSUE THREAD

**Issue by Chr1s1997** [fission/fission#1649]
The fission shows
Error calling function pical: 502; Please try again or fix the error: error sending request to function
on the pi calculation function, whereas when I run the hello function on fission docs, it's working properly. I wonder whether my code is wrong or I missed some of the setups.

[pi cal.zip](https://github.com/fission/fission/files/4810890/pi.cal.zip)

**Comment by vishal-biyani** [comment]
Hi @Chr1s1997 Can you please show us how you created the environment and function please?

**Comment by vishal-biyani** [comment]
Hi @Chr1s1997 please update us with logs when you get a chance, I am closing this issue, for now, but please feel free to reopen!
