### ISSUE TITLE
Why environment doesn't update?

### ISSUE THREAD

**Issue by dayeol** [fission/fission#1656]
Hello, I am trying to customize the Python environment by following commands
But apparently the environment is not updated.
Could you advise if I am missing something?

I was using `fission/python-env`
```
fission env create --name test --image fission/python-env --poolsize=1
fission fn create --name testfn --code hello.py --env test
fission fn test --name testfn
```
Works fine. Great.

In order to update the environment:
In `fission/environments/python`. changed stuffs and ran
```
docker build -t dayeol/customized-python-env .
docker push dayeol/customized-python-env
```
And then ran:
```
fission env update --name test --image dayeol/customized-python-env
```

But then I still get the results from the previous environment.

I also tried to delete and re-create the environment, but still, there was no luck.
Is the image cached somewhere if I use the same environment name?

Thank you for helping!

**Comment by vishal-biyani** [comment]
Hey @dayeol If you are using exactly same tag for the image the [Kubernetes's ImagePullPolicy](https://kubernetes.io/docs/concepts/containers/images/#updating-images) might be causing this. The default value in Fission installation is :

`pullPolicy: IfNotPresent` 

Can you try changing the tag of env image and see if it helps?

**Comment by vishal-biyani** [comment]
Hey @dayeol - I am going to close this issue, but please feel free to reopen if you have issues/questions!
