### ISSUE TITLE
NodeJS context object explanation

### ISSUE THREAD

**Issue by tayupov** [fission/fission#166]
Hi, I was looking through your available examples and could not find an explanation for the context object that is passed to my function. It kinda looks like the same object that express is giving me, but I'm not sure.

Can you point me to a specification for the object?

Thanks

**Comment by tobias** [comment]
While not a specification, you can see how it is constructed here: https://github.com/fission/fission/blob/master/environments/nodejs/server.js#L79

**Comment by tayupov** [comment]
Thanks!
