### ISSUE TITLE
Websockets support

### ISSUE THREAD

**Issue by airhorns** [fission/fission#1662]
**Is your feature request related to a problem? Please describe.**

Fission doesn't yet support running servers that speak Websockets instead of HTTP, but, they are annoying to run and would benefit from the same simplicity that Fission allows for normal services! It'd be nice to be able to deploy a function that supported `HTTP UPGRADE` requests and have it cold start quickly, autoscale, route logs to the same place as other functions, etc.

**Describe the solution you'd like**

I think for Fission to do this, it'd have to support:

 - long running connections in the router
 - very big or no request timeouts
 - websocket UPGRADE requests in each environment's function harness
 - graceful restart support for functions with open connections during new function deploys
 - a clear way to integrate with the function harness in a way that supports websockets (probably using the most common package for handling websockets in each language, like `ws` for nodejs)

I also think it's important to not model websockets as one event per socket message -- lots of websocket protocols/usecases are stateful and require being connected to the same backend process for socket's lifetime. So I don't think it's wise to terminate websocket connections at the router and then have the router dispatch events to a function, and instead the router should just pass through the connection to the backend that can decide to accept or decline the UPGRADE request and then handle it if so.

Most websocket servers are implemented using some sort of pubsub system or message broker on the backend like Redis or RabbitMQ, so that any websocket server backend can handle a given incoming websocket connection. This plays nice with Fission (and k8s') model of pod statelessness. I think it'd be fine for "stateful" websocket backends that require special/stateful routing to be out of scope for fission.

Also, if it is not insanely hard to implement, my ideal solution would not require websocket handling functions to be separate or different from normal HTTP functions. It'd be slightly annoying to have to split out a function into two just to implement two different transports for the same actual functionality, thought I don't think the end of the world. I've had this use case when building GraphQL APIs -- often nodejs folks mount the HTTP and WS transport at the same URL endpoint so that the same backends can serve either request using whatever handy state they have in memory, instead of having to set up two different functions with two different scaling sets and whatnot. I don't think this should be mandated but it'd be nice for getting started.

**Describe alternatives you've considered**

You can run websocket servers using normal k8s just fine these days: `nginx-ingress-controller` supports routing websocket connections just fine, and with k8s termination grace periods you can implement graceful connection shutdown for a good end user experience. It's just annoying to get right and repeated every time you want to set this up!

**Comment by vishal-biyani** [comment]
Hey @airhorns - thanks for such a detailed request - we will do some work and consider building this out in upcoming releases.

**Comment by airhorns** [comment]
Any movement on this? I realize it's a doozy but it'd be amazing to get support at some point!

**Comment by vishal-biyani** [comment]
Hey @airhorns - this is a feature we would love to have in Fission. I am prioritizing this and plan to land in 1.13/1.14 roughly!

**Comment by airhorns** [comment]
I think this relates to https://github.com/fission/fission/issues/1888 a little bit in that if we want to allow handling websockets in the same container as other requests we'd need to support pod re-use or simultaneous use for different functions . For websockets specifically, I think re-use matters a lot because a lot of websocket connections will be idle at lot of the time and waste resources. An open websocket would be an open connection such that the router and executor have to see the pod as in use, but the connection isn't necessarily doing anything and often won't be, for example if the websocket is being used for pushing changes from the server to the client, and nothing happens to be changing on the server for a while. This would leave the one pod dedicated to handling that websocket as a significant allocation of resources that sit mostly idle, so it'd be great to be able to send many websocket connections to the same pod such that we didn't have to pay one-pods-worth-of-resources per connection.

Pod re-use for different functions would allow operators to map different functions and "bin pack" in a way their workload into pods that get efficient use.

**Comment by LucasUnplugged** [comment]
Just a note that it would be great to use uws for Node.js — or at least have that option. https://github.com/uNetworking/uWebSockets

Apparently it is faster than ws, and is used by SocketCluster/Asyngular:
https://ably.com/topic/websockets#web-sockets

**Comment by vishal-biyani** [comment]
Closed by #1982 & https://github.com/fission/environments/pull/49
