### ISSUE TITLE
Keda Connectors

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1663]
As part of the PR https://github.com/fission/fission/pull/1657 - the Keda integration is in place (Solves https://github.com/fission/fission/issues/1565). 

The initial PR had Kafka connector only and the following connectors need to be developed. The connectors are generic and are maintained in the https://github.com/fission/keda-connectors repo.

Instead of creating one issue for each connector, this issue will act as a single place to track all connectors and PRs can be linked as contributions come in.

- [ ] ActiveMQ Artemis
- [x] Apache Kafka - https://github.com/fission/keda-connectors/pull/1
- [ ] AWS CloudWatch
- [ ] AWS Kinesis Stream
- [ ] AWS SQS Queue
- [ ] Azure Blob Storage
- [ ] Azure Event Hubs
- [ ] Azure Monitor
- [ ] Azure Service Bus
- [ ] Azure Storage Queue
- [ ] Cron
- [ ] External
- [ ] Google Cloud Platform‎ Pub/Sub
- [ ] Huawei Cloudeye
- [ ] Liiklus Topic
- [ ] MySQL
- [ ] NATS Streaming
- [ ] PostgreSQL
- [ ] Prometheus
- [x] RabbitMQ Queue - https://github.com/fission/keda-connectors/pull/3
- [ ] Redis Lists
- [ ] Redis Streams

**Comment by vishal-biyani** [comment]
@therahulbhati Once your Keda integration is in - maybe a simple guide to writing a connector in this issue would be helpful for new contributors. You can take the example of Kafka or RabbitMQ connector and explain!

**Comment by therahulbhati** [comment]
Sure @vishal-biyani will do that.

**Comment by ajoslin103** [comment]
Yes please, I need also MQTT

**Comment by therahulbhati** [comment]
# Connector Development Guide

The job of the connector is to read messages from the topic, invoke fission function, and write response or error in the respective queues.

## Following are steps required to write a connector:
1. Create a Consumer for the queue
2. Create a Producer for the queue
3. Read msg from the queue using the consumer
4. Create a POST request with the following headers using values specified during message queue trigger creation and headers from the consumed message.
```
{
   "X-Fission-MQTrigger-Topic": Topic,
   "X-Fission-MQTrigger-RespTopic":ResponseTopic,
   "X-Fission-MQTrigger-ErrorTopic":ErrorTopic,
   "Content-Type":"ContentType"
}
```
5. Invoke fission function per consumed message in a retry loop with max retries specified while creating a message queue trigger.
6. Write response in response queue, if reponse topic is specified while creating message queue trigger
7. Write error in error queue if error topic is specified while creating message queue trigger
8. The final step is to dockerize your code

**Comment by vishal-biyani** [comment]
Closing this issue here as Keda-Connectors will be tracked in their own repo.
