### ISSUE TITLE
Sentry integration

### ISSUE THREAD

**Issue by vir-mir** [fission/fission#1665]
Dear all, 

I would like to integrate sentry, for my world functions, I use python. Fission, under the hood uses Flask framework. 

This is good, but when I started reading about how integration works (https://docs.sentry.io/platforms/python/flask/), I realized that the launch is hidden from me.

You can tell me how to be in this situation, maybe there is a simple and elegant solution, in order to connect the sentry?

**Comment by vishal-biyani** [comment]
Hi @vir-mir You might have to enhance the Python environment and add the Sentry dependency somewhere here: https://github.com/fission/fission/blob/master/environments/python/server.py#L25

Secondly the key can be added with environment variables which are supported in [podspec](https://docs.fission.io/docs/spec/podspec/envvar/)

While you can do all of this in function too I am sure you don't want every dev to have write the same code in all functions. Please let me know if that clarifies.

**Comment by vir-mir** [comment]
@vishal-biyani  Yes, that's what I thought. tell me, maybe I can make you MR, what would it be in delivery out of the box?

**Comment by vishal-biyani** [comment]
Hi @vir-mir Sure - you can make a PR such that it is fairly generic and works in a way that if user does not specify the sentry key in ENV - sentry is not initialized. I would be happy to get it in Fission!
