### ISSUE TITLE
Functions scalability with PoolManager Executor type

### ISSUE THREAD

**Issue by matthieu-eck** [fission/fission#1666]
Hello,

I would like to know if it is planned to use the `PoolManager` Executor type with the load-balancer and auto-scale mechanism like the `NewDeploy` does.

It would be nice to be able to use warm pools and to still be able to auto-scale and use load-balancing.

Thanks!

**Comment by vishal-biyani** [comment]
Hi @matthieu-eck At the moment at least we don't have plans to introduce service/HPA in the pool manager executor. There are couple of reasons for this:
- The service entrypoint update when a new pod is added takes some time and this comes in the request path
- Scaling is in a way built-in pool manager - it creates a new pod for an execution.
- At some point, we might have a combined new executor where initial requests are served from pool but beyond initial once are from a new deploy kind of setup. 

I am curious what is your use case and what problem you are trying to solve?

**Comment by vishal-biyani** [comment]
Hi @matthieu-eck I am closing this for lack of specific ask & followup but please feel free to reopen this if you would like to add more context/use case that you are solving.

**Comment by vladimirtiukhtin** [comment]
@vishal-biyani why do you create a new pod for execution instead of adjusting poolmgr replica count?

**Comment by sanketsudake** [comment]
Hi @vladimirtiukhtin Kindly refer this explanation slack thread.

https://fissionio.slack.com/archives/C3LUX6BBP/p1653550288429479?thread_ts=1653515861.187329&cid=C3LUX6BBP

> The way poolmgr works is  it tries to maintain the poolsize. So when you call a function one of the old pods serves the request while a new pod is created and when the pods have been idle for sometime, the old pods starts terminating so that the number of pods would to be equal to the poolsize.

Essentially poolsize is kind of fixed. We pick up a pod from pool specialize it and serve function request using it. Since we are picking up one pod from pool, pool size is kind of maintained by adding a new pod.

**Comment by vladimirtiukhtin** [comment]
Hi @sanketsudake, thanks. Yes, I understand the concept. Behaviour I am observing is that new pods do not belong to the poolmgr replicaset. Those one who do have
```
    ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: poolmgr-python-default-76686955-9f6dcc9f6
      uid: 4b702551-9fcf-4f66-8dbd-a2bf9d574afe
```
in their metadata. Newly created pods do not have this

**Comment by sanketsudake** [comment]
yes this is desired behaviour.  
Pool manager under the hood create a deployment with pool size.
So all pods which belong to deployment(internally replicaset) will have owner reference of the replicaset.

Pods which are specialized, ie, function code is loaded into them won't be part of deployment, so they are pooled out of pool and wont have owner reference. 
Fission executor would be cleaning up them when idle timeout reaches for function pod and there are no active requests on function pod.
