### ISSUE TITLE
"native-or-bluebird deprecated, use any-promise instead."

### ISSUE THREAD

**Issue by awitherow** [fission/fission#167]
The package https://github.com/normalize/mz/blob/master/package.json has updated to quite a higher version number than which is currently implemented in the package.json for the fission-nodejs-runtime.

Is there anything holding us back from keeping these dependencies more up to date?

**Comment by soamvasani** [comment]
You're right, the package.json needs to be updated. (Nothing holding us back, just something nobody's done yet.)
