### ISSUE TITLE
Support for arm64

### ISSUE THREAD

**Issue by odidev** [fission/fission#1672]
**Is your feature request related to a problem? Please describe.**
Hi Team,

I have observed that in https://github.com/fission/fission/blob/master/hack/travis-kube-setup.sh#L17 file the STATICCHECK_VERSION=2019.2.3 which is not available for arm64 and it becomes available from version 2020.1.2. With this new version, the package is failing as certain checks like ST1019 and S1039 became available since 2020.1

**Describe the solution you'd like**
I have seen that you are trying to add arm64 support for the package. Are you looking into this issue also?

**Comment by vishal-biyani** [comment]
@odidev We would love to add ARM64 support but at the moment there is no active work going on. Would you like to contribute this feature to Fission?

**Comment by odidev** [comment]
Yes, I would like to contribute to this feature of fission. I was trying to add arm64 job on Travis-ci and it looks that the end to end tests are getting skipped as we don't have google cloud credentials so we are not sure whether the test will be running fine or not and rest everything is working fine.

Commit link- https://github.com/odidev/fission/commit/705388c70f316e7303fc131fad1f14f0b31988e7

Travis Link- https://travis-ci.com/github/odidev/fission/builds/177991861

Can I raise PR with these changes?

**Comment by RealHarshThakur** [comment]
We're going to provide multi-arch images from next release. https://github.com/fission/fission/pull/1929
