### ISSUE TITLE
Feature request on Auto Scaling using http route requests

### ISSUE THREAD

**Issue by hd40910** [fission/fission#1679]
Hi @vishal-biyani ,

We have a feature where we need to use the same function for parallel execution of the same transition with different data.
This means the same function will be called multiple times in parallel and we should start executing them immediately.

**Use case Example :**
1.	Develop a Function1 which connects to a target server and sleeps for 120 seconds.
2.	Call this function 5 times via http route and provide a random target server on every request.

**Current Support:**
```
PoolManager : The 5 requests will be executed sequentially
New Deploy:
	Without Auto Scaling:
		We need to have a min and max replica to 5 – These pods are sitting ideal and consuming memory all the time – Not preferred but do the job
	With Auto Scaling:
		The scaling is available using :
			--minmemory value      Minimum memory to be assigned to pod (In megabyte)
			--maxmemory value      Maximum memory to be assigned to pod (In megabyte)
			--minscale value       Minimum number of pods (Uses resource inputs to configure HPA)
			--maxscale value       Maximum number of pods (Uses resource inputs to configure HPA)
			--targetcpu value      Target average CPU usage percentage across pods for scaling (default: 80)
		These metrics are not connected to the number of requests we are receiving in parallel but more towards the utilization by pods.
```
Is there any other supported way that can help support this use case ?

**Comment by vishal-biyani** [comment]
Hi @hd40910 

I think there are two distinct problems that we are talking about here.

The first one is of calling X number of functions based on the number of events received. This is a pure orchestration problem and the best way to design is to have a parent/orchestrator function call subsequent functions and wait for the execution of all. If you do this synchronously or async is a design choice.

Coming to the second problem - of scaling function pods on custom metrics, this is not supported as of now in Fission but there is a feature request open for that: https://github.com/fission/fission/issues/854 

I will close this issue, for now, we can track the custom metric discussion in above issue itself.

**Comment by hd40910** [comment]
Thanks @vishal-biyani
