### ISSUE TITLE
CRD api version `apiextensions.k8s.io/v1beta1` is currently deprecated and is to be removed in Kubernetes 1.19

### ISSUE THREAD

**Issue by ankitjain235** [fission/fission#1688]
As per Kubernetes 1.16 release notes: 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.16.md#deprecations-and-removals
`The apiextensions.k8s.io/v1beta1 version of CustomResourceDefinition is deprecated and will no longer be served in v1.19. Use apiextensions.k8s.io/v1 instead. (#79604, @liggitt)`
Currently fission is using apiextensions.k8s.io/v1beta1 to create CRDs.
This could cause issues to support upcoming Kubernetes versions.

**Comment by sanketsudake** [comment]
Closing this as fixed in 1.13.1
