### ISSUE TITLE
Failed to get service for function (hello,): (Error 4) 400 Bad Request

### ISSUE THREAD

**Issue by wayarmy** [fission/fission#169]
Hello,

I've just deploy fission into my k8s cluster running on AWS. But when i deploy first "Hello-world" functions, everything is ok. But when i deploy second functions (the same with hello-world). I had a problem "500 internal server". This is logs of fission router:

2017/04/05 08:30:26 Proxying request for /hello to 100.96.3.34:8888
100.96.3.1 - - [05/Apr/2017:08:30:26 +0000] "GET /hello HTTP/1.1" 304 0
2017/04/05 08:30:29 Not cached, getting new service for {hello-test 54c28304-b9ff-4041-bd13-0659d43b51aa}
2017/04/05 08:30:29 Proxying request for /hello to 100.96.3.34:8888
100.96.3.1 - - [05/Apr/2017:08:30:29 +0000] "GET /hello HTTP/1.1" 304 0
2017/04/05 08:30:30 Proxying request for /hello to 100.96.3.34:8888
100.96.3.1 - - [05/Apr/2017:08:30:30 +0000] "GET /hello HTTP/1.1" 304 0
2017/04/05 08:30:34 Not cached, getting new service for {hello }
2017/04/05 08:30:34 Failed to get service for function (hello,): (Error 4) 400 Bad Request
100.96.3.1 - - [05/Apr/2017:08:30:34 +0000] "GET /hello HTTP/1.1" 500 32

Am i wrong, or what's the problem. I'm running k8s with version 1.6.0 on AWS.

Thanks !!!

**Comment by soamvasani** [comment]
Can you take a look at the poolmgr logs?  I think this might be #160.

**Comment by soamvasani** [comment]
Can't debug this without more logs.  Please file a new issue or reopen this if you have logs.
