### ISSUE TITLE
Optimize get calls to function crd in api.go

### ISSUE THREAD

**Issue by therahulbhati** [fission/fission#1713]
Get calls are made to k8s while getting serviceURL and untap function service. Under high load, this could become a bottleneck, this could be improved using solutions like caching or somehow reusing the function from the request body.

**Comment by vishal-biyani** [comment]
Hi @therahulbhati I think we can do something similar to 1860 for this one too?

**Comment by therahulbhati** [comment]
Yes @vishal-biyani, this is done in https://github.com/fission/fission/pull/1812
