### ISSUE TITLE
curl http://${FISSION_ROUTER}/hello returns HTTP 404

### ISSUE THREAD

**Issue by bharathnatarajan1** [fission/fission#1717]
Kubernetes Version V1.9.0, Fission Version 1.11.0, Windows 10 Enterprise, driver=docker minikube version  v1.13.0

**Describe the bug**
Getting HTTP 404 when trying to access fission function 'hello' through $FISSION_ROUTER.

**To Reproduce**
 

1. fission env create --name node --image fission/node-env
2. fission fn create --name hello --code hello.js --env node
3. fission route create --function hello --url /hello
4. curl http://${FISSION_ROUTER}/hello

**Expected result**
Hello, world!

**Actual result**
404 page not found

**Screenshots/Dump file**
```
PS C:\Windows\system32> fission route list
NAME                                 METHOD URL                                                                                                                                 FUNCTION(s) INGRESS HOST PATH                                                                                                                                TLS ANNOTATIONS
271b55d8-08e5-4b48-b716-8c6a2d3e5a89 GET    /C:/ProgramData/App-V/B26A42BE-666F-400A-8BE9-BBF04AA7C7A3/13A487C3-8753-433D-A58C-4929C1405264/Root/VFS/ProgramFilesX64/Git/hello2 hello2      false   *    /C:/ProgramData/App-V/B26A42BE-666F-400A-8BE9-BBF04AA7C7A3/13A487C3-8753-433D-A58C-4929C1405264/Root/VFS/ProgramFilesX64/Git/hello2
5fc7e873-ecef-425a-afc3-1ca1518016ff GET    /C:/ProgramData/App-V/B26A42BE-666F-400A-8BE9-BBF04AA7C7A3/13A487C3-8753-433D-A58C-4929C1405264/Root/VFS/ProgramFilesX64/Git/hello  hello       false   *    /C:/ProgramData/App-V/B26A42BE-666F-400A-8BE9-BBF04AA7C7A3/13A487C3-8753-433D-A58C-4929C1405264/Root/VFS/ProgramFilesX64/Git/hello
```

```
PS C:\Windows\system32> fission fn get --name=hello

module.exports = async function(context) {
    return {
        status: 200,
        body: "hello, world!\n"
    };
``

```

PS C:\Windows\system32> kubectl --namespace fission get pods
NAME                                                     READY   STATUS    RESTARTS   AGE
buildermgr-7d7c4cfd87-2k6ft                              1/1     Running   1          175m
busybox                                                  1/1     Running   0          62m
controller-7c86dcd559-89fz5                              1/1     Running   0          175m
executor-7f4c497bb-55z62                                 1/1     Running   1          175m
fission-prometheus-alertmanager-c5ff7cc96-h47fv          2/2     Running   0          175m
fission-prometheus-kube-state-metrics-68466fff67-psmpf   1/1     Running   0          175m
fission-prometheus-node-exporter-7m5x2                   1/1     Running   0          175m
fission-prometheus-pushgateway-69c586776c-7z9mw          1/1     Running   0          175m
fission-prometheus-server-5d465bcb-g87f8                 2/2     Running   0          175m
influxdb-59649c8c6-5cqwd                                 1/1     Running   0          175m
kubewatcher-7c6f655859-gg4lc                             1/1     Running   0          175m
logger-5p22v                                             2/2     Running   0          175m
mqtrigger-nats-streaming-5967dbc5d6-dlpsx                1/1     Running   3          175m
nats-streaming-6c6d7c6fbf-xqgjl                          1/1     Running   0          175m
router-6c44ffbbcc-bdd9m                                  1/1     Running   1          175m
storagesvc-7cf567d47f-s579r                              1/1     Running   0          175m
timer-55855fb7-vq4xc                                     1/1     Running   0          175m
```

```
PS C:\Windows\system32> kubectl --namespace fission logs router-6c44ffbbcc-bdd9m
{"level":"info","ts":"2020-09-17T08:38:15.208Z","caller":"fission-bundle/main.go:130","msg":"skipping trace exporter registration"}
{"level":"info","ts":"2020-09-17T08:38:40.115Z","caller":"router/router.go:236","msg":"starting router","port":8888}
{"level":"info","ts":"2020-09-17T08:44:20.930Z","logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:502","msg":"UnTapService Called"}
{"level":"info","ts":"2020-09-17T09:26:06.270Z","logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:502","msg":"UnTapService Called"}
{"level":"info","ts":"2020-09-17T09:30:52.195Z","logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:502","msg":"UnTapService Called"}
{"level":"info","ts":"2020-09-17T09:35:58.337Z","logger":"triggerset.http_trigger_set.hello","caller":"router/functionHandler.go:502","msg":"UnTapService Called"}

PS C:\Windows\system32> kubectl --namespace fission logs storagesvc-7cf567d47f-s579r
{"level":"info","ts":"2020-09-17T08:37:49.821Z","caller":"fission-bundle/main.go:130","msg":"skipping trace exporter registration"}
{"level":"info","ts":"2020-09-17T08:37:49.822Z","caller":"storagesvc/storagesvc.go:234","msg":"storage service started"}
{"level":"info","ts":"2020-09-17T09:37:49.822Z","logger":"archive_pruner","caller":"storagesvc/archivePruner.go:78","msg":"getting orphan archives"}
{"level":"info","ts":"2020-09-17T10:37:49.822Z","logger":"archive_pruner","caller":"storagesvc/archivePruner.go:78","msg":"getting orphan archives"}

```

```
PS C:\Windows\system32> kubectl --namespace fission logs timer-55855fb7-vq4xc
{"level":"info","ts":"2020-09-17T08:38:34.314Z","caller":"fission-bundle/main.go:130","msg":"skipping trace exporter registration"}

PS C:\Windows\system32> kubectl --namespace fission logs executor-7f4c497bb-55z62
{"level":"info","ts":"2020-09-17T08:38:24.673Z","caller":"fission-bundle/main.go:130","msg":"skipping trace exporter registration"}
{"level":"info","ts":"2020-09-17T08:38:40.399Z","caller":"executor/executor.go:255","msg":"Starting executor","instanceID":"qof26h7z"}
{"level":"info","ts":"2020-09-17T08:38:40.402Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:390","msg":"Poolmanager starts to clean orphaned resources","instanceID":"qof26h7z"}
{"level":"info","ts":"2020-09-17T08:38:40.402Z","logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:285","msg":"Newdeploy starts to clean orphaned resources","instanceID":"qof26h7z"}
{"level":"info","ts":"2020-09-17T08:38:40.841Z","logger":"executor","caller":"executor/api.go:250","msg":"starting executor API","port":8888}
{"level":"info","ts":"2020-09-17T08:39:11.037Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:99","msg":"creating pool","environment":{"name":"nodejs","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/environments/nodejs","uid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","resourceVersion":"1221","generation":1,"creationTimestamp":"2020-09-17T08:39:10Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:39:10Z"}]}}
{"level":"info","ts":"2020-09-17T08:39:11.061Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:140","msg":"deployment created","environment":{"name":"nodejs","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/environments/nodejs","uid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","resourceVersion":"1221","generation":1,"creationTimestamp":"2020-09-17T08:39:10Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:39:10Z"}]}}
{"level":"info","ts":"2020-09-17T08:44:20.808Z","logger":"generic_pool_manager.function_service_cache","caller":"fscache/functionServiceCache.go:175","msg":"Not found in Cache"}
{"level":"info","ts":"2020-09-17T08:44:20.809Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:581","msg":"choosing pod from pool","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T08:44:20.813Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:223","msg":"found ready pods","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"ready_count":3,"total":3}
{"level":"info","ts":"2020-09-17T08:44:20.813Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:254","msg":"relabel pod","pod":"{\"metadata\":{\"annotations\":{\"executorInstanceId\":\"qof26h7z\"}, \"labels\":{\"environmentName\":\"nodejs\",\"environmentNamespace\":\"default\",\"environmentUid\":\"749ffbda-f58e-43f3-ad68-cdb0b700230d\",\"executorType\":\"poolmgr\",\"functionName\":\"hello\",\"functionNamespace\":\"default\",\"functionUid\":\"16622077-59b8-438a-8636-5108af7aef41\",\"managed\":\"false\"}}}"}
{"level":"info","ts":"2020-09-17T08:44:20.834Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:278","msg":"chose pod","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"pod":"poolmgr-nodejs-default-1221-8656459bbb-xcj2j","elapsed_time":0.024623305}
{"level":"info","ts":"2020-09-17T08:44:20.835Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:348","msg":"calling fetcher to copy function","function":"hello","url":"http://172.18.0.20:8000/"}
{"level":"info","ts":"2020-09-17T08:44:20.835Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:352","msg":"specializing pod","function":"hello"}
{"level":"info","ts":"2020-09-17T08:44:20.876Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:635","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-xcj2j","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T08:44:20.916Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:676","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-xcj2j","podNamespace":"fission-function","function":"hello","functionNamespace":"default","specialization_host":"172.18.0.20:8888"}
{"level":"info","ts":"2020-09-17T08:46:21.261Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:637","msg":"release idle function resources","function":"hello","address":"172.18.0.20:8888","executor":"poolmgr","pod":"poolmgr-nodejs-default-1221-8656459bbb-xcj2j"}
{"level":"info","ts":"2020-09-17T09:26:06.165Z","logger":"generic_pool_manager.function_service_cache","caller":"fscache/functionServiceCache.go:175","msg":"Not found in Cache"}
{"level":"info","ts":"2020-09-17T09:26:06.167Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:581","msg":"choosing pod from pool","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T09:26:06.171Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:223","msg":"found ready pods","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"ready_count":3,"total":3}
{"level":"info","ts":"2020-09-17T09:26:06.171Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:254","msg":"relabel pod","pod":"{\"metadata\":{\"annotations\":{\"executorInstanceId\":\"qof26h7z\"}, \"labels\":{\"environmentName\":\"nodejs\",\"environmentNamespace\":\"default\",\"environmentUid\":\"749ffbda-f58e-43f3-ad68-cdb0b700230d\",\"executorType\":\"poolmgr\",\"functionName\":\"hello\",\"functionNamespace\":\"default\",\"functionUid\":\"16622077-59b8-438a-8636-5108af7aef41\",\"managed\":\"false\"}}}"}
{"level":"info","ts":"2020-09-17T09:26:06.177Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:278","msg":"chose pod","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"pod":"poolmgr-nodejs-default-1221-8656459bbb-rcxqj","elapsed_time":0.009647272}
{"level":"info","ts":"2020-09-17T09:26:06.177Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:348","msg":"calling fetcher to copy function","function":"hello","url":"http://172.18.0.21:8000/"}
{"level":"info","ts":"2020-09-17T09:26:06.177Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:352","msg":"specializing pod","function":"hello"}
{"level":"info","ts":"2020-09-17T09:26:06.234Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:635","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-rcxqj","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T09:26:06.263Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:676","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-rcxqj","podNamespace":"fission-function","function":"hello","functionNamespace":"default","specialization_host":"172.18.0.21:8888"}
{"level":"info","ts":"2020-09-17T09:28:08.843Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:637","msg":"release idle function resources","function":"hello","address":"172.18.0.21:8888","executor":"poolmgr","pod":"poolmgr-nodejs-default-1221-8656459bbb-rcxqj"}
{"level":"info","ts":"2020-09-17T09:30:52.101Z","logger":"generic_pool_manager.function_service_cache","caller":"fscache/functionServiceCache.go:175","msg":"Not found in Cache"}
{"level":"info","ts":"2020-09-17T09:30:52.103Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:581","msg":"choosing pod from pool","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T09:30:52.107Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:223","msg":"found ready pods","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"ready_count":3,"total":3}
{"level":"info","ts":"2020-09-17T09:30:52.107Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:254","msg":"relabel pod","pod":"{\"metadata\":{\"annotations\":{\"executorInstanceId\":\"qof26h7z\"}, \"labels\":{\"environmentName\":\"nodejs\",\"environmentNamespace\":\"default\",\"environmentUid\":\"749ffbda-f58e-43f3-ad68-cdb0b700230d\",\"executorType\":\"poolmgr\",\"functionName\":\"hello\",\"functionNamespace\":\"default\",\"functionUid\":\"16622077-59b8-438a-8636-5108af7aef41\",\"managed\":\"false\"}}}"}
{"level":"info","ts":"2020-09-17T09:30:52.119Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:278","msg":"chose pod","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"pod":"poolmgr-nodejs-default-1221-8656459bbb-zw4r2","elapsed_time":0.01523011}
{"level":"info","ts":"2020-09-17T09:30:52.122Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:348","msg":"calling fetcher to copy function","function":"hello","url":"http://172.18.0.20:8000/"}
{"level":"info","ts":"2020-09-17T09:30:52.122Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:352","msg":"specializing pod","function":"hello"}
{"level":"info","ts":"2020-09-17T09:30:52.175Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:635","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-zw4r2","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T09:30:52.187Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:676","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-zw4r2","podNamespace":"fission-function","function":"hello","functionNamespace":"default","specialization_host":"172.18.0.20:8888"}
{"level":"info","ts":"2020-09-17T09:32:54.123Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:637","msg":"release idle function resources","function":"hello","address":"172.18.0.20:8888","executor":"poolmgr","pod":"poolmgr-nodejs-default-1221-8656459bbb-zw4r2"}
{"level":"info","ts":"2020-09-17T09:35:58.232Z","logger":"generic_pool_manager.function_service_cache","caller":"fscache/functionServiceCache.go:175","msg":"Not found in Cache"}
{"level":"info","ts":"2020-09-17T09:35:58.234Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:581","msg":"choosing pod from pool","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T09:35:58.237Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:223","msg":"found ready pods","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"ready_count":3,"total":3}
{"level":"info","ts":"2020-09-17T09:35:58.237Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:254","msg":"relabel pod","pod":"{\"metadata\":{\"annotations\":{\"executorInstanceId\":\"qof26h7z\"}, \"labels\":{\"environmentName\":\"nodejs\",\"environmentNamespace\":\"default\",\"environmentUid\":\"749ffbda-f58e-43f3-ad68-cdb0b700230d\",\"executorType\":\"poolmgr\",\"functionName\":\"hello\",\"functionNamespace\":\"default\",\"functionUid\":\"16622077-59b8-438a-8636-5108af7aef41\",\"managed\":\"false\"}}}"}
{"level":"info","ts":"2020-09-17T09:35:58.242Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:278","msg":"chose pod","labels":{"environmentName":"nodejs","environmentNamespace":"default","environmentUid":"749ffbda-f58e-43f3-ad68-cdb0b700230d","executorType":"poolmgr","functionName":"hello","functionNamespace":"default","functionUid":"16622077-59b8-438a-8636-5108af7aef41","managed":"false"},"pod":"poolmgr-nodejs-default-1221-8656459bbb-zv2gf","elapsed_time":0.007692955}
{"level":"info","ts":"2020-09-17T09:35:58.242Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:348","msg":"calling fetcher to copy function","function":"hello","url":"http://172.18.0.22:8000/"}
{"level":"info","ts":"2020-09-17T09:35:58.242Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:352","msg":"specializing pod","function":"hello"}
{"level":"info","ts":"2020-09-17T09:35:58.317Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:635","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-zv2gf","function":{"name":"hello","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello","uid":"16622077-59b8-438a-8636-5108af7aef41","resourceVersion":"1447","generation":1,"creationTimestamp":"2020-09-17T08:42:29Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T08:42:29Z"}]}}
{"level":"info","ts":"2020-09-17T09:35:58.333Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:676","msg":"specialized pod","pod":"poolmgr-nodejs-default-1221-8656459bbb-zv2gf","podNamespace":"fission-function","function":"hello","functionNamespace":"default","specialization_host":"172.18.0.22:8888"}
{"level":"info","ts":"2020-09-17T09:37:59.467Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:637","msg":"release idle function resources","function":"hello","address":"172.18.0.22:8888","executor":"poolmgr","pod":"poolmgr-nodejs-default-1221-8656459bbb-zv2gf"}
{"level":"error","ts":"2020-09-17T09:39:41.176Z","logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:420","msg":"error creating k8s resources for function","error":"environments.fission.io \"node\" not found","function_name":"hello2","function_namespace":"default"}
{"level":"error","ts":"2020-09-17T09:39:41.176Z","logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:326","msg":"error eager creating function","error":"error creating k8s resources for function hello2_default: environments.fission.io \"node\" not found","errorVerbose":"environments.fission.io \"node\" not found\nerror creating k8s resources for function hello2_default\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).createFunction\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:424\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).initFuncController.func1.1\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:324\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","function":{"metadata":{"name":"hello2","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello2","uid":"12a78c78-5276-4b75-abfa-ef0c5152a2a2","resourceVersion":"3993","generation":1,"creationTimestamp":"2020-09-17T09:39:41Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T09:39:41Z"}]},"spec":{"environment":{"namespace":"default","name":"node"},"package":{"packageref":{"namespace":"default","name":"hello2-66e82f8f-0527-4410-8252-783d175f6825","resourceversion":"3992"}},"secrets":null,"configmaps":null,"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"newdeploy","MinScale":1,"MaxScale":5,"TargetCPUPercent":80,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":60,"idletimeout":120}}}
{"level":"error","ts":"2020-09-17T09:41:28.239Z","logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:338","msg":"error deleting function","error":"error deleting kubernetes objects of function {hello2  default /apis/fission.io/v1/namespaces/default/functions/hello2 12a78c78-5276-4b75-abfa-ef0c5152a2a2 4070 1 2020-09-17 09:39:41 +0000 UTC <nil> <nil> map[] map[] [] nil []  [{fission-bundle Update fission.io/v1 2020-09-17 09:39:41 +0000 UTC nil}]}: fsvc not found in cache: {hello2  default /apis/fission.io/v1/namespaces/default/functions/hello2 12a78c78-5276-4b75-abfa-ef0c5152a2a2 4070 1 2020-09-17 09:39:41 +0000 UTC <nil> <nil> map[] map[] [] nil []  [{fission-bundle Update fission.io/v1 2020-09-17 09:39:41 +0000 UTC nil}]}: Resource not found - key '12a78c78-5276-4b75-abfa-ef0c5152a2a2' not found","errorVerbose":"Resource not found - key '12a78c78-5276-4b75-abfa-ef0c5152a2a2' not found\nfsvc not found in cache: {hello2  default /apis/fission.io/v1/namespaces/default/functions/hello2 12a78c78-5276-4b75-abfa-ef0c5152a2a2 4070 1 2020-09-17 09:39:41 +0000 UTC <nil> <nil> map[] map[] [] nil []  [{fission-bundle Update fission.io/v1 2020-09-17 09:39:41 +0000 UTC nil}]}\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).fnDelete\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:721\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).deleteFunction\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:439\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).initFuncController.func2.1\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:336\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337\nerror deleting kubernetes objects of function {hello2  default /apis/fission.io/v1/namespaces/default/functions/hello2 12a78c78-5276-4b75-abfa-ef0c5152a2a2 4070 1 2020-09-17 09:39:41 +0000 UTC <nil> <nil> map[] map[] [] nil []  [{fission-bundle Update fission.io/v1 2020-09-17 09:39:41 +0000 UTC nil}]}\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).deleteFunction\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:441\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).initFuncController.func2.1\n\t/go/src/pkg/executor/executortype/newdeploy/newdeploymgr.go:336\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","function":{"metadata":{"name":"hello2","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello2","uid":"12a78c78-5276-4b75-abfa-ef0c5152a2a2","resourceVersion":"4070","generation":1,"creationTimestamp":"2020-09-17T09:39:41Z","managedFields":[{"manager":"fission-bundle","operation":"Update","apiVersion":"fission.io/v1","time":"2020-09-17T09:39:41Z"}]},"spec":{"environment":{"namespace":"default","name":"node"},"package":{"packageref":{"namespace":"default","name":"hello2-66e82f8f-0527-4410-8252-783d175f6825","resourceversion":"3992"}},"secrets":null,"configmaps":null,"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"newdeploy","MinScale":1,"MaxScale":5,"TargetCPUPercent":80,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":60,"idletimeout":120}}}
{"level":"info","ts":"2020-09-17T09:42:47.980Z","logger":"new_deploy","caller":"newdeploy/newdeploy.go:161","msg":"set up all RBAC objects for function","function_name":"hello2","function_namespace":"default"}
```

```
$ echo $FISSION_ROUTER
127.0.0.1:30737
```


**Additional context**

Using minikube on Windows 10 Enterprise for Kubernetes Cluster. Have configured 'FISSION_ROUTER' as mentioned at https://docs.fission.io/docs/installation/env_vars/ and have enable port forwarding using below command since we are using minikube:
kubectl --namespace fission port-forward $(kubectl --namespace fission get pod -l svc=router -o name) 30737:8888 &

**Comment by vishal-biyani** [comment]
Hi @bharathnatarajan1 The logs say that `"error":"environments.fission.io "node" not found"` Can you please please ping on slack and seek some help. I am closing this issue as this does not seem like a bug.

**Comment by YonSunZhen** [comment]
Hi, @bharathnatarajan1 ,how do you fix this problem, i have suffer from the problem the same to you. Thanks!
