### ISSUE TITLE
Alert user if setting poolsize to zero

### ISSUE THREAD

**Issue by swaroopnuli** [fission/fission#1720]
**Fission/Kubernetes version**

<pre>
$ fission --version
1.11.0
$ kubectl version
AWS EKS 1.17.9
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
AWS EKS

**Describe the bug**

Poolmanger Functions associated with Environments having poolsize set to 0 are failing.

Please provide an indication if functions cannot be created with poolsize 0.
Otherwise have flexiblity of scalingup even with poolsize 0
**To Reproduce**

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by vishal-biyani** [comment]
The Poolsize for pool manager functions can not be zero because the pods are specialized from pool. You need a pool of at least 1 size for pool manager functions! I am closing this issue but please let us know if you have other questions.

**Comment by swaroopnuli** [comment]
Got it. It will be helpful if there is an alert or poolsize=0 disabled to avoid it.

**Comment by Divya063** [comment]
Maybe having a check for poolsize while creating or updating the env would work @vishal-biyani can I pick this up?

**Comment by vishal-biyani** [comment]
@Divya063 Yes please pick it up. Yes this is a CLI change and can be added as a check

**Comment by sanketsudake** [comment]
Closing issue since respective checks added via #1837. The fix would be available in upcoming release 1.13.
