### ISSUE TITLE
Idle timeout and function timeout does not work as expected

### ISSUE THREAD

**Issue by chenjr0719** [fission/fission#1722]
Hi there, I would like to confirm the behavior of function's `idletimeout` and `functiontimeout`. If my function will running longer than 120 secs and I set the `idletimeout` to 30 secs with `functiontimeout` to 180 secs, does my function pod be recycled before response?

Now I'm using 1.11.0 release and my function pod will be recycled. This is a little be different from my expect. :sweat_smile:

I thought that it will execute my function successfully then get the response before `functiontimeout` and after 30 secs of `idletimeout`, the function pod will be recycled.

However, the function pod will be cycled after 30 secs even my function is not yet responded. And it will cause an error `error sending request to function`. May I know in this case, how to config this two arguments correctly?

Here is the code to reproduce the error:

```python
import time


def main():
    time.sleep(120)
    return "Done"
```

And the command to create the function:

```shell
fission fn create --name test --env python --code test.py --idletimeout 30 --fntimeout 180
```

**Comment by vishal-biyani** [comment]
Closed by #1724, will be available in release 1.11.1
