### ISSUE TITLE
I need a rest api service for fission

### ISSUE THREAD

**Issue by jamesduan** [fission/fission#1729]
In my project , i want a rest api service to manage fission function and http trigger routers.Not use fission cmd client to manage function.

**Comment by pingdai** [comment]
RestAPI ：https://github.com/fission/fission/blob/52508e19343ef93da4ce8960908c5569f44da225/pkg/controller/api.go#L193

**Comment by RealHarshThakur** [comment]
@jamesduan sorry for late reply but you can already do it. For example: if you have a function named `hello`, 
Router exposes this function at `http://routerip/fission-function-hello` . Please reopen if you don't think this is solved

**Comment by jeacott1** [comment]
@RealHarshThakur I don't think that's what the OP meant.
I think @pingdai answer was closer to what he wanted. I'm also looking for a published client api or lib I can embed in my code to drive fission without using the cli. 
Is there perhaps a published swagger/openapi spec for fission somewhere?
