### ISSUE TITLE
Failed to create environment: unexpected end of JSON input

### ISSUE THREAD

**Issue by emersonwood** [fission/fission#173]
The [controller client](https://github.com/fission/fission/blob/master/controller/client/client.go)  is expecting a HTTP 201 response code from the controller, implemented in e1cb5f6e0981f8e1a023e84b6ae414725ea8dd8e, but is instead getting a 200 code.

```
func (c *Client) handleCreateResponse(resp *http.Response) ([]byte, error) {
	if resp.StatusCode != 201 {
		return nil, fission.MakeErrorFromHTTP(resp)
	}
	body, err := ioutil.ReadAll(resp.Body)
	return body, err
}
```

Both the body and the error are returned as nil, so the body cannot be unmarshalled from JSON which causes the error seen by the end user.

```
        body, err := c.handleCreateResponse(resp)
	if err != nil {
		return nil, err
	}

	var m fission.Metadata
	err = json.Unmarshal(body, &m)
	if err != nil {
		return nil, err
	}
```

I suspect this is happening because the docker images in [fission.yaml](https://github.com/fission/fission/blob/master/fission.yaml) are alpha20170124 - before this commit was made in master, meaning the controller is returning the 200 status code. The client that is being installed from http://fission.io/mac/fission must be newer than this expecting the 201 code.

**Comment by emersonwood** [comment]
The solution to this problem is to update the controller.

The easiest way to do this is download the fission.yaml file and change all instances of `fission/fission-bundle:alpha20170124` with `fission/fission-bundle:alpha20170324` and then run `kubectl create -f fission.yaml`. Note you might have to delete any existing pods with `kubectl delete -f fission.yaml` first.

**Comment by mingfang** [comment]
@emersonwood the new version fixes this and another problem I was having. What is the best way to keep track of new versions?

**Comment by emersonwood** [comment]
@mingfang the yaml file points to the fission docker hub, where the images are made public. You can check here regularly for available versions:
https://hub.docker.com/r/fission/fission-bundle/tags/

**Comment by soamvasani** [comment]
Updated the fission.yaml, versions are now compatible.  Existing setups can be fixed with:
```
kubectl apply -f http://fission.io/fission.yaml
```
