### ISSUE TITLE
typo in readme.md

### ISSUE THREAD

**Issue by Parikshit-Hooda** [fission/fission#1736]
**Fission/Kubernetes version**

<pre>
$ fission --version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

There is a typo in the repo's README.md file.

**To Reproduce**

1. Open README.md file.
2. Search for **meetnigs**.

**Expected result**

**meetings**.

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

Fixing in scope of hacktoberfest'20

**Comment by khushijindal** [comment]
Hey @Parikshit-Hooda can I take up this issue?

**Comment by Gauravsaha-97** [comment]
I would like to work on this issue.
