### ISSUE TITLE
Pods stuck at 'ContainerCreating'

### ISSUE THREAD

**Issue by saharshoza** [fission/fission#174]
**Kubernetes version**:
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.1", GitCommit:"b0b7a323cc5a4a2019b2e9520c21c7830b7f708e", GitTreeState:"clean", BuildDate:"2017-04-03T20:44:38Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```

**Environment**:
- **Cloud provider or hardware configuration**: 
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
```
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```
- **Kernel** (e.g. `uname -a`):
`4.4.0-72-generic #93-Ubuntu SMP Fri Mar 31 14:07:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`

**What happened**: I ran the following commands on a remote bare metal host:
`minikube start --vm-driver=kvm`
`kubectl create -f http://fission.io/fission.yaml`
`kubectl create -f http://fission.io/fission-nodeport.yaml`
`kubectl config set-context minikube --namespace fission`
`kubectl get pods -o wide`

```
NAME                           READY     STATUS              RESTARTS   AGE       IP        NODE
controller-1637203237-9w81n    0/1       ContainerCreating   0          43m       <none>    minikube
etcd-2122244727-pvmjv          0/1       ContainerCreating   0          43m       <none>    minikube
kubewatcher-2300228496-jsl3j   0/1       ContainerCreating   0          43m       <none>    minikube
poolmgr-3531518326-p5pzt       0/1       ContainerCreating   0          43m       <none>    minikube
router-2621354073-7rmq5        0/1       ContainerCreating   0          43m       <none>    minikube
```

I see that the pods are not yet running and no IP has been assigned. I confirm this by running  `kubectl get endpoints`

```
NAME         ENDPOINTS   AGE
controller   <none>      43m
etcd         <none>      43m
poolmgr      <none>      43m
router       <none>      43m
```
When I run `kubectl events`, I see the following error:
`Warning FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/pause-amd64:3.0\""`

I also see that I cannot ping google.com inside minikube ssh. (The VM is unable to connect to the internet.) I verified that my machine is not behind a proxy by running `env | grep -i proxy`. Could the missing endpoints for the pods be the reason for this?

**What I expected to see happen**:
When I run the same on my laptop as opposed to a remote bare metal instance I see the following after the same steps as above:

```
NAME         ENDPOINTS         AGE
controller   172.17.0.4:8888   14m
etcd         172.17.0.7:2379   14m
poolmgr      172.17.0.8:8888   14m
router       172.17.0.5:8888   14m
```
Hence I am not sure why it is not running on the remote instance in the same way. Can someone please guide me on how to go around fixing this?

**Comment by soamvasani** [comment]
> I also see that I cannot ping google.com inside minikube ssh. (The VM is unable to connect to the internet.)

Then the rest is failing is as expected -- your cluster is trying to pull the `pause` container from `gcr.io` and failing to do so.  I don't know enough here about your setup to debug this.

> I verified that my machine is not behind a proxy by running env | grep -i proxy

It's possible that there are other proxies in play; for example you could be behind a company firewall (again, I don't know enough about your setup).

Sorry, but this doesn't sound like a fission bug so I'm going to close this issue.  I suggesting asking for help in the #minikube or #kubernetes-users channels in the [kubernetes slack](http://slack.k8s.io/).  If you're still stuck, please DM me on the [fission slack](http://slack.fission.io).
