### ISSUE TITLE
Multiple documentation issues

### ISSUE THREAD

**Issue by EricBrianAnil** [fission/fission#1747]
1. It is mentioned that there is "more below" for environments, but nothing is mentioned regarding the environments in the documentation
2. It would be better to have a link to the licensing in the README like most official repositories
3. Could have official backlinks for external tools or websites mentioned in the README to redirect users  aptly

**Comment by kzuri** [comment]
Heyy @EricBrianAnil , I would like to help with this issue 😄

**Comment by genericbrian** [comment]
> Heyy @EricBrianAnil , I would like to help with this issue 😄

Heyy, thanks for the concern, but I think #1748 closes the above mentioned issues :)

**Comment by kzuri** [comment]
> > Heyy @EricBrianAnil , I would like to help with this issue 😄
> 
> Heyy, thanks for the concern, but I think #1748 closes the above mentioned issues :) 

No problem
