### ISSUE TITLE
1.0 / Production Ready Roadmap

### ISSUE THREAD

**Issue by tiny-dancer** [fission/fission#176]
Fission is marked early alpha and not production ready.  Wandering what the remaining TODO items are to be considered 1.0 / prod ready?

Having a list or tagging issues accordingly would help increase priority awareness for contributors and self-document gotchas for early consumers.

Great project and apologies if I missed this documented elsewhere.

**Comment by DanielFerreiraJorge** [comment]
I'd also like to know that!

**Comment by soamvasani** [comment]
Thanks for asking, folks.  We'll use the beta milestone to track this.  I'm going through issues marking them for beta right now.  

Feel free to nominate issues for beta by commenting on them, or file new issues if you think something is missing and not tracked.
