### ISSUE TITLE
# [Codecov](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=h1) Report

### ISSUE THREAD

**Issue by mohitrakhade20** [fission/fission#1778]
# [Codecov](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=h1) Report
> Merging [#1744](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=desc) into [master](https://codecov.io/gh/fission/fission/commit/0face3e9664461adf41871234fc82109ee7f80ba?el=desc) will **decrease** coverage by `7.22%`.
> The diff coverage is `n/a`.

[![Impacted file tree graph](https://codecov.io/gh/fission/fission/pull/1744/graphs/tree.svg?width=650&height=150&src=pr&token=mBWjJYSfIK)](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=tree)

```diff
@@            Coverage Diff             @@
##           master    #1744      +/-   ##
==========================================
- Coverage   28.41%   21.18%   -7.23%     
==========================================
  Files          69       52      -17     
  Lines        5040     3701    -1339     
==========================================
- Hits         1432      784     -648     
+ Misses       3390     2847     -543     
+ Partials      218       70     -148     
```

| [Impacted Files](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=tree) | Coverage Δ | |
|---|---|---|
| [pkg/crd/crdvalidations.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NyZC9jcmR2YWxpZGF0aW9ucy5nbw==) | `0.00% <0.00%> (-100.00%)` | :arrow_down: |
| [pkg/crd/crd.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NyZC9jcmQuZ28=) | `0.00% <0.00%> (-93.24%)` | :arrow_down: |
| [pkg/crd/client.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NyZC9jbGllbnQuZ28=) | `0.00% <0.00%> (-32.00%)` | :arrow_down: |
| [pkg/controller/configmapApi.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvY29uZmlnbWFwQXBpLmdv) | | |
| [pkg/controller/timeTriggerApi.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvdGltZVRyaWdnZXJBcGkuZ28=) | | |
| [pkg/controller/api.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvYXBpLmdv) | | |
| [pkg/controller/crd.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvY3JkLmdv) | | |
| [pkg/controller/storagesvc.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvc3RvcmFnZXN2Yy5nbw==) | | |
| [pkg/controller/environmentApi.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvZW52aXJvbm1lbnRBcGkuZ28=) | | |
| [pkg/controller/secretApi.go](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree#diff-cGtnL2NvbnRyb2xsZXIvc2VjcmV0QXBpLmdv) | | |
| ... and [10 more](https://codecov.io/gh/fission/fission/pull/1744/diff?src=pr&el=tree-more) | |

------

[Continue to review full report at Codecov](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=continue).
> **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> Powered by [Codecov](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=footer). Last update [0face3e...df14ef4](https://codecov.io/gh/fission/fission/pull/1744?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

_Originally posted by @codecov in https://github.com/fission/fission/pull/1744#issuecomment-701664814_

**Comment by vishal-biyani** [comment]
Hey @mohitrakhade20 What is this issue for?

**Comment by vishal-biyani** [comment]
Irrelevant & closing.
