### ISSUE TITLE
helm and the handling of the fission-function namespace 

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#180]
helm keeps track of one namespace for a "release".  But fission operates in two namespaces: (a) one for the fission services itself (for which we use the helm release namespace, thanks to #170), but also (b) one for the functions.

Separating the namespaces allows users to independently set quotas etc. on functions. But now helm doesn't know about this namespace, so it can't delete it correctly for example.

I'm not sure what the solution is here: we could use the fission namespace for both things when we're installed by helm, or we could investigate if there is a way to manage a second namespace correctly while using helm.

**Comment by ktrance** [comment]
According to this Helm issue: https://github.com/kubernetes/helm/issues/2060 , it is not currently supported to have multiple namespaces under one release. 
Or rather while you can install multi-namespaced charts tiller cannot query then or delete them etc. 

If that is correctly understood then for now at least the only option would appear to use a single namespace and wait for full helm support.

**Comment by soamvasani** [comment]
Thanks @ktrance.  Seems like we have to currently choose between a manual step in uninstall vs. rolling everything into one namespace.

I'd love to know how exactly the current design breaks with chart upgrades. Will have to try it out. If we can get that to work well then a manual step during uninstall seems acceptable.

**Comment by soamvasani** [comment]
Seems to work ok now. Helm install creates the function namespace and helm delete cleans it up.
