### ISSUE TITLE
Timer triggers with cron syntax produce incorrect "next invocation"

### ISSUE THREAD

**Issue by antHogis** [fission/fission#1813]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2020-09-16T15:37:59Z"
    GitCommit: 09b4ffed78ad7a7eea7ebaf47e7644843b0a0b12
    Version: 1.11.0
server:
  fission/core:
    BuildDate: "2020-09-16T13:41:28Z"
    GitCommit: f034a1c734af51cdd6dd4449d1db253a67e699c3
    Version: 1.11.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.11-dispatcher", GitCommit:"2e298c7e992f83f47af60cf4830b11c7370f6668", GitTreeState:"clean", BuildDate:"2019-09-19T22:20:12Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.9-gke.6300", GitCommit:"eb6985a7ebfd53457b0b91ba08fac07597bb87af", GitTreeState:"clean", BuildDate:"2020-09-15T09:20:11Z", GoVersion:"go1.13.9b4", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
GKE

**Describe the bug**
Fission produces timing incorrectly from cron string in Timer Triggers, or at least outputs the next invocation incorrectly. When given cron syntax `0 1 * * *` (every day at 01:00), and the current time is `2020-10-07T12:25:11Z`, the output of the next invocation is `2020-10-07T13:01:00Z` upon timer trigger creation.

**To Reproduce**
<pre>
$ fission env create --name nodejs --image fission/node-env --builder fission/node-builder
$ fission fn create --name foo --code foo.js --env nodejs
$ fission tt create --name foo-nightly --function foo --cron "0 1 * * *" 
</pre>

**Expected result**
<pre>
$ fission tt create --name foo-nightly --function foo --cron "0 1 * * *" 
trigger 'foo-nightly' created
Current Server Time:    2020-10-07T12:25:11Z
Next 1 invocation:      2020-10-08T01:00:00Z
</pre>

**Actual result**
<pre>
$ fission tt create --name foo-nightly --function foo --cron "0 1 * * *" 
trigger 'foo-nightly' created
Current Server Time:    2020-10-07T12:25:11Z
Next 1 invocation:       2020-10-07T13:01:00Z
</pre>

**Additional context**
The following command seems to produce the expected result, judging by the "next invocation" output. However, the cron syntax here is incorrect for the desired result.
<pre>
fission tt create --name foo-nightly --function foo --cron "0 * 1 * *"                                                                                                                                                                                                  
trigger 'foo-nightly' created
Current Server Time:    2020-10-07T12:30:47Z
Next 1 invocation:      2020-10-08T01:00:00Z
</pre>

The contents of the foo.js function:
<pre>
module.exports = (context) => {
    return {
        status: 200,
        body: 'OK'
    }
}
</pre>

**Comment by YLcoding** [comment]
@antHogis 

So I had similar questions so I look into the source code of the `timer` function.

Fission use this library for corn job: [github.com/robfig/cron](cron)

They use a non-standard cron job format that starts with seconds. Please follow this link to check their cron expression format -> [github.com/robfig/cron](cron)

the moral of the story is if you want to do `every day at 01:00`, you want to write your cron expression like this with an additional 0 at the beginning to represent second.

```
fission timer showschedule --cron "0 0 1 * * *" --round 5                                                                                  
Current Server Time: 	2021-08-09T21:18:09Z
Next 1 invocation: 	2021-08-10T01:00:00Z
Next 2 invocation: 	2021-08-11T01:00:00Z
Next 3 invocation: 	2021-08-12T01:00:00Z
Next 4 invocation: 	2021-08-13T01:00:00Z
Next 5 invocation: 	2021-08-14T01:00:00Z
```

I tested it and it worked.

@gauravgahlot 

Maybe this is something that worth mention in CLI --help docs.  Most people are used to the standard cron job format.  Maybe I could add it in.

**Comment by gauravgahlot** [comment]
@YLcoding Please go ahead and submit a PR. This would definitely be helpful for users.
