### ISSUE TITLE
Feature Request: Override Environment settings from newdeploy function spec

### ISSUE THREAD

**Issue by justinfx** [fission/fission#1820]
**Is your feature request related to a problem? Please describe.**
I will  have many functions that accesses NFS volumeMount resources with permissions that vary between user/group. I would like to be able to deploy a function that can set the `securityContext` "user", "group", "supplementalGroups" values so that the function runs with the correct permissions for the data on the mounted volumes. Currently both the poolmgr and newdeploy executor type functions rely on a named reference to a shared Environment. This means the `securityContext` can only be defined at the environment and every function either has to use that named env, or they would have to deploy unique copies of the environment for every new variation of podSpec values. 
It seems unwieldy to have to maintain many Environment specs and use the "name" with the right securityContext to match the desired function. 

**Describe the solution you'd like**
Because a newdeploy executor results in a discrete deployment instance for each function, it would make sense that the function would have access to override all of the values of the named environment. Or to even fully define its own environment (less of a priority, but seems to be a related feature). With this ability, I would be able to set the `securityContext` on a per-function basis. This also seems to make sense as a feature as being in the spirit of the newdeploy executor and making it entirely self-contained instead of coupled to a environment spec.

**Describe alternatives you've considered**
The only alternative I can see for working around my problem is to manage the creation of a new copy of the environment with a unique name that pairs with each function that needs a different user/group/supplementaryGroups

**Additional context**
For some additional background on the nature of this problem, I work for a Visual Effects studio with a primary reliance on NFS mounted filesystems. These filesystems enforce group level permissions that map to projects. That is, if I do not have access to Lord of the Rings, I should not be able to access files in the Lord of the Rings project group. If we are deploying functions that expect to operate on project data, we need to make sure the user in the project, deploying the function, can set their group permissions for the container.

**Comment by justinfx** [comment]
I'm curious how seriously this feature request would be considered and whether it fits well into the intended goals of the `newdeploy` executor. While we are still working through our own prototypes and implementations, we see this as a requirement to ultimately continue with Fission. So it would be good to know if its within the realm of possibility? I am happy to go into more detail about any use-case questions. Much appreciated!

**Comment by vishal-biyani** [comment]
Hi @justinfx I think that you are proposing makes perfect sense and would be beneficial for other users as well. We will do some design with and prioritise this for one of upcoming releases.
