### ISSUE TITLE
Error fetching configmap/secret to function from fission-function namespace

### ISSUE THREAD

**Issue by Magomedali** [fission/fission#1828]
**Fission/Kubernetes version**

<pre>
Fission version: 1.11.0
Kubectl version: v1.15.11-eks
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

AWS/eks

**Describe the bug**
Error fetching configmap and secret when run function.
Secrets "scr-access-token" is forbidden: User "system:serviceaccount:fission-function:fission-fetcher" cannot get resource "secrets" in API group "" in the namespace "fission-function"

**To Reproduce**

Step 2: Create configmap or secret in the namespace "fission-function"
Step 3: Create function with that secret/configmap
Step 3: Run this function

**Expected result**

Running function with successfully fetching secrets and configmaps from namespace "fission-function"

**Actual result**

Fetching failed

**Screenshots/Dump file**

{"level":"error","ts":"2020-10-12T09:23:28.289Z","logger":"fetcher","caller":"fetcher/fetcher.go:340","msg":"error getting secret from kubeapi","error":"secrets \"scr-access-token\" is forbidden: User \"system:serviceaccount:fission-function:fission-fetcher\" cannot get resource \"secrets\" in API group \"\" in the namespace \"fission-function\"","secret_name":"scr-access-token","secret_namespace":"fission-function","stacktrace":"github.com/fission/fission/pkg/fetcher.(*Fetcher).FetchSecretsAndCfgMaps\n\t/go/src/pkg/fetcher/fetcher.go:340\ngithub.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializePod\n\t/go/src/pkg/fetcher/fetcher.go:597\ngithub.com/fission/fission/pkg/fetcher.(*Fetcher).SpecializeHandler\n\t/go/src/pkg/fetcher/fetcher.go:197\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2375\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878"}

**Pull request**
#1836

**Comment by therahulbhati** [comment]
@Magomedali Are your function and secret/configmap both in fission-function namespace?

**Comment by Magomedali** [comment]
> @Magomedali In steps to reproduce, are your function and secret/configmap both in fission-function namespace?

@therahulbhati No, it turns out they are in different namespaces. Sorry for my carelessness ))

**Comment by therahulbhati** [comment]
It's fine @Magomedali. Thanks for updating us.
