### ISSUE TITLE
Integrate golangci-lint with fission CI

### ISSUE THREAD

**Issue by gauravgahlot** [fission/fission#1835]
### Problem

At present, there are a lot of linting issues across fission. Some of them are being addressed during Hacktoberfest. However, we need a concrete solution to avoid any new issues and maintain our code standard.

### Solution

I propose to introduce `golangci-lint` in the fission CI. `golangci-lint` is a fast Go linters runner. It runs linters in parallel, uses caching, supports yaml config, has integrations with all major IDE and has dozens of linters included.

Please check the [documentation](https://golangci-lint.run/) for more details.

**Note**: I have proposed `golangci-lint` since I have some experience using it in a different project. However, any other suggestions are most welcome. 

### Execution

**Phase I**
- if we straight away introduce `golangci-lint` in the CI, all the PRs will fail, and contributions will be blocked
- to avoid that, any contributor can run `golangci-lint` locally and fix the issues for an individual package and submit a PR
- we shall multiple PRs against this issue 

**Phase II**
 - integrate `golangci-lint` with fission CI
 - fix any failing PRs (asking contributors)

**Comment by sanketsudake** [comment]
Closing this as done as part of https://github.com/fission/fission/pull/2089
