### ISSUE TITLE
Consider not using cluster-admin

### ISSUE THREAD

**Issue by coderanger** [fission/fission#1845]
Hi there, this is 100% a drive-by issue because I was helping someone in Kubernetes Slack with a problem but I wanted to make sure this is on your radar. In your deployment manifests, you bind the fission ServiceAccount to `cluster-admin`. That seems highly unnecessary and a big security hole. I'm sure it makes setup much simpler since it looks like the main controller deployment sets up a lot of secondary API objects after startup, but maybe at least support a more secure mode where Fission only gets the permissions it needs for normal operations and those secondary global objects are set up via the manifests? For example, it looks like you install your CustomResourceDefinition objects this way.

**Comment by vishal-biyani** [comment]
Hi @coderanger - thanks for bringing this to notice, this is definitely a big no, will fix it ASAP!
