### ISSUE TITLE
Fission environment image updates not getting reflected in NewDeploy function pods.

### ISSUE THREAD

**Issue by abbaspw21** [fission/fission#1848]
**Fission/Kubernetes version**
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

$ fission version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
```

**Describe the bug**
In case if there is change in fission environment image then that change is not getting reflected in new deploy fission function pods when environment and function both are running in **different namespace**. In case if environment and function both are running in same namespace then everything works fine.

**To Reproduce**
To reproduce it deploy an fission environment and function in different namespaces and then update the image in fission environment.

**Expected result**
Its expected that fission function pods for newdeploy would get recreated and fission environment image change would be visible in them.

**Actual result**
In actual its observed that fission function pods for newdeploy functions keeps on running with old image and even when pod is restarted this change is not visible. To update the image we have to redeploy the fission function

**Additional context**
In newdeploymgr.go currently fission environment namespace is used to find the newdeploy functions which are impacted by the change of image in fission environment in place of which it should look on all the function impacted across all the namespaces.

https://github.com/fission/fission/blob/master/pkg/executor/executortype/newdeploy/newdeploymgr.go#L393

**Comment by abbaspw21** [comment]
@vishal-biyani

**Comment by abbaspw21** [comment]
@vishal-biyani Can you please help us with the ETA for release 1.12.0.

**Comment by vishal-biyani** [comment]
@abbaspw21 Planned for release in the second week of December.

**Comment by harshthakur9030** [comment]
@abbaspw21 Can you please explain the use case a bit more in detail? I am trying to understand why Functions and Environments are in different namespaces because the function pods would be in the environment namespace in the end.

**Comment by abbaspw21** [comment]
@harshthakur9030 Fission supports different namespaces for environment and functions and we are using this capability to manage/segregate the function resources (which are using same fission environment) in different different namespaces as per our requirement and design.
Its just that cm update are not getting reflected in the above case.

**Comment by harshthakur9030** [comment]
@abbaspw21 Sorry, I didn't yet understand.  What is being achieved by this particular design of having environment and function in different namespaces? The execution context of function pods would remain in the environment namespace regardless, so what is the objective to have functions in different namespace?

**Comment by abbaspw21** [comment]
Hi @vishal-biyani / @RealHarshThakur,
Even after upgrading fission to 1.12.0 we are facing this issue.

**Comment by RealHarshThakur** [comment]
Hey @abbaspw21 , I just checked again and it's working. Here's what I tried:
* fission env create --name nodejs --image fission/node-env --envns=env
* fission function create --name hello --env nodejs --code hello.js --fns=func --envns=env
* fission env update --name nodejs --image fission/node-env-debian --envns=env

Can you please tell me what you've tried? 
There's an open issue around namespace inconsistency so this won't work if we don't specify namespace or use default namespace.

**Comment by abbaspw21** [comment]
Hi @RealHarshThakur , 
In our case we are deleting and recreating the environment.

Steps : 

- Create environment
- Create new deploy function
- Delete environment
- Create same environment back again.

**Comment by RealHarshThakur** [comment]
@abbaspw21 seems to be a different issue related to newdeploy alone.  Newdepl

**Comment by RealHarshThakur** [comment]
@abbaspw21 seems to be a different issue related to NewDeploy . Problem is that NewDeploy is kind off independent of the environment pods.

**Comment by abbaspw21** [comment]
@RealHarshThakur As per my understanding NewDeploy pods are created from fission environment spec and so if am recreating a fission environment its expected that existing NewDeploy function's pods are recreated to accommodate the new changes.

**Comment by blackfly19** [comment]
Hi @abbaspw21. We have raised quite a few PRs to fix this issue. First thing the `fission env update` will update the image which will reflect in the new deploy pods. Secondly now you will not be able to delete the env until atleast one function exists associated to the env. So the only way to change image is via `fission env update`.
I am closing this issue. Feel free to open it if you are still facing issues.
