### ISSUE TITLE
"http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in .ms" errors occurring in executor

### ISSUE THREAD

**Issue by danyc** [fission/fission#1858]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.11-eks-065dce", GitCommit:"065dcecfcd2a91bd68a17ee0b5e895088430bd05", GitTreeState:"clean", BuildDate:"2020-07-16T01:44:47Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Amazon EKS

**Describe the bug**

Executor pod restarted and many occurrences of:
`
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 5ms                                                                                                     
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 10ms                                                                                                   
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 20ms                                                                                                   
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 40ms                                                                                                    
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 80ms                                                                                                    
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 5ms                                                                                                    
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 10ms                                                                                                    
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 20ms                                                                                                    
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 40ms                                                                                                    
│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 80ms 
`

**To Reproduce**

Tried the [Autoscaling](https://docs.fission.io/docs/usage/executor/#autoscaling) scenario from docs on my fission deployment done via 1.11.2 chart to my EKS cluster, with the following values file:

```
## Kubernetes configuration
## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP.
serviceType: ClusterIP

## For minikube, set this to NodePort, elsewhere use LoadBalancer or ClusterIP.
routerServiceType: LoadBalancer

## Image base repository
## Leave it empty for using existing local image
repository: index.docker.io

## Fission image repository
image: fission/fission-bundle

## Image pull policy
pullPolicy: IfNotPresent

## Fission image version
imageTag: 1.11.2

## Port at which Fission controller service should be exposed
controllerPort: 31313

## Port at which Fission router service should be exposed
routerPort: 31314

## Port at which NATS streaming service should be exposed
## (only if nats enabled and not external)
natsStreamingPort: 31316

## Set to false if you create the namespaces manually
createNamespace: false

## Namespace in which to run fission functions (this is different from
## the release namespace)
functionNamespace: fission-function

## Namespace in which to run fission builders (this is different from
## the release namespace)
builderNamespace: fission-builder

## Enable istio integration
enableIstio: true

fetcher:
  ## Fetcher repository
  image: fission/fetcher
  ## Fetcher image version
  imageTag: 1.11.2

  ## Fetcher is only for to downloading or uploading archive.
  ## Normally, you don't need to change the value here, unless necessary.
  resource:
    cpu:
      requests: "10m"
      ## Low CPU limits will increases the function specialization time.
      limits: ""
    mem:
      requests: "16Mi"
      limits: ""

## Logger config
logger:
  influxdbAdmin: "admin"
  fluentdImageRepository: index.docker.io
  fluentdImage: fluent/fluent-bit
  fluentdImageTag: 1.5.1

  ## Fluent-bit writes/reads it’s own sqlite database to record a history of tracked
  ## files and a state of offsets, this is very useful to resume a state if the ser-
  ## vice is restarted. For Kubernetes environment with constraints like OpenShift,
  ## the containers are limited to write hostPath volume. Hence, we have to enable
  ## security context and set privileged to true.
  enableSecurityContext: false

  ## Enable PodSecurityPolicies to allow privileged container
  ## Only required in some clusters and when enableSecurityContext is true
  podSecurityPolicy:
    enabled: false

    ## Configure additional capabilities
    additionalCapabilities:
    # example values for linkerd
    #- NET_RAW
    #- NET_ADMIN

executor:
  adoptExistingResources: false
  podReadyTimeout: 300s

## Router config
router:
  deployAsDaemonSet: true
  svcAddressMaxRetries: 5
  svcAddressUpdateTimeout: 30s
  unTapServiceTimeout: 3600s
  ## Display endpoint access logs
  ## To be aware of enabling logging endpoint access log, it increases
  ## router resource utilization when under heavy workloads.
  displayAccessLog: false

  ## Add annotations for router
  # svcAnnotations:
  #   cloud.google.com/load-balancer-type: Internal

  ## For router to match encoded path.
  ## If true, "/foo%2Fbar" will match the path "/{var}";
  ## Otherwise, it will match the path "/foo/bar".
  useEncodedPath: false

  roundTrip:
    ## If true, router will disable the HTTP keep-alive which result in performance degradation.
    ## But it ensures that router can redirect new coming requests to new function pods.
    ##
    ## If false, router will enable transport keep-alive feature for better performance.
    ## However, the drawback is it takes longer to switch to newly created function pods
    ## if using newdeploy as executor type for function. If you want to preserve the
    ## performance while keeping the short switching time to new function, you can create
    ## an environment with short grace period by setting flag "--graceperiod" (default 360s),
    ## so that kubernetes will be able to reap old function pod quickly.
    ##
    ## For details, see https://github.com/fission/fission/issues/723
    disableKeepAlive: false

    ## The keep-alive period for an active network connection to function pod.
    keepAliveTime: 30s

    ## HTTP transport request timeout
    timeout: 5s

    ## The length of request timeout will multiply with timeoutExponent after each retry
    timeoutExponent: 2

    ## Max retries times of a failed request
    maxRetries: 10

  ## Sample with a rate per time window (traces/second)
  traceSamplingRate: 0.5

## Message queue trigger config
### NATS Streaming, enabled by default
nats:
  # whether or not to use NATS
  enabled: true

  # if true, don't install NATS, but
  external: false

  # Address of NATS server (domain:port)
  # change from default for external NATS
  hostaddress: "nats-streaming:4222"

  # Authorization token to use with NATS
  authToken: "defaultFissionAuthToken"

  # NATS streaming clusterID
  clusterID: "fissionMQTrigger"

  # Client name registered with NATS streaming
  clientID: "fission"

  # Queue group registered with NATS streaming
  queueGroup: "fission-messageQueueNatsTrigger"

  # The image to use for NATS streaming server
  streamingserver:
    image: nats-streaming

## Azure-storage-queue: enable and configure the details
azureStorageQueue:
  enabled: false
  key: ""
  accountName: ""

## Kafka: enable and configure the details
kafka:
  enabled: true
  # note: below link is only for reference.
  # Please use the brokers link for your kafka here.
  brokers: "your-bootstrap-server.kafka:9092" # or your-bootstrap-server.kafka:9092/9093
  authentication:
    tls:
      enabled: false
      # InsecureSkipVerify controls whether a client verifies the server's certificate chain and host name.
      insecureSkipVerify: false # Warning: Setting this to true, makes TLS susceptible to man-in-the-middle attacks
      caCert: "" # path to certificate containing public key of CA authority
      userCert: "" # path to certificate containing public key of the user signed by CA authority
      userKey: "" # path to private key of the user


  # brokers: 'my-broker.kafka:9092' # or my-bootstrap-server.kafka:9092/9093
  # Sample config for authentication
  #   authentication:
  #   tls:
  #     enabled: true
  #     caCert: 'auth/kafka/ca.crt'
  #     userCert: 'auth/kafka/user.crt'
  #     userKey: 'auth/kafka/user.key'

  ## version of Kafka broker
  ## For 0.x it must be a string in the format
  ## "major.minor.veryMinor.patch" example: 0.8.2.0
  ## For 1.x it must be a string in the format
  ## "major.major.veryMinor" example: 2.0.1
  ## Should be >= 0.11.2.0 to enable Kafka record headers support
  # version: "0.11.2.0"

## Persist data to a persistent volume.
persistence:
  ## If true, fission will create/use a Persistent Volume Claim unless storageType is set to s3
  ## If false, use emptyDir
  ##
  enabled: true

  ## Must be set to either local or S3.
  ## If storateType is set(other than local), one of its backend configuration must be set as below.
  #storageType: local | s3

  ## Sample configruation for AWS s3 storage backend
  #s3:
  # bucketName: <awsBucketName>
  # subDir: <sub directory within a bucket>
  # accessKeyId: <awsAccessKeyId>
  # secretAccessKey: <awsSecretAccessKey>
  # region: <awsRegion>

  ## A manually managed Persistent Volume Claim name
  ## Requires persistence.enabled: true
  ## If defined, PVC must be created manually before volume will be bound
  ##
  # existingClaim:

  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner. (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"

  accessMode: ReadWriteOnce
  size: 8Gi

## Extend the container specs for the core fission pods.
## Can be used to add things like affinty/tolerations/nodeSelectors/etc.
## For example:
## extraCoreComponentPodConfig:
##   affinity:
##     nodeAffinity:
##       requiredDuringSchedulingIgnoredDuringExecution:
##         nodeSelectorTerms:
##           - matchExpressions:
##             - key: capability
##               operator: In
##               values:
##                 - app
#extraCoreComponentPodConfig:
#  affinity:
#  tolerations:
#  nodeSelector:

## Analytics let us count how many people installed fission. Set to
## false to disable analytics.
analytics: false

## Internally used for generating an analytics job for non-helm installs
analyticsNonHelmInstall: false

## Enable Heapster only in clusters where heapster does not exist already
heapster: false

## Enable InfluxDB
influxdb:
  enabled: true
  image: influxdb:1.7

# Allow user to override busybox image used in fluent-bit init container
busyboxImage: busybox

## Archive pruner is a garbage collector for archives on the fission storage service.
## This interval configures the frequency at which it runs inside the storagesvc pod.
## The value is in minutes.
pruneInterval: 60

## Fission pre-install/pre-upgrade checks live in this image
preUpgradeChecksImage: fission/pre-upgrade-checks

## if there are any pod specialization errors when a function is triggered and this flag is set to true, the error
## summary is returned as part of http response
debugEnv: false

## Prometheus for scrapping service metrics
prometheus:
  ## set this flag to true if prometheus needs to be deployed along with fission
  enabled: false

  ## If enabled is false, please assign the prometheus service URL
  ## that is accessible by components.
  serviceEndpoint: "http://monitoring-prometheus-oper-prometheus:9090/"
#    serviceEndpoint: "http://prometheus-pushgateway.general:9091"

## set this flag to false if you dont need canary deployment feature
canaryDeployment:
  enabled: true

# Use these flags to enable opentracing, the variable is endpoint of Jaeger collector in the format shown below
#traceCollectorEndpoint: "http://jaeger-collector.jaeger.svc:14268/api/traces?format=jaeger.thrift"
#traceSamplingRate: 0.75

## Message Queue Trigger Kind, KEDA: enable and configuration
mqt_keda:
  enabled: true
  connector_images:
    kafka:
      image: fission/keda-kafka-http-connector
      tag: 1
    rabbitmq:
      image: fission/keda-rabbitmq-http-connector
      tag: 1
    awskinesis:
      image: fission/keda-awskinesis-http-connector
      tag: 1
    aws_sqs:
      image: fission/keda-aws-sqs-http-connector
      tag: 1
    nats_steaming:
      image: fission/keda-nats-streaming-http-connector
      tag: 1

```

**Expected result**

No errors or pod restarts

**Actual result**
I get many failures:
```
Status code distribution:
  [200]	213 responses
  [502]	3655 responses

Error distribution:
  [6132]	Get "http://xxx.eu-west-1.elb.amazonaws.com/hello-js": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
I've checked the pods and noticed executor restarted a couple of times and logs many errors:
`│ 2020/11/06 09:37:26 http: Accept error: accept tcp [::]:8888: accept4: too many open files; retrying in 80ms `

The logs in router pods have:
`{"level":"error","ts":"2020-11-06T09:37:26.533Z","logger":"triggerset.http_trigger_set.000c76a1-d7f0-4f4d-bcef-3385f811cc69","caller":"router/functionHandler.go:535","msg":"error from GetServiceForFunction", "error":"error posting to getting service for function: Post http://executor.fission/v2/getServiceForFunction: dial tcp 172.20.93.169:80: connect: connection refused","errorVerbose":"Post http://executor.fission/v2/getServiceForFunction: dial tcp 172.20.93.169:80: connect: connection refused\nerror posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction\n\t/go/src/pkg/executor/client/client.go:78\ngithub.com/fission/fission/pkg/router.functionHandler.getServiceEntryFromExecutor\n\t/go/src/pkg/router/functionHandler.go:532\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\t/go/src/pkg/router/functionHandler.go:187\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:259\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\t/go/src/pkg/router/functionHandler.go:424\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:1995\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.7.0/mux.go:212\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\t/go/src/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.22.0/plugin/ochttp/server.go:86\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2774\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1878\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337","error_message":"error posting to getting service for function: Post http://executor.fission/v2/getServiceForFunction: dial tcp 172.20.93.169:80: connect: connection refused","function":{"kind":"Function","apiVersion":"fission.io/v1","metadata":{"name":"hello-js","namespace":"default","selfLink":"/apis/fission.io/v1/namespaces/default/functions/hello-js","uid":"464f6958-51ac-4df6-a00c-d10d5b3976d5","resourceVersion":"241120394","generation":1,"creationTimestamp":"2020-11-06T06:51:24Z"},"spec":{"environment":{"namespace":"default","name":"node"},"package":{"packageref":{"namespace":"default","name":"hello-js-34b61285-6bdf-4025-acaf-696a4051e7cf","resourceversion":"241120392"}},"secrets":null,"configmaps":null,"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"newdeploy","MinScale":1,"MaxScale":6,"TargetCPUPercent":50,"SpecializationTimeout":120},"StrategyType":"execution"},"functionTimeout":60,"idletimeout":120}},"status_code":500} `

Am I missing some additional configuration to make it work?

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by therahulbhati** [comment]
Looks like you need to fine-tune few things:
1. Increase client-side timeout (-t param in hey tool)
2. Increase load balancer timeout `service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "900"`
3. Increase `ulimit -n` and refer to this doc for more fine-tuning settings https://k6.io/docs/misc/fine-tuning-os

**Comment by therahulbhati** [comment]
@danyc, did the above tuning helped?

**Comment by danyc** [comment]
Hello,

I was able to apply only the 1st suggestion and it helped, thank you.
For 2nd: because the deployment is done via helm chart, I cannot apply the additional annotation (or I don't know how).
For 3rd: would need to build a custom executor image.

Closing the issue.

**Comment by therahulbhati** [comment]
@danyc For 2nd, you can use following command: `kubectl annotate service router -nfission service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout="900"`
