### ISSUE TITLE
Poolmgr pod getting reaped immediately after specialization during environment change

### ISSUE THREAD

**Issue by airhorns** [fission/fission#1862]
**Fission/Kubernetes version**

Fission: v1.11.2
Kub

<pre>
inspector ~/C/gadget (main) ➜  fission version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
inspector ~/C/gadget (main) ➜  kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"4fb7ed12476d57b8437ada90b4f93b17ffaeed99", GitTreeState:"clean", BuildDate:"2020-07-15T16:18:16Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17+", GitVersion:"v1.17.12-gke.1504", GitCommit:"17061f5bd4ee34f72c9281d49f94b4f3ac31ac25", GitTreeState:"clean", BuildDate:"2020-10-19T17:00:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
</pre>

Kubernetes platform: GKE

**Describe the bug**

We're having a problem where the fission router is returning 504s for a small number of requests. I see this stuff in my logs:

 - a request comes in to the router for a function running in a poolmgr environment with no pods currently running
 - the executor specializes a pod for the request
 - the pod specialize completes
 - the request is made to the specialized pod by the router, and the process inside the pod accepts the request and starts processing it
 - the executor reaps the pod quite soon after
 - the pod is terminated very quickly and the inner process never finishes the request
 - the router gets a `context deadline exceeded` from the request from never hearing back and returns a 504

I can't quite be certain, but I believe this is happening because right around the same time the request comes in to the router, our CI/CD pipeline updates the Environment CRD with a new docker image, and fission starts recreating the pool responsible for running the function.

Here's the executor's log for an example where this happened

```
  |   | 2020-11-18 14:02:58 | {"level":"info","ts":"2020-11-18T19:02:58.750Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:289","msg":"chose pod","labels":{"environmentName":"js-sandbox","environmentNamespace":"gadget-app-sandbox-production","environmentUid":"22e65558-66ea-4c8c-87c0-a766822cd152","executorType":"poolmgr","functionName":"appenv-119-fn","functionNamespace":"gadget-app-sandbox-production","functionUid":"515488e1-6b27-48ba-bfea-aecf627302eb","managed":"false"},"pod":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","elapsed_time":0.029227993}
-- | -- | -- | --
  |   | 2020-11-18 14:02:59 | {"level":"info","ts":"2020-11-18T19:02:59.081Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:646","msg":"specialized pod","pod":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","function":{"name":"appenv-119-fn","namespace":"gadget-app-sandbox-production","selfLink":"/apis/fission.io/v1/namespaces/gadget-app-sandbox-production/functions/appenv-119-fn","uid":"515488e1-6b27-48ba-bfea-aecf627302eb","resourceVersion":"75984168","generation":1,"creationTimestamp":"2020-11-18T14:16:37Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"fission.io/v1\",\"kind\":\"Function\",\"metadata\":{\"name\":\"appenv-119-fn\",\"namespace\":\"gadget-app-sandbox-production\",\"annotations\":{}},\"spec\":{\"InvokeStrategy\":{\"ExecutionStrategy\":{\"ExecutorType\":\"poolmgr\",\"MaxScale\":3,\"MinScale\":0,\"SpecializationTimeout\":30,\"TargetCPUPercent\":0},\"StrategyType\":\"execution\"},\"configmaps\":null,\"environment\":{\"name\":\"js-sandbox\",\"namespace\":\"gadget-app-sandbox-production\"},\"functionTimeout\":15,\"idletimeout\":120,\"package\":{\"packageref\":{\"name\":\"empty\",\"namespace\":\"gadget-app-sandbox-production\"}},\"resources\":{},\"secrets\":[{\"name\":\"appenv-119-secret\",\"namespace\":\"gadget-app-sandbox-production\"}]}}"}}} Show context
  |   | 2020-11-18 14:02:59 | {"level":"info","ts":"2020-11-18T19:02:59.098Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:687","msg":"specialized pod","pod":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","podNamespace":"gadget-app-sandbox-production","function":"appenv-119-fn","functionNamespace":"gadget-app-sandbox-production","specialization_host":"10.36.4.43:8888"}
  |   | 2020-11-18 14:06:29 | {"level":"info","ts":"2020-11-18T19:06:29.093Z","logger":"generic_pool_manager","caller":"poolmgr/gpm.go:637","msg":"release idle function resources","function":"appenv-119-fn","address":"10.36.4.43:8888","executor":"poolmgr","pod":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b"}
```

and here's the pod's output for the same example:

```

  |   | 2020-11-18 13:54:05 | {"level":"info","ts":"2020-11-18T18:54:05.672Z","caller":"app/server.go:136","msg":"fetcher ready to receive requests"}
-- | -- | -- | --
  |   | 2020-11-18 13:54:06 | yarn workspace v1.22.5
  |   | 2020-11-18 13:54:06 | warning Skipping preferred cache folder "/app/.cache/yarn" because it is not writable.
  |   | 2020-11-18 13:54:06 | warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1010".
  |   | 2020-11-18 13:54:06 | yarn node v1.22.5
  |   | 2020-11-18 13:54:06 | warning Skipping preferred cache folder "/app/.cache/yarn" because it is not writable.
  |   | 2020-11-18 13:54:06 | warning Selected the next writable cache folder in the list, will be "/tmp/.yarn-cache-1010".
  |   | 2020-11-18 13:54:10 | {"level":30,"time":1605725650303,"pid":46,"hostname":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","userVisible":true,"name":"gadget-app-sandbox","msg":"Server listening at http://0.0.0.0:8888"}
  |   | 2020-11-18 14:02:59 | {"level":"info","ts":"2020-11-18T19:02:59.052Z","logger":"fetcher","caller":"fetcher/fetcher.go:321","msg":"successfully placed","location":"/userfunc/deployarchive"}
  |   | 2020-11-18 14:02:59 | {"level":"info","ts":"2020-11-18T19:02:59.061Z","logger":"fetcher","caller":"fetcher/fetcher.go:621","msg":"calling environment v2 specialization endpoint"}
  |   | 2020-11-18 14:02:59 | {"level":30,"time":1605726179068,"pid":46,"hostname":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","userVisible":true,"name":"gadget-app-sandbox","reqId":1,"req":{"method":"POST","url":"/v2/specialize","hostname":"127.0.0.1:8888","remoteAddress":"127.0.0.1","remotePort":34178},"msg":"incoming request"}
  |   | 2020-11-18 14:02:59 | {"level":"info","ts":"2020-11-18T19:02:59.081Z","logger":"fetcher","caller":"fetcher/fetcher.go:584","msg":"specialize request done","elapsed_time":0.318706318}
  |   | 2020-11-18 14:02:59 | {"level":30,"time":1605726179082,"pid":46,"hostname":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","userVisible":true,"name":"gadget-app-sandbox","reqId":1,"res":{"statusCode":200},"responseTime":13.698388010263443,"msg":"request completed"}
  |   | 2020-11-18 14:02:59 | {"level":30,"time":1605726179112,"pid":46,"hostname":"poolmgr-js-sandbox-gadget-app-sandbox-production-76115721-gq47b","userVisible":true,"name":"gadget-app-sandbox","reqId":2,"req":{"method":"POST","url":"/","hostname":"10.36.4.43:8888","remoteAddress":"10.36.4.140","remotePort":44426},"msg":"incoming request"}
```

You can see in my functions logging code there's an `incoming request` message for `reqId=2`, which would be the request after the specialize request, and it just never finishes because the pod is terminated. 

**To Reproduce**

I have been struggling to reproduce this locally, but I believe you need to trigger a poolmgr function execution right around the same time that you change the Environment such that the pool needs to be recreated.

**Expected result**

The function should execute on either generation of the environment. If on the old one, it should be gracefully shut down like a normal environment change would cause, or if on the new generation it should be reaped when idle. 

**Actual result**

Function pod is killed mid-request-processing.

**Screenshots/Dump file**

[fission-dump_1605728610.zip](https://github.com/fission/fission/files/5562360/fission-dump_1605728610.zip)

**Additional context**

Happy to do more experiments or share more logs if that would help, this is a doozy!

**Comment by airhorns** [comment]
I think I actually incorrectly correlated this bug with changes to the environment CRD. I stopped changing anything about the environment for all of today and still saw lots of 504s. Any pointers to what might be causing the pod to get reaped right after being created?

**Comment by vishal-biyani** [comment]
Hi @airhorns So the `"idletimeout":120` parameter affects how soon the pods are reaped after they are specialized. Can you try increasing that value in the function spec please?

**Comment by airhorns** [comment]
I think I totally screwed this one up and it's my fault! I misread the logs -- the reap is happening the appropriate amount of time after the pod is idle, just in combination with a user-land timeout. Apologies for the noise!
