### ISSUE TITLE
404 getting fission-openshift.yaml

### ISSUE THREAD

**Issue by methadata** [fission/fission#187]
Hi!

When deploying Fission following the steps in the README, there's a 404 when trying to execute:
```
oc create -f http://fission.io/fission-openshift.yaml
```

Could you upload that file from the repository to the fission.io site? This way, the procedure is consistent with other plattforms (i.e. k8s), and there's no need to change the README file.

Thanks!

**Comment by soamvasani** [comment]
Whoops, fixed now.  Thanks!
