### ISSUE TITLE
Define API with decorators for python

### ISSUE THREAD

**Issue by jpedrick** [fission/fission#1870]
**Is your feature request related to a problem? Please describe.**

I would like to be able to deploy an entire REST API using a single or multiple "fission *api* create" from a single package or python file.

**Describe the solution you'd like**

For example: Simply use flask annotation "@app.route()" to define the routes and other annotations for my API in python. 

Instead of manually deciding the url and method when invoking "fission route create --url /path --method GET" have fission read the function decorators to build the appropriate function routers from the python file. Then a full REST API could be deployed from a single python package.

**Describe alternatives you've considered**

I have developed my own makefile based deployment, but it still requires having separate python files for each function.

**Additional context**

Ideally it would have full flask decorator support so that a multi-route file could be generated:

```
@app.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        return do_the_login()
    else:
        return show_the_login_form()

@app.route('/user/<username>')
def profile(username):
    return '{}\'s profile'.format(escape(username))

@app.route('/user/<username>')
def show_user_profile(username):
    # show the user profile for that user
    return 'User %s' % escape(username)

@app.route('/post/<int:post_id>')
def show_post(post_id):
    # show the post with the given id, the id is an integer
    return 'Post %d' % post_id

@app.route('/path/<path:subpath>')
def show_subpath(subpath):
    # show the subpath after /path/
    return 'Subpath %s' % escape(subpath)

```

**Comment by vishal-biyani** [comment]
Hi @jpedrick This is similar to https://github.com/fission/fission/issues/638. One of the challenges in doing so at the moment is a standard framework that allows route scanning and listing. And of course, this has to be possible across multiple languages.

**Comment by vishal-biyani** [comment]
Hi, @jpedrick I will close this in favor of #638 - please feel free to add any comments/requests on that one.
