### ISSUE TITLE
Exit code 0 for fission spec apply even if some specs failed

### ISSUE THREAD

**Issue by danyc** [fission/fission#1881]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-eks-31566f", GitCommit:"31566f851673e809d4d667b7235ed87587d37722", GitTreeState:"clean", BuildDate:"2020-10-20T23:25:14Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Amazon EKS

**Describe the bug**

Exit code 0 for fission spec apply even if some specs failed

**To Reproduce**

I'm using a .sh script in a pipeline step to deploy the fission specs:
<pre>
#!/bin/bash

environment=$1

echo "Deploying spec-files to $environment"

# remove any previous functions code
rm -r -f "spec-files/$environment/functions"

# copy functions code to spec-files/env/functions
rsync -a --exclude="cookiecutter-fission-function-poetry" "functions" "spec-files/$environment"

fission spec apply --wait --specdir "spec-files/$environment/specs"
if [ $? -eq 0 ]
then
  echo "Success."
  exit 0
else
  echo "Failure" >&2
  exit 1
fi
</pre>
I have a package that fails on build:
<pre>
Deploying spec-files to qa-01
 DeployUID: xxxx
 Resources:
  * 2 Functions
  * 1 Environments
  * 2 Packages 
  * 2 Http Triggers 
  * 2 MessageQueue Triggers
  * 0 Time Triggers
  * 0 Kube Watchers
  * 2 ArchiveUploadSpec
 Validation Successful
 2 packages updated: data-retrieval-pkg, hello-dc-pkg
 2 functions updated: data-retrieval, hello-dc
 ------
 Name:        hello-dc-pkg
 Environment: python-dc
 Status:      succeeded
 Build Logs:
...
------
 Name:        data-retrieval-pkg
 Environment: python-dc
 Status:      failed
 Build Logs:
 Error building deployment package: Internal error - {"artifactFilename":"data-retrieval-pkg-ktem3n-gpauce","buildLogs":"error building source package: error starting cmd: fork/exec ./build.sh: no such file or directory
 "}
 ------
 Success.
</pre>

**Expected result**

Since there was a failure in spec apply, I was expecting the exit code of fission spec apply to be different than 0.

**Actual result**
As the log above shows, exit code is 0 ("Success" string is logged).
Therefore my pipeline step is reported as successful, even if the deploy failed.
Is there another way to make the deployment script report the failure?

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by vishal-biyani** [comment]
Hey @danyc Thanks for raising this issue and this is valid issue. We will prioritize for one of the upcoming releases.
