### ISSUE TITLE
combined yaml fails with kind v0.9

### ISSUE THREAD

**Issue by ggilley** [fission/fission#1884]
I have a script I use to set up a local fission cluster for testing. It started failing recently.

```
#!/bin/bash
export FISSION_NAMESPACE=fission
kind create cluster
kubectl cluster-info --context kind-kind
kubectl --context kind-kind get pods -A
kubectl --context kind-kind create namespace $FISSION_NAMESPACE
kubectl --context kind-kind apply -f \
    https://github.com/fission/fission/releases/download/1.11.2/fission-all-1.11.2.yaml

```

It appears to be a problem with the namespace as creating via the helm chart works.

**Comment by RealHarshThakur** [comment]
@ggilley We need to create namespace `fission` and deploy yaml in that namespace. I'll update the docs with necessary steps. Thanks for reporting

**Comment by sanketsudake** [comment]
Closing issue as seems outdated and Fission install works with yaml in recent releases.
