### ISSUE TITLE
Requests per pod & pod reuse

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1888]
As a Function user, I want to be able to control how the pods are utilized for executing requests. Some scenarios listed below:

From https://github.com/fission/fission/issues/1628#issuecomment-730386158:

> to be able to control the number of requests sent to one pod simultaneously. For them, they want to set it to 1 to guarantee all the pod's resources to processing that one request

> let many requests go to the same backend instance 

> user-controllable requests-per-pod concurrency limit

Also, some users want that a request should be executed in a container and that container never be reused: https://github.com/fission/fission/issues/906

> For increased isolation between invocations it would be nice to have each one done in a separate container. An example use-case is the conversion of untrusted documents to PDF.

There is another issue for reuse of pods across functions: https://github.com/fission/fission/issues/54 

All these scenarios are variations of a user-controllable feature that allow a user to control reuse and requests being sent to a pod. This issue will track all these requests and draft an initial design for pursuing implementation.

**Comment by therahulbhati** [comment]
Only for the pool manager strategy
OnceOnly: Specialize, serve exactly one function, and then garbage collect
           IdleTimeout - Zero?
RequestsPerPod
N (RPP): Based on the N number provided by the user that many requests can be served by a pod at a given time
    1 Function - pool size 3, concurrency 5, N=5, TReqs = 25
        First 5 requests to same specialized pod
        And at the peak you will be having 5 pods, each serving 5 requests so 25 at peak
    1 Function - pool size 3, concurrency 5, N=1, TReqs = 5
        First 5 requests to same specialized pod

**Comment by therahulbhati** [comment]
Applies only to pool manager strategy:
Scenarios:
1. OnceOnly: Specialize a pod, serve exactly one request, and then garbage collect. (Never reuse)
2. Have a parameter  `requestPerPod` or `rpp` and each pod would serve that many requests at any given time.
Example
    1 Function - pool size 3, concurrency 5, N=5, TReqs = 25
        First 5 requests to same specialised pod
        And at peak you will be having 5 pods, each serving 5 requests so at peak 25
    1 Function - pool size 3, concurrency 5, N=1, TReqs = 5
        First 5 requests to same specialised pod

**Comment by airhorns** [comment]
Another approach would be to not limit by request concurrency but instead by observed CPU saturation. It's hard to tune request concurrency because the amount of work to do a request can change over time -- more cache hits at night while things aren't changing that often for example. If that were the case, then you'd be under-using the pods at night wasting resources, and over-using them in the middle of the day processing requests more slowly than you needed to.

knative has an upper limit on simultaneous requests to one pod, but it often scales before that's hit because it is watching and sees the pod bumping up against it's CPU limit. I feel like fission already has the fetcher sidecar container too!

**Comment by airhorns** [comment]
Oh -- another bonus of using CPU based scaling like that is that the router doesn't need to coordinate with anything else to tap and untap services, it can just load balance using least connections or something like that, and then as the autoscaler notices changes load new backends get added and removed. This adds a bit of resiliency where the router doesn't strictly need a connection to a central coordinator, and also a bit more throughput as time isn't spent talking to that central coordinator.

**Comment by therahulbhati** [comment]
**Design**
Max request that can be served concurrently will be equal to concurrency x rpp 
**Scenarios**: 

1. The very first request comes a new pod is specialized to serve the request.
2. More request comes, rpp for a single pod is reached, new pod is specialized to serve the request.
3. If all pods are serving requests wait for 5 seconds(configurable) and check again, then return 429 or serve the request. 
4. If a pod is serving 'x' requests(x < rpp) and CPU consumed is more than 85 percent(configurable) then specialize another pod to serve the request.
5. If all pods are serving in total 'y' request (y < maxConcurrentRequests) and all of them have CPU utilization of more than 85 percent, wait for 5 seconds and check again, then depending on check return 429 or serve the request.

**Comment by vishal-biyani** [comment]
Closing this issue as most of needs are satisfied with #1946 and #1978
