### ISSUE TITLE
Deploying fission on AWS CloudFormation Kuberenetes results in unreachable EXTERNAL_IP

### ISSUE THREAD

**Issue by davidthewatson** [fission/fission#189]
I deployed Fission on my AWS CloudFormation Kubernetes cluster using the instructions here:

https://github.com/fission/fission#get-and-run-fission-gke-or-other-cloud

The create step worked fine. However, when I got to exporting the FISSION_URL, I discovered that the EXTERNAL_IP never got set and as a result, the command that sets FISSION_URL returns nothing.

I think this is due to the following issue on AWS:

https://github.com/kubernetes/kubernetes/issues/23562

When I do:

    $ kubectl --namespace fission get svc controller

I see a UUID in the EXTERNAL_IP column for the row that is retrieved to build FISSION_URL, as opposed to an actual IP address.

Does the project need a separate set of AWS YAML via pull request for AWS or can this be made to work for both GKE and AWS?

**Comment by soamvasani** [comment]
Thanks for filing this. Would you mind posting the output of `kubectl get svc -o yaml`?

**Comment by soamvasani** [comment]
(Or email it to me soamvasani@platform9.com if you don't want to post it publicly)

**Comment by davidthewatson** [comment]
@soamvasani I sent email. Thanks!

**Comment by soamvasani** [comment]
The bug is that instructions try to look for the ingress IP, but there is only an ingress hostname on AWS.  The instructions need to be updated to use the ingress hostname when it's available.

**Comment by life1347** [comment]
Close due to aged. Feel free to reopen it.
