### ISSUE TITLE
Alertmanager failed to start on pod with IPv6 address

### ISSUE THREAD

**Issue by NeverBehave** [fission/fission#1895]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-19T08:38:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

Manual

**Describe the bug**

When alertmanager pod was assigned with IPv6 Address, it complains the address has too many colons.

**To Reproduce**

Set up Calico with IPv6 Pool for pods and install fission following the guide

**Expected result**

The alertmanager should start with no issue 

**Actual result**

```
k logs -n fission fission-prometheus-alertmanager-c5ff7cc96-ghs8z prometheus-alertmanager
level=info ts=2020-12-24T02:27:44.538Z caller=main.go:197 msg="Starting Alertmanager" version="(version=0.18.0, branch=HEAD, revision=1ace0f76b7101cccc149d7298022df36039858ca)"
level=info ts=2020-12-24T02:27:44.538Z caller=main.go:198 build_context="(go=go1.12.6, user=root@868685ed3ed0, date=20190708-14:31:49)"
level=error ts=2020-12-24T02:27:44.539Z caller=main.go:222 msg="unable to initialize gossip mesh" err="invalid advertise address: address 2a0e:xxxx:xxxx:xxxx:7e48:cff1:8353:e1a8:6783: too many colons in address"
```

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

IPv6 Only Cluster

**Comment by vishal-biyani** [comment]
Hi @NeverBehave I think this issue is better filed in Prometheus repo if it just about alert manager. There are a bunch of issues related to IPV6 in Prometheus project. If this is something of a problem with Fission pods, please reopen. I will close this for now.

**Comment by NeverBehave** [comment]
gotcha, I think it's also a good idea to let people know the metrics, due to this reason, is not working properly. The core seems to be fine.

**Comment by NeverBehave** [comment]
I don't know if this worth another issue but I would like to keep a record here.
Due to the reason https://github.com/npm/cli/issues/348 , the builder (fission/nideenv) in the example won't run under IPv6 only network. Switch to a debian based image will solve this problem.
