### ISSUE TITLE
Kata Containers/gVisor example

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#1898]
A lot of use cases need Fission and the functions running in a more isolated runtime such as gVisor/Kata containers. A working example with Fission functions running in isolated containers would be useful for Fission users.

**Comment by RealHarshThakur** [comment]
Related : https://github.com/fission/blog.fission.io/pull/61

**Comment by vishal-biyani** [comment]
Closed by fission/blog.fission.io#61
