### ISSUE TITLE
Performance issues on concurrent function requests

### ISSUE THREAD

**Issue by thschue** [fission/fission#1909]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4901", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-11-06T18:22:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
* Google Kubernetes Engine
* Amazon EKS
* K3s

**Describe the bug**

Concurrent requests to a deployed function on Fission >=1.10 are very slow (take more than 2 seconds) and fission crashes in high-load situations. This problem does not exist in Fission 1.9. 

Also tried to run the current master and the fix provided in https://github.com/fission/fission/pull/1890 without any success.

**To Reproduce**
* Install Kubernetes Cluster
* Install Fission (Helm-Chart)
* Install Fission CLI
* Install Fission Demo-Function (hello)
* Create a Route for Demo function
* Run load tests (using hey) (concurrency 5)

**Expected result**

* Response Times ~500msec

**Actual result**
* Response Times > 2sec

**Screenshots/Dump file**

<pre>
$ fission support dump
Has already been submitted
</pre>

**Comment by baichinger** [comment]
We tracked down the performance issue to communication between Executor and Kubernetes API. Executor makes two requests per user request. IMO, the result of those requests can be cache to a certain extent.

The response times can be greatly improved by introducing caches to the executor and pool manager. See https://github.com/baichinger/fission/commit/12896eb34fc9274045d4d7408a72577bd7b24c71 for a very rough workaround.

**Comment by vishal-biyani** [comment]
Hi @baichinger We would love to make this change upstream - do you mind raising a PR when you get a chance!

**Comment by baichinger** [comment]
Hi @vishal-biyani! My hacky improvement lacks quite a bit on quality. There are no tests, it uses a randomly picked cache and the parameters to it are just wild guesses. Most importantly, it does not handle new/changed/deleted functions and therefore would lead to weird bugs.

My comment was intended as food for thought. The problems introduced by excessive usage of the Kubernetes API (custom resources) needs to be properly addressed. I can think of two approaches here: Sophisticated usage of caching or switch from get/list operations to watches. Both techniques have their downsides. It could even be a combined solution.
