### ISSUE TITLE
Helm Install - --set persistence.storageClass Not Applying to Prometheus PVCs

### ISSUE THREAD

**Issue by Daniel-Vaz** [fission/fission#1910]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2
server:
  fission/core:
    BuildDate: "2020-10-20T14:43:45Z"
    GitCommit: 52508e19343ef93da4ce8960908c5569f44da225
    Version: 1.11.2

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:00:47Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform **
KubeADM Single Node Cluster deployed on BareMetal, using MetalLB and Istio.

**Describe the bug**
When deploying Fission using Helm, the flag "**persistence.storageClass**" gets ignored for the Prometheus PVC creation. 

**To Reproduce**
When deploying Fission using Helm ([Documentation](https://docs.fission.io/docs/usage/enabling-istio-on-fission/)) I pass the following flags:
<pre>
helm install --namespace $FISSION_NAMESPACE --set router.useEncodedPath=true --set enableIstio=true --set persistence.storageClass=csi-rbd-sc --name-template fission https://github.com/fission/fission/releases/download/1.11.2/fission-all-1.11.2.tgz
</pre>

I specify the existing Storage Class with the correct name:
<pre>
NAME            PROVISIONER           RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-rbd-sc      rbd.csi.ceph.com      Delete          Immediate           false                  16h
</pre>

But when installing Fission only the PVC for "fission-storage-pvc" gets created. The Other 2 for Prometheus dont:
<pre>
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
fission-prometheus-alertmanager   Pending                                                                                       15m
fission-prometheus-server         Pending                                                                                       15m
fission-storage-pvc               Bound     pvc-6a829118-e65b-46cb-b534-c8f3ce17d351   8Gi        RWO            csi-rbd-sc     15m
</pre>

This makes so that the Prometheus Services gets stuck in Pending state:
<pre>
NAME                                                     READY   STATUS             RESTARTS   AGE
buildermgr-57886dcfb8-hssxl                              2/2     Running            0          18m
controller-7bdcb5d485-7n95s                              2/2     Running            1          18m
executor-757d8dc7f7-w4fdz                                2/2     Running            0          18m
fission-prometheus-alertmanager-c5ff7cc96-lqwdq          0/3     Pending            0          18m
fission-prometheus-kube-state-metrics-68466fff67-txfxz   2/2     Running            1          18m
fission-prometheus-node-exporter-64tv4                   1/1     Running            0          18m
fission-prometheus-pushgateway-69c586776c-h7vhv          2/2     Running            0          18m
fission-prometheus-server-5d465bcb-5w55w                 0/3     Pending            0          18m
influxdb-59649c8c6-lmpkv                                 2/2     Running            0          18m
kubewatcher-77788c86b5-mng8n                             2/2     Running            0          18m
logger-pkgc4                                             3/3     Running            0          18m
mqtrigger-nats-streaming-7c6649875b-k7xjk                1/2     CrashLoopBackOff   8          18m
nats-streaming-6c6d7c6fbf-pd5nv                          2/2     Running            0          18m
router-994599847-xn95q                                   2/2     Running            0          18m
storagesvc-7c675f69c-v8kwf                               2/2     Running            0          18m
timer-6f568f9d85-hwrf9                                   2/2     Running            0          18m
</pre>

**Expected result**
Passing the flag "**persistence.storageClass**" makes so that all prometheus PVCs use the specified Storage Class. 

**Actual result**
PVC's get stuck in Pending State because they are not using the Storage Class:
<pre>
NAME                              STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
fission-prometheus-alertmanager   Pending                                                                                       15m
fission-prometheus-server         Pending                                                                                       15m
fission-storage-pvc               Bound     pvc-6a829118-e65b-46cb-b534-c8f3ce17d351   8Gi        RWO            csi-rbd-sc     15m
</pre>

<pre>
$ fission support dump
[fission-dump_1610106551.zip](https://github.com/fission/fission/files/5786992/fission-dump_1610106551.zip)
</pre>

**Comment by Daniel-Vaz** [comment]
Bellow can be seen the Error the PVC's report:
<pre>
Events:
  Type    Reason         Age                   From                         Message
  ----    ------         ----                  ----                         -------
  Normal  FailedBinding  2m7s (x102 over 27m)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
</pre>

**Comment by tusharRepo** [comment]
As prometheus is a different helm chart which is being called from fission helm chart you need to pass prometheus helm chart values separately.

Prometheus helm chart link: https://github.com/helm/charts/tree/master/stable/prometheus

additional parameters:
--set prometheus.alertmanager.persistentVolume.storageClass=csi-rbd-sc --set prometheus.server.persistentVolume.storageClass=csi-rbd-sc

final command:
helm install --namespace $FISSION_NAMESPACE --set router.useEncodedPath=true --set enableIstio=true --set persistence.storageClass=csi-rbd-sc --set prometheus.alertmanager.persistentVolume.storageClass=csi-rbd-sc --set prometheus.server.persistentVolume.storageClass=csi-rbd-sc --name-template fission https://github.com/fission/fission/releases/download/1.11.2/fission-all-1.11.2.tgz

**Comment by Daniel-Vaz** [comment]
Thanks for the explanation @tusharRepo !
All is working.
