### ISSUE TITLE
Should not retry 4xx errors

### ISSUE THREAD

**Issue by ggilley** [fission/fission#1915]
When using Message Queue Triggers, fission retries a function call when an error occurs. This is a great feature when it fails because a server is unavailable, etc. However, when certain failures occur, you do not want to retry, but fail the function. In particular when a function returns an http 4xx error. These errors indicate a client side error and should not be retried. For example, a 400 bad request error. [https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400](url)

I believe that fission should not retry when the function returns a 4xx error. I've had to put hacks in my functions to ignore bad requests otherwise the function will retry forever (it's because of bugs in my client code, but it could turn into a denial-of-service attack with an increasing number of retrying function failures that will never succeed)

**Comment by thevibhu** [comment]
Hi, can i take up this issue?
