### ISSUE TITLE
Python env: stdout is buffered

### ISSUE THREAD

**Issue by wzhliang** [fission/fission#1927]
**Fission/Kubernetes version**

<pre>
$ fission --version
1.11.0

$ kubectl version
1.12.1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

Logs in Python code cannot be easily examined because fission/python-env:latest use the default setup where IO is buffered.
This can be fixed either with `python -u` or the `PYTHONUNBUFFERED` variable
**To Reproduce**

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by vishal-biyani** [comment]
hi @wgliang Thanks for raising the issue. Would you like to raise a PR for this in fission/environments repo?

**Comment by wzhliang** [comment]
Sure. Any pointers? @vishal-biyani

**Comment by wzhliang** [comment]
https://github.com/fission/environments/pull/69

**Comment by vishal-biyani** [comment]
Thanks a lot again for your contribution and PR to Fission repo, @wzhliang 🎉
