### ISSUE TITLE
Creating service accounts (security concern)

### ISSUE THREAD

**Issue by RealHarshThakur** [fission/fission#1928]
Once user has installed fission, the service accounts would exist by default. The only reason we require this permission is because the controller will create if they don't already exist, right? If so, two scenarios where this helps 
 * Getting into a state where service accounts are deleted
 * Incomplete installation
  
 Can't we just give an error to the user through CLI when such a thing happens?

https://github.com/fission/fission/blob/master/pkg/executor/executortype/poolmgr/gp.go#L128

**Comment by sanketsudake** [comment]
This is fixed now, we don't need service account permission explicitly. If the user has a service account check enabled which is newly added, then only we need a service account to create permission.

https://github.com/fission/fission/blob/8df4fd0e7cdc9973744d5742e7cb83d50e9c053a/charts/fission-all/templates/_fission-kubernetes-roles.tpl#L120

We have also removed role binding and role permissions.
