### ISSUE TITLE
Execution strategies for functions

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#193]
Fission today uses a pool of running environment pods and loads the function into a running pod on-demand.  This is great for cold-start times but it isn't the only strategy.  An alternative is to launch a a new pod on each cold start. This is slower, but acceptable when cold-start times aren't a priority (most async use cases).

There are trade-offs of each approach and neither one fits all use cases.  The pool buys us very fast cold start (especially with preloading common libraries, cold start can be < 10ms), which is important for any use case where the latency is "visible" to a user.  Mostly this the REST API use case.  But, using a pool doesn't allow us to mount volumes for a function, or set CPU/memory requests and limits.

We should implement multiple strategies for executing functions, and choose an appropriate one automatically based on what the function needs.  For example, if a function needs a volume mounted, it should use the new-pod strategy.

The downside of this approach is that a user can't have both volume access and fast cold-starts.  In the future we can investigate working on k8s changes to allow dynamic volume mounting in running pods (though I have no idea how the k8s maintainers feel about that).  But short of that, there's no way to get both fast cold-start and volumes in the same function.

Hybrid approaches are also possible: the first instance of a function can be drawn from the pool (to make cold start fast), and subsequent instances can be be created in new pods (to make autoscaling easier).  The beginnings of this implementation already exist on the `autoscaling` branch.

**Comment by erwinvaneyk** [comment]
Interesting idea about the strategy-based approach @soamvasani. There is definitely something to gain by deploying the functions based on the priority/requirements of a function. 

Regarding the volume mounting, what are the use cases? If it is for caching/temporary storage, it might be an idea to look at how AWS Lambda does it. There it provides by default a `tmp` storage (~512MB) that persists (to some extend) across invocations.

**Comment by soamvasani** [comment]
The other use case for this is if users want to specify functions as docker images. Then we'd need to start the pod on request.

**Comment by soamvasani** [comment]
So, we keep coming with use cases for doing this.

This approach will allow more fine-grained tuning of resource utilization and auto-scaling. It would allow functions to have Kubernetes [`ResourceRequirements`](https://godoc.org/k8s.io/kubernetes/pkg/api#ResourceRequirements). Functions will also be able to specify some characteristics of their Deployment, like the initial scale, and some attributes for the autoscaler, such as min and max scale. (We'll have to add all these properties to the FunctionSpec.)

This approach will also allow us to run specific functions with service accounts, which is very useful when writing controller functions -- functions triggered by Kubernetes watches that turn around and do something else in the API. (Today's approaches give us environment-level control for this kind of stuff, but not function-level control.)

**Comment by soamvasani** [comment]
@vishal-biyani I think we should probably break this into 2 or more steps--

A good first step is to add a very thin abstraction on top of poolmgr, with the same API as poolmgr. This step would not add any new functionality.

And then in the next step we could add another backend for this abstraction, based on creating new deployments. A third step could start adding the features described above, changing the API (FunctionSpec etc.) in the process.

**Comment by soamvasani** [comment]
closing, `newdeploy` has been available from 0.5.0 onwards.
