### ISSUE TITLE
NATS Streaming triggers

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#194]
Launch functions from events via NATS streaming server.

**Comment by soamvasani** [comment]
cc @life1347

**Comment by life1347** [comment]
![httptrigger](https://cloud.githubusercontent.com/assets/202578/26530311/54ce6284-4405-11e7-8012-976521eb41b4.png)

Above is the blueprint of message queue trigger proposal.

Currently, I am writing a general `MessageQueueTrigger` for multiple message queues (#194 #195 #196 #197 #198) to extend. After that, we only need to implement the different part of multiple message queues separately without too much redundant code. And I am wandering does trigger needs to send back the function response to origin event publisher? or just ignore it?

**Comment by erwinvaneyk** [comment]
Nice informative diagram @life1347 ! What is not entirely clear from it though is the location of the generic `MessageQueueTrigger` in this context. Is it correct that the `Nats, CloudPubSub Trigger ...etc` are the implementations of this interface that you describe?

Given the generic nature of message queue usage, it might be best to emit the response of the function as separate event. This would allow users to determine for themselves whether they care about the response. (if the response is irrelevant to them, they can just ignore it)

**Comment by life1347** [comment]
@erwinvaneyk Yes, correct. But since it's still under the implementation, the design may be slightly changed in the end. I'll update a new diagram once the design is confirmed.

**Comment by soamvasani** [comment]
@life1347 @erwinvaneyk I think it makes sense to emit the response back into the queue.  The event trigger for the function could include an optional "response topic" that the function's response would be sent into.

**Comment by javierbq** [comment]
In the case of AMQP it would be nice if the subscriber gets the response so it can ack or nack the message depending on the result of the function.

**Comment by soamvasani** [comment]
MessageQueueTrigger supports NATS streaming, #218.
