### ISSUE TITLE
Helm chart completeness

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#199]
We have a helm chart today, but it needs some work.

- [ ] Split into smaller yamls to follow helm best practices (one for each deployment, svc, etc.)
- [x] Use persistent volumes for function storage 
- [x] Integrate influxdb into the chart, use persistent volume for log storage
- [x] Add fission-rbac rules into the chart
- [x] Add an installation test to travis
- [x] Replace yaml-based installation instructions with helm instructions

**Comment by rapitable** [comment]
I think you mentioned moving to helm as part of today's release. Once done would be good to add fission here too: https://kubeapps.com/

**Comment by soamvasani** [comment]
We've had working helm charts for some time now.  (Let's separately track the idea of getting it into the default repo.)
