### ISSUE TITLE
Error Listing Functions. Too Many Open Files

### ISSUE THREAD

**Issue by atsai1220** [fission/fission#1998]
**Fission/Kubernetes version**

My fission cli is 1.12.0
<pre>
❯ fission version --verbosity=2
Setting up port forward to application=fission-api in namespace
Waiting for local port 57529
Starting port forward from local port 57529
Waiting for port forward 57529 to start...
Using kubeconfig from "/Users/atsai/.kube/config"
Connected to Kubernetes API
Connecting to port 8888 on pod fission/fission
Starting port forwarder
Forwarding from 127.0.0.1:57529 -> 8888
Forwarding from [::1]:57529 -> 8888
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
Handling connection for 57529
....
....
❯ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T21:16:14Z", GoVersion:"go1.16.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.7", GitCommit:"1dd5338295409edcfff11505e7bb246f0d325d15", GitTreeState:"clean", BuildDate:"2021-01-13T13:15:20Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Ubuntu nodes

**Describe the bug**

Unable to use `fission` CLI due to too many new connections.
```
❯ fission fn list --fns fission-function
E0412 12:13:06.953700   29501 portforward.go:306] Error accepting connection on port 55610: accept tcp4 127.0.0.1:55610: accept: too many open files
E0412 12:13:06.953700   29501 portforward.go:306] Error accepting connection on port 55610: accept tcp4 127.0.0.1:55610: accept: too many open files
log: exiting because of error: log: cannot create log: open /var/folders/rc/3zhj71t15hs8mtmn6h_fzc0r0000gp/T/fission.LP-ATSAI-OSX.atsai.log.WARNING.20210412-121306.29501: too many open files
```

Howveer if I use my browser then I am able to query the Fission API directly while the fission query is running on the running port.

This works in a browser while the Fission CLI is trying.
```
http://localhost:55610/v2/functions?namespace=fission-function
```
**To Reproduce**

**Expected result**

**Actual result**

**Screenshots/Dump file**

This command hangs since I am unable to use the CLI.
<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by vishal-biyani** [comment]
Hi @atsai1220 This does not look like an issue in Fission but either your machine or your cluster is running out of file descriptions. If it is Kubernetes cluster it could be related to this one: https://github.com/kubernetes/kubernetes/issues/64315 

I suggest please check on a different setup if you can and reopen if you still run into same issue!

**Comment by atsai1220** [comment]
Hello! Providing some more info and workaround.

Workaround:
``` shell
kubectl port-forward svc/controller -n fission 8000:80
export FISSION_URL="http://127.0.0.1:8000"
# then this responds right away without error
fission version --verbosity=2
```

I noticed in `util.go:GetApplicationUrl` would create a port-foward if `FISSION_URL` env var is not set. Not sure what the difference between fission doing the port-forwarding versus port-forwarding manually though but sharing just in case someone else runs into this issue whether it is because of their local network environment or otherwise.
```
func GetApplicationUrl(selector string, kubeContext string) (string, error) {
	var serverUrl string
	// Use FISSION_URL env variable if set; otherwise, port-forward to controller.
	fissionUrl := os.Getenv("FISSION_URL")
	if len(fissionUrl) == 0 {
		fissionNamespace := GetFissionNamespace()
		localPort, err := SetupPortForward(fissionNamespace, selector, kubeContext)
		if err != nil {
			return "", err
		}
		serverUrl = "http://127.0.0.1:" + localPort
	} else {
		serverUrl = fissionUrl
	}
	return serverUrl, nil
}
```

**Comment by atsai1220** [comment]
> Hello! Providing some more info and workaround.
> 
> Workaround for me is to manually port-forward to the controller first and configuring the environment variable `FISSION_URL`.
> 
> ```shell
> kubectl port-forward svc/controller -n fission 8000:80
> export FISSION_URL="http://127.0.0.1:8000"
> # then this responds right away without error
> fission version --verbosity=2
> ```
> 
> I noticed in `util.go:GetApplicationUrl` would create a port-foward if `FISSION_URL` env var is not set. Not sure what the difference between fission doing the port-forwarding versus port-forwarding manually though but sharing just in case someone else runs into this issue whether it is because of their local network environment or otherwise.
> 
> ```go
> func GetApplicationUrl(selector string, kubeContext string) (string, error) {
> 	var serverUrl string
> 	// Use FISSION_URL env variable if set; otherwise, port-forward to controller.
> 	fissionUrl := os.Getenv("FISSION_URL")
> 	if len(fissionUrl) == 0 {
> 		fissionNamespace := GetFissionNamespace()
> 		localPort, err := SetupPortForward(fissionNamespace, selector, kubeContext)
> 		if err != nil {
> 			return "", err
> 		}
> 		serverUrl = "http://127.0.0.1:" + localPort
> 	} else {
> 		serverUrl = fissionUrl
> 	}
> 	return serverUrl, nil
> }
> ```

Unfortunately this does not work anymore

```
❯ export FISSION_URL="http://127.0.0.1:8000"
❯ kubectl port-forward svc/router -n fission 8000:80 &
[1] 31405

❯ fission version
Handling connection for 8000
Warning: Error getting Fission API version: unexpected end of JSON input
client:
  fission/core:
    BuildDate: "2021-08-03T11:34:27Z"
    GitCommit: 9b5eb069d69d47d22ecc0270bf8619857ea3f19f
    Version: 1.14.1
server:
  fission/core: {}
```
