### ISSUE TITLE
Opentracing integration

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#200]
Integrate opentracing into fission.  Expose the function call itself, but also fission-internal stuff like cold-start, routing overhead, etc.

This will allow users to trace fission functions as part of a bigger solution, as well as troubleshoot performance problems with fission itself.

**Comment by yqf3139** [comment]
Open Tracing seems quite easy to use. Will make a quick demo integration. 

Some discussions:
- When we instrumenting the code, we should provide a switch to collect trace or not. How to make the switch by the image version or the function calling params?
- Tracing has some overlap with metrics. I think metrics is more general statistics about the system, it is always collected and all the time-series data are reduced to provide insights. And in tracing, we choose some special case and have a detailed look at the workflow. If we want to summary the trace data, maybe we have to export them to other database to make the analysis.
- We can connect several fission services into one trace. For example, we can trace what fission does in a function call workflow (router get the request, choose or start a user function endpoint, proxy the request to the user function, user function does it's job and then return the response, router finish this request).

**Comment by vishal-biyani** [comment]
Thank you so much again https://github.com/ajbouh for your work on this. This is now part of Fission 🎉
