### ISSUE TITLE
Keda Connector pods: Scheduling, memory requirements etc.

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#2005]
Currently the Keda-Connector pods are scheduled based on deployment created by Fission. That means there is no easy way to schedule them on specific nodes or based on taints or tolerations etc. It should be possible to schedule the keda-connector pods (Which do heavy lifting of processing the messages) based on things such as node-selector or taints/tolerations etc.

Also the user would potentially like to specify memory & CPU etc. for Keda-connector pods. So it seems like a PodSpec like features for MQT would make sense so that the pods that do the work of consuming messages can be scheduled as per user needs, assigned resources etc.

**Comment by RealHarshThakur** [comment]
Closing this as this PR is merged.  https://github.com/fission/fission/pull/2021
