### ISSUE TITLE
Fission version Upgrade issue for RequestPerPod field

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#2008]
When you upgrade from a version such as 1.12.0 to current master version - one applies the CRD and the Fission install. The RequestPerPod field introduced in https://github.com/fission/fission/pull/1946 is visible in CRD. But a CR of a function which was created before the upgrade - one can not see the RPP field. Ideally the Function CR should show the field with default value. This is not a breaking change as the default of RPP is 1 before this feature but something that needs to be fixed in either upgrade process or something in CR upgrades.

**Comment by sanketsudake** [comment]
@RealHarshThakur can you please link recent related PRs to this issue ? Also please let me know if we can close this issue now with recent validations ?

**Comment by RealHarshThakur** [comment]
We had a discussion internally and decided it's okay to not have it in the CR as the field is optional to the user.
