### ISSUE TITLE
newdeploy function name can exceed k8s max name field size

### ISSUE THREAD

**Issue by samoscybercraig** [fission/fission#2009]
<pre>
client:
  fission/core:
    BuildDate: "2021-02-11T13:35:47Z"
    GitCommit: ca1a0d4d67a78dd4eaa7790408549d8fb6fc20ca
    Version: 1.12.0
server:
  fission/core:
    BuildDate: "2021-02-11T13:35:47Z"
    GitCommit: ca1a0d4d67a78dd4eaa7790408549d8fb6fc20ca
    Version: 1.12.0
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

All Kuberenetes platforms

**Describe the bug**

When using the newdeploy executor method, if you have a fairly long function name, the executor doesn't truncate to keep it below 63 so prevents the svc being created in k8s. 

**To Reproduce**

Create a function with a 35 char long function name

**Expected result**

Everything to work, functions to invoke etc

**Actual result**

Error and SVC is not created

**Screenshots/Dump file**

Error seen in logs is 

```
error creating service for function: error creating k8s resources for function test7-generate-data-1-t534cfc0323d8_mynamespace: error creating service newdeploy-test7-generate-data-1-t534cfc0323d8-mynamespace-af8a-deb6d5e37e2e: Service \"newdeploy-test7-generate-data-1-t534cfc0323d8-mynamespace-af8a-deb6d5e37e2e\" is invalid: metadata.name: Invalid value: \"newdeploy-test7-generate-data-1-t534cfc0323d8-mynamespace-af8a-deb6d5e37e2e\": must be no more than 63 characters"
```

`newdeploy` = added by fission 
`test7-generate-data-1-t534cfc0323d8` = our internal function name
`mynamespace` = our namespace
`af8a-deb6d5e37e2e` = UID added by fission

**Additional context**

Fix is to truncate this line to always be less than 63 chars. 

```
func (deploy *NewDeploy) getObjName(fn *fv1.Function) string {
	// use meta uuid of function, this ensure we always get the same name for the same function.
	uid := fn.ObjectMeta.UID[len(fn.ObjectMeta.UID)-17:]
	return strings.ToLower(fmt.Sprintf("newdeploy-%v-%v-%v", fn.ObjectMeta.Name, fn.ObjectMeta.Namespace, uid))
}
```

https://github.com/fission/fission/blob/1cd8f4d4f799d1f4af56e6ee75c7b21f264f9587/pkg/executor/executortype/newdeploy/newdeploymgr.go#L759

**Comment by sanketsudake** [comment]
Thanks, @samoscybercraig for reporting it. The fix is merged in master. It would be available in the upcoming 1.14 release.
