### ISSUE TITLE
Prometheus integration

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#201]
Expose prometheus metrics from the router and poolmgr.  Both of these have lots of useful information: number of function calls, number of cold starts, number of function instances, number of http errors, etc.

**Comment by soamvasani** [comment]
cc @yqf3139

**Comment by yqf3139** [comment]
Hi @soamvasani . 
In this issue we need to add a Prometheus deployment and instrument fission-bundle.
The results can be pulled from Prometheus by several queries. For visualization, we can add a Grafana deployment and provide basic configs to let user to watch the metrics easily, or they have to run the queries by themselves.

I will try to list some metrics which I think is useful:

## From k8s, automatically
Prometheus can collect the container resource usage automatically. For example, `container_memory_usage_bytes`, the rate of `container_memory_usage_bytes` and I/O related metrics, specialized/unspecialized container count labelled by funcname, func uid or environment.

## From router
Function calls total count, latency, response size distribution labelled by cold start or not, func name, func uid, path, status code, http method, the event source.
Currently router is a single instance. The metric collecting may face some challenge when the instance can autoscale.

**Comment by zdlgrj** [comment]
Hi folks, any plan to merge #211? and is there any documentation or best practice for integrating Prometheus with Fission?

**Comment by yqf3139** [comment]
@zdlgrj 
#211 should work although it still needs some discussion.

**Comment by prithviramesh** [comment]
@yqf3139 I am working on something similar, and I come across your PR recently. Can we discuss #211 sometime over the fission slack? I'm thinking of cherry picking over your commits into a new branch and adding my changes on top of it as well

**Comment by soamvasani** [comment]
Closed by #677
