### ISSUE TITLE
Documentation links to hello.js, but returns HTTP404

### ISSUE THREAD

**Issue by scriptsrc** [fission/fission#2010]
This URL:

https://docs.fission.io/docs/installation/

Under the `Run an example` section.

```
...
$ curl -LO https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js
...
```

That URL returns a 404:

```
$ curl -LO https://raw.githubusercontent.com/fission/fission/master/examples/nodejs/hello.js
$ ls
hello.js
$ cat hello.js
404: Not Found
```

**Comment by vishal-biyani** [comment]
Hi, Sorry we moved the examples to a different directory, please try with https://raw.githubusercontent.com/fission/examples/master/nodejs/hello.js

Will restore this file in main repo as it is widely used!
