### ISSUE TITLE
I am working on windows 10 when i try to execute the CMD (kubectl create -f nginx-deployment.yml) error: path “nginx-deployment.yml” does not exist

### ISSUE THREAD

**Issue by kumar9989** [fission/fission#2025]
i have given exact path and exact name ,but still same error
https://i.stack.imgur.com/TJnYL.png
https://i.stack.imgur.com/n822X.png

**Comment by Sam-Sundar-Apty** [comment]
As far as I see from the images you are not in the same directory.

Can you press "shift+right click" on configmap.yaml and copy file path and then give kubectl apply -f <absolute path>


Also this is not a fission error !

**Comment by sanketsudake** [comment]
@kumar9989 As  @Sam-Sundar-Apty  pointed out this doesn't seems to be Fission issue. So closing it. If you still need help and have any specific details feel free to reopen it.
