### ISSUE TITLE
Add a CLI command to launch the UI

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#203]
`fission ui` should open fission-ui in a browser, if it is installed. If the UI isn't installed, it should output directions on how to install the ui.

**Comment by soamvasani** [comment]
@yqf3139 @dgoujard

**Comment by yqf3139** [comment]
To fulfill this issue, there are some problems:
- To determine fission-ui is installed, I saw #190 and will try to read the fission-ui service from k8s api
- To open an url on different platform, I think we can find a package like [this] (https://github.com/skratchdot/open-golang), or we have to wrap it for ourselves

**Comment by life1347** [comment]
Fission UI is deprecated. Close this until we have newer version.
