### ISSUE TITLE
How to employ my own complex python project? I need a demo

### ISSUE THREAD

**Issue by cd4806088** [fission/fission#2031]
**I need to deploy a complex python project of my own by fission.** 

There is a final func provided by the project to realize some special function, but the python file where the **func** locates needs other pkgs wirten by me, rather than some dependencies that can be writen in requirements.txt to solve.

The projects is like:

**project_folder**
- pkg_1
  - __init__.py
  - add.py
- pkg_2
  - __init__.py
  - sonfunc.py
- my_final_func_folder
  - __init__.py
  - build.sh
  - requirement.txt
  - final_func.py    *#from pkg_1 import add , from pkg_2 import sonfunc , import yaml*
 
actually, the situation can be much more complex, such the _pkg_2::sonfunc.py_ may depend other my own pkgs.

I dont't find such demo in [docs](https://docs.fission.io/docs), can you give me some suggestions? Thanks.

**Comment by chenjr0719** [comment]
Hi @cd4806088 , I think you can just simply include the `pkg_1` and `pkg_2` when creating the fission package of `my_final_func_folder`. Would you mind to share how you create your fission package and fission function?

**Comment by cd4806088** [comment]
> Hi @cd4806088 , I think you can just simply include the `pkg_1` and `pkg_2` when creating the fission package of `my_final_func_folder`. Would you mind to share how you create your fission package and fission function?

Thanks for your reply! I will have a try next, and show my steps here

**Comment by cd4806088** [comment]
this is my steps here:

- myfission_python_demo
  - funcs
    - __init__.py # import funcs.add \ add = funcs.add.add
    - add.py # def add(a, b): return a + b
  - main.py
  - requirements.txt

- the content of main .py 

  ```python
  import funcs as fn
  
  def cook(a, b, oper):
      if oper == "+":
          return fn.add(a, b)
      else:
          return a - b;
  
  def main():
      res = cook(3, 8, "+")
      return '%d + %d = %d' % (3, 8, res)
  ```

- the requirements.txt is empty

- the fission steps:

```bash
  - cd .. && zip -r demo_1.zip ./myfission_python_demo (i don't konw whether should use "-jr")
  - fission env create --name python --image fission/python-env:latest --builder fission/builder:latest
  - fission fn create --name faas-add --env python --src demo_1.zip --entrypoint "main.main"
  - fission route create --name faas-add-route  --function faas-add --url /faas_add
 ```
  - THEN IN MY chrome，I access the URL: **http://{cluster nodes ip}:{router nodeport}/faas_add**, but get no res with **HTTP ERROR 500**
  - THE URL:**http://{cluster nodes ip}:{router nodeport}/hello** is useful for hello.js demo, so it's the problem for fission pkg of my python project


so what should i do to configure the project?  should i build a series of fission functions through breaking up all my project?
if so, can I identify that  the use of fission is intrusive?

**Comment by chenjr0719** [comment]
Sorry for the late reply @cd4806088.

I believe the 500 error is caused by the incorrect import from your package. The zip command you used is not correct. I think you can build the package like this and it would be easier:
```shell
fission pkg create --name my_pkg --env python --deploy funcs --deploy main.py --deploy requirements.txt
fission fn create --name faas-add --pkg my_pkg --entrypoint "main.main"
```

**Comment by cd4806088** [comment]
Thanks for your reply! @chenjr0719 
I have test your method, and it works! 
Hope this issue can help more developer.
