### ISSUE TITLE
Enable multiples kubernetes version in testing in Github CI flow

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2042]
**Is your feature request related to a problem? Please describe.**
Currently, in the existing CI flow, we are able to verify only one Kubernetes version at a time, based on [kind config ](https://github.com/fission/fission/blob/master/kind.yaml). We need support for multiple Kubernetes version verification in the same flow.

**Describe the solution you'd like**
We should be able to run CI flow for multiple versions.
Eg. If we want to verify 1.19 & 1.21 in the existing CI flow we should be able to that.

- We need a way to mention a list of  Kubernetes version against which we would like to verify Fission.
- Verification of Kubernetes version and tests should run in parallel.
- List of versions would be hardcoded in CI flow and we can change it as needed, depending on deprecation or new Kubernetes releases.
- Build time should not get impacted as we are verifying multiple versions, since verification should be done in parallel.
- These fixes might require changes in test scripts and the way we access Kubernetes context currently.

**Additional context**
-

**Comment by vishal-biyani** [comment]
@sanketsudake Captured here already: https://github.com/fission/fission/issues/1603

**Comment by hellozee** [comment]
Feel free to copy workflows from [here](https://github.com/tetratelabs/istio)

**Comment by sanketsudake** [comment]
Closing this as we are able to verify multiple Kubernetes versions with CI.
