### ISSUE TITLE
what is the latest Kubernetes version certified for fission

### ISSUE THREAD

**Issue by shubha84** [fission/fission#2056]
Hi,
what is the latest Kubernetes version certified for fission? 
@vishal-biyani

**Comment by vishal-biyani** [comment]
Hi @shubha84 We have tested with K8S 1.20 but have not done much testing beyond 1.21 yet - but will be done soon. Also there will be a new page in the documentation around compatibility etc. as part of this release. Please do check docs if you need that info after release. Happy to answer any other questions here or on Slack

**Comment by shubha84** [comment]
@vishal-biyani ,
Thanx for confirmation !
