### ISSUE TITLE
NATS streaming server has a deprecated notice and they suggest to use JetStream

### ISSUE THREAD

**Issue by vCillusion** [fission/fission#2062]
NATS streaming server has a deprecated notice, and they suggest using JetStream

WARNING: Deprecation Notice :warning:
The NATS Streaming Server is being deprecated. Critical bug fixes and security fixes will be applied until June of 2023. NATS-enabled applications requiring persistence should use JetStream.
https://github.com/nats-io/nats-streaming-server

A configurable way for MQ Trigger to support all the KEDA supported triggers.

**Comment by vishal-biyani** [comment]
Hey @vCillusion Are you using the Keda connector based MQTrigger or MQTrigger built in Fission?

**Comment by shaunc** [comment]
I'm hoping to use MQTrigger built into fission ... :)

**Comment by xgenvn** [comment]
@shaunc the built-in MQTrigger in fission seems deprecated and replaced by Keda-based instead.
Ref: https://fission.io/docs/usage/triggers/message-queue-trigger/

**Comment by sanketsudake** [comment]
We are still tracking https://github.com/kedacore/keda/issues/2391 and we will release support in Fission once available in Keda.

**Comment by sanketsudake** [comment]
We have added nats jetstream connector now for fission. Should be available in 1.17.0-rc2 release and onwards.

https://github.com/fission/fission/pull/2517
