### ISSUE TITLE
A pkg crd upload src and build failed first time, upload deployArchive next time, invoke function failed

### ISSUE THREAD

**Issue by jingb** [fission/fission#2063]
**Fission/Kubernetes version**

<pre>
$ fission --version
$ kubectl version
</pre>
fission 1.12
k8s v1.19.4

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

A pkg crd upload src and build failed first time, upload deployArchive next time, invoke function failed

**To Reproduce**

**Expected result**
invoke function success

**Actual result**
"error creating service for function: Internal error - error fetching deploy package: cannot fetch deployment: package build status was not "succeeded": pkg a201199b-f0fb-459e-91d5-e467711bae42.22b81b51-5aaa-466d-8d1a-f67464168111 has a status of failed"

**And I edit the pkg crd status to succeeded manually, it works** 

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by sanketsudake** [comment]
@jingb could you please share the fission dump?
Also, you can check `fission pkg info <package_name>` if there are any errors in the package build.
You can rebuild of the package with `fission pkg rebuild <package_name>`

**Comment by jingb** [comment]
@sanketsudake yes，the pkg exactly build failed and I could get the build logs and know how to fix.
I mean if I do such steps  
1. upload pkg source code and build failed 
2. I get the build log and fix the problem locally and I upload the deploy archive that build locally not the source code 
3. invoke the functions failed cause the router or executor juede the funtion's pkg last build status is failed  
It's not a bug strictly speaking.

**Comment by soharab-ic** [comment]
Please try latest fission version `v1.20.5` and re-open if issue remains.
