### ISSUE TITLE
Incorrect environment spec version

### ISSUE THREAD

**Issue by gauravgahlot** [fission/fission#2075]
The environment spec version should not be 1.

<pre>
➜ fission spec init
Creating fission spec directory 'specs'

➜ fission env create --name=python --image=fission/python-env --spec
poolsize setting default to 3
Saving Environment 'default/python' to 'specs/env-python.yaml'

➜ cat specs/env-python.yaml
apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: python
  namespace: default
spec:
  builder: {}
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    image: fission/python-env
  version: 1
</pre>

**Comment by soharab-ic** [comment]
Please try out latest release `v1.20.4` and reopen if issue still remains.
