### ISSUE TITLE
Support adding labels and annotations in PodSpec

### ISSUE THREAD

**Issue by munjalpatel** [fission/fission#2080]
**Is your feature request related to a problem? Please describe.**
We use Vault to take care of all our secrets.
Vault allows injection of these secrets in the container if we add proper `annotations`
Currently, I do not find a way to label or annotate Fission functions.

**Describe the solution you'd like**
Extend PodSpec to accept labels and annotations.

cc: @vishal-biyani

**Comment by sanketsudake** [comment]
Support for labels is merged, it would be available in 1.14.  All labels & annotations assigned to Environment would be assigned to pods created via environment.
