### ISSUE TITLE
Unable to deploy CRDs for Fission v1.13.0

### ISSUE THREAD

**Issue by munjalpatel** [fission/fission#2081]
I am trying to deploy `Fission v1.13.0` and running into issues while creating crds.

Issue 1: The following command hangs and doesn't do anything:
```
kubectl create -k "github.com/fission/fission/crds/v1?ref=1.13.0"
```

To resolve, I manually created a manifest by cloning and using `kubectl customize .` 

Then, issue 2: when I try to create cards, using `kubectl apply -f ./crds.yaml`, I get the following error:
```
customresourcedefinition.apiextensions.k8s.io/canaryconfigs.fission.io created
customresourcedefinition.apiextensions.k8s.io/functions.fission.io created
customresourcedefinition.apiextensions.k8s.io/httptriggers.fission.io created
customresourcedefinition.apiextensions.k8s.io/kuberneteswatchtriggers.fission.io created
customresourcedefinition.apiextensions.k8s.io/messagequeuetriggers.fission.io created
customresourcedefinition.apiextensions.k8s.io/packages.fission.io created
customresourcedefinition.apiextensions.k8s.io/timetriggers.fission.io created
The CustomResourceDefinition "environments.fission.io" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
```

cc: @vishal-biyani

**Comment by sanketsudake** [comment]
@munjalpatel can you please try `kubectl create -k` [with verbosity](https://kubernetes.io/docs/reference/kubectl/cheatsheet/#kubectl-output-verbosity-and-debugging
) ? You can set verbosity level to 8 may be.

You can also try,
```
 kubectl create -k "http://github.com/fission/fission/crds/v1?ref=1.13.0"
```

If it doesnt work, please share output with verbosity,
```
 kubectl create  -v 8 -k "http://github.com/fission/fission/crds/v1?ref=1.13.0"
```

For local try also, please use `kubectl create` or `kubectl replace` only, as `kubectl apply` would give error as above, it is expected. 
Kubernetes apply has character limit, so we cant really go beyond it, specially Environment CRD spec, as it is big.

**Comment by sanketsudake** [comment]
@munjalpatel Closing this issue. Please reopen if you face this issue again with the latest 1.13.1 release.

**Comment by munjalpatel** [comment]
@sanketsudake thanks for your input. However, `kubectl create` wouldn't work in our case as we use `Pulumi / Terraform` to deploy our infrastructure and I don't believe most of the Gitops tools would support `kubectl create`.

**Comment by rcmorano** [comment]
Just wanted to drop here my cli workaround for this issue. I'm relying on `kfilt` for it [0].

Given this [1] `kustomization.yaml`, you can cleanly apply it by executing this from the kustomization dir:

``` 
# create 'environments.fission.io' only
kubectl kustomize --enable-helm . | kfilt -n environments.fission.io | kubectl create -f -
# exclude environments.fission.io from the full apply
kubectl kustomize --enable-helm . | kfilt -N environments.fission.io | kubectl apply -f -
```

[0] https://github.com/ryane/kfilt
[1] 
```
bases:
- https://github.com/fission/fission/crds/v1?ref=v1.15.1 

helmCharts:
- name: fission-all
  valuesFile: helm-values.yaml
  namespace: fission
  releaseName: init0
  version: v1.15.1
  repo: https://fission.github.io/fission-charts/
```

**Comment by ingyamilmolinar** [comment]
Using `kubectl apply --server-side=true -f` can help.
https://github.com/kubernetes-sigs/kubebuilder/issues/2556
