### ISSUE TITLE
Support resource deletion as successful when resource is not found

### ISSUE THREAD

**Issue by abbaspw21** [fission/fission#2108]
**Is your feature request related to a problem? Please describe.**
Currently while deleting any Fission CRD (like package, function) using Fission CLI, if the specified resource is not found then command exits with non zero error code.

**Describe the solution you'd like**
We are looking for something similar to what we have in K8 where while deleting a resource if we pass `--ignore-not-found=true ` then in place of throwing non zero error code if resource is not found for deletion K8 skips the deletion of the resource and exits gracefully.

**Comment by sanketsudake** [comment]
@abbaspw21 could you please share how you got this issue? Is it possible to reproduce it?
