### ISSUE TITLE
Support force deployment of resources with different deployment UID

### ISSUE THREAD

**Issue by abbaspw21** [fission/fission#2109]
**Is your feature request related to a problem? Please describe.**
Currently while deploying Fission resources via specs, if any resource is already deployed with some other deployment UID then Fission spec apply fails due to conflict.

**Describe the solution you'd like**
We are looking for a solution where we can forcefully apply specs of a resource even if it is deployed with some other deployment UID on the basis of some flag in Fission CLI like `--force`.

**Describe alternatives you've considered**
Currently we are searching for the resource and are deleting it before applying the specs just to avoid conflicts.

**Comment by sjk7524068** [comment]
> **Describe alternatives you've considered** Currently we are searching for the resource and are deleting it before applying the specs just to avoid conflicts.

Hello there~ It's amzing that fission1.16 support --allowconflict now, but since I was using fission1.12, would you mind tell how to searching for exist resource and delete

best

**Comment by sjk7524068** [comment]
@abbaspw21 
> > **Describe alternatives you've considered** Currently we are searching for the resource and are deleting it before applying the specs just to avoid conflicts.
> 
> Hello there~ It's amzing that fission1.16 support --allowconflict now, but since I was using fission1.12, would you mind tell how to searching for exist resource and delete
> 
> best
