### ISSUE TITLE
Access POST parameters

### ISSUE THREAD

**Issue by georak** [fission/fission#2110]
Could you give me an example on how I can access POST parametes in nodejs or python?

**Comment by vishal-biyani** [comment]
Hi @georak For Python you can find [details here](https://docs.fission.io/docs/usage/languages/python/#query-parameters) and for NodeJS [details here](https://docs.fission.io/docs/usage/languages/nodejs/#query-string) - Hope that helps. Please reopen issue or join slack if you still need help.
