### ISSUE TITLE
Timeout while building package

### ISSUE THREAD

**Issue by chinochao** [fission/fission#2111]
Fission Core: 1.13.1
Kubernetes: 1.19.10
Kubernetes Platform: Rancher/K8s

I have a regular function using source code that works perfectly. However, I have created a package from the https://github.com/fission/examples in the nodejs and it seems those are timing out while building. 

```
$ fission package info --name nodejs
Name:        nodejs
Environment: nodejs
Status:      failed
Build Logs:
Build timeout due to environment builder not ready
```

Here are the logs from the buildermgr container.
```
{"level":"info","ts":"2021-07-09T17:42:40.584Z","logger":"builder_manager.package_watcher","caller":"buildermgr/pkgwatcher.go:91","msg":"starting build for package","package_name":"nodejs","resource_version":"165838687"}
{"level":"error","ts":"2021-07-09T17:59:05.239Z","logger":"builder_manager.package_watcher","caller":"buildermgr/pkgwatcher.go:280","msg":"max retries exceeded in building source package, timeout due to environment builder not ready","package":"nodejs.default"}
```

**Comment by vishal-biyani** [comment]
@chenjr0719 Can you please show us how you created the environment and function for this one?

**Comment by chenjr0719** [comment]
Oops, I think you tag wrong guy here @vishal-biyani . 😅

**Comment by vishal-biyani** [comment]
Oops Sorry @chenjr0719! I meant to tag @chinochao

**Comment by chinochao** [comment]
Actually, I was able to fix the issue. It was related to our network using a proxy and I needed to update the images in the nodejs Environment to use the proxy.

`apiVersion: fission.io/v1
kind: Environment
metadata:
  creationTimestamp: null
  name: nodejs
  namespace: default
spec:
  builder:
    command: build
    image: PROXY_URL/fission/node-builder-12.16:1.11.0
    podspec:
      containers:
      - name: fetcher
        env:
        - name: LOG_LEVEL
          value: info
      - name: builder
        volumeMounts:
        - mountPath: /.npm
          name: npm
      volumes:
        - emptyDir: {}
          name: npm
      securityContext:
        runAsUser: 1001
  imagepullsecret: ""
  keeparchive: false
  poolsize: 3
  resources: {}
  runtime:
    image: PROXY_URL/fission/node-env-12.16:1.11.0
    podspec:
      containers:
      - name: fetcher
        env:
        - name: LOG_LEVEL
          value: info
      securityContext:
        runAsUser: 1001
  version: 2`
