### ISSUE TITLE
Deprecate router url mention in fission fn commands

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2159]
**Is your feature request related to a problem? Please describe.**
Currently, there are two ways to create HTTPTrigger using the fission command.

1. `fission fn create` with below parameters
```text
  --url=''                              URL pattern (See gorilla/mux supported patterns)
  --prefix=''                           Prefix with which functions are exposed. NOTE: Prefix takes
                                        precedence over URL/RelativeURL
  --method=[GET]                        HTTP Methods: GET,POST,PUT,DELETE,HEAD. To mention single
                                        method: --method GET and for multiple methods --method GET --method
                                        POST.
```
2. and `fission route` command.

2nd way is more preferrable and more maintained, whereas 1st is not actively used also it increases the burden on project development and maintaining feature parity across both commands.

We should deprecate eventually remove 1st one and only keep 2nd one.

**Describe the solution you'd like**
As mentioned above deprecate route creation via `fission fn` commands and only keep it in `fission route create` commands.

**Additional context**
Following are benefits
1. Reduce code duplication
2. Reduce burden to keep the same functionality on both commands and less confusion for user

**Comment by nickmancari** [comment]
I can help with this.

**Comment by sanketsudake** [comment]
@nickmancari  Thanks for your interest, feel free to take it up. Do let me know if you need any inputs from my side.
Would be happy to see corresponding PR 😄

**Comment by nickmancari** [comment]
Great! I have a PR in on this.

**Comment by praddy26** [comment]
Is this issue still open?

**Comment by nickmancari** [comment]
#2171 Not anymore. I labeled those flags as deprecated.

**Comment by ChandanChainani** [comment]
@nickmancari please close the issue
