### ISSUE TITLE
Namespace is not consistent in all places inside the CLI --fnNamespace --triggerNamespace 

### ISSUE THREAD

**Issue by Stradivario** [fission/fission#2177]
**Is your feature request related to a problem? Please describe.**
Partially yes. I have found out that the CLI for creating TimeTriggers is not consistent when we define `Namespace` for the executor

**Describe the solution you'd like**
I would like to propose universal parameter to define `namespace` for example `--namespace` 

**Additional context**

For example i want to create a `timetrigger` for function `abv` which will run on every minute and it is inside some specific namespace 

```bash
fission tt create --name test-trigger --function abv --cron "*/1 * * * *" --fnNamespace 612bbb9fb5167c549f11hfa4
```

In the next moment i want to delete this trigger but i got an error that `--fnNamespace` flag is not appropriate for executing this method and it throws `Error: unknown flag: --fnNamespace`

```bash
fission tt delete --name test-trigger --fnNamespace 612bbb9fb5167c549f11hfa4
```

I have then decide to ask `--help` and i found out that the parameter for using namespace is different than `create` it is `--triggerNamespace` 

```
fission tt delete --name test-trigger --triggerNamespace 612bbb9fb5167c549f11hfa4
```

It is quite confusing to have such a different ways of defining namespaces and it makes me make mistakes every time when i try to create or delete function. My proposal is to have unified way of defining namespace with just `--namespace` argument.

And this is not only for `timetriggers` it should be changed all over the place.
Please correct me if i wrongly catch the vibe of this parameter.

Best Regards,
Kristiyan Tachev
@Stradivario

**Comment by kbbqiu** [comment]
Ah beat me to making this request! There's also this open ticket to provide a list all namespace option which could be lumped together with this work!
https://github.com/fission/fission/issues/924

**Comment by neha-Gupta1** [comment]
Implemented common flag `--namespace` across the CLI.
