### ISSUE TITLE
Helm chart creates a LoadBalancer even when set to ClusterIP

### ISSUE THREAD

**Issue by chrispytoes** [fission/fission#2192]
I'm really not sure if this is a bug but it's at least not documented anywhere. I am trying to install Fission without its own `LoadBalancer`. I have `serviceType` and `routerServiceType` both set to `ClusterIP`, but a `LoadBalancer` is still created upon installing.

I need to expose Fission via my own Ingress and pre-existing `LoadBalancer`.

**Comment by sanketsudake** [comment]
Hi @chrispytoes,

Typically we create following services in `fission` namespace.
```sh
kubectl get svc -n fission
NAME             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
controller       ClusterIP   10.96.235.13    <none>        80/TCP         18h
executor         ClusterIP   10.96.84.167    <none>        80/TCP         18h
influxdb         ClusterIP   10.96.69.68     <none>        8086/TCP       18h
nats-streaming   ClusterIP   10.96.49.3      <none>        4222/TCP       18h
router           NodePort    10.96.146.205   <none>        80:31314/TCP   18h
storagesvc       ClusterIP   10.96.251.48    <none>        80/TCP         18h
```

If you are mentioning `routerServiceType` as `ClusterIP` then `router` service type should be that only.

I am assuming you are passing values correctly.
Can you confirm values if you have installed Fission with the helm?

```sh
$ helm list -A
NAME   	NAMESPACE	REVISION	UPDATED                             	STATUS  	CHART             	APP VERSION
fission	fission  	1       	2021-09-14 16:41:23.677893 +0530 IST	deployed	fission-all-1.14.1	1.14.1
$ helm get values fission -n fission | grep routerService
routerServiceType: NodePort
$ helm get values fission -n fission | grep serviceType
serviceType: ClusterIP
```

Also if you want to use ingress with Fission, Fission supports ingress with Fission routes as well as you can create ingress outside Fission.
https://docs.fission.io/docs/usage/triggers/http-trigger/

Feel free to let me know if have any further queries.

**Comment by chrispytoes** [comment]
@sanketsudake I figured out it was because I installed the chart as a dependency of my own, and was supplying the values via the parent chart's `values.yaml`. I installed it directly and that worked, but I do prefer to run external charts under a parent chart so is there any way to make that work? This isn't normally an issue for me with other charts.

**Comment by sanketsudake** [comment]
I see few discussions on the helm side but nothing conclusive.

https://github.com/helm/helm/issues/6699
https://github.com/helm/helm/pull/6876

As I mentioned above as long as Fission gets correct values, it would respect it. I don't have clear implementation thoughts on how the Fission chart can be used subchart.

Closing this issue probably stands more on the Helm side than on the Fission side.

Feel free to open a Github discussion if you have any ideas to bounce off or need any changes on the Fission side.
