### ISSUE TITLE
Panic: non-positive interval for NewTicker (mqtrigger-kafka)

### ISSUE THREAD

**Issue by Invader007** [fission/fission#2209]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2021-08-03T11:34:27Z"
    GitCommit: 9b5eb069d69d47d22ecc0270bf8619857ea3f19f
    Version: 1.14.1
server:
  fission/core:
    BuildDate: "2021-08-03T09:53:20Z"
    GitCommit: 9b5eb069d69d47d22ecc0270bf8619857ea3f19f
    Version: 1.14.1

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3+k3s1", GitCommit:"1d1f220fbee9cdeb5416b76b707dde8c231121f2", GitTreeState:"clean", BuildDate:"2021-07-22T20:52:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
K3S  (1.21.3)

**Describe the bug**
Since image Version 1.14.1, 1.15.1RC (1.13.1 works fine) there is this panic Error in mqtrigger-kafka view seconds after adding a kafka trigger

<pre>
panic: non-positive interval for NewTicker

goroutine 94 [running]:
time.NewTicker(0x0, 0x0)
	/usr/local/Cellar/go@1.16/1.16.8/libexec/src/time/tick.go:24 +0x151
github.com/bsm/sarama-cluster.(*Consumer).cmLoop(0xc0003f00f0, 0xc0008a8d20)
	/Users/sanket/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/consumer.go:452 +0x5a
github.com/bsm/sarama-cluster.(*loopTomb).Go.func1(0xc0008855e0, 0xc0009ec3d0)
	/Users/sanket/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:73 +0x7b
created by github.com/bsm/sarama-cluster.(*loopTomb).Go
	/Users/sanket/go/pkg/mod/github.com/bsm/sarama-cluster@v2.1.15+incompatible/util.go:69 +0x66
</pre>

**To Reproduce**

Fission 1.14.1 with latest Strimzi operator (Kafka 2.8)

build a sample sample fkt (https://docs.fission.io/docs/usage/triggers/message-queue-trigger/kafka/)

**Comment by torblerone** [comment]
Is there any chance of this issue being fixed soon?

**Comment by sanketsudake** [comment]
This fix would be available in 1.15.1
