### ISSUE TITLE
Cannot use poolmgr executor with KEDA

### ISSUE THREAD

**Issue by coopstah13** [fission/fission#2225]
I am trying to convert our existing HTTP triggers to KEDA MQ Triggers. We currently use the poolmgr executor, and when this is used, KEDA is unable to operate on the ScaledObject because it is expecting a deployment for the function to pre-exist (it doesn't with poolmgr) and thusly fails. This should probably be documented that you need to use newdeploy instead of poolmgr with KEDA (unless you didn't expect this behavior in which case this is a bug).

**Comment by vishal-biyani** [comment]
Hey @coopstah13 That is not true. The ScaledManager for Keda used in MQT scales only the object which is consuming messages (Keda-Connector). After that the function is called over HTTP and it does not matter if it is PoolManager or NewDeployment. Can you please tell us more about what error you are you running into and more details about your setup and functions etc.?

**Comment by coopstah13** [comment]
OK, when I create a keda trigger there is no keda-connector deployment created. I only get a scaled object which references a non-existent deployment. I assumed (wrongly apparently) that I was supposed to have been using newdeploy because of this and that fission was assuming that deployment name. The status of the created ScaledObject is `ScaledObject doesn't have correct scaleTargetRef specification`. When I look at the KEDA logs, there are errors about not finding the deployment referenced (which makes sense since it doesn't exist). Is it allowed to have both an HTTP and MQ trigger simultaneously for the same function? I've been attempting to use the CLI tool to create my trigger.

**Comment by vishal-biyani** [comment]
Hi @coopstah13 and @Algorab I suspect some error is happening when you are creating MQTrigget and hence it can not find the deployment of Keda-Connectors (And not the function deployment itself) Can you please try example here: https://github.com/fission/examples/tree/master/samples/kafka-keda 

In mean time I will also try to reproduce and validate this again. Also samples directory has other Keda examples other than Kafka too, just search for "keda": https://github.com/fission/examples/tree/master/samples

**Comment by Algorab** [comment]
Yes it happens when I create the mqtrigger. The function it self is working. With function test the result is the expected.

I dig the last days though a couple of examples. I think also  these you are mentioned. I will try the examples tomorrow directly.

**Comment by coopstah13** [comment]
Yes, I agree that the problem is it can't find the keda connector deployment - and that is because it never got created (on my system). Based on my (ever-evolving and naive) knowledge of fission, I don't think that the issue is using poolmgr. I suspect something else is at play with my environment or I just ran into a potential bug.

**Comment by Algorab** [comment]
@vishal-biyani the example you mentioned is working (didn't produce the error so far). What I see, this example use a javascript for the consumer. I create an example which use go as consumer. For this I use basically the spec files from the kafka-keda example and accommodate it for use it with go. 

The new example is under: [kafka-keda-k2k-go](https://github.com/Algorab/examples/tree/kafka-keda-k2k-go/samples/kafka-keda-k2k-go)

Hopefully the error is then easier to reproduce.
