### ISSUE TITLE
Package crd name conflicts with the go package key word and run code-generate faile

### ISSUE THREAD

**Issue by jingb** [fission/fission#2268]
**Fission/Kubernetes version**

<pre>
$ fission --version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

I add a new crd and want to genenrate code 
use k8s.io/code-generator/generate-groups.sh all  to generate the client code failed

errors in package "……/pkg/apis/genclient/clientset/versioned/typed/core/v1":
unable to format file "……/pkg/apis/genclient/clientset/versioned/typed/core/v1/package.go" (27:29: expected 'IDENT', found 'package' (and 10 more errors)).

**Cause the package crd name conflicts with the package keyword**, I remove the meta gen info on the package, do it again and  it works.

the code after generated 
![image](https://user-images.githubusercontent.com/9337766/142966443-7c67d080-3d1f-4663-84b4-a45ef62839ec.png)

the code generated before
![image](https://user-images.githubusercontent.com/9337766/142981260-c915d858-7c4e-479b-9295-5450646a4338.png)

I want to know how to add the _ prefix like that. I can not find anything useful in the [code-generator](https://github.com/kubernetes/code-generator)

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by sanketsudake** [comment]
Hey @jingb ,

We have forked upstream code-generator and modified it to generate code.

https://github.com/fission/code-generator/tree/upstream-1.22

You can check this commit https://github.com/fission/code-generator/commit/5a6074d93a9e2bb176a6fcb971d6d846ceeeb2bf

Typically I get latest code-generator code and run https://github.com/fission/code-generator/blob/upstream-1.22/fission-script.sh script on top it, which does necessary replacement.


Once code-generator is modified, we run `make` commands from the Fission project.
```
make codegen 
make generate-crds
```

**Comment by jingb** [comment]
> Hey @jingb ,
> 
> We have forked upstream code-generator and modified it to generate code.
> 
> https://github.com/fission/code-generator/tree/upstream-1.22
> 
> You can check this commit [fission/code-generator@5a6074d](https://github.com/fission/code-generator/commit/5a6074d93a9e2bb176a6fcb971d6d846ceeeb2bf)
> 
> Typically I get latest code-generator code and run https://github.com/fission/code-generator/blob/upstream-1.22/fission-script.sh script on top it, which does necessary replacement.
> 
> Once code-generator is modified, we run `make` commands from the Fission project.
> 
> ```
> make codegen 
> make generate-crds
> ```

It works! Thank!
