### ISSUE TITLE
how to integrate with kubebuilder

### ISSUE THREAD

**Issue by jingb** [fission/fission#2272]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to add some field on the existing crd. For example the Function crd. If I want to add a field funtionType, and it can be only two value A or B. We can add some metadata like  // +kubebuilder:validation:Enum=A;B on the field.
And use kubebuilder to generate the crd definition yaml and install in my cluster. I found since release 1.13, there are all the crd definition yamls in crds directory. And there are some kubebuilder metadata on the crd definition file types.go

**Describe the solution you'd like**
I guess that fission has already use kubebuilder to generate crd definition yaml, but I can not find anything about it in the project or the document. Any one could tell me how to use kubebuilder integrate with fission. Thanks.

**Comment by sanketsudake** [comment]
Hey @jingb 

As of now, we don't use kubebuilder. Though we have tried to achieve parity to use the same tools which kubebuilder does.

We have few commands in the fission project which we use upon makeing any changes in types.

https://github.com/fission/fission/blob/24737e895885d9428aeace7b69858a54a5cc8a13/Makefile#L85

1. The typical process is, you make changes in https://github.com/fission/fission/blob/master/pkg/apis/core/v1/types.go
2. Run all generators.

```
# depends on fission modified code-generator https://github.com/fission/code-generator/tree/upstream-1.22
make codegen # generate code 
# depends on https://github.com/kubernetes-sigs/controller-tools
make  generate-crds # generate CRD 
```

**Comment by jingb** [comment]
@sanketsudake  Thanks. I used to think that we could just edit crd yaml manually without kubebuilder or operator-sdk. And didn't know that we could use kubernetes-sigs/controller-tools to generate yaml definition directly. Thanks again
