### ISSUE TITLE
fission cli hangs after new install

### ISSUE THREAD

**Issue by shaunc** [fission/fission#2278]
**Fission/Kubernetes version**

<pre>
$ fission version --client-only=true
client:
  fission/core:
    BuildDate: "2021-11-23T09:29:28Z"
    GitCommit: 5349a591
    Version: v1.15.0
server:
  fission/core: {}

$ sw_vers
ProductName:    macOS
ProductVersion: 11.6.2
BuildVersion:   20G314

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

EKS

**Describe the bug**

After a new install of fission, the cli does not connect to the cluster controller. For instance:
```
fission support dump --verbosity 2
Setting up port forward to application=fission-api in namespace 
Waiting for local port 51696
Starting port forward from local port 51696
Waiting for port forward 51696 to start...
Using kubeconfig from "/Users/shauncutts/.kube/config"
Connected to Kubernetes API
Connecting to port 8888 on pod fission/controller-7487dcd5d-mk7f8
Starting port forwarder
Forwarding from 127.0.0.1:51696 -> 8888
Forwarding from [::1]:51696 -> 8888
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
Handling connection for 51696
...
```
The messages continue forever.  At the same time, the log of the controller:
```
% kc logs deploy/executor --follow
{"level":"info","ts":"2021-12-13T19:58:00.546Z","caller":"otel/provider.go:202","msg":"OTEL_EXPORTER_OTLP_ENDPOINT not set, skipping Opentelemtry tracing"}
{"level":"info","ts":"2021-12-13T19:58:00.585Z","caller":"fission-bundle/main.go:57","msg":"Starting executor","instanceID":"ordyigjc"}
{"level":"info","ts":"2021-12-13T19:58:00.585Z","logger":"generic_pool_manager.pool_pod_controller","caller":"poolmgr/gpm.go:134","msg":"pool pod controller handlers registered"}
{"level":"info","ts":"2021-12-13T19:58:00.586Z","logger":"new_deploy","caller":"executor/executor.go:351","msg":"Newdeploy starts to clean orphaned resources","instanceID":"ordyigjc"}
{"level":"info","ts":"2021-12-13T19:58:00.586Z","logger":"CaaF","caller":"executor/executor.go:351","msg":"CaaF starts to clean orphaned resources","instanceID":"ordyigjc"}
{"level":"info","ts":"2021-12-13T19:58:00.586Z","logger":"generic_pool_manager","caller":"executor/executor.go:351","msg":"Poolmanager starts to clean orphaned resources","instanceID":"ordyigjc"}
{"level":"info","ts":"2021-12-13T19:58:00.647Z","logger":"executor","caller":"runtime/asm_amd64.s:1371","msg":"starting executor API","port":8888}
{"level":"info","ts":"2021-12-13T19:58:00.847Z","logger":"generic_pool_manager.pool_pod_controller","caller":"runtime/asm_amd64.s:1371","msg":"Waiting for informer caches to sync"}
{"level":"info","ts":"2021-12-13T19:58:00.847Z","logger":"generic_pool_manager.pool_pod_controller","caller":"runtime/asm_amd64.s:1371","msg":"Started workers for poolPodController"}
```
This doesn't change when I execute "support dump" (or any other cli command).

The pods seem all in order:
```
% kc get pods          
NAME                              READY   STATUS    RESTARTS   AGE
buildermgr-7cbfb59c9d-b5lvr       1/1     Running   0          6h15m
busybox                           1/1     Running   0          6h28m
controller-7487dcd5d-mk7f8        1/1     Running   0          6h15m
executor-f968d87d7-gqngc          1/1     Running   0          6h15m
kubewatcher-6c575598c6-mb7fj      1/1     Running   0          6h15m
mqtrigger-keda-58b45c69dd-zp29w   1/1     Running   0          6h15m
router-57bd4d79b7-zdnlb           1/1     Running   0          6h15m
storagesvc-68c876b57d-649sq       1/1     Running   0          6h15m
timer-5799d5f746-4z768            1/1     Running   0          6h15m
```
Busybox is running to check DNS. Inside busybox:

```
kubectl -n fission run busybox --image=busybox --restart=Never --tty -it
If you don't see a command prompt, try pressing enter.
/ # nslookup executor
Server:         172.20.0.10
Address:        172.20.0.10:53

Name:   executor.fission.svc.cluster.local
Address: 172.20.110.7

*** Can't find executor.svc.cluster.local: No answer
*** Can't find executor.cluster.local: No answer
*** Can't find executor.ec2.internal: No answer
*** Can't find executor.fission.svc.cluster.local: No answer
*** Can't find executor.svc.cluster.local: No answer
*** Can't find executor.cluster.local: No answer
*** Can't find executor.ec2.internal: No answer

#
```
(would seem to be normal?)

**To Reproduce**

helm install:

https://gist.github.com/shaunc/61f433e655d47dab89693a48caa576f7

The cluster default namespace is fission:
```
CURRENT   NAME                    CLUSTER                 AUTHINFO                NAMESPACE
          eks_cd-prod-k8          eks_cd-prod-k8          eks_cd-prod-k8          crane-web
*         eks_ff-prod-k8-211202   eks_ff-prod-k8-211202   eks_ff-prod-k8-211202   fission
          ...
```

**Expected result**

The client should communicate with the controller in the cluster.
**Actual result**

The client does not successfully communicate with the controller in the cluster.

**Screenshots/Dump file**

<pre>
$ fission support dump
(hangs -- see above)
</pre>

**Additional context**

I'm running weave-cni in the cluster. Does fission need to communicate with EKS kubernetes master?

**UPDATE** I'm able to connect from cli in docker container running on local dev mac -- so the problem is specific to the client and to macos.

**Comment by shaunc** [comment]
Possibly also related to using `routerServiceType` `clusterIP` ? -- added to question.

**Comment by shaunc** [comment]
NB -- I've spun up a new cluster without weave -- and have the same problem.

**Comment by sanketsudake** [comment]
Hi @shaunc , Typically fission CLI does port forwarding to Fission controller service and then makes request via `localhost:<port forward>`. As we see in your output, `Forwarding from [::1]:51696 -> 8888`
Behaviour is same on MacOs and Linux.

Fission CLI first sets up port-forwarding to Fission controller service. Service type is ClusterIP in your case.
Once port forwarding/tunneling is setup we make REST API calls via over that port.

I am just wondering if there something at play due to network or any firewall rules on the client side.
I use MacOs for day to day work, I couldnt notice this issue for myself or from community so far.

**Comment by shaunc** [comment]
I'm wondering if this could be an RBAC issue of some sort? ... (but then why would it work from linux?) I am experiencing [problems with specs](https://github.com/fission/fission/issues/2305) 

I've been ssh-ing to ubuntu while this issue is still open. Both my mac and the ubuntu machine in the basement are on the same network, and I haven't don't any special firewall configuration on my mac. (My python environment might be a little wonky, as I use from a shell with anaconda venv, but fission cli looks not to depend on that.) 

Is there some way to turn more detailed logging on in the cluster, perhaps? I wonder if we can actually see what happens to those messages forwarded....

**Comment by JShamdasani** [comment]
Can confirm, I am also facing the same issues on MacOS but it works 100% fine on my Archlinux machine.

**Comment by gauravgahlot** [comment]
I tested this out and it worked. Left a comment about the steps here:
https://github.com/fission/fission/pull/2405#issuecomment-1094265817

**Comment by gauravgahlot** [comment]
@sanketsudake I believe we can close this now.

**Comment by sanketsudake** [comment]
Closing this issue. Feel free to reopen if you observe any similar issue once we have 1.16-rc2
