### ISSUE TITLE
Running into i/o timeout. Setup not able to connect to fission server.

### ISSUE THREAD

**Issue by shekharupland** [fission/fission#228]
Hello, 

I am running a local kubernetes cluster on REHL7. I followed the instruction and deployed the fission and also set the FISSION_URL and FISSION_ROUTER env properties. However while executing fission cli I am running to connection error. 
Could you please provided me any pointers. 
This is a kubeadm based setup, which I am using to try fission.
Output of kubectl get pods --all-namespaces -o wide :

fission       controller-2539654023-7f94r             1/1       Running            0          58m       172.17.0.2      vm-4
fission       etcd-73675509-wplds                     1/1       Running            0          58m       172.17.0.6      vm-4
fission       kubewatcher-2402157042-pnn1m            0/1       CrashLoopBackOff   10         58m       172.17.0.3      vm-4
fission       poolmgr-3736272841-bcqr2                0/1       CrashLoopBackOff   12         58m       172.17.0.5      vm-4
fission       router-2952920748-vqn3p                 0/1       CrashLoopBackOff   12         58m       172.17.0.4      vm-4

output of fission env list:
Failed to list environments: Get http://10.107.186.129:31313/v1/environments: dial tcp 10.107.186.129:31313: i/o timeout

 kubectl --namespace fission get svc controller -o wide 
NAME         CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE       SELECTOR
controller   10.107.186.129   <nodes>       80:31313/TCP   1h        svc=controller

kubectl --namespace fission get svc router -o wide
NAME      CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE       SELECTOR
router    10.107.40.165   <nodes>       80:31314/TCP   1h        svc=router

**Comment by life1347** [comment]
Hi @shekharupland, from the output of `kubectl --namespace fission get svc controller -o wide`, I think the IP `10.107.186.129` is the cluster IP, which means that it's only accessible in the k8s cluster. 

Since your k8s cluster doesn't have a external IP, you should set the env `FISSION_URL` like this `http://<your host ip>:31313`.  For example, my computer IP is 10.101.0.199, so that my FISSION_URL is `http://10.101.0.199:31313`.

**Comment by shekharupland** [comment]
Thanks for the reply. Ya I tried that too. But it doesn't help.
I think the problem is out of 5 fission pod, 3 are running into an error i.e.
controller-2539654023-7f94r    1/1       Running            0          2d        172.17.0.2   vm-4
etcd-73675509-wplds            1/1       Running            0          2d        172.17.0.6   vm-4
kubewatcher-2402157042-7z13h   0/1       CrashLoopBackOff   19         2h        172.17.0.3   vm-4
poolmgr-3736272841-nrr7m       0/1       CrashLoopBackOff   23         2h        172.17.0.5   vm-4
router-2952920748-95dj8        0/1       CrashLoopBackOff   23         2h        172.17.0.4   vm-4

I fetched the docker container logs to dig little deeper, And I see following : 
In fission router : 
Starting router at port 8888
2017/06/12 19:50:36 Failed to connect to controller after 5 retries: Get http://controller.fission/v1/triggers/http: dial tcp: lookup controller.fission on 10.96.0.10:53: read udp 172.17.0.4:56029->10.96.0.10:53: i/o timeout

In fission pool mgr : 
starting poolmgr at port 8888
2017/06/12 19:50:09 Failed to cleanup: the server does not allow access to the requested resource (get deployments.extensions)
2017/06/12 19:51:29 Failed to connect to controller 5 times: Get http://controller.fission/v1/environments: dial tcp: lookup controller.fission on 10.96.0.10:53: read udp 172.17.0.5:44217->10.96.0.10:53: i/o timeout

In fission kubewatcher : 
Failed to connect to controller: Get http://controller.fission/v1/watches: dial tcp: lookup controller.fission on 10.96.0.10:53: read udp 172.17.0.3:50601->10.96.0.10:53: i/o timeout

Not sure from where it is picking the IP : 10.96.0.10:53.

**Comment by soamvasani** [comment]
>  2017/06/12 19:50:09 Failed to cleanup: the server does not allow access to the requested resource (get deployments.extensions)

This is issue #160. Please use `fission-rbac.yaml` or create an RBAC rule allowing fission to operate as admin on the cluster:

```
kubectl create clusterrolebinding fission-admin --clusterrole cluster-admin --serviceaccount fission:default
```

**Comment by shekharupland** [comment]
Still seeing the same issue, I also captured the machine logs : 

docker_sandbox.go:263] Couldn't find network status for fission/router-133236643-wq8tf through plugin: invalid network status for
Jun 12 18:08:29 vm-4 kubelet: I0612 18:08:29.603004    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/0f064d78-4c1d-11e7-874d-c6b073e98f26-flannel-token-m7dhx" (spec.Name: "flannel-token-m7dhx") pod "0f064d78-4c1d-11e7-874d-c6b073e98f26" (UID: "0f064d78-4c1d-11e7-874d-c6b073e98f26").
Jun 12 18:08:29 vm-4 kubelet: I0612 18:08:29.604407    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/configmap/0f064d78-4c1d-11e7-874d-c6b073e98f26-flannel-cfg" (spec.Name: "flannel-cfg") pod "0f064d78-4c1d-11e7-874d-c6b073e98f26" (UID: "0f064d78-4c1d-11e7-874d-c6b073e98f26").
Jun 12 18:08:31 vm-4 kubelet: I0612 18:08:31.608658    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/813ae82e-4fb9-11e7-874d-c6b073e98f26-fission-svc-token-s867d" (spec.Name: "fission-svc-token-s867d") pod "813ae82e-4fb9-11e7-874d-c6b073e98f26" (UID: "813ae82e-4fb9-11e7-874d-c6b073e98f26").
Jun 12 18:08:31 vm-4 kubelet: I0612 18:08:31.828680    6508 kuberuntime_manager.go:458] Container {Name:kubewatcher Image:fission/fission-bundle:alpha20170328 Command:[/fission-bundle] Args:[--kubewatcher] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:fission-svc-token-s867d ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 12 18:08:31 vm-4 kubelet: E0612 18:08:31.831993    6508 kubelet_network.go:103] Found and omitted duplicated dns domain in host search line: 'opcwlaas.oraclecloud.internal.' during merging with cluster dns domains
Jun 12 18:08:31 vm-4 kubelet: I0612 18:08:31.832860    6508 kuberuntime_manager.go:742] checking backoff for container "kubewatcher" in pod "kubewatcher-769133274-tclrz_fission(813ae82e-4fb9-11e7-874d-c6b073e98f26)"
Jun 12 18:08:31 vm-4 kubelet: I0612 18:08:31.833938    6508 kuberuntime_manager.go:752] Back-off 1m20s restarting failed container=kubewatcher pod=kubewatcher-769133274-tclrz_fission(813ae82e-4fb9-11e7-874d-c6b073e98f26)
Jun 12 18:08:31 vm-4 kubelet: E0612 18:08:31.834857    6508 pod_workers.go:182] Error syncing pod 813ae82e-4fb9-11e7-874d-c6b073e98f26 ("kubewatcher-769133274-tclrz_fission(813ae82e-4fb9-11e7-874d-c6b073e98f26)"), skipping: failed to "StartContainer" for "kubewatcher" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=kubewatcher pod=kubewatcher-769133274-tclrz_fission(813ae82e-4fb9-11e7-874d-c6b073e98f26)"
Jun 12 18:08:34 vm-4 kubelet: I0612 18:08:34.617808    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/812ff56e-4fb9-11e7-874d-c6b073e98f26-fission-svc-token-s867d" (spec.Name: "fission-svc-token-s867d") pod "812ff56e-4fb9-11e7-874d-c6b073e98f26" (UID: "812ff56e-4fb9-11e7-874d-c6b073e98f26").
Jun 12 18:08:34 vm-4 kubelet: I0612 18:08:34.826570    6508 kuberuntime_manager.go:458] Container {Name:poolmgr Image:fission/fission-bundle:alpha20170328 Command:[/fission-bundle] Args:[--poolmgrPort 8888] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:fission-svc-token-s867d ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 12 18:08:34 vm-4 kubelet: E0612 18:08:34.830049    6508 kubelet_network.go:103] Found and omitted duplicated dns domain in host search line: 'opcwlaas.oraclecloud.internal.' during merging with cluster dns domains
Jun 12 18:08:34 vm-4 kubelet: I0612 18:08:34.831194    6508 kuberuntime_manager.go:742] checking backoff for container "poolmgr" in pod "poolmgr-1327499456-bw1t1_fission(812ff56e-4fb9-11e7-874d-c6b073e98f26)"
Jun 12 18:08:34 vm-4 kubelet: I0612 18:08:34.832437    6508 kuberuntime_manager.go:752] Back-off 5m0s restarting failed container=poolmgr pod=poolmgr-1327499456-bw1t1_fission(812ff56e-4fb9-11e7-874d-c6b073e98f26)
Jun 12 18:08:34 vm-4 kubelet: E0612 18:08:34.833464    6508 pod_workers.go:182] Error syncing pod 812ff56e-4fb9-11e7-874d-c6b073e98f26 ("poolmgr-1327499456-bw1t1_fission(812ff56e-4fb9-11e7-874d-c6b073e98f26)"), skipping: failed to "StartContainer" for "poolmgr" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=poolmgr pod=poolmgr-1327499456-bw1t1_fission(812ff56e-4fb9-11e7-874d-c6b073e98f26)"
Jun 12 18:08:39 vm-4 kubelet: I0612 18:08:39.540245    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/814c70bb-4fb9-11e7-874d-c6b073e98f26-fission-svc-token-s867d" (spec.Name: "fission-svc-token-s867d") pod "814c70bb-4fb9-11e7-874d-c6b073e98f26" (UID: "814c70bb-4fb9-11e7-874d-c6b073e98f26").
Jun 12 18:08:39 vm-4 kubelet: E0612 18:08:39.826545    6508 kubelet_network.go:103] Found and omitted duplicated dns domain in host search line: 'opcwlaas.oraclecloud.internal.' during merging with cluster dns domains
Jun 12 18:08:40 vm-4 kubelet: I0612 18:08:40.540972    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/811a66ab-4fb9-11e7-874d-c6b073e98f26-fission-svc-token-s867d" (spec.Name: "fission-svc-token-s867d") pod "811a66ab-4fb9-11e7-874d-c6b073e98f26" (UID: "811a66ab-4fb9-11e7-874d-c6b073e98f26").
Jun 12 18:08:40 vm-4 kubelet: I0612 18:08:40.825995    6508 kuberuntime_manager.go:458] Container {Name:router Image:fission/fission-bundle:alpha20170328 Command:[/fission-bundle] Args:[--routerPort 8888] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:fission-svc-token-s867d ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jun 12 18:08:40 vm-4 kubelet: E0612 18:08:40.828504    6508 kubelet_network.go:103] Found and omitted duplicated dns domain in host search line: 'opcwlaas.oraclecloud.internal.' during merging with cluster dns domains
Jun 12 18:08:40 vm-4 kubelet: I0612 18:08:40.828611    6508 kuberuntime_manager.go:742] checking backoff for container "router" in pod "router-133236643-wq8tf_fission(811a66ab-4fb9-11e7-874d-c6b073e98f26)"
Jun 12 18:08:40 vm-4 kubelet: I0612 18:08:40.829933    6508 kuberuntime_manager.go:752] Back-off 5m0s restarting failed container=router pod=router-133236643-wq8tf_fission(811a66ab-4fb9-11e7-874d-c6b073e98f26)
Jun 12 18:08:40 vm-4 kubelet: E0612 18:08:40.830283    6508 pod_workers.go:182] Error syncing pod 811a66ab-4fb9-11e7-874d-c6b073e98f26 ("router-133236643-wq8tf_fission(811a66ab-4fb9-11e7-874d-c6b073e98f26)"), skipping: failed to "StartContainer" for "router" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=router pod=router-133236643-wq8tf_fission(811a66ab-4fb9-11e7-874d-c6b073e98f26)"
Jun 12 18:08:42 vm-4 kubelet: I0612 18:08:42.544558    6508 operation_generator.go:597] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/813ae82e-4fb9-11e7-874d-c6b073e98f26-fission-svc-token-s867d" (spec.Name: "fission-svc-token-s867d") pod "813ae82e-4fb9-11e7-874d-c6b073e98f26" (UID: "813ae82e-4fb9-11e7-874d-c6b073e98f26").

I am using flanneld as a network overlay for my kubernetes cluster, do you think it might have to something with this behaviour?

**Comment by soamvasani** [comment]
@shekharupland can you drop by the slack channel so we can help debug this?  Thanks

http://slack.fission.io

**Comment by shekharupland** [comment]
One more observation : 

curl -vvv http://127.0.0.1:31313/v1/environments
* About to connect() to 127.0.0.1 port 31313 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 31313 (#0)
> GET /v1/environments HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:31313
> Accept: */*
> 
< HTTP/1.1 500 Internal Server Error
< Content-Type: text/plain; charset=utf-8
< X-Content-Type-Options: nosniff
< Date: Tue, 13 Jun 2017 05:56:50 GMT
< Content-Length: 123
< 
client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://etcd:2379 exceeded header timeout

* Connection #0 to host 127.0.0.1 left intact

This I tried on the vm on which controller container is running.

**Comment by shekharupland** [comment]
In addition to that: fission controller logs also have similar logs. 
time="2017-06-13T06:05:14Z" level=info msg="Created directory /filestore" 
time="2017-06-13T06:05:14Z" level=info msg="Server started" port=8888 
goroutine 18 [running]:
runtime/debug.Stack(0x80, 0x80, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x1a
github.com/fission/fission/controller.(*API).respondWithError(0x19c49860, 0xf76fd048, 0x19db2460, 0x97023e0, 0x19ad4290)
	/Users/soam/gopath/src/github.com/fission/fission/controller/api.go:59 +0x1e
github.com/fission/fission/controller.(*API).EnvironmentApiList(0x19c49860, 0xf76fd048, 0x19db2460, 0x19c94100)
	/Users/soam/gopath/src/github.com/fission/fission/controller/environmentApi.go:33 +0x10c
github.com/fission/fission/controller.(*API).EnvironmentApiList-fm(0xf76fd048, 0x19db2460, 0x19c94100)
	/Users/soam/gopath/src/github.com/fission/fission/controller/api.go:86 +0x38
net/http.HandlerFunc.ServeHTTP(0x19e05548, 0xf76fd048, 0x19db2460, 0x19c94100)
	/usr/local/go/src/net/http/server.go:1942 +0x34
github.com/fission/fission/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0x19c9a690, 0xf76fd048, 0x19db2460, 0x19c94100)
	/Users/soam/gopath/src/github.com/fission/fission/vendor/github.com/gorilla/mux/mux.go:114 +0xce
github.com/fission/fission/vendor/github.com/gorilla/handlers.loggingHandler.ServeHTTP(0x9704d20, 0x19a0c0b8, 0x9702640, 0x19c9a690, 0x970b060, 0x19bf0000, 0x19c94000)
	/Users/soam/gopath/src/github.com/fission/fission/vendor/github.com/gorilla/handlers/handlers.go:69 +0xdc
github.com/fission/fission/vendor/github.com/gorilla/handlers.(*loggingHandler).ServeHTTP(0x19ad5920, 0x970b060, 0x19bf0000, 0x19c94000)
	<autogenerated>:8 +0x69
net/http.serverHandler.ServeHTTP(0x19c95780, 0x970b060, 0x19bf0000, 0x19c94000)
	/usr/local/go/src/net/http/server.go:2568 +0x70
net/http.(*conn).serve(0x19c2e000, 0x970bd40, 0x19db2140)
	/usr/local/go/src/net/http/server.go:1825 +0x578
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x225
time="2017-06-13T06:07:25Z" level=error msg="Error: 500: client: etcd cluster is unavailable or misconfigured; error #0: client: endpoint http://etcd:2379 exceeded header timeout\n" 
172.17.0.1 - - [13/Jun/2017:06:07:24 +0000] "GET /v1/environments HTTP/1.1" 500 123

**Comment by soamvasani** [comment]
This issue isn't tracking any one particular problem. If you're still having issues, please reach out on slack, thanks.
