### ISSUE TITLE
Getting an error "error posting to getting service for function" while running functions

### ISSUE THREAD

**Issue by RahulMetangale** [fission/fission#2301]
Hi Team,

We are recently seeing following error while running fission functions:
`{"level":"error","ts":"2022-01-16T12:48:04.559Z","logger":"triggerset.http_trigger_set.432597-http","caller":"router/functionHandler.go:641","msg":"error from GetServiceForFunction","error":"error posting to getting service for function: context deadline exceeded","errorVerbose":"context deadline exceeded\nerror posting to getting service for function\ngithub.com/fission/fission/pkg/executor/client.(*Client).GetServiceForFunction\n\t/go/src/github.com/fission/fission/pkg/executor/client/client.go:83\ngithub.com/fission/fission/pkg/router.functionHandler.getServiceEntryFromExecutor\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:638\ngithub.com/fission/fission/pkg/router.functionHandler.getServiceEntry\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:662\ngithub.com/fission/fission/pkg/router.(*RetryingRoundTripper).RoundTrip\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:223\nnet/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/go/src/net/http/httputil/reverseproxy.go:284\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\t/go/src/github.com/fission/fission/pkg/router/functionHandler.go:497\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\t/go/src/github.com/fission/fission/pkg/router/mutablemux.go:52\ngo.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP\n\t/go/pkg/mod/go.opencensus.io@v0.23.0/plugin/ochttp/server.go:92\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374","error_message":"error posting to getting service for function: context deadline exceeded","function":{"kind":"Function","apiVersion":"fission.io/v1","metadata":{"name":"432597","namespace":"default","uid":"91b0d343-2e6b-45b5-978e-22079fd12d1a","resourceVersion":"263009850","generation":1,"creationTimestamp":"2022-01-16T12:42:03Z","managedFields":[{"manager":"unknown","operation":"Update","apiVersion":"fission.io/v1","time":"2022-01-16T12:42:03Z","fieldsType":"FieldsV1","fieldsV1":{"f:spec":{".":{},"f:InvokeStrategy":{".":{},"f:ExecutionStrategy":{".":{},"f:ExecutorType":{},"f:MaxScale":{},"f:MinScale":{},"f:SpecializationTimeout":{},"f:TargetCPUPercent":{}},"f:StrategyType":{}},"f:concurrency":{},"f:configmaps":{},"f:environment":{".":{},"f:name":{},"f:namespace":{}},"f:functionTimeout":{},"f:package":{".":{},"f:functionName":{},"f:packageref":{".":{},"f:name":{},"f:namespace":{}}},"f:resources":{},"f:secrets":{}}}}]},"spec":{"environment":{"namespace":"default","name":"python-env-build-198406-1f04db"},"package":{"packageref":{"namespace":"default","name":"432597-pkge"},"functionName":"sum.main"},"resources":{},"InvokeStrategy":{"ExecutionStrategy":{"ExecutorType":"poolmgr","MinScale":0,"MaxScale":0,"TargetCPUPercent":0,"SpecializationTimeout":300},"StrategyType":"execution"},"functionTimeout":120,"concurrency":500}},"status_code":500}`

This used to work before. 

Environment details:
Azure Kubernetes Service : 1.20.9
Fission: 1.14.1

Able to resolve executor.fission suing dnsutil pod
![image](https://user-images.githubusercontent.com/5917001/149661667-c296dd2a-558f-465c-a6a0-49c8965db2c9.png)

From router pod
![image](https://user-images.githubusercontent.com/5917001/149664593-0b9075ca-bb0a-4543-8b16-5885517b788c.png)

Recent changes to cluster:
1. Kubernetes version upgrade from 1.20.7 to 1.20.9

**Comment by sanketsudake** [comment]
Hey @RahulMetangale,

The error you have observed in the logs and DNS details shared below seems a bit unrelated to me.

Error observed in logs typically could happen if specialization via executor take some extra time or there is no sufficient pool with pool manager for function specialization.

Could you please share if you are facing issues for all function calls or only specific function calls?

**Comment by RahulMetangale** [comment]
Hi @sanketsudake 

Thank you for your response.

I was able to resolve the issue. This was happening for all functions. 

Resolution:
This issue started occurring when we upgraded our AKS kubernetes version from 12.0.7 to 1.20.9.

To resolve the issue we had to run following commands again. So my guess is after Kubernetes version upgrade  fission CRD upgrade is needed.

```
#Replace fission CRDs
kubectl replace -k "github.com/fission/fission/crds/v1?ref=1.14.1"

#Delete the current replica set 
kubectl delete rs -n fission $(kubectl get rs -n fission | grep storagesvc| awk '$2==1 && $3==1 && $4==1 {print $1}') || true

helm upgrade fission https://github.com/fission/fission/releases/download/1.14.1/fission-core-1.14.1.tgz --install --wait --reset-values --timeout 1800s --create-namespace --namespace "fission" -f fissionConfig.yaml
```

I hope this helps.

Thanks,
Rahul Metangale
