### ISSUE TITLE
Internal error when deploying specs

### ISSUE THREAD

**Issue by shaunc** [fission/fission#2305]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-11-23T09:29:28Z"
    GitCommit: 5349a591
    Version: v1.15.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.1", GitCommit:"86ec240af8cbd1b60bcc4c03c20da9b98005b92e", GitTreeState:"clean", BuildDate:"2021-12-16T11:41:01Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21+", GitVersion:"v1.21.2-eks-06eac09", GitCommit:"5f6d83fe4cb7febb5f4f4e39b3b2b64ebbbe3e97", GitTreeState:"clean", BuildDate:"2021-09-13T14:20:15Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)** EKS

**Describe the bug**

Communicating with functions created in spec causes internal error in fission
**To Reproduce**

Apply specs:
[specs.zip](https://github.com/fission/fission/files/7917540/specs.zip)
[sendsftp.zip](https://github.com/fission/fission/files/7917538/sendsftp.zip)

Port forward:
```
kubectl --namespace fission port-forward $(kubectl --namespace fission get pod -l svc=router -o name) 8889:8888
export FISSION_ROUTER=127.0.0.1:8889
```
Attempt to access function:
```
$ curl http://$FISSION_ROUTER/cdf/send-sftp/check
Handling connection for 8889
error sending request to function
```
Look at logs:
```
{"level":"error","ts":"2022-01-22T03:36:36.306Z","logger":"triggerset.http_trigger_set.cdf-send-sftp-check","caller":"httputil/reverseproxy.go:295","msg":"error sending request to function","trace_id":"d26ca378513b7ad6a6470496680f3752","error":" - Internal error - [cdf-send-sftp-check] error creating service for function: Internal error - error specializing function pod: Internal error - <!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2 Final//EN\">\n<title>500 Internal Server Error</title>\n<h1>Internal Server Error</h1>\n<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>","function":{"namespace":"default","name":"cdf-send-sftp-check"},"status":"Internal Server Error","code":500,"stacktrace":"net/http/httputil.(*ReverseProxy).ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/httputil/reverseproxy.go:295\ngithub.com/fission/fission/pkg/router.functionHandler.handler\n\tpkg/router/functionHandler.go:529\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/server.go:2049\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\t/Users/sanket/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210\ngithub.com/fission/fission/pkg/router.(*mutableRouter).ServeHTTP\n\tpkg/router/mutablemux.go:52\ngo.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*Handler).ServeHTTP\n\t/Users/sanket/go/pkg/mod/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.26.0/handler.go:179\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/server.go:2867\nnet/http.(*conn).serve\n\t/usr/local/Cellar/go@1.16/1.16.10/libexec/src/net/http/server.go:1932"}
```
Other pods have similar errors -- see:
[fission-dump_1642822157.zip](https://github.com/fission/fission/files/7917553/fission-dump_1642822157.zip)

**Expected result**

The function should run.
**Actual result**
Triggering the function via http causes an internal error.

**Screenshots/Dump file**

( see above)
**Additional context**

One possible problem mentioned in the error message is "server is overloaded" -- however, the cluster is not very busy:
```
$ kc top nodes
NAME                           CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
ip-10-16-10-236.ec2.internal   105m         5%     1534Mi          46%       
ip-10-16-15-38.ec2.internal    162m         8%     2573Mi          77%       
ip-10-16-17-185.ec2.internal   174m         9%     2934Mi          88%       
ip-10-16-22-148.ec2.internal   114m         5%     1461Mi          43%       
```

**Comment by blackfly19** [comment]
Hi @shaunc . I got the same issue so I did some digging. I found out that the error is due to the flask application. [https://www.youtube.com/watch?v=p_so34WgnyY](url) So you will have to debug your flask app first and then try running again.

**Comment by shaunc** [comment]
hmm.. but I'm not using flask?

**Comment by sanketsudake** [comment]
Closing this issue , this seems more application specific or env related.

Please try again with latest python env and feel free to reopen if seems Fission issue.
