### ISSUE TITLE
Deleting an environment leaves environment pods in terminating state

### ISSUE THREAD

**Issue by garrit-schroeder** [fission/fission#2340]
Fission Version

client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

K3S Kubernetes Version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2+k3s1", GitCommit:"10bca343e85180f668522fe252552da20220cb7a", GitTreeState:"clean", BuildDate:"2021-09-23T22:46:18Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}

Issue:

When running

`fission env delete --name python`

the pods from `kubectl get pod -n fission-function` are going into terminating state but are not getting removed. 

I am using the official python-env containers. 

`NAME   IMAGE              BUILDER_IMAGE          POOLSIZE MINCPU MAXCPU MINMEMORY MAXMEMORY EXTNET GRACETIME
python fission/python-env fission/python-builder 3        0      0      0         0         false  0`

**Comment by blackfly19** [comment]
Hi @garrit-schroeder. It does take sometime in removing the pods from the namespace `fission-function` but eventually it does. Mine took around 10 minutes.

**Comment by shubham-bansal96** [comment]
ide
