### ISSUE TITLE
program seems to be blocked under poolmgr type if the requests workload surge

### ISSUE THREAD

**Issue by LinYKen** [fission/fission#2357]
**Fission/Kubernetes version**

<pre>
$ fission --version 1.15
$ kubectl version 1.23
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Google Kubernetes Engine
**Describe the bug**

When the executortype is poolmanager, I use hey tool to send the request to a url address, for example, set the number of total requests to be 1000, it takes a lot of time, perhaps 3-5mins to complete and nearly 30% of the requests fail. Then the program seems to be blocked, when I try to apply maybe 2000 requests with hey it doesn't work, also, the pods under namespace fission-function then gradually turn into terminating status. And now, if I curl the url again, then it doesn't work and return the **error sending request to function** message.
**To Reproduce**

fission env create --name nodepool --image fission/node-env --version 3 --poolsize 3
fission function create --name nodepool --env nodepool --code hello.js --rpp 50
fission route create --function nodepool --url nodepool
hey -n 1000 http://$FISSION_ROUTE/nodepool (extremely slow, can use the kubectl get pods to see that many new containers are creating)
hey -n 2000 http://$FISSION_ROUTE/nodepool (extremely slow, pods don't change, seems to be blocked, failed finally)
curl http://$FISSION_ROUTE/nodepool  (blocked? failed finally)

**Expected result**

It should return the normal results from hey
**Actual result**
nearly 30% requests exceed the context deadline

**Screenshots/Dump file**

![image](https://user-images.githubusercontent.com/38637805/153760342-3b5da627-038c-4757-a865-b8630b7172cd.png)

<pre>
$ fission support dump
</pre>

**Additional context**

[fission-dump_1644766553.zip](https://github.com/fission/fission/files/8055939/fission-dump_1644766553.zip)

**Comment by sanketsudake** [comment]
Closing this issue as seems to be related to https://github.com/fission/fission/issues/2357
Please track https://github.com/fission/fission/issues/2357 for further updates.
