### ISSUE TITLE
Require '--code <path>' when updating function

### ISSUE THREAD

**Issue by CamelCaseNotation** [fission/fission#237]
Updating function without --code <path> does nothing.
Assume a function named `test` exists with code that simply prints "Hello, World!". Changing the file containing the code responsible for printing that statement and then running:

`fission function update --name test`

does not update the code when you test it by hitting the endpoint configured in the route.
The `--code` flag is explicitly required but not stated as such in the help message. Currently it only says `Need name of function, use --name`

**Comment by life1347** [comment]
Hi @CamelCaseNotation

A user may just want to update the environment of function, the `--code` flag is not required under this situation. 

However, the command needs to print a message for notification when no change is made to the function. I just push a PR to improve the usability of cli.

Thanks for your report. 😄

**Comment by soamvasani** [comment]
Thanks @life1347

**Comment by CamelCaseNotation** [comment]
Thank you!
