### ISSUE TITLE
Provide RBAC capabilities to be managed/enhanced by administrators

### ISSUE THREAD

**Issue by torbendury** [fission/fission#2372]
**Is your feature request related to a problem? Please describe.**
After a short talk in your slack, theres basically two situations at the moment:

#### A
I, as an administrator, need to provide fission as a FaaS platform to developers. I want them to be able to deploy their functions, but not neccessarily create them (including everything else, meaning triggers, routes, ...) and in any case not delete them by mistake. The easiest way is to prevent them from doing anything manually (the DevOps way) by providing them CI/CD pipelines that deploy their code automatically.

Problem: I don't know what they want (and be honest: they don't know either). I'll end up crafting a unique pipeline that'll need many adjustments. But: My environment is safe.

#### B
I, as an administrator, **still** need to provide a FaaS platform. Since I'm already working overtime, I just give them access to the platform, go on vacation for a week and leave them alone with it. After a week, you hear sirens in the distance.

Problems: They didn't know what they want, tried every possible tutorial _for the lulz_ and completely broke the platform. Anti-DevOps: Giving developers full access to everything so they can play manually.

**Describe the solution you'd like**
I want to be able to use Fission RBAC to provide developers some _basic_ access to the platform (e.g. deploying only certain functions, prevent deletion, ... - this might include k8s namespace RBAC features to decouple everything a little more!). Since I don't want to be the Single-Point-of-Failure, I want to give _administrator_ access other colleagues.

Note: This does not have to be completely sophisticated and polished, this can start as a MVP and be elaborated further later.

**Describe alternatives you've considered**
The two alternatives that come to my mind have been mentioned above and might both end in catastrophic scenarios.

**Additional context**
Kubernetes offers beautiful RBAC, both namespace- and cluster-scoped, which should be utilized. With this, you still don't need to manage authorization + login, but can use the existing API.

One might create a `ClusterRole` called `fission-administrator` and `fission-developer` which includes a basic set of permissions that can then be assigned and/or derived and polished.

**Comment by torbendury** [comment]
Hi everyone! Has this topic made it to any roadmap or is there maybe already an ETA for this?

**Comment by praddy26** [comment]
Hello @torbendury 

This issue has been assigned to me and it's a work in progress. It needs a major rewrite in our CLI code and hence we have to do a thorough regression testing before we make it a GA.

**Comment by plonkernickel** [comment]
Hi @praddy26 ! 

Are there any updates to this? Missing RBAC management is a blocker for us to hand over our fission installation to developers, we want to thrive the _least privilege_ principle when letting developers work with fission.

**Comment by sanketsudake** [comment]
A couple of changes related to this are already merged into the Fission source. Changes would be available in the Fission 1.18 release.

**Comment by sanketsudake** [comment]
This is available now in the [1.18.0-rc1 ](https://fission.io/docs/releases/v1.18.0-rc1/) release.

We have documented permissions RBAC and plan to enhance in future releases.
https://fission.io/docs/usage/rbac-permissions/
