### ISSUE TITLE
Old poolmgr pods that are idle are not getting deleted

### ISSUE THREAD

**Issue by thegedge** [fission/fission#2373]
**Fission/Kubernetes version**

```
$ fission version
client:
  fission/core: {}
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.16.13", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6-gke.1500", GitCommit:"7ce0f9f1939dfc1aee910732e84cba03840df91e", GitTreeState:"clean", BuildDate:"2021-11-17T09:30:26Z", GoVersion:"go1.16.9b7", Compiler:"gc", Platform:"linux/amd64"}
```

**Kubernetes platform (e.g. Google Kubernetes Engine)**

GKE

**Describe the bug**

We're seeing really old, specialized function pods in our cluster (4 days+). We're seeing the error message here printed over a long period of time:

https://github.com/fission/fission/blob/e1d86d896977ec03fe205f20d9ca189f1ad85db7/pkg/executor/executortype/poolmgr/poolpodcontroller.go#L417-L421

**To Reproduce**

N/A

**Expected result**

All specialized function pods that are idle are deleted.

**Actual result**

Specialized pods linger around because they cannot be deleted.

**Screenshots/Dump file**

Here's an example log entry we see every 30 minutes:

```
2022-02-28T01:53:23.996Z 	ERROR	generic_pool_manager.pool_pod_controller	 poolmgr/poolpodcontroller.go:244	failed to delete pod	 {"error": "pods \"poolmgr-js-sandbox-gadget-app-sandbox-production-431977607hrqxd\" not found", "pod": "poolmgr-js-sandbox-gadget-app-sandbox-production-431977607hrqxd", "pod_namespace": "gadget-app-sandbox-production"}
```

From this screenshot you can see it happening over 4 days (these are the fission log events relating to a specific sandbox):

<img width="745" alt="log events bar chart over time" src="https://user-images.githubusercontent.com/833576/156083028-0b2f7f2f-8830-4e26-9e5c-4fecdeb38819.png">

All fission pods have been running for 10 days, making me think there's something cached somewhere. Let me know if there's additional context that would be helpful in debugging.

**Comment by sanketsudake** [comment]
Related issue https://github.com/fission/fission/issues/2237

**Comment by sanketsudake** [comment]
Please subscribe to #2237 for further updates. Closing this issue as a duplicate.

**Comment by sanketsudake** [comment]
@thegedge 
So code linked in the issue, is called when env gets updated/deleted. Upon env update/deletion we cleanup relevant pods.
I think mostly env pod might be getting deleted earlier through some other loop. 

https://github.com/fission/fission/blob/e1d86d896977ec03fe205f20d9ca189f1ad85db7/pkg/executor/executortype/poolmgr/poolpodcontroller.go#L417-L421

Do we see any issue such that pod is mentioned as not found in the logs, but it is actually present in the Kubernetes cluster ?
If its not present, then mostly I think its already cleaned up.

In that case we may see issue due to https://github.com/fission/fission/issues/2237

**Comment by thegedge** [comment]
> Do we see any issue such that pod is mentioned as not found in the logs, but it is actually present in the Kubernetes cluster ?

Just verified that these pods are indeed still present (via `kubectl`).

**Comment by sanketsudake** [comment]
@thegedge could you please confirm if function namespace you have is same ? 
You can check values provided to helm chart. `values.functionNamespace` ? If it is `gadget-app-sandbox-production` only.

Also please see if service account attached to executor pod has delete permissions.

```
2022-02-28T01:53:23.996Z 	ERROR	generic_pool_manager.pool_pod_controller	 poolmgr/poolpodcontroller.go:244	failed to delete pod	 {"error": "pods \"poolmgr-js-sandbox-gadget-app-sandbox-production-431977607hrqxd\" not found", "pod": "poolmgr-js-sandbox-gadget-app-sandbox-production-431977607hrqxd", "pod_namespace": "gadget-app-sandbox-production"}
```

**Comment by thegedge** [comment]
Actually, there is a service account where those two commands say "yes": `fission-svc`. Looks like that is used by the executor's `ReplicaSet`, so I think we're good there 👍

**Comment by sanketsudake** [comment]
Cool looks like we try to delete pod with namespace `fission-production-function` and pod name. I will changes to code. So this should get resolved.
Where as in log we pick up correct namespace.
