### ISSUE TITLE
Unable to complete installation and connect to http trigger

### ISSUE THREAD

**Issue by emmmplayer** [fission/fission#2377]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.5", GitCommit:"5c99e2ac2ff9a3c549d9ca665e7bc05a3e18f07e", GitTreeState:"clean", BuildDate:"2021-12-16T08:38:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:19:12Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

I'm trying to complete the installation on a local machine using minikube and docker. I'm following these steps:
https://fission.io/docs/usage/languages/python/

The installation ends ok. I'm able to create a new function and also create a new HTTP trigger but I'm unable to actually reach the HTTP trigger.
Running:
curl $FISSION_ROUTER/hello
Ends with:
curl: (28) Failed to connect to 192.168.49.2 port 31314: Operation timed out

I'm able to run 'fission function test' successfully and create as many functions as needed.

kubectl get pods -n fission:
NAME                                READY   STATUS      RESTARTS   AGE
buildermgr-774879664b-ljcjh         1/1     Running     0          30h
controller-6d455d7b75-twbjg         1/1     Running     0          30h
executor-577ff745f-jb7m5            1/1     Running     0          30h
fission-fission-all-v1.15.1-tzxst   0/1     Completed   0          30h
kubewatcher-5dc7f4ccb5-2dhrw        1/1     Running     0          30h
mqtrigger-keda-79c5b694c7-l8pz5     1/1     Running     0          30h
router-579cb5c588-wgll7             1/1     Running     0          30h
storagesvc-c5f6d46f-492vh           1/1     Running     0          30h
timer-d98c67879-dsggw               1/1     Running     0          30h

**To Reproduce**
fission environment create --name python --image fission/python-env
fission function create --name hello --env python --code hello.py 
fission function test --name hello
fission route create --method GET --url /hello --function hello 
export FISSION_ROUTER=$(minikube ip):$(kubectl -n fission get svc router -o jsonpath='{...nodePort}')
curl $FISSION_ROUTER/hello

**Expected result**

Succesful HTTP response.
**Actual result**
HTTP timeout.
**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>
[fission-dump_1646237645.zip](https://github.com/fission/fission/files/8171142/fission-dump_1646237645.zip)

**Additional context**

**Comment by techmaharaj** [comment]
Hi, 
I tried the same code and it worked fine. I checked the logs that you have shared and found the `path` to be different for the trigger. Can you verify the path for the trigger again? As per the logs I see that the trigger path is `/hellod` and not `/hello` and hence you might be getting this error.

![image](https://user-images.githubusercontent.com/10296271/156411758-373d1681-2322-4a68-ae9d-b8e19b18c8e8.png)

**Comment by emmmplayer** [comment]
Hi,

I apologize for the mistake. I have actually tried connecting to hellod.
I have just tried to create a new function/trigger with the same results.
I hope you will find the info in the new dump file.

Thank you,
D.
[fission-dump_1646245043.zip](https://github.com/fission/fission/files/8171938/fission-dump_1646245043.zip)

**Comment by emmmplayer** [comment]
I'm not sure if it is clear from the logs, but I'm running on a Mac.

**Comment by sanketsudake** [comment]
Hi @emmmplayer , 

There could issues in in terms firewall or port forwarding from minikube to fission router.

Since fission fn test is working. Could you try port forwarding and then try to hit URL ?

```
# Do port forward with kubectl to router service
kubectl port-forward svc/router -n fission 8080:80
# Note you can have any port instead of 8080

# Do a request with curl
curl  localhost:8080/hello
```

**Comment by emmmplayer** [comment]
Hi and thank you for your reply,

That works and localhost responded well.
Any idea what to do next?

Thanks,
D.

**Comment by sanketsudake** [comment]
Hi @emmmplayer  You can probably try telnet over router IP and port and see if you are able to establish connection.
If not might be some issue in connectivity. 
 MacOS doesn't do port forwarding I think there are some special setting need to be done to forward traffic from OS to minikube exposed IP.

**Comment by KiraSkate** [comment]
@sanketsudake Can you tell me what to do next? I can only succeed when using port-forward. Other times I use "curl $FISSION_ROUTER/hello" and it fails. This has troubled me for several days.
