### ISSUE TITLE
fission fn test -b '{"works": false}'

### ISSUE THREAD

**Issue by edokan** [fission/fission#2406]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"b631974d68ac5045e076c86a5c66fba6f128dc72", GitTreeState:"clean", BuildDate:"2022-01-19T17:51:12Z", GoVersion:"go1.16.12", Compiler:"gc", Platform
:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:14Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:
"linux/amd64"}

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker Desktop on Windows 11

**Describe the bug**
When I create a function and try to test it using CLI with a post body via `-b`, post-data is not sent. I create an httptrigger with POST method and try again with the CLI, fails again. A sample request with cUrl works. 

**To Reproduce**
create a hello world function with the following file

`fission fn create --env nodejs --code hello --name post-hello`

```js
module.exports = async function(context) {
    return {
        status: 200,
        body: "output is: " + JSON.stringify(context.request.body)
    };
}
```

and try to test it

`fission fn test --name post-hello -b '{"message": "hello there"}'`

I tried with `--method POST` too.

**Expected result**

Expected to access post body in the function code

**Actual result**
Output is `output is: `

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by blackfly19** [comment]
Hi @edokan . You need to mention `Content-Type` as well.
eg.
```
fission fn test --name consumer --body='{"message":"hello there"}' --method=POST -H Content-Type:application/json
```

**Comment by sanketsudake** [comment]
Hey @edokan Please tryout passing content type as suggested by @blackfly19 .

Closing this issue, feel free reopen if you are still facing issue.
