### ISSUE TITLE
Labels aren't applied to k8 resource when using --labels flag on fission env create --spec 

### ISSUE THREAD

**Issue by khamonsol** [fission/fission#2418]
**Fission/Kubernetes version**

<pre>
client:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1
server:
  fission/core:
    BuildDate: "2021-12-29T03:57:30Z"
    GitCommit: 327275d1
    Version: v1.15.1

Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:10:45Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+k3s1", GitCommit:"61a2aab25eeb97c26fa3f2b177e4355a7654c991", GitTreeState:"clean", BuildDate:"2021-11-04T00:24:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**
When create an env using fission spec apply, labels aren't applied to the kube resource. 

**To Reproduce**
fission env create --spec --labels='logicmon=no' --name ${APP_NAME}-${ENV} --image fission/go-env-1.17 --builder fission/go-builder-1.17 --envns $NS

**Expected result**
kubectl describe <env-resource> should result in a resource with the label logicmon=no

**Actual result**
No label is applied. 

**Additional context**
The label is added to other k8 resources built with the spec apply feature, the env is the only place I have found this to fail.

When manually inspecting the generated env yaml file, the label is present in the yaml. It seems the generator is working, but the spec apply routine does not respect the metadata:labels block when creating an environment.

**Comment by blackfly19** [comment]
Hi @khamonsol . I followed the exact steps(using `fission spec`) mentioned by you but I am able to see the labels in the env CR.
```
apiVersion: v1
items:
- apiVersion: fission.io/v1
  kind: Environment
  metadata:
    creationTimestamp: "2022-06-30T06:14:49Z"
    generation: 1
    labels:
      logicmon: "no"
    name: goenv
    namespace: testns
    resourceVersion: "697707"
    uid: 0682647d-4f8b-4b9d-b397-f375aefb918a
  spec:
    builder:
      command: build
      container:
        name: ""
        resources: {}
      image: fission/go-builder-1.17
    imagepullsecret: ""
    keeparchive: false
    poolsize: 3
    resources: {}
    runtime:
      container:
        name: ""
        resources: {}
      image: fission/go-env-1.17
    version: 2
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```
Can you please update fission to the latest version and then try again?

**Comment by sanketsudake** [comment]
Hey @khamonsol Closing issue as no response. Kindly try out steps suggested by @blackfly19 .

Feel free to reopen if you are able to reproduce issue.
