### ISSUE TITLE
function build failed with local paths or url

### ISSUE THREAD

**Issue by AetheWu** [fission/fission#2425]
**Fission/Kubernetes version**

<pre>
$ fission --version
$ kubectl version
</pre>
fission version: v1.16.0-rc1
kubectl version: v1.22.5

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

A golang function was built failed with the correct zip file, but could be built successfully with the single file

**To Reproduce**

1. create a go env: `fission env create --name go --image fission/go-env-1.16 --builder fission/go-builder-1.16`
2. create a go functon with the zip file: `fission fn create --name go --env go --src hello.zip --entrypoint Handler`
3. test the function

**Expected result**

a golang function can be created and run successfully with the zip file.

**Actual result**
run failed.

**Screenshots/Dump file**

=== Build Logs ===command=build
env=[PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin HOSTNAME=go-12356954-5749d9965c-b8gxd GOLANG_VERSION=1.16.9 GOPATH=/usr GO111MODULE=on KUBERNETES_PORT_443_TCP=tcp://10.43.0.1:443 KUBERNETES_PORT_443_TCP_PORT=443 GO_12356954_PORT=tcp://10.43.246.135:8000 GO_12356954_PORT_8000_TCP_PORT=8000 GO_12356954_PORT_8001_TCP=tcp://10.43.246.135:8001 GO_12356954_PORT_8001_TCP_PROTO=tcp GO_12356954_SERVICE_PORT=8000 GO_12356954_PORT_8001_TCP_ADDR=10.43.246.135 KUBERNETES_SERVICE_PORT_HTTPS=443 KUBERNETES_PORT=tcp://10.43.0.1:443 KUBERNETES_PORT_443_TCP_PROTO=tcp GO_12356954_SERVICE_PORT_FETCHER_PORT=8000 GO_12356954_PORT_8000_TCP=tcp://10.43.246.135:8000 GO_12356954_PORT_8000_TCP_PROTO=tcp GO_12356954_PORT_8000_TCP_ADDR=10.43.246.135 KUBERNETES_SERVICE_HOST=10.43.0.1 KUBERNETES_SERVICE_PORT=443 KUBERNETES_PORT_443_TCP_ADDR=10.43.0.1 GO_12356954_SERVICE_HOST=10.43.246.135 GO_12356954_SERVICE_PORT_BUILDER_PORT=8001 GO_12356954_PORT_8001_TCP_PORT=8001 HOME=/root SRC_PKG=/packages/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre DEPLOY_PKG=/packages/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre-hjvi6d]
{"level":"info","ts":"2022-05-06T12:43:58.792Z","logger":"builder","caller":"builder/builder.go:116","msg":"builder received request","request":{"srcPkgFilename":"test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre","command":"build"}}
{"level":"info","ts":"2022-05-06T12:43:58.792Z","logger":"builder","caller":"builder/builder.go:118","msg":"starting build"}
Building in directory /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
++ basename /packages/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
+ srcDir=/usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
+ trap 'rm -rf /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre' EXIT
+ '[' -d /packages/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre ']'
+ echo 'Building in directory /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre'
+ ln -sf /packages/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
+ cd /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
+ '[' '!' -z 1.16.9 ']'
+ version_ge 1.16.9 1.12
++ tr ' ' '\n'
++ sort -rV
++ head -n 1
++ echo 1.16.9 1.12
{"level":"error","ts":"2022-05-06T12:43:58.815Z","logger":"builder","caller":"builder/builder.go:130","msg":"error building source package","error":"error waiting for cmd \"build\": exit status 1","errorVerbose":"exit status 1\nerror waiting for cmd \"build\"\ngithub.com/fission/fission/pkg/builder.(*Builder).build\n\t/go/src/github.com/fission/fission/pkg/builder/builder.go:226\ngithub.com/fission/fission/pkg/builder.(*Builder).Handler\n\t/go/src/github.com/fission/fission/pkg/builder/builder.go:127\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2417\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374","stacktrace":"github.com/fission/fission/pkg/builder.(*Builder).Handler\n\t/go/src/github.com/fission/fission/pkg/builder/builder.go:130\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2042\nnet/http.(*ServeMux).ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2417\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2843\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1925"}
{"level":"info","ts":"2022-05-06T12:43:58.816Z","logger":"builder","caller":"builder/builder.go:97","msg":"build request complete","elapsed_time":0.023919527}
+ test 1.16.9 == 1.16.9
+ '[' -f go.mod ']'
+ go mod download
+ GOFLAGS=-buildmode=plugin
+ '[' -d vendor ']'
+ version_ge 1.16.9 1.15
++ echo 1.16.9 1.15
++ tr ' ' '\n'
++ sort -rV
++ head -n 1
+ test 1.16.9 == 1.16.9
+ go build -buildmode=plugin -o /packages/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre-hjvi6d .
no Go files in /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
+ rm -rf /usr/src/test1-e159eb07-7c08-4601-9ac8-543d1e77d732-riobre
error waiting for cmd "build": exit status 1

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by AetheWu** [comment]
By the way, the node function can be created successfully with the zip src. So, what's the correct step to create a go  function with dependencies?

**Comment by AetheWu** [comment]
It's urgent and I need your help plzzzz

**Comment by AetheWu** [comment]
What I can guarantee is that there is no problem with the go code and all steps are based on the tutorial. So confused I am.

**Comment by blackfly19** [comment]
Hi @AetheWu. Did you include the go.mod and the go.sum file in the zip?

**Comment by AetheWu** [comment]
> Hi @AetheWu. Did you include the go.mod and the go.sum file in the zip?

@blackfly19 yes, i did.

**Comment by blackfly19** [comment]
Hi @AetheWu . Can you please specify which tutorial were you following when this error occurred?

**Comment by blackfly19** [comment]
Hi @AetheWu. I didn't get any response from your side so I am assuming you fixed the issue. If you still have any problems, feel free to reopen the issue.
