### ISSUE TITLE
NodeJS web framework compatibility

### ISSUE THREAD

**Issue by dkolba** [fission/fission#243]
The http context of a node.js function invocation is constructed via express: https://github.com/fission/fission/blob/master/environments/nodejs/server.js#L79

How would one use a different node.js web framework, like hapi.js or restify, within the function?

**Comment by yqf3139** [comment]
Modify the server.js file and use the web framework you like. 
Then follow the [instructions here](https://github.com/fission/fission/tree/master/environments/nodejs) to rebuild the nodejs image. 
Glad to see nodejs environment image using other frameworks contributed to fission.

**Comment by soamvasani** [comment]
@dkolba yes, you can create a new fission environment, and add it to your fission cluster using `fission env create`.  You can use the existing nodejs environment as a starting point.  Free free to join the slack channel http://slack.fission.io if you have further questions!
