### ISSUE TITLE
Python custom functions not getting called in fission logs error 502 bad gateway

### ISSUE THREAD

**Issue by Shahnawaz-1** [fission/fission#2431]
### Discussed in https://github.com/fission/fission/discussions/2430

<div type='discussions-op-text'>

<sup>Originally posted by **Shahnawaz-1** May 18, 2022</sup>
I have installed fission and created 
1 .Package 
2.  Env
3. function hello world
4. tested and running fine

But
When i tried to run custom functions like finding a max number.

```. def max_of_two( x, y ):
    if x > y:
        return x
    return  #y
def max_of_three( x, y, z ):
    return max_of_two( x, max_of_two( y, z ) )
print(max_of_three(3, 6, -5))  
```

 it gives a error 

``` Error querying logs: Internal error - 502 Bad  @Gateway%```

Also when i try to check logs the same error reflecting

@vishal-biyani 
@sanketsudake 
@fission
@fission.io</div>
@kubernetes
@cncf
@awslambda

**Comment by sanketsudake** [comment]
Closing as duplicate.
