### ISSUE TITLE
Python v2 environment

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#245]
This issue will track modifying the python environment for v2. It'll be our first supported language on v2 envs.

Steps to work on this:
 - [ ] Modify runtime to support package loading and v2 interface
 - [ ] Create a builder image that can transform a source package to a deployment package
 - [ ] Test scripts to test environments in docker easily, without running them in fission
 - [ ] Examples
 - [ ] Documentation for programmers   

For the runtime, the main change is the need to support loading a package instead of just one file.

The new interface is documented here:
https://github.com/fission/fission/blob/master/Documentation/wip/env-api.md

And the types are here (see `FunctionLoadRequest`):
https://github.com/fission/fission/blob/controller-tpr-compatible-types/types.go

**Comment by Disturbing** [comment]
Hey @soamvasani 

Have you guys thought / discuss doing the load request information in the metadata / headers of the request itself?

When the router forwards a request to the server and *if* the router knows the server does not have warm loaded function, it can add the request in the header of the actual call versus doing a separate function load request.

Correct me if I'm wrong, but after reading this is what I'm imagining is going on:

1) Client hits router /hello
2) Router asks warm container - load /hello for me please.
3) warm container responds success
4) Router forwards /hello to warm container
5) warm container responds to hello.

-- My proposition if the above is correct --

1) Client hits router /hello
2) Router forwards /hello to warm container with added headers for loading function
3) warm container reads headers and loads function
4) warm container responds to /hello

This may save a few ms in RTT.

**Comment by soamvasani** [comment]
@Disturbing let's move this discussion to #253, since it's not python specific.
