### ISSUE TITLE
Idempotent commands

### ISSUE THREAD

**Issue by rochdev** [fission/fission#246]
Right now most fission commands have a `create` and `update` subcommands but there is no equivalent idempotent subcommand.

`kubectl` has the `apply`command and I think it would make sense to add the same functionality as `fission <command> apply`.

The use case would be when you don't know if a function already exists on the cluster, for example when using automation and continuous delivery.

**Comment by soamvasani** [comment]
While we don't have `fission apply` just yet, we do have `kubectl apply` since we switched to using kubernetes resources for our state.

**Comment by life1347** [comment]
Close this since we have `fission spec apply` now
