### ISSUE TITLE
Watch fission CRs in specific namespaces. 

### ISSUE THREAD

**Issue by pintonunes** [fission/fission#2469]
Hello,

Its possible to filter which namespaces fission will watch for functions, packages and so on?

Quick look at the code and seems is watching all namespaces without any configurable flag. 
https://github.com/fission/fission/blob/613062549d3ef0fffa524e95e981bb32a0105518/pkg/executor/executor.go#L287-L290

Am I missing something?

**Comment by sanketsudake** [comment]
This should be possible, provided we define configuration to be passed via helm chart.

**Comment by pintonunes** [comment]
Can you give an example? Which value should be passed to helm to ensure fission will onlt watch CRs on namespace X?

**Comment by sanketsudake** [comment]
@pintonunes we would enhancements in Fission source for it. Not possible as of now.

**Comment by nunojca** [comment]
@sanketsudake any plans to solve this? For us this can be a security issue as someone can create a Fission CRDs on any namespace and it will be processed.

**Comment by sanketsudake** [comment]
Few changes are work in progress on this issue https://github.com/fission/fission/pull/2539

**Comment by shubham-bansal96** [comment]
@pintonunes 
We have made changes for the issue in #2539. These changes will be a part of 1.18 release.
