### ISSUE TITLE
Python function with dependencies - Example KO

### ISSUE THREAD

**Issue by voldor** [fission/fission#2473]
hello, i'm following the tutorial to create and execute a Python function with depedencies from here : https://fission.io/docs/usage/languages/python/

im doing the following (create all the files with the right permissions)

fission package create --sourcearchive demo-src-pkg.zip --env python --buildcmd "./build.sh"
_Package 'demo-src-pkg-zip-myth' created_
fission pkg info –-name pkg demo-src-pkg-zip-myth
fission fn create --name srcpy --pkg demo-src-pkg-zip-myth --entrypoint "user.main"
fission fn test --name srcpy

But unfortunately it returns the following error:

_←[31mError←[0m: Error calling function srcpy: 500; Please try again or fix the error: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>

←[31mError←[0m: Error getting function logs from controller: error getting logs from controller, status code: '500'. Try to get logs from log database.
Error querying logs: Internal error - 502 Bad Gateway_

I do not have any clue about how to debug this.
Someone could help me ?

**Comment by voldor** [comment]
Hello to work around this issue i had to return an answer with flask like :
resp = flask.Response('Hello World')
resp.status_code = 200



Otherwise it is not working but

**Comment by shubham-bansal96** [comment]
@voldor 
Please share your code in zip folder for which you are getting an error.

cc: @sanketsudake

**Comment by shubham-bansal96** [comment]
Feel free to reopen this issue, if you are able to reproduce this again.
