### ISSUE TITLE
arm64 version of fission cli can not connect to the server

### ISSUE THREAD

**Issue by nmiletic** [fission/fission#2481]
**Fission/Kubernetes version**

Fission version 1.16.0
Kubernetes version v1.24.1

<pre>
$ fission --version
Unable to get because it times out

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/arm64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker Kubernetes

**Describe the bug**
Issue happens on MacBook Pro M1. 

arm64 version of fission CLI can not connect to the API server. It always returns time out. 
when using amd64 version on the same machine (MacBook Pro m1) it works just fine. 

**To Reproduce**

curl -Lo fission https://github.com/fission/fission/releases/download/v1.16.0/fission-v1.16.0-darwin-arm64 \                                                                                           && chmod +x fission

./fission environment list --verbosity=2                                                                                                                                                                
Setting up port forward to application=fission-api in namespace
Waiting for local port 61661
Starting port forward from local port 61661
Using kubeconfig from "/Users/nmiletic/.kube/config"
Connected to Kubernetes API
Connecting to port 8888 on pod fission/controller-cf8bf9bf7-jblmv
Starting port forwarder
Forwarding from 127.0.0.1:61661 -> 8888
Forwarding from [::1]:61661 -> 8888
Waiting for port forward 61661 to start...
Handling connection for 61661
Error dialing on local port 61661: dial tcp :61661: i/o timeout
Handling connection for 61661
Error dialing on local port 61661: dial tcp :61661: i/o timeout
Handling connection for 61661
Error dialing on local port 61661: dial tcp :61661: i/o timeout
Handling connection for 61661
...

**Additional context**

amd64 version works just fine

**Comment by sanketsudake** [comment]
This could be related to https://github.com/fission/fission/issues/2462
Please check PR https://github.com/fission/fission/pull/2468

**Comment by sanketsudake** [comment]
Hi @nmiletic , would it be possible for you to try out CLI from latest source ?
PR #2468 should probably resolve the issue.

cc @shubham-bansal96

**Comment by nmiletic** [comment]
Hi @sanketsudake , I've built fission-cli from master for arm64 and it works fine. Thank you

**Comment by sanketsudake** [comment]
Cool. Kindly tryout 1.17-rc2/1.17 version its released.
Closing this issue for now, feel free to reopen if you still face issue after release.
