### ISSUE TITLE
python builder fills /packages mount causing low disk space on a node

### ISSUE THREAD

**Issue by nmiletic** [fission/fission#2487]
**Fission/Kubernetes version**

<pre>
$ fission --version
client:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
server:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:26:19Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.1", GitCommit:"3ddd0f45aa91e2f30c70734b175631bec5b5825a", GitTreeState:"clean", BuildDate:"2022-05-24T12:18:48Z", GoVersion:"go1.18.2", Compiler:"gc", Platform:"linux/arm64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker Desktop Kubernetes

**Describe the bug**
Python builder pod does not clean up old builds in /packages mount leading to filling the disk space on the node. 

**To Reproduce**
Deploy many versions of the same function. 
fission spec apply

**Expected result**
Old packages should be removed from /packages mount point once the new version of the function is built. 

**Actual result**

**Screenshots/Dump file**
<pre>
root@python-21308-5567d99646-pktxv:/packages# ls -l
total 111668
drwxr-xr-x 4 root root    4096 Jul 12 16:34 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-8okz86
drwxr-xr-x 4 root root    4096 Jul 12 16:34 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-8okz86-ggnbon
-rw-r--r-- 1 root root 3156154 Jul 12 16:34 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-8okz86-ggnbon.zip
-rw------- 1 root root     803 Jul 12 16:34 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-8okz86.tmp
drwxr-xr-x 4 root root    4096 Jul 13 09:21 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-94z0kj
drwxr-xr-x 4 root root    4096 Jul 13 09:22 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-94z0kj-c3kcpc
-rw-r--r-- 1 root root       0 Jul 13 09:22 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-94z0kj-c3kcpc.zip
-rw------- 1 root root     882 Jul 13 09:21 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-94z0kj.tmp
drwxr-xr-x 4 root root    4096 Jul 12 14:17 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-agjeyw
drwxr-xr-x 4 root root    4096 Jul 12 14:17 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-agjeyw-shir3s
-rw-r--r-- 1 root root       0 Jul 12 14:17 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-agjeyw-shir3s.zip
-rw------- 1 root root     738 Jul 12 14:17 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-agjeyw.tmp
drwxr-xr-x 4 root root    4096 Jul 13 09:39 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-apo9yj
drwxr-xr-x 4 root root    4096 Jul 13 09:39 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-apo9yj-qffodh
-rw-r--r-- 1 root root       0 Jul 13 09:39 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-apo9yj-qffodh.zip
-rw------- 1 root root     878 Jul 13 09:39 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-apo9yj.tmp
drwxr-xr-x 4 root root    4096 Jul 13 08:15 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-cxyimo
drwxr-xr-x 4 root root    4096 Jul 13 08:15 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-cxyimo-vztfzp
-rw-r--r-- 1 root root 3156218 Jul 13 08:15 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-cxyimo-vztfzp.zip
-rw------- 1 root root     841 Jul 13 08:15 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-cxyimo.tmp
drwxr-xr-x 4 root root    4096 Jul 12 14:19 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-etl0hh
drwxr-xr-x 4 root root    4096 Jul 12 14:19 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-etl0hh-7dqc0y
-rw-r--r-- 1 root root       0 Jul 12 14:19 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-etl0hh-7dqc0y.zip
-rw------- 1 root root     708 Jul 12 14:19 calc-eval-321124eb-8c8d-4aa6-9bf1-ca466d46bac2-etl0hh.tmp
...
</pre>

<pre>
$ fission support dump

</pre>

**Comment by soharab-ic** [comment]
Fixed in PR https://github.com/fission/fission/pull/2979.
Please use latest python environment and builder images.
