### ISSUE TITLE
Default value for Buildstatus of Package resource is ambiguous

### ISSUE THREAD

**Issue by WoWsj** [fission/fission#2488]
**Describe the bug**

I developed an operator with Fission, and I found that

- default value of `BuildStatus` for Package is `Pending`
https://github.com/fission/fission/blob/9cedeb4fa6dd6fd77a115e61546414b7367ad53e/crds/v1/fission.io_packages.yaml#L124-L127
- but, pkgwatcher uses `pending` for build trigger  
https://github.com/fission/fission/blob/9cedeb4fa6dd6fd77a115e61546414b7367ad53e/pkg/apis/core/v1/const.go#L47

There is no issue if you created a package resource with Fission CLI. However, if you create a package resource without CLI, package will be stuck in `Pending` status.

**To Reproduce**

In a situation where the upstream CRD is applied, create a package without specifying the status.

**Expected result**

Package resources will build deployment archives when resources created.

**Actual result**

Package resources will be stuck in `BuildStatus` `Pending`

---

I'm not sure if this issue is intended or a bug. However, if it is intended, I don't think it is an appropriate pattern to distinguish whether or not the spelling is capitalized.

Thanks! 😄

**Comment by shubham-bansal96** [comment]
@WoWsj 
Thanks for notifying us, you are right the value for BuildStatus is ambiguous. 

But after looking into code, i just want to know that are you trying to skip the validation part. I mean we have implemented a validation in our code that if there is ambiguous value then user will get error message as "PackageStatus.BuildStatus Pending not a valid build status" .

**Comment by WoWsj** [comment]
Thank you for your quick response! @shubham-bansal96 

> i just want to know that are you trying to skip the validation part.
No, I didn't do anything for skipping the validation part. I just apply a YAML manifest using `kubectl`.
