### ISSUE TITLE
fission package rebuild error

### ISSUE THREAD

**Issue by sjk7524068** [fission/fission#2490]
by following YAML Tutorial, when I GET to the step "Apply: deploy your functions to Fission", I got a package build error and I had to do a rebuild, but still I can not finish the job:

here comes the rebuild error message:

`Error uploading deployment package: Internal error - error archiving zip file: file already exists: /packages/calc-eval-d442ca4b-175f-4ea3-9b7f-a2c3e6875c4f-z0uwbn-hlnlb1.zip
`

I want to know why and how to fix this

**Comment by Yanghaihai1020** [comment]
I also had the same problem, do you know how to fix this?

**Comment by Yanghaihai1020** [comment]
I also had the same problem, do you know how to fix this?

**Comment by hklang10** [comment]
I got this error when my pod/storagesvc was not running.

**Comment by saltbo** [comment]
why close? Got the same problem too...

**Comment by haladynkamil** [comment]
Same problem, why is it closed?

**Comment by bigbird-0101** [comment]
hello,brother, i get it   1.18 up fix
this is 1.18 code  pkgwather.go
we can see pkgw.buildWithCache(ctx, pkg) ,when building package, sync build cache ,but 1.17 all  is go route and in go route build cache .
however,when buildmgr have some node, error still occur. because it is not distributed Lock,so buildmgr best one node
`
func (pkgw *packageWatcher) packageInformerHandler(ctx context.Context) k8sCache.ResourceEventHandlerFuncs {
	processPkg := func(ctx context.Context, pkg *fv1.Package) {
		var err error
		if len(pkg.Status.BuildStatus) == 0 {
			_, err = setInitialBuildStatus(ctx, pkgw.fissionClient, pkg)
			if err != nil {
				pkgw.logger.Error("error filling package status", zap.Error(err))
			}
			// once we update the package status, an update event
			// will arrive and handle by UpdateFunc later. So we
			// don't need to build the package at this moment.
			return
		}
		// Only build pending state packages.
		if pkg.Status.BuildStatus == fv1.BuildStatusPending {
			pkgw.buildWithCache(ctx, pkg)
		}
	}
	return k8sCache.ResourceEventHandlerFuncs{
		AddFunc: func(obj interface{}) {
			pkg := obj.(*fv1.Package)
			processPkg(ctx, pkg)
		},
		UpdateFunc: func(oldObj, newObj interface{}) {
			oldPkg := oldObj.(*fv1.Package)
			pkg := newObj.(*fv1.Package)

			// TODO: Once enable "/status", check generation for spec changed instead.
			//   Before "/status" is enabled, the generation and resource version will be changed
			//   if we update the status of a package, hence we are not able to differentiate
			//   the spec change or status change. So we only build package which has status
			//   us "pending" and user have to use "kubectl replace" to update a package.
			if oldPkg.ResourceVersion == pkg.ResourceVersion &&
				pkg.Status.BuildStatus != fv1.BuildStatusPending {
				return
			}
			processPkg(ctx, pkg)
		},
	}
}
`
