### ISSUE TITLE
Context Deadline Exceeded Error While Running the Sample Hello World

### ISSUE THREAD

**Issue by skywalker2022** [fission/fission#2493]
Hello,

I have installed a Kubernetes cluster one master and two worker nodes by Magnum on OpenStack and then installed Fission on it. I simply followed the official document:
https://fission.io/docs/installation/
Installed with Helm and Basic with LoadBalancer option. No error appeared during the installation, but when I tried to test the sample hello world (any language) I received the following error:

#fission function test --name hello-go --verbosity=2

Error: error executing HTTP request: Get "http://127.0.0.1:34712/fission-function/hello-go": context deadline exceeded

All instances and load balancers in OpenStack are in healthy status.

#fission version
client:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
server:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0

#kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}

#kubectl get pod,svc -n fission
NAME                                  READY   STATUS    RESTARTS   AGE
pod/buildermgr-648dc8bc4-qd8pn        1/1     Running   0          3d2h
pod/controller-5b9d8f7c76-rnxz6       1/1     Running   0          3d2h
pod/executor-7bf4f9d9c9-dqmfr         1/1     Running   0          3d2h
pod/kubewatcher-8688df66c5-qdjfv      1/1     Running   0          3d2h
pod/mqtrigger-keda-5b8749f5bb-smq5c   1/1     Running   0          3d2h
pod/router-77966569c4-lrrqx           1/1     Running   0          3d2h
pod/storagesvc-78fd7f867b-9skcf       1/1     Running   0          3d2h
pod/timer-5dd7d7fb69-lsfmx            1/1     Running   0          3d2h

NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)        AGE
service/controller   ClusterIP      10.254.35.4      <none>         80/TCP         3d2h
service/executor     ClusterIP      10.254.27.181    <none>         80/TCP         3d2h
service/router       LoadBalancer   10.254.179.100   45.XX.XX.XX   80:30791/TCP   3d2h
service/storagesvc   ClusterIP      10.254.15.111    <none>         80/TCP         3d2h

#fission function list
NAME      ENV    EXECUTORTYPE MINSCALE MAXSCALE MINCPU MAXCPU MINMEMORY MAXMEMORY SECRETS CONFIGMAPS
hello-go  go     poolmgr      0        0        0      0      0         0
hello-js  nodejs poolmgr      0        0        0      0      0         0
hello-js2 nodejs poolmgr      0        0        0      0      0         0
hello-js3 nodejs poolmgr      0        0        0      0      0         0
hello-py  python poolmgr      0        0        0      0      0         0

Log from the router pod:
#kubectl logs router-77966569c4-lrrqx -n fission

[ERR] POST http://executor.fission/v2/getServiceForFunction request failed: Post "http://executor.fission/v2/getServiceForFunction": context canceled
{"level":"error","ts":"2022-07-25T18:28:03.187Z","logger":"triggerset.http_trigger_set.hello-py","caller":"router/functionHandler.go:700","msg":"error from GetServiceForFunction","trace_id":"95d2b4faf9f6411ddb8c67cf7cbc2c92","error":"error posting to getting service for function: POST http://executor.fission/v2/getServiceForFunction

There is not name resolution possible inside the router:
#kubectl -n fission exec -it router-77966569c4-lrrqx – sh

#nslookup executor.fission
Server:		10.254.0.10
Address:	10.254.0.10:53

** server can't find executor.fission: NXDOMAIN

** server can't find executor.fission: NXDOMAIN

**Comment by shubham-bansal96** [comment]
@skywalker2022 

This is a known issue and we have already made code changes for the same under this PR https://github.com/fission/fission/pull/2468
This issue will get fix in upcoming releases.

**Comment by skywalker2022** [comment]
[fission-dump_1658772133.zip](https://github.com/fission/fission/files/9187677/fission-dump_1658772133.zip)

**Comment by skywalker2022** [comment]
I deleted the Kubernetes cluster, created another one, and installed Fission again.

#kubectl get all -n fission

NAME                                  READY   STATUS    RESTARTS   AGE
pod/buildermgr-648dc8bc4-jb2ws        1/1     Running   0          4m6s
pod/controller-5b9d8f7c76-zzrvm       1/1     Running   0          4m6s
pod/executor-7bf4f9d9c9-c2j7c         1/1     Running   0          4m5s
pod/kubewatcher-8688df66c5-vjj2d      1/1     Running   0          4m6s
pod/mqtrigger-keda-5b8749f5bb-jd2fr   1/1     Running   0          4m6s
pod/router-77966569c4-krjvh           1/1     Running   0          4m6s
pod/storagesvc-78fd7f867b-q9xlv       1/1     Running   0          4m5s
pod/timer-5dd7d7fb69-mdmsf            1/1     Running   0          4m6s

NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)        AGE
service/controller   ClusterIP      10.254.118.129   <none>         80/TCP         4m6s
service/executor     ClusterIP      10.254.184.225   <none>         80/TCP         4m6s
service/router       LoadBalancer   10.254.129.142   45.88.81.157   80:32628/TCP   4m6s
service/storagesvc   ClusterIP      10.254.163.74    <none>         80/TCP         4m6s

NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/buildermgr       1/1     1            1           4m6s
deployment.apps/controller       1/1     1            1           4m6s
deployment.apps/executor         1/1     1            1           4m6s
deployment.apps/kubewatcher      1/1     1            1           4m6s
deployment.apps/mqtrigger-keda   1/1     1            1           4m6s
deployment.apps/router           1/1     1            1           4m6s
deployment.apps/storagesvc       1/1     1            1           4m6s
deployment.apps/timer            1/1     1            1           4m6s

NAME                                        DESIRED   CURRENT   READY   AGE
replicaset.apps/buildermgr-648dc8bc4        1         1         1       4m6s
replicaset.apps/controller-5b9d8f7c76       1         1         1       4m6s
replicaset.apps/executor-7bf4f9d9c9         1         1         1       4m5s
replicaset.apps/kubewatcher-8688df66c5      1         1         1       4m6s
replicaset.apps/mqtrigger-keda-5b8749f5bb   1         1         1       4m6s
replicaset.apps/router-77966569c4           1         1         1       4m6s
replicaset.apps/storagesvc-78fd7f867b       1         1         1       4m6s
replicaset.apps/timer-5dd7d7fb69            1         1         1       4m6s

As you can see 45.88.81.157 is the cluster load balancer IP address.
Then I tried to create env and function by --server option, but every time I received the error not found message:

fission function create --name hello-py --env python --code hello.py --server='http://45.88.81.157'
Error: error creating package: error creating package: Resource not found - 404 page not found

Finally I decided to just run the test command with --server option:
fission function test --name hello-py --server='http://45.88.81.157' --verbosity 2

But it still tries to conncet to 127.0.0.1

# fission function test --name hello-py --server='http://45.88.81.157' --verbosity 2
Setting up port forward to application=fission-router in namespace fission
Waiting for local port 40614
Starting port forward from local port 40614
Using kubeconfig from environment "/root/fission/config"
Connected to Kubernetes API
Connecting to port 8888 on pod fission/router-77966569c4-krjvh
Starting port forwarder
Forwarding from 127.0.0.1:40614 -> 8888
Waiting for port forward 40614 to start...
Port forward from local port 40614 started
Function test url: http://127.0.0.1:40614/fission-function/hello-py
Handling connection for 40614
GET /fission-function/hello-py HTTP/1.1
Host: 127.0.0.1:40614
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip

Handling connection for 40614


Error: error executing HTTP request: Get "http://127.0.0.1:40614/fission-function/hello-py": context deadline exceeded

Do you have any idea how I can set the loadbalancer IP address instead of 127.0.0.1 ?

**Comment by skywalker2022** [comment]
#kubectl logs pod/executor-5d48cd87b8-9qptx

{"level":"error","ts":"2022-07-28T13:59:02.979Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:495","msg":"failed to relabel pod","trace_id":"546df01620d5319c3ce1d6ed6a96a770","error":"pods \"poolmgr-nodejs-default-228049-6f4fffb695-wdkx7\" is forbidden: PodSecurityPolicy: unable to validate pod: []","pod":"poolmgr-nodejs-default-228049-6f4fffb695-wdkx7"

#kubectl get psp
NAME                PRIV   CAPS   SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
magnum.privileged   true   *      RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            *

Any idea?

**Comment by weisttl** [comment]
+1

**Comment by pfb93** [comment]
+1

**Comment by shubham-bansal96** [comment]
@skywalker2022 @weisttl 
Are you still facing this issue with fission v1.18.0 ?

**Comment by skywalker2022** [comment]
> @skywalker2022 @weisttl Are you still facing this issue with fission v1.18.0 ?

I stopped using fission anymore. I had lots of problems with it.

**Comment by skywalker2022** [comment]
> Hi @skywalker2022 , would you please tell us what framework you are using now, knative?

Although my project is now completed and finished, I tried both knative and openfaas and both are great!

**Comment by BTYHunter** [comment]
thanks

> > Hi @skywalker2022 , would you please tell us what framework you are using now, knative?
> 
> Although my project is now completed and finished, I tried both knative and openfaas and both are great!

thanks

**Comment by BTYHunter** [comment]
> > Hi @skywalker2022 , would you please tell us what framework you are using now, knative?
> 
> Although my project is now completed and finished, I tried both knative and openfaas and both are great!

thanks

**Comment by soharab-ic** [comment]
Please try the latest fission version `v1.20.5` and re-open if issue remains.
