### ISSUE TITLE
Can't create 2 httptriggers with prefix url

### ISSUE THREAD

**Issue by Tri0L** [fission/fission#2520]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2022-07-06T09:35:52Z"
    GitCommit: 770c19a2
    Version: v1.17.0-rc1
server:
  fission/core:
    BuildDate: "2022-07-06T09:35:52Z"
    GitCommit: 770c19a2
    Version: v1.17.0-rc1

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/arm64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5", GitCommit:"aea7bbadd2fc0cd689de94a54e5b7b758869d691", GitTreeState:"clean", BuildDate:"2021-09-15T21:04:16Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.23) and server (1.21) exceeds the supported minor version skew of +/-1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

Tying to create 2 httptriggers with prefix for 2 different functions, but receiving error.

**To Reproduce**
<pre>
# Add the stock NodeJS env to your Fission deployment
% fission env create --name nodejs --image fission/node-env
poolsize setting default to 3
environment 'nodejs' created

# A javascript function that prints "hello world"
% curl -LO https://raw.githubusercontent.com/fission/examples/main/nodejs/hello.js

# Upload your function code to fission
% fission function create --name hello-js --env nodejs --code hello.js
Package 'hello-js-1b4968f0-8e5e-4d5c-9572-1ffeef296d5b' created
function 'hello-js' created

# Create second function
% fission function create --name bye-js --env nodejs --code hello.js
Package 'bye-js-b55627ff-9659-4571-badc-5ff3d87150cc' created
function 'bye-js' created

# Create first httptrigger
% fission httptrigger create --prefix /hello --method GET --function hello-js --name hello
trigger 'hello' created

# Create second httptrigger
% fission httptrigger create --prefix /bye --method GET --function bye-js --name bye

Options:
  --function=[]                    Name(s) of the function for this trigger. (If 2 functions are
                                   supplied with this flag, traffic gets routed to them based on weights supplied
                                   with --weight flag.)
  --url=''                         URL pattern (See gorilla/mux supported patterns) [DEPRECATED for 'fn
                                   create', use 'route create' instead]
  --name=''                        HTTP trigger name
  --method=[GET]                   HTTP Methods: GET,POST,PUT,DELETE,HEAD. To mention single method:
                                   --method GET and for multiple methods --method GET --method POST. [DEPRECATED
                                   for 'fn create', use 'route create' instead]
  --createingress=false            Creates ingress with same URL
  --ingressrule=''                 Host for Ingress rule: --ingressrule host=path (the format of
                                   host/path depends on what ingress controller you used)
  --ingressannotation=[]           Annotation for Ingress: --ingressannotation key=value (the format of
                                   annotation depends on what ingress controller you used)
  --ingresstls=''                  Name of the Secret contains TLS key and crt for Ingress (the
                                   usability of TLS features depends on what ingress controller you used)
  --weight=[]                      Weight for each function supplied with --function flag, in the same
                                   order. Used for canary deployment
  --fnNamespace='default' (--fns)  Namespace for function object
  --spec=false                     Save to the spec directory instead of creating on cluster
  --dry=false                      View the generated specs
  --prefix=''                      Prefix with which functions are exposed. NOTE: Prefix takes
                                   precedence over URL/RelativeURL [DEPRECATED for 'fn create', use 'route create'
                                   instead]
  --keepprefix=false               Keep the prefix in the URL while forwarding request to the function

Global Options:
  --server=''         Server URL
  --verbosity=1 (-v)  CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
  --kube-context=''   Kubernetes context to be used for the execution of Fission commands

Usage:
  fission httptrigger create [options]

Error: create HTTP trigger: Resource exists - HTTPTrigger with same Host, URL & method already exists (hello)
</pre>

**Expected result**

Trigger created

**Actual result**
```Error: create HTTP trigger: Resource exists - HTTPTrigger with same Host, URL & method already exists (hello)```

**Comment by Tri0L** [comment]
Found workaround. We can use placeholders + regexp in `url` param instead of `prefix`:
```
fission httptrigger create --url '/hello/{internal-uri:[\/A-z0-9]*}' --method GET --function hello-js --name hello
fission httptrigger create --url '/bye/{internal-uri:[\/A-z0-9]*}' --method GET --function bye-js --name bye
```

**Comment by sanketsudake** [comment]
This would be fixed in rc2 release.
