### ISSUE TITLE
Configmap and secrets injection support for container function

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2531]
Currently when we pass configmap & secret with `fission fn create` or `fission run-container` command.
Respective configmap and secret should get injected into the function container.

Also consider PR https://github.com/fission/fission/pull/2528

Functionality should work
- Configmap should get injected based on reference
- Secret should get injected based on reference
- configmap/secret once updated, function pod should restart.

**Comment by soharab-ic** [comment]
**Executortype `poolmgr` and `newdeploy`:**
- ConfigMap and Secrets are injected as volumeMounts.
- ConfigMap/Secret once updated, newdeploy pod is restarted and specialized `poolmgr` pod is terminated.

**Executortype `container`:**
- ConfigMap and Secrets are injected based on reference.
- ConfigMap/Secret once updated, function pod is restarted.
