### ISSUE TITLE
Fission cli hang after install

### ISSUE THREAD

**Issue by ironman-gf** [fission/fission#2532]
**Fission/Kubernetes version**

<pre>
$ fission version v1.16.0
$ kubectl version 1.24.2
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

I use my local minikube as testing environment, followed install instruction for minikube to use helm to install the fission feature.
After install the fission cli in my Mac OS, I tried to execute "fission version" "fission check" both are hanging. 
**To Reproduce**

1. Set up minikube in your local.
2. Use below commands to helm install fission:
"export FISSION_NAMESPACE="fission"
kubectl create namespace $FISSION_NAMESPACE
kubectl create -k "github.com/fission/fission/crds/v1?ref=v1.16.0"
helm repo add fission-charts https://fission.github.io/fission-charts/
helm repo update
helm install --version v1.16.0 --namespace $FISSION_NAMESPACE fission \
  --set serviceType=NodePort,routerServiceType=NodePort \
  fission-charts/fission-all"
3. install fission cli by using: "curl -Lo fission https://github.com/fission/fission/releases/download/v1.16.0/fission-v1.16.0-darwin-amd64 && chmod +x fission && mv fission /usr/local/bin/"
4. execute fission version or fission check
**Expected result**

should pop up fission client and version version, or pop up the checking results.
**Actual result**
Both 2 commands hanging.
**Screenshots/Dump file**

I use "fission support dump --verbosity 2" try to dig more details:
Setting up port forward to application=fission-api in namespace fission
Waiting for local port 53424
Starting port forward from local port 53424
Using kubeconfig from "/Users/a673641/.kube/config"
Connected to Kubernetes API
Connecting to port 8888 on pod fission/controller-5cb4575c98-w2c57
Starting port forwarder
Forwarding from 127.0.0.1:53424 -> 8888
Forwarding from [::1]:53424 -> 8888
Waiting for port forward 53424 to start...
Handling connection for 53424
Error dialing on local port 53424: dial tcp :53424: i/o timeout
Handling connection for 53424
Error dialing on local port 53424: dial tcp :53424: i/o timeout
<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by sanketsudake** [comment]
@ironman-gf could you please try CLI from this release ?

https://github.com/fission/fission/releases/tag/v1.16.1

**Comment by ironman-gf** [comment]
> 

Seems like run into syntax error:
 % fission version
/usr/local/bin/fission: line 8: syntax error near unexpected token `newline'
/usr/local/bin/fission: line 8: `<!DOCTYPE html>'
 ~ % fission check
/usr/local/bin/fission: line 8: syntax error near unexpected token `newline'
/usr/local/bin/fission: line 8: `<!DOCTYPE html>'
~ % fission --help
/usr/local/bin/fission: line 8: syntax error near unexpected token `newline'
/usr/local/bin/fission: line 8: `<!DOCTYPE html>'

**Comment by ironman-gf** [comment]
> 

It works. Thanks for the quick response and helpful info. That's cool~

**Comment by sanketsudake** [comment]
Request to use 1.16.1 release or later as they become available.

Closing issue for now.
