### ISSUE TITLE
Nodejs env cannot catch exceptions in callback functions and restarting causes failure

### ISSUE THREAD

**Issue by yqf3139** [fission/fission#254]
In node js functions, we often invoke some async functions and then exceptions in the callback functions cannot be catched by `server.js`. This often causes the process to exit.

Here is an example code causes this issue:
```
module.exports = function(context, callback) {
    setTimeout(function(){
        callback(200, "");
        throw new Error('');
    }, 1000);
}
```
The exception crashes the nodejs env, when kubernetes try to restart the nodejs env, another error occurs and then the pod continues to crash loop backoff.
```
Error: EEXIST: file already exists, symlink '/usr/src/app/node_modules' -> '/userfunc/node_modules'
```
The second issue is pretty easy to solve. But for the first, how can we handle this type of exceptions?

**Comment by erwinvaneyk** [comment]
For the first bug, although the function/user is at fault here, we still should indeed minimize the impact of the errors. What about adding https://nodejs.org/api/process.html#process_event_uncaughtexception to the environment. That might be useful to avoid functions crashing the whole environment.

**Comment by yqf3139** [comment]
Thanks @erwinvaneyk .
I tried your suggestion and it can catch the exception. Can we assume that the user code is functional when it fails to catch some exception @soamvasani ? If so, we can continue to run the container to serve more requests.
Also for nodejs env, if the container exits, it has to reload the user code and skip symlinking node module folder.

**Comment by vishal-biyani** [comment]
Closing for now as relevant PR is closed, please reopen if still an issue.
