### ISSUE TITLE
Fission emitting separate traces for specialization and requests

### ISSUE THREAD

**Issue by airhorns** [fission/fission#2545]
**Fission/Kubernetes version**

Fission 1.17rc1
GKE 1.22

**Describe the bug**

Fission emits two different traces when it specializes a new pod for a poolmgr function to serve a request: one trace for the specialization work, and one trace for the actual request processed by the function. If a request is made to the fission router with an existing trace propagation header, that header makes it through to the function within the pod, but that tracing context is ignored for the work done by the executor and fetcher to specialize a new pod if that is necessary.

Here's what one of the request traces we see looks like:
![CleanShot 2022-09-14 at 12 45 10@2x](https://user-images.githubusercontent.com/158950/190214060-2ea21e6b-2e9e-4ad5-b086-f5a6e81e5c93.png)

Here's what one of the specialization traces we see looks like:
![CleanShot 2022-09-14 at 12 43 06@2x](https://user-images.githubusercontent.com/158950/190213664-69372993-ea79-4124-b8d8-a8ced8add759.png)

**To Reproduce**

Specialize a new `poolmgr` function with opentelemetry tracing in place

**Expected result**

Instead of two traces, I think there should only be one, combined one. Specialization makes the request take more time, so when looking at a request trace, it's useful (and important?) to be able to see that specialization is what made it slow. I think this is probably a small bug in the otel context propagation somewhere. I took a look but couldn't spot it.

**Actual result**

Two traces emitted.

**Comment by sanketsudake** [comment]
I think we lost the injection of otelhttp transport in [PR #2414](https://github.com/fission/fission/pull/2414) the executor MakeClient call, which could be causing the issue.

Following should possibly fix,

```
func MakeClient(logger *zap.Logger, executorURL string) *Client {
	hc := retryablehttp.NewClient()
	hc.HTTPClient.Transport = otelhttp.NewTransport(hc.HTTPClient.Transport)
	c := &Client{
		logger:      logger.Named("executor_client"),
		executorURL: strings.TrimSuffix(executorURL, "/"),
		tappedByURL: make(map[string]TapServiceRequest),
		requestChan: make(chan TapServiceRequest, 100),
		httpClient:  hc,
	}
	go c.service()
	return c
}
```

@shubham-bansal96 please validate this on your end.
