### ISSUE TITLE
`fission function run-container` missing --imagepullsecret option

### ISSUE THREAD

**Issue by suguiura** [fission/fission#2569]
I tried to run a `fission function run-container` to an image at a registry with authentication, and I got a `ErrImagePull` status because it was unable to authenticate.

A workaround for this problem is to [create a secret](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#create-an-imagepullsecret) and use it in a [spec file](https://doc.crds.dev/github.com/fission/fission/fission.io/Function/v1@v1.16.2) for the function at spec.podspec.imagePullSecrets[].name.

However, it would be better if we could supply a --imagepullsecret to the fission cli, so we could run it both without a spec file, or without manually editting it.

**Comment by suguiura** [comment]
```shell
$  fission version
client:
  fission/core:
    BuildDate: "2022-09-16T13:24:57Z"
    GitCommit: b36e0516
    Version: v1.17.0

```

**Comment by Akshit42-hue** [comment]
Working on it :)

**Comment by Akshit42-hue** [comment]
So basically we have to add --imagepullsecret command in the fission Cli. Correct me if I am wrong :)

**Comment by sanketsudake** [comment]
@Akshit42-hue Yes, we will need to accept the image pull secret name from the user and embed it into the function spec.
We can assume the user already creates an image pull secret.

**Comment by Akshit42-hue** [comment]
We already have an imagepullsecret command 
[Ref](https://fission.io/docs/usage/function/private-registry/)

**Comment by suguiura** [comment]
@Akshit42-hue, your reference is for the `fission environment` command, which is different from the function (sub)command.

The "Pull an Image From a Private Registry" page was one of the first documentations I read when I finally found out the `fission function run-container` doesn't have the option.

By the way, when I create a funcion with `run-container`, I don't even have to create a fission environment, right?

**Comment by suguiura** [comment]
@Akshit42-hue, your reference is for the `fission environment` command, which is different from the function (sub)command.

The "Pull an Image From a Private Registry" page was one of the first documentations I read when I finally found out the `fission function run-container` doesn't have the option.
