### ISSUE TITLE
Add function invoke subcommand

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#257]
There has already been some talk (can't find the exact issue at the moment) about adding a `fission fn invoke <name/id>` to bypass the http route setup, as it is generally irrelevant during the development/testing of the function.

~~To take it one step further, I propose that we expose functions by default. This could be enabled/disabled by toggling some development flag on the fission-bundle, or leave it to the users to block requests to the 'dev' HTTP namespace.~~

When you create a function "hello", given that the function name can be assumed to be unique. We immediately expose the function (for all HTTP methods) through something like this:
`$FISSION_ROUTER/_function/hello`. When the function versioning is added to the master branch, we could change the path to include the version: `$FISSION_ROUTER/_function/hello-<version>`. In that case the path without a version will simply point to the newest version.

When the function is deleted, the paths are also immediately deleted.

This will also allow a `fission function invoke <name/id>` to be trivial to implement.

**Comment by yqf3139** [comment]
@erwinvaneyk  
Every function is default on `$FISSION_ROUTER/fission-function/$FUNCION_NAME` after the function is created. This feature is not well documented. We can add the cli `invoke` command and furthermore, toggling, blocking and versioning.

**Comment by erwinvaneyk** [comment]
Ah thanks @yqf3139 , I missed that completely then 👍 

I will leave this issue open for the CLI improvements in that case.

**Comment by soamvasani** [comment]
Thanks for bringing up this issue @erwinvaneyk and @yqf3139.

We need to separate those default `fission-function` routes to another router, so that the main router can be exposed outside the cluster without exposing all functions.

And once we do that, we will also need an API that will allow functions without triggers to be invoked. That API would be subject to authentication, of course.

**Comment by soamvasani** [comment]
`fission fn test` does this
