### ISSUE TITLE
Helm upgrade fails due pre-upgrade-checks

### ISSUE THREAD

**Issue by poloskov-k** [fission/fission#2581]
**Versions**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2022-09-16T13:24:57Z"
    GitCommit: b36e0516
    Version: v1.17.0
server:
  fission/core:
    BuildDate: "2022-09-16T13:24:57Z"
    GitCommit: b36e0516
    Version: v1.17.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
I'm using k3d
<pre>
$ k3d version
k3d version v5.4.6
k3s version v1.24.4-k3s1 (default)
</pre>

**Describe the bug**

_pre-upgrade-checks_ crashes during helm upgrade. There is a mismatch in _pre-upgrade-checks_ code and actual CRDs.
Code require _RequestPerPod/OnceOnly/PodSpec_ while CRDs have _requestPerPod/onceOnly/podSpec_ fields.

**To Reproduce**

Try to install and then upgrade fission via helm.
PS: set analytics to false because it doesn't work as well.

<pre>
helm install --version v1.17.0 --namespace fission fission fission-charts/fission-all --set analytics=false
helm upgrade fission fission-charts/fission-all --namespace fission --version v1.17.0 --set analytics=false
</pre>
**Expected result**

_helm upgrade_ should be successful.

**Actual result**
_helm upgrade_ fails after timeout:
<pre>
$ helm upgrade fission fission-charts/fission-all --namespace fission --version v1.17.0 --set analytics=false
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
</pre>
This is happening because of _pre-upgrade-checks_ job fails with:
<pre>
{"level":"info","ts":"2022-10-25T17:39:01.100Z","logger":"pre_upgrade_task_client","caller":"preupgradechecks/checks.go:97","msg":"Checking if user has applied the latest CRDs"}
{"level":"fatal","ts":"2022-10-25T17:39:01.100Z","caller":"preupgradechecks/main.go:70","msg":"New CRDs are not applied","error":"could not find RequestPerPod/OnceOnly/PodSpec in Function CRD","stacktrace":"main.main\n\tcmd/preupgradechecks/main.go:70\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/proc.go:250"}
</pre>

**Comment by shubham-bansal96** [comment]
@poloskov-k 
I believe you are upgrading fission below than 1.14 to 1.17. There are lot of changes has been made in version 1.14 related to CRD and fission has a logic of pre-upgrade checks of CRD while upgrading fission.

To resolve this issue, please set the value preUpgradeChecks.enabled=false in helm chart. 

Try out this and your issue will resolve.
```
helm upgrade fission fission-charts/fission-all --namespace fission --version v1.17.0 --set analytics=false, preUpgradeChecks.enabled=false
```

Closing this issue, but feel free open it, if you still face any issue.

**Comment by poloskov-k** [comment]
@shubham-bansal96
No, unfortunately, it was a clean install. I installed 1.17.0 and tried upgrade with the same version in purpose to update chart values.
