### ISSUE TITLE
Helm upgrade fails due pre-upgrade-checks

### ISSUE THREAD

**Issue by poloskov-k** [fission/fission#2582]
Reopening issue https://github.com/fission/fission/issues/2581

**Versions**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2022-09-16T13:24:57Z"
    GitCommit: b36e0516
    Version: v1.17.0
server:
  fission/core:
    BuildDate: "2022-09-16T13:24:57Z"
    GitCommit: b36e0516
    Version: v1.17.0
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.2", GitCommit:"5835544ca568b757a8ecae5c153f317e5736700e", GitTreeState:"clean", BuildDate:"2022-09-21T14:33:49Z", GoVersion:"go1.19.1", Compiler:"gc", Platform:"windows/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4+k3s1", GitCommit:"c3f830e9b9ed8a4d9d0e2aa663b4591b923a296e", GitTreeState:"clean", BuildDate:"2022-08-25T03:45:26Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
$ helm version
version.BuildInfo{Version:"v3.9.4", GitCommit:"dbc6d8e20fe1d58d50e6ed30f09a04a77e4c68db", GitTreeState:"clean", GoVersion:"go1.17.13"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
I'm using k3d
<pre>
$ k3d version
k3d version v5.4.6
k3s version v1.24.4-k3s1 (default)
</pre>

**Describe the bug**

_pre-upgrade-checks_ crashes during helm upgrade. There is a mismatch in _pre-upgrade-checks_ code and actual CRDs.
Code require _RequestPerPod/OnceOnly/PodSpec_ in Function CRD while actual CRD have _requestsPerPod/onceOnly/podSpec_ fields (you can check it here https://github.com/fission/fission/blob/main/crds/v1/fission.io_functions.yaml).
And _PodSpec_ in MQT CRD instead a _podspec_ (https://github.com/fission/fission/blob/main/crds/v1/fission.io_messagequeuetriggers.yaml).
**NOTE**: This is a clean fission install, not actually upgrading to a new fission version, just upgrading chart values.

**To Reproduce**

Try to install and then upgrade fission via helm.
PS: set analytics to false because it doesn't work as well.

<pre>
kubectl create namespace fission
kubectl create -k "github.com/fission/fission/crds/v1?ref=v1.17.0"
helm repo add fission-charts https://fission.github.io/fission-charts/
helm repo update
helm install --version v1.17.0 --namespace fission fission fission-charts/fission-all --set analytics=false
# fission works fine from this point
helm upgrade fission fission-charts/fission-all --namespace fission --version v1.17.0 --set analytics=false --set enableIstio=true
# this one fails by timeout due to pre-upgrade-checks error
</pre>
**Expected result**

_helm upgrade_ should be successful.

**Actual result**
_helm upgrade_ fails after timeout:
<pre>
$ helm upgrade fission fission-charts/fission-all --namespace fission --version v1.17.0 --set analytics=false --set enableIstio=true
Error: UPGRADE FAILED: pre-upgrade hooks failed: timed out waiting for the condition
</pre>
This is happening because of _pre-upgrade-checks_ job fails with:
<pre>
{"level":"info","ts":"2022-10-25T17:39:01.100Z","logger":"pre_upgrade_task_client","caller":"preupgradechecks/checks.go:97","msg":"Checking if user has applied the latest CRDs"}
{"level":"fatal","ts":"2022-10-25T17:39:01.100Z","caller":"preupgradechecks/main.go:70","msg":"New CRDs are not applied","error":"could not find RequestPerPod/OnceOnly/PodSpec in Function CRD","stacktrace":"main.main\n\tcmd/preupgradechecks/main.go:70\nruntime.main\n\t/opt/hostedtoolcache/go/1.19.0/x64/src/runtime/proc.go:250"}
</pre>

**Comment by shubham-bansal96** [comment]
@poloskov-k 
I just tried same steps as mentioned by you to install and upgrade fission and it's working fine. Please refer the attached screenshot for the same.

It looks like some old CRD exists in your cluster. While installing fission if CRD already exists then fission skip creating new CRD. 
Please try uninstalling fission completely from your cluster for once. Refer below mentioned link for uninstalling fission. Once uninstalled then perform the same steps again for installing and upgrading of fission.
https://fission.io/docs/installation/uninstallation/

![Screenshot from 2022-10-26 19-41-43](https://user-images.githubusercontent.com/62992590/198052381-b93bef22-4f25-4650-aebb-158630f87e0d.png)

**Comment by poloskov-k** [comment]
@shubham-bansal96 
Tried that. Uninstalled fission chart, then uninstalled CRDs. Here is a clean install screenshots:

![image](https://user-images.githubusercontent.com/74617611/198070173-bf5b7eb3-9e44-44eb-be21-e42b728bb3f9.png)
![image](https://user-images.githubusercontent.com/74617611/198070327-fa95aa84-e913-421e-93d6-899b8d7129f0.png)

**Comment by lionello** [comment]
I'm getting the same error as you, clean install, also `enableIstio: true`.

**Comment by sanketsudake** [comment]
@lionello @poloskov-k can you please check if you are facing same issue with 1.18?

**Comment by a-finocchiaro** [comment]
Same happens to me on v1.18, I was able to resolve it by setting this:

```yaml
preUpgradeChecks:
  enabled: false
```
Probably not the best way to resolve the issue, but it seems to at least bypass the problem. This also only happened to me after I had to uninstall and re-install fission in my cluster.

**Comment by soharab-ic** [comment]
Please try latest fission version `v1.20.4` and re-open if issue remains.
