### ISSUE TITLE
-n flag throwing an error for kubewatcher

### ISSUE THREAD

**Issue by shubham-bansal96** [fission/fission#2595]
**Describe the bug**
While creating of kubewatcher in different namespace using -n flag then CLI is throwing an error. 
Note - This issue is only with creating kubewatcher, for listing and deleting it's working fine.

![Screenshot from 2022-11-02 17-14-14](https://user-images.githubusercontent.com/62992590/199481608-9bc8958e-387b-4333-918c-7cd5e2db466f.png)

However --namespace flag is working fine. Also if we look for options using --help then it shows --ns instead of -n inside --namespace field.
![Screenshot from 2022-11-02 17-15-30](https://user-images.githubusercontent.com/62992590/199481816-4b33889a-64c2-4c99-895e-5ee85ad925ee.png)

**To Reproduce**

Create kubewatcher in different namespace (other than default)
```
fission watch create --name hellgo-ns1 --function hellogo-ns1 -n testns1
```

**Expected result**
fission should allow to create kube watcher using -n flag, same as function and packages.

**Actual result**
Fission-CLI is throwing an error
```
Error: unknown shorthand flag: 'n' in -n
See 'fission watch create --help' for usage
```
**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by neha-Gupta1** [comment]
Done in: #2622
