### ISSUE TITLE
Prevent cross namespace references for configmap/secrets in functions

### ISSUE THREAD

**Issue by sanketsudake** [fission/fission#2599]
**Describe the bug**

Currently, fission allows cross-namespace references for configmap/secrets in function. We should prevent this as it unnecessarily adds complexity and breaks our model for multitenancy. 
As part of this  
- We need to prevent users from having cross-namespace references for configmap/secret via validations
- Remove namespace fields for secret/configmap from function spec
- Changes in the backend to optimize code and watch for a specific namespace.

**Additional context**

**Comment by sanketsudake** [comment]
@neha-Gupta1 We can have validations here via validation webhooks.

**Comment by neha-Gupta1** [comment]
https://github.com/fission/fission/pull/2627 
This issue won't arise from CLI. Because in both `spec apply` and `function create/update` commands we assume and set functions namespace as config/secret's namespace.
