### ISSUE TITLE
poolmgr can't reach logger pods while using weave 

### ISSUE THREAD

**Issue by sokoow** [fission/fission#261]
I can't get logs working properly, all I see in influxdb logs is SELECT statements, not ever an INSERT when executing the function. I created my logging pod after functions were created - is there any hookpoint to the logs ?

**Comment by soamvasani** [comment]
@sokoow Thanks for reporting the problem.  Could you please post logs from poolmgr? Here's how:

```
kubectl -n fission logs $(kubectl -n fission get pod -l svc=poolmgr -o name)
```

@life1347, would you mind taking a look? Thanks.

**Comment by sokoow** [comment]
```
2017/07/20 18:23:42 starting poolmgr at port 8888
2017/07/20 18:28:50 Creating pool for environment {python 03cbc947-c62c-4a01-8d40-8a939d56a874}
2017/07/20 18:28:50 [{python 03cbc947-c62c-4a01-8d40-8a939d56a874}] Deployment created
2017/07/20 18:30:08 [hello] Checking for cached function service
2017/07/20 18:30:08 [hello] No cached function service found, creating one
2017/07/20 18:30:08 [hello] getting environment for function
2017/07/20 18:30:08 [&{hello 241d0997-03e0-44b1-ac4e-9fccb3704ad8}] getting function from controller
2017/07/20 18:30:08 [&{hello 241d0997-03e0-44b1-ac4e-9fccb3704ad8}] getting env from controller
2017/07/20 18:30:08 [hello] getting generic pool for env
2017/07/20 18:30:08 [hello] getting function service from pool
2017/07/20 18:30:08 [&{hello 241d0997-03e0-44b1-ac4e-9fccb3704ad8}] Choosing pod from pool
2017/07/20 18:30:08 [map[unmanaged:true functionName:hello functionUid:241d0997-03e0-44b1-ac4e-9fccb3704ad8 poolmgrInstanceId:d9GTBfEx]] found 3 ready pods of 3 total
2017/07/20 18:30:08 relabeling pod: [python-03cbc947-c62c-4a01-8d40-8a939d56a874-ymcq8uwp-10799r0xk6]
2017/07/20 18:30:08 Chosen pod: python-03cbc947-c62c-4a01-8d40-8a939d56a874-ymcq8uwp-10799r0xk6 (in 33.497375ms)
2017/07/20 18:30:08 [&{hello 241d0997-03e0-44b1-ac4e-9fccb3704ad8}] calling fetcher to copy function
2017/07/20 18:30:08 [&{hello 241d0997-03e0-44b1-ac4e-9fccb3704ad8}] specializing pod
2017/07/20 18:30:08 Error connecting to izgw80dh1orapoc2cdlxpyz log daemonset pod: Post http://172.25.155.95:1234/v1/log: dial tcp 172.25.155.95:1234: getsockopt: connection refused
2017/07/20 18:30:08 Specialized pod: python-03cbc947-c62c-4a01-8d40-8a939d56a874-ymcq8uwp-10799r0xk6
2017/07/20 18:30:08 Using pod IP for specialized pod
10.36.0.3 - - [20/Jul/2017:18:30:08 +0000] "POST /v1/getServiceForFunction HTTP/1.1" 200 14
```

I can't find anything listening on port 1234

**Comment by life1347** [comment]
Hi @sokoow 
Since poolmgr notifies logger to transmit function pod logs when the pod was initialized. From log 
```
2017/07/20 18:30:08 Error connecting to izgw80dh1orapoc2cdlxpyz log daemonset pod: Post http://172.25.155.95:1234/v1/log: dial tcp 172.25.155.95:1234: getsockopt: connection refused
```
we can see that poolmgr failed to notified logger(log daemonset pod) because it's not existed yet.

Could you help me to (re)create a function again and see if logs works?

**Comment by soamvasani** [comment]
@sokoow just a sanity check, but did you install fission-logger.yaml?

**Comment by sokoow** [comment]
Yes I did, I can see two logger pods on each of my kube nodes, but nothing is listening on port 1234. Confused a bit.

**Comment by soamvasani** [comment]
The port is being listened on by the logger pods. Would you mind posting the logs from those pods? Maybe they failed to start for some reason.

**Comment by life1347** [comment]
@sokoow Do you enable RBAC in your cluster?

**Comment by sokoow** [comment]
Yes, I used rbac version of yaml to deploy fission

**Comment by life1347** [comment]
Could you help me to add `serviceAccount: fission-admin` in the daemonset logger? And delete logger so that k8s will create a logger with new yaml config.
Ref: https://github.com/fission/fission/pull/239/commits/b6116d6ba667059d6d14c72b3e7b74880f8ab89e

**Comment by sokoow** [comment]
on both loggers I have: 

```
time="2017-07-20T18:23:56Z" level=info msg="starting poolmgr at port :1234" 
```

yet I don't see anything listening on port :1234

**Comment by life1347** [comment]
If you recreate the function and curl it, still not show any function logs? And would you mind to join the slack (http://slack.fission.io/) so that I can help you more quickly :)

**Comment by soamvasani** [comment]
Just to update from the slack convo, it looks like this occurred because poolmgr couldn't reach the logger pod IP directly, because the weave network on the cluster prohibited that. 

This stuff about calling the logger is a bit of an anti pattern. We could perhaps eliminate that by having the logger pod watch the Kubernetes API for local pods with a fission label on them.

**Comment by keslerm** [comment]
I'm seeing the same thing w/ the Flannel networking addon.

It looks like it's trying to reach the pod on it's network interface IP and not the cluster ip

    2017/08/06 19:27:02 Error connecting to liberty log daemonset pod: Post http://192.168.1.97:1234/v1/log: dial tcp 192.168.1.97:1234: getsockopt: connection refused

**Comment by life1347** [comment]
The ways logger works are different now, executor no longer talks to logger anymore. Close it, feel free to reopen it if the same thing happened.
