### ISSUE TITLE
fission route list view misaligned

### ISSUE THREAD

**Issue by sokoow** [fission/fission#262]
Is this view misaligned ? FUNCTION_UID is in wrong place! :)
```
NAME                                 METHOD URL       FUNCTION_NAME FUNCTION_UID
21bc0e64-e3ae-401d-a57e-f8c0714f4bd2 PUT    /hello    hello
3fa06ab7-3490-4880-b481-5afd0a434246 GET    /hello-go hello-go
4fcca2aa-90c3-4872-a7d4-aa7dc2bfd0bf GET    /hello    hello
7e9d49b3-4fbf-4adc-8a69-7766a98a9242 POST   /hello    hello
98bda29d-0483-4e0e-8262-ec2293a26d3a DELETE /hello    hello
cccb23ce-2ed0-4309-805c-28c68547b971 GET    /request  request
```

**Comment by yqf3139** [comment]
@sokoow The http trigger names are uuid randomly generated, the same format as function uid. And because usually we do not specify function uid, the uid field are empty. Maybe we should put a placeholder for empty fields.

**Comment by soamvasani** [comment]
The missing FUNCTION_UID field was removed, and yes the names of routes are generated UIDs.
