### ISSUE TITLE
source_to_image integration

### ISSUE THREAD

**Issue by dmlond** [fission/fission#268]
It might be useful to specify a function as a source_to_image builder image, and git repository. The git repository would contain the function code, and any build artifacts (Gemfile, pkg.json, etc.) that are supported by the assemble script of the source_to_image builder image. This might be solved by [#192](https://github.com/fission/fission/issues/192) and/or [#235](https://github.com/fission/fission/issues/235).

**Comment by erwinvaneyk** [comment]
HI @dmlond! That is indeed something on the roadmap. With the V2 environments (https://github.com/fission/fission/pull/266) the notion of a builder and build phase is introduced. From there it should be a small step to hook the building to a git repo.

**Comment by dmlond** [comment]
Thanks so much. This is a very cool project.

**Comment by soamvasani** [comment]
This work is being tracked in #103, so I'm going to close this.
