### ISSUE TITLE
Panic for the abnormal function of newdeploy

### ISSUE THREAD

**Issue by saltbo** [fission/fission#2681]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2022-05-24T07:28:44Z"
    GitCommit: ed1e4a5c
    Version: v1.16.0
server:
  fission/core:
    BuildDate: "2022-09-16T13:24:57Z"
    GitCommit: b36e0516
    Version: v1.17.0
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:43Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.8", GitCommit:"5575935422cc1cf5169dfc8847cb587aa47bac5a", GitTreeState:"clean", BuildDate:"2021-06-16T12:53:07Z", GoVersion:"go1.15.13", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.20) exceeds the supported minor version skew of +/-1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

![image](https://user-images.githubusercontent.com/17308208/211236088-d635ab81-2ac0-4d35-a105-afc9bbfe5942.png)

**To Reproduce**

create a function using container image, When the image is not found or no auth

**Expected result**

no errors

**Actual result**
panic

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by saltbo** [comment]
Is there any plan to release a bugfix version like v1.17.1? @sanketsudake

**Comment by sanketsudake** [comment]
Hi @saltbo mostly it will come in 1.18.0. Not planning 1.17.x now.
