### ISSUE TITLE
Can not create ingress route when using nginx-ingress, also router is getting exposed via loadbalancer.

### ISSUE THREAD

**Issue by yaymarius** [fission/fission#2708]
**Fission/Kubernetes version**
fission 1.1.8
kubernetes -v

<pre>
$ fission version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Kubernetes at VULTR
**Describe the bug**

Can not use ingress-nginx with fission. when creating ingress route 

{"level":"error","ts":"2023-01-27T13:44:36.372Z","logger":"triggerset.http_trigger_set","caller":"router/ingress.go:48","msg":"failed to create ingress","error":"ingresses.networking.k8s.io is forbidden: User \"system:serviceaccount:fission:fission-router\" cannot create resource \"ingresses\" in API group \"networking.k8s.io\" in the namespace \"fission\"","stacktrace":"github.com/fission/fission/pkg/router.createIngress\n\tpkg/router/ingress.go:48"}
**To Reproduce**

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by shubham-bansal96** [comment]
@yaymarius 
By default router is exposed via loadbalancer in fission. You can change this configuration by setting the value of `routerServiceType` in helm chart.

**Comment by yaymarius** [comment]
@shubham-bansal96 Seems like it's missing ingress permissios in 1.18.0. Also had to set default ingress controller in settings to be cababel to route them through ingress nginx.

**Comment by shubham-bansal96** [comment]
Yes, ingress permission is missing. We have fixed this and these changes will available in next release.
