### ISSUE TITLE
Question on Timer

### ISSUE THREAD

**Issue by lwshuo** [fission/fission#271]
Hi team,

I have a question about the timer, I created it and I can see it by running `fission tt list` but I don't see it in the UI, and also do I need to start the timer or it just starts once created? I didn't really see the function getting triggered.
Not sure if i misunderstood something. 
![image](https://user-images.githubusercontent.com/25490314/29028800-632cb896-7b53-11e7-9e86-09c08997c89c.png)

Thank you!

**Comment by yqf3139** [comment]
Hi. Which UI version you are using? In the UI yaml for k8s, it is the `fission/fission-ui:0.1.0`. So it is a little bit outdated. I will make a small release soon.  And also for UI issues you can send it in the fission-ui repo.

**Comment by yqf3139** [comment]
The timer starts once created. To make sure the timer is working, use kubectl to list the pods in fission namespace and grep timer.

**Comment by lwshuo** [comment]
hmm I don't see the pods, if I can list it then that means they were created, right?
![image](https://user-images.githubusercontent.com/25490314/29034661-fda16f62-7b66-11e7-9975-d8afab476492.png)

**Comment by c0dyhi11** [comment]
Hello,

I am having the same issue as above. But I do see the timer in the UI...
But `kubectl get pods -n fission | grep -i timer` returns nothing.
And I only see the following pods:
`NAME                           READY     STATUS    RESTARTS   AGE`
`controller-2728072551-nj146    1/1       Running   0          5h`
`etcd-3648863197-qt8dg          1/1       Running   0          5h`
`fission-ui-3766949794-w1zp5    2/2       Running   0          5h`
`kubewatcher-2881489874-2n9vx   1/1       Running   0          5h`
`poolmgr-3414952376-2z47n       1/1       Running   0          5h`
`router-2179532955-k8m2l        1/1       Running   0          5h`

Any help would be great.
Thank you,
Cody Hill

```
fission --version
fission version 0.0.0

I'm using release  2017-Jul-05

**Comment by soamvasani** [comment]
@c0dyhi11 @lwshuo  please try the latest release (0.2.1). I just tried it out via the cli and it works well:
https://github.com/fission/fission/releases/tag/v0.2.1
