### ISSUE TITLE
Missing Namespace Error While Creating A Fission Spec For Route

### ISSUE THREAD

**Issue by techmaharaj** [fission/fission#2721]
**Fission/Kubernetes version**

<pre>
$ fission version
fission version
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.0", GitCommit:"4ce5a8954017644c5420bae81d72b09b735c21f0", GitTreeState:"clean", BuildDate:"2022-05-03T13:46:05Z", GoVersion:"go1.18.1", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Local Minikube

**Describe the bug**
While creating the fission spec for a route, I'm getting an error `Error: an empty namespace may not be set when a resource name is provided.`

I don't get it for any other resource type.

**To Reproduce**

Create fission specs for a route, can use the sample mentioned here

<pre>
fission spec init
fission environment create --name python --image fission/python-env --builder fission/python-builder:latest --spec
fission package create --name frontend-pkg --sourcearchive frontend.zip --env python --buildcmd "./build.sh" --spec
fission package create --name backend-pkg --sourcearchive backend.zip --env python --buildcmd "./build.sh" --spec
fission fn create --name frontend --pkg frontend-pkg --entrypoint "app.main" --spec
fission fn create --name backend --pkg backend-pkg --entrypoint "shortenurl.main" --spec
fission route create --name frontend --method POST --method GET --url /main --function frontend --spec
fission route create --name backend --method POST --url /shorturl --function backend --spec
</pre>

**Expected result**
Specs should be created correctly and yaml files should be generated.

**Actual result**

<pre>
fission route create --name frontend --method POST --method GET --url /main --function frontend --spec

Options:
  --function=[]            Name(s) of the function for this trigger. (If 2 functions are supplied with
                           this flag, traffic gets routed to them based on weights supplied with --weight
                           flag.)
  --url=''                 URL pattern (See gorilla/mux supported patterns) [DEPRECATED for 'fn create',
                           use 'route create' instead]
  --name=''                HTTP trigger name
  --method=[GET]           HTTP Methods: GET,POST,PUT,DELETE,HEAD. To mention single method: --method
                           GET and for multiple methods --method GET --method POST. [DEPRECATED for 'fn
                           create', use 'route create' instead]
  --createingress=false    Creates ingress with same URL
  --ingressrule=''         Host for Ingress rule: --ingressrule host=path (the format of host/path
                           depends on what ingress controller you used)
  --ingressannotation=[]   Annotation for Ingress: --ingressannotation key=value (the format of
                           annotation depends on what ingress controller you used)
  --ingresstls=''          Name of the Secret contains TLS key and crt for Ingress (the usability of TLS
                           features depends on what ingress controller you used)
  --weight=[]              Weight for each function supplied with --function flag, in the same order.
                           Used for canary deployment
  --spec=false             Save to the spec directory instead of creating on cluster
  --dry=false              View the generated specs
  --prefix=''              Prefix with which functions are exposed. NOTE: Prefix takes precedence over
                           URL/RelativeURL [DEPRECATED for 'fn create', use 'route create' instead]
  --keepprefix=false       Keep the prefix in the URL while forwarding request to the function

Global Options:
  --server=''          Server URL
  --verbosity=1 (-v)   CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
  --kube-context=''    Kubernetes context to be used for the execution of Fission commands
  --namespace='' (-n)  If present, the namespace scope for this CLI request

Usage:
  fission httptrigger create [options]

Error: an empty namespace may not be set when a resource name is provided
</pre>

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>
[fission-dump_1676357299.zip](https://github.com/fission/fission/files/10729550/fission-dump_1676357299.zip)

**Additional context**

**Comment by soharab-ic** [comment]
Please try latest fission version `v1.20.4` and re-open if issue remains.
