### ISSUE TITLE
autoscaling/v2beta2 HorizontalPodAutoscaler is deprecated in v1.23+, unavailable in v1.26+; use autoscaling/v2 HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by yaymarius** [fission/fission#2722]
Seems like fission is way behind on HPA?

**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
$ kubectl version
Client Version: v1.26.0
Kustomize Version: v4.5.7
Server Version: v1.25.6
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Vultr Hosted Kubernetes
**Describe the bug**

**To Reproduce**
Create newdeploy functions and executor crashes.

**Expected result**

Should autoscale on load
**Actual result**
Fails to autoscale.
**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by ingyamilmolinar** [comment]
yep, fission doesn't work for k8s >= `1.26` since they are using a [deprecated](https://github.com/kubernetes/kubernetes/pull/114886) client-go package for HPA:
In [master](https://github.com/fission/fission/blob/main/go.mod) `client-go` is `v0.25.4` which still uses `autoscaling/v2beta2`. 

I had to downgrade my k8s installation to `1.25.10` to make the `newdeploy` executor work which is sad. Otherwise, I kept getting these errors in the executor pod:
```
{"level":"error","ts":"2023-06-06T20:35:22.959Z","logger":"new_deploy","caller":"newdeploy/newdeploymgr.go:463","msg":"error creating HPA","error":"the server could not find the requested resource","hpa":"newdeploy-hello-py-default-8831-f8e4f27ca8a2","stacktrace":"github.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).fnCreate\n\tpkg/executor/executortype/newdeploy/newdeploymgr.go:463\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).createFunction.func1\n\tpkg/executor/executortype/newdeploy/newdeploymgr.go:384\ngithub.com/fission/fission/pkg/throttler.(*Throttler).RunOnce\n\tpkg/throttler/throttler.go:215\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).createFunction\n\tpkg/executor/executortype/newdeploy/newdeploymgr.go:382\ngithub.com/fission/fission/pkg/executor/executortype/newdeploy.(*NewDeploy).FunctionEventHandlers.func1.1\n\tpkg/executor/executortype/newdeploy/funchandlers.go:36"}
```

**Comment by oEscal** [comment]
I am experiencing problems with this issue as well. In my case, I am using the latest version of K3s (v1.27).

**Comment by jwebb1334** [comment]
I am also experiencing this problem. Would be great if this would get updated. I'd rather not downgrade our entire cluster to 1.25.
