### ISSUE TITLE
There is a problem running the hello world example of python

### ISSUE THREAD

**Issue by kurihada** [fission/fission#2729]
**Fission/Kubernetes version**

<pre>
$ fission version 
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.1", GitCommit:"8f94681cd294aa8cfd3407b8191f6c70214973a4", GitTreeState:"clean", BuildDate:"2023-01-18T15:58:16Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8", GitCommit:"a12b886b1da059e0190c54d09c5eab5219dd7acf", GitTreeState:"clean", BuildDate:"2022-06-16T05:51:36Z", GoVersion:"go1.17.11", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
minikube

**Describe the bug**

When I follow the documentation to execute the example of python, I get the following error
<pre>
$fission function test --name hello-py --namespace fission
Error: Error calling function hello-py: 404; Please try again or fix the error: 404 page not found

Error: Error getting function logs from controller: error executing get logs request: no active pods found. Try to get logs from log database.
Warning: version<1.18 used fission-function as pod's default namespace. Specify appropriate namespace with --pod-namespace tag or export an environment variable for function-namespace FUNCTION_NAMESPACE

Options:
  --name=''               Function name
  --method=[GET]          HTTP Methods: GET,POST,PUT,DELETE,HEAD. To mention single method: --method GET
                          and for multiple methods --method GET --method POST. [DEPRECATED for 'fn create',
                          use 'route create' instead]
  --header=[] (-H)        Request headers
  --body='' (-b)          Request body
  --query=[] (-q)         Request query parameters: -q key1=value1 -q key2=value2
  --timeout=1m0s (-t)     Length of time to wait for the response. If set to zero or negative number, no
                          timeout is set
  --dbtype='kubernetes'   Log database type, e.g. influxdb (currently influxdb and kubernetes logs are
                          supported)
  --subpath=''            Sub Path to check if function internally supports routing

Global Options:
  --server=''          Server URL
  --verbosity=1 (-v)   CLI verbosity (0 is quiet, 1 is the default, 2 is verbose)
  --kube-context=''    Kubernetes context to be used for the execution of Fission commands
  --namespace='' (-n)  If present, the namespace scope for this CLI request

Usage:
  fission function test [options]

Error: error getting function response
</pre>

**Expected result**

<pre>
Hello, world!
</pre>

**Comment by FlappiTomic** [comment]
Same thing happened to me, I was using nodejs example.

**Comment by wwwang0** [comment]
Same to me. All components were running. The logs are simple, and I cannot find out anything wrong except for k8s 1.18

**Comment by manuparra** [comment]
Same error with 1.18, for the basic python example. 
Any ideas?

**Comment by NikhilSharmaWe** [comment]
Run `fission-check` to check if fission components successfully running or not.

**Comment by danroberts** [comment]
this also happens to me with the nodejs example, with docker-desktop. 

`fission check` reports everything running fine

I had a previous fission installation <1.18 which I believe I have deleted correctly.

**Comment by danroberts** [comment]
It seems to me that for whatever reason, the function pods were going into the default namespace. 

I wasn't able to figure out how to get them to go into the normal fission namespace, however, if I used the environment variable:

`export FUNCTION_NAMESPACE=default`

and then deleted my environment 

`fission env delete --name nodejs`

and recreated it, the example worked.

**Comment by Yanghaihai1020** [comment]
Same error with 1.19, for the basic js example.
Any ideas?

**Comment by braumzhu** [comment]
Same error with 1.19, for the basic js example.
Any ideas?

**Comment by sanketsudake** [comment]
Please check comments on #2860. 

You should verify if namespace configured with fission and used with fission are the same.

https://github.com/fission/fission/issues/2860#issuecomment-1784441090

Feel free reopen if think this is a different issue.
