### ISSUE TITLE
MQT Keda (Kafka): Error topic ignored

### ISSUE THREAD

**Issue by Altair-Bueno** [fission/fission#2739]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.2", GitCommit:"fc04e732bb3e7198d2fa44efa5457c7c6f8c0f5b", GitTreeState:"clean", BuildDate:"2023-02-22T13:32:21Z", GoVersion:"go1.20.1", Compiler:"gc", Platform:"darwin/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.6", GitCommit:"d921bc6d1810da51177fbd0ed61dc811c5228097", GitTreeState:"clean", BuildDate:"2021-10-27T17:44:26Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.26) and server (1.21) exceeds the supported minor version skew of +/-1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

Hosted Kubernetes

**Describe the bug**

Errors should appear through the error topic

**To Reproduce**

```py
# kafka.py
def main():
    return {"error": "Error message"}, 400
```

```sh
export TOPICIN=test-input
export TOPICOUT=test-output
export TOPICERROR=test-error
export BROKERS=kafka.kafka:9092

fission mqt create --name kafka-py-conn --function kafka-py --mqtype kafka --mqtkind keda --topic "$TOPICIN" --resptopic "$TOPICOUT" --errortopic "$TOPICERROR" --maxretries 3 --metadata bootstrapServers=$BROKERS --metadata consumerGroup=kafka-py --metadata "topic=$TOPICIN"  --cooldownperiod=30 --pollinginterval=5 
```

**Expected result**

See the error message on `test-error`

**Actual result**

`test-output` show the following messasge

```text
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

[4583c02a-265f-4d6d-8c5d-92f9abaa905c3024991097.zip](https://github.com/fission/fission/files/10942454/4583c02a-265f-4d6d-8c5d-92f9abaa905c3024991097.zip)

**Additional context**

**Comment by Altair-Bueno** [comment]
Update: Minimal example with specs

[kafka.zip](https://github.com/fission/fission/files/10956319/kafka.zip)

**Comment by sjk7524068** [comment]
This can also be tracking from MQT:Rabittmq and MQT:Redis, ERROR-TOPIC seems not working as expected. No results be stored and there is no way you can consuming message from queue ERROR-TOPIC.

**Comment by NikhilSharmaWe** [comment]
In my case the error message specified in the function is logged. See:
`Error: Error calling function kafka-py: 400; Please try again or fix the error: {"error":"Error message"}`

My Fission and Kubernetes versions are the same as yours.

**Comment by Altair-Bueno** [comment]
Would you mind sharing your Helm values used for deployment?

```yml
router:
  deployAsDaemonSet: true

mqt_keda:
  enabled: true

persistence:
  enabled: false
# Enable logs
influxdb:
  enabled: true
```

**Comment by Altair-Bueno** [comment]
Well, something is clearly not working for sjk and me. How do i debug this? My Kafka brokers are working as expected, and KEDA pods appears to be healthy (default installation). Fission was installed following the installation docs, with a couple of changes (values above)

**Comment by Tri0L** [comment]
Have same problem.
v1.17.0
v1.18.0

This is because of problem in kafka-http-connector https://github.com/fission/keda-connectors/issues/143

**Comment by soharab-ic** [comment]
Please try latest fission version `v1.20.4` and re-open if issue remains.
