### ISSUE TITLE
The cold start failure of poolmgr function is not counted in metric.

### ISSUE THREAD

**Issue by saltbo** [fission/fission#2754]
**Fission/Kubernetes version**

<pre>
$ fission version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

The cold start failure of poolmgr function is not counted in metric.

**To Reproduce**

ColdStarts
<img width="1225" alt="image" src="https://user-images.githubusercontent.com/17308208/228413803-cec43dd5-1621-4d69-a0d6-b4ae2dcc0b8a.png">
ColdStartsErrors
<img width="895" alt="image" src="https://user-images.githubusercontent.com/17308208/228413777-d9d6e5dd-baf7-4271-918c-5dadd31197f4.png">

**Expected result**

count the cold start error for the poolmgr function

**Actual result**
not count

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by NikhilSharmaWe** [comment]
@sanketsudake Could you please take a look at this issue and let us know whether this is a reasonable bug or not? So, @saltbo can continue to work on it.
