### ISSUE TITLE
the function seemly can not work, I hope you help me.

### ISSUE THREAD

**Issue by QWQyyy** [fission/fission#2760]
I start my K8s cluster and deploy fission,  it also check by CLI，But I can't invoke my function.
![image](https://user-images.githubusercontent.com/54056797/228903650-c8d9015e-d2c2-4e54-a7b8-9efe2db4b3e4.png)
![image](https://user-images.githubusercontent.com/54056797/228903734-b258c2d7-1ba1-473a-9203-615cfb486209.png)
K8s version is 1.22.4
fission version is 1.18.0
we deploy fission not use helm，use the Basic with LoadBalancer yaml
the fission display in that：
![image](https://user-images.githubusercontent.com/54056797/228904347-c1d8bc89-bb09-4f31-90c1-66f390b9221b.png)
![image](https://user-images.githubusercontent.com/54056797/228904578-11303fbc-e510-45bc-8526-498ab8d4878a.png)
we can create env and deploy function, but I cant run my function, or get any response.
![image](https://user-images.githubusercontent.com/54056797/228905479-795b0616-2451-4237-8b69-d27bc34852bf.png)
could you give me some advidse?

**Comment by QWQyyy** [comment]
![image](https://user-images.githubusercontent.com/54056797/228905876-9ddf9a16-3c0d-4647-944a-8881873e5a88.png)
this is function list.

**Comment by saltbo** [comment]
You can create functions in the `default` namespace

**Comment by QWQyyy** [comment]
> You can create functions in the `default` namespace

thank you, let me try.

**Comment by QWQyyy** [comment]
> You can create functions in the `default` namespace

这的确是一个bug，只有default命名空间中可以成功启动函数，不知道是不是fission设计上没有考虑命名空间权限问题，我现在已经能够成功运行函数
![image](https://user-images.githubusercontent.com/54056797/229133718-69b7b629-bc1e-4512-a6ad-f2e5820ba06f.png)
我在OpenFaaS那边并没有遇到过这种问题，值得记录一下！

**Comment by sanketsudake** [comment]
Please try latest release once https://github.com/fission/fission/releases/tag/v1.19.0-rc1 
See if you still face issue

**Comment by NikhilSharmaWe** [comment]
> > You can create functions in the `default` namespace
> 
> 这的确是一个bug，只有default命名空间中可以成功启动函数，不知道是不是fission设计上没有考虑命名空间权限问题，我现在已经能够成功运行函数 ![image](https://user-images.githubusercontent.com/54056797/229133718-69b7b629-bc1e-4512-a6ad-f2e5820ba06f.png) 我在OpenFaaS那边并没有遇到过这种问题，值得记录一下！

@QWQyyy For creating a fission function in a namespace other than the `default` namespace, you need to set the env var `FISSION_FUNCTION_NAMESPACE` to the namespace needed.
