### ISSUE TITLE
How to use Prometheus to monitor fission in the case of personal K8s cluster Nodeport deployment

### ISSUE THREAD

**Issue by QWQyyy** [fission/fission#2763]
I deploy the minikube yaml file in my 3 VM K8s cluster, but we can not use this page（https://fission.io/docs/usage/observability/prometheus/）create Prometheus watch, we should use myself Prometheus watch it？

**Comment by QWQyyy** [comment]
maybe we should deploy Prometheus bin file and create some yaml file to watch fission, I see five `\metrics` pointend.

**Comment by QWQyyy** [comment]
now we deploy Prometheus in K8s, and we can see some graph, but why it not full?
![image](https://user-images.githubusercontent.com/54056797/229312709-d8d3a093-05f2-4627-a9d9-9d22f7e41f85.png)
and we see the `default` function can not woring in promethus, some graph only display `fission` namespace.
why?
![image](https://user-images.githubusercontent.com/54056797/229312761-5069c386-8a32-4c71-8653-995e48b256b6.png)
![image](https://user-images.githubusercontent.com/54056797/229312768-2954d726-86ee-4e21-966e-83146cb6b390.png)

**Comment by QWQyyy** [comment]
I hope you give me some suggestion for create grafana panel or Prometheus query to display number of copies of the function, the request rate of function, we need graph like that:
 
![image](https://user-images.githubusercontent.com/54056797/229312861-cf85d48b-a682-4fb1-bbd0-70186429bde5.png)
![image](https://user-images.githubusercontent.com/54056797/229312872-c0d79e2d-8cfb-41ad-8db8-b6ca68b1b353.png)
the two pic this my result of openfaas cluster, I hope fission alse give some demo, thank you.

**Comment by QWQyyy** [comment]
I think the serverless function autoscale should be Observability. I hope Fission Metrics Reference get it.

**Comment by QWQyyy** [comment]
@AlekSi @ajbouh @sbfaulkner

**Comment by QWQyyy** [comment]
K8s v1.22.4
fission v1.18.0
Prometheus v2.37.6
grafana v8.5.22

**Comment by AlekSi** [comment]
@QWQyyy please don't spam-mention me

**Comment by soharab-ic** [comment]
@QWQyyy Please try out latest fission version `v1.20.5` and use this [doc](https://fission.io/docs/usage/observability/prometheus/) for prometheus setup. Re-open if you still face any issue.
