### ISSUE TITLE
Docker Compose v3 stack

### ISSUE THREAD

**Issue by prologic** [fission/fission#277]
Can we have a `docker-compose.yml` v3.3 built for this thing? Kubernetes is awesome I'm sure but I'm running stock Docker Swarm mode clusters.

**Comment by soamvasani** [comment]
Supporting Docker Swarm would be cool but it is quite a bit of work (the poolmgr is entirely Kubernetes specific, most of the other components could be reused).  All the environments could be reused, though.

We're focusing on Kubernetes right now so unless someone picks this up, we're probably not going to work on it in the next 6 months at least.

If you want something right now based on images, Swarm has the "faas" project: https://github.com/alexellis/faas

**Comment by prologic** [comment]
Thanks for the info! Appreciate it.

Can we make this clear in the README at least that Kubernetes?


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by soamvasani** [comment]
Thought it was clear already?  We say "Serverless functions for Kubernetes" in the heading :)

**Comment by prologic** [comment]
Ahh so it does :)


James Mills / prologic

E: prologic@shortcircuit.net.au
W: prologic.shortcircuit.net.au

**Comment by soamvasani** [comment]
Closing until we have a concrete plan to do this.

**Comment by alexellis** [comment]
@soamvasani - OpenFaaS has support for various back-ends primarily Kubernetes and Docker Swarm - then Hyper.sh, Rancher Cattle and Nomad. http://github.com/openfaas/faas
