### ISSUE TITLE
Deleting package in fission CLI doesn't delete the files on the server.

### ISSUE THREAD

**Issue by haladynkamil** [fission/fission#2773]
**Fission/Kubernetes version**

<pre>
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0

Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**
Im currently using Fission CLI to create packages just like in the tutorial. When i use `fission pkg delete` it does delete the package so i cannot see it in `list` or create functions that are using it. But when i looked at my server, in `packages/` all the files seems to be stored. Also when im updating a package it just creates a new directory with another alias added after `-`. Since i cannot delete the files and updating creates a new ones, it will quickly skyrocket to insane mess.
**To Reproduce**
Create a package using fission pkg create, delete package using fission pkg delete.

**Expected result**

I would like to be able to delete all files associated to package when im deleting it using CLI. I would like to replace old files with new ones when im using fission pkg update
**Actual result**
Tons of files being stored on the server without purpose.
**Screenshots/Dump file**

![image](https://user-images.githubusercontent.com/45035368/230599215-4e15118b-9f4a-4147-860e-32e38ca4a73e.png)

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by haladynkamil** [comment]
Anything?

**Comment by ntreq** [comment]
same problem

**Comment by soharab-ic** [comment]
PR https://github.com/fission/fission/pull/2979 is merged for this issue.
