### ISSUE TITLE
Unable to access secrets when running container image as a function

### ISSUE THREAD

**Issue by karthiktondapu** [fission/fission#2783]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0
server:
  fission/core:
    BuildDate: "2023-01-13T06:26:33Z"
    GitCommit: deb3523b
    Version: v1.18.0

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

My function is unable to access a secret created in fission namespace. The function is deployed via a container image. Initial investigation suggests that /secrets is not mounted into the pod.

**To Reproduce**
Create a secret
```bash
$ kubectl -n fission create secret generic my-secrets --from-literal=passwd="TESTVALUE"
secret/my-secrets created

$ kubectl get secret my-secrets -n fission
NAME      TYPE     DATA   AGE
passwd   Opaque   1      2s
```
Create function using container image and pass secret
```bash
fission function run-container --name cn-hello-world --secret my-secrets  --image <dockerhub.image.url>:<tag> --port 8082 -n fission
```

When the function code (golang os.ReadFile) tries to access secrets it gives 
```bash
open /secrets/fission/my-secrets/passwd: no such file or directory
```

`kubectl describe pods container-cn-hello-fission-......` output doesn't show /secrets being mounted to the container filesystem.

```bash
    Restart Count:  1
    Environment:
      ...
      NEW_RELIC_METADATA_KUBERNETES_DEPLOYMENT_NAME:       
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jnc29 (ro)
Conditions:
  Type              Status
```

**Expected result**

Function should be able to access secrets mounted at `/secrets/<namespace>/<name>/<key>`

**Actual result**
Function is not able to access the secrets since /secrets is not getting mounted to the container filesystem

**Comment by soharab-ic** [comment]
@karthiktondapu The secrets and configMaps are mounted as environment variables to the function.
