### ISSUE TITLE
how to set nodeSelector  to Environment POD

### ISSUE THREAD

**Issue by BTYHunter** [fission/fission#2786]
How to set `nodeSelector` to environment POD/DEPLOYMENT, say node js function environment？There is one approach after `fission env create` and use `kubectl edit deployment`. In the `templates` files, there are only one component `router` supports set `nodeSelector`, is there any approach to resolve it?

**Comment by Tri0L** [comment]
You can use spec files and set nodeSelector in podspec field of `runtime` / `builder`.

https://fission.io/docs/reference/crd-reference/#environmentspec
