### ISSUE TITLE
[pkg builder error] Error building deployment package: Post "http://python-1097.default:8001": POST http://python-1097.default:8001 giving up after 5 attempt(s)

### ISSUE THREAD

**Issue by QWQyyy** [fission/fission#2801]
I encountered a strange error that prevented me from deploying the pkg package:
![image](https://github.com/fission/fission/assets/54056797/707839e8-84c6-4ad3-9ccf-cdb78174db69)
However, my pkg package has been verified on other nodes, and I have repeatedly reinstalled K8s and session, but the problem still cannot be resolved.

**Comment by QWQyyy** [comment]
I have encountered this problem twice in a row in the past few days. I don't know how I resolved it last time, but it is currently very challenging.

**Comment by soharab-ic** [comment]
Please try latest release `v1.20.4` and reopen if issue remains.
