### ISSUE TITLE
Failed to create a package through openapi

### ISSUE THREAD

**Issue by weisttl** [fission/fission#2802]
**Fission/Kubernetes version**

<pre>
$ fission version v1.19.0
$ kubectl version  1.25.4
</pre>

**Kubernetes platform (desktop)**

**Describe the bug**
Failed to create a package through openapi, while succeed when using the fission cli.

**To Reproduce**

```
curl --location --request POST 'http:/127.0.0.1:31313/v2/packages' --header 'Content-Type: application/json' --data-raw '{
    "metadata": {
        "name": "hello2",
        "namespace": "fission"
    },
    "spec": {
        "environment": {
            "namespace": "fission",
            "name": "python"
        },
        "source": {
            "checksum": {}
        },
        "deployment": {
                "type": "url",
                "url": "https://raw.githubusercontent.com/fission/examples/main/python/hello.py",
                "checksum": {
                    "type": "sha256",
                    "sum": "9a530894234529dc405a7039fff2cbf9b80fd3163826321de8476e7c00bcf511"
                }
            }
    }
}'
```

**Actual result**

**Screenshots/Dump file**
<img width="462" alt="image" src="https://github.com/fission/fission/assets/65213571/83919a8f-2571-43bc-8548-bfb86c7dd271">

<pre>
$ fission support dump
</pre>

**Additional context**

[fission-dump_1684825300.zip](https://github.com/fission/fission/files/11540528/fission-dump_1684825300.zip)

**Comment by rahulvramesh** [comment]
any luck ?

**Comment by weisttl** [comment]
> any luck ?

No, I replaced the Open API with Fission CLI.

**Comment by jeacott1** [comment]
why do maintainers never respond to issues like this?

**Comment by sanketsudake** [comment]
We have deprecated APIs through controller and removed from 1.20 release. Please use kubernetes API directly as they have better RBAC mechanism.
