### ISSUE TITLE
Issue upgrading fission from 1.16.3 to 1.19.0

### ISSUE THREAD

**Issue by fauzankhan007** [fission/fission#2814]
**Fission/Kubernetes version**

<pre>
$ fission version : v1.19.0
$ kubectl version: v1.19.9
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**
Post fission upgrade we are getting below error in controller pod.
{"level":"fatal","ts":"2023-06-15T21:21:15.418Z","logger":"controller","caller":"controller/controller.go:46","msg":"failed to find fission CRDs","error":"8 errors occurred:\n\t* CRD canaryconfigs.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"canaryconfigs.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD environments.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"environments.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD functions.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"functions.fission.io\" is forbidden: :q! \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD httptriggers.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"httptriggers.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD kuberneteswatchtriggers.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"kuberneteswatchtriggers.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD messagequeuetriggers.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"messagequeuetriggers.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD packages.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"packages.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\t* CRD timetriggers.fission.io not found: customresourcedefinitions.apiextensions.k8s.io \"timetriggers.fission.io\" is forbidden: User \"system:serviceaccount:fission:fission-controller\" cannot get resource \"customresourcedefinitions\" in API group \"apiextensions.k8s.io\" at the cluster scope\n\n","stacktrace":"github.com/fission/fission/pkg/controller.Start\n\tpkg/controller/controller.go:46\nmain.runController\n\tcmd/fission-bundle/main.go:54\nmain.main\n\tcmd/fission-bundle/main.go:248\nruntime.main\n\t/opt/hostedtoolcache/go/1.20.4/x64/src/runtime/proc.go:250"
Steps followed
1. replaced the crds 
2. Then ran the helm upgrade command "helm install  fission --namespace fission --set builderNamespace=fission-builder --set functionNamespace=fission-function --set serviceType=NodePort,routerServiceType=NodePort --set prometheusDeploy=false ./fission-all -f k8/config.yaml"
3. to fix i have also created clusterrole and binded the clusterrole with SA "fission-controller".
4. post this controller error was fixed but fission-function pods were not spinning up
5. Also sa fission-svc is missing in latest version, created the same and created the clusterrole for apigroup and mapped the SA with the clusterrole then too fission-function pods were not coming up.

**To Reproduce**

upgrade fission from 1.16.3 to 1.19.0 version

**Expected result**
fission-function pods should come up

**Actual result**
fission-function pods are not coming up
**Screenshots/Dump file**
[fission-dump_1687178592.zip](https://github.com/fission/fission/files/11788241/fission-dump_1687178592.zip)

**Comment by fauzankhan007** [comment]
@sanketsudake Can you please suggest on this

**Comment by fauzankhan007** [comment]
@shubham-bansal96 can you please help on this issue.

**Comment by g1zm0e** [comment]
@cccs-as  can you share what you did? I had to add default to additionalnamespace

**Comment by soharab-ic** [comment]
Please follow the [upgrade doc](https://fission.io/docs/installation/upgrade/#upgrade-to-the-latest-fission-version).
You can also try the latest release `v1.20.4`.
