### ISSUE TITLE
Observing higher resource requests than limit when supplying same requests and limit for environment

### ISSUE THREAD

**Issue by ChayanBansal** [fission/fission#2815]
**Fission/Kubernetes version**

<pre>
$ fission version
client:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
server:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.2", GitCommit:"7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647", GitTreeState:"clean", BuildDate:"2023-05-17T14:13:27Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.2-eks-c12679a", GitCommit:"002c6bc4e142b1f48b9405140e559194a094dcff", GitTreeState:"clean", BuildDate:"2023-05-22T20:23:13Z", GoVersion:"go1.20.4", Compiler:"gc", Platform:"linux/amd64"}
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
EKS [eks.2]

**Describe the bug**
I have created an env as `fission env create --name ax91-python --version 3 --image <my-image> --builder <my-image> --mincpu 256 --maxcpu 256 --minmemory 256 --maxmemory 256 --poolsize 250 --graceperiod 180`
Please note that the resource request and limit are same here.
When the env is created and on running the `kubectl describe node <node>` the allocations look like this
<img width="775" alt="image" src="https://github.com/fission/fission/assets/33371154/d428f947-046a-4790-824a-74b9b5b701b1">

**To Reproduce**
To reproduce you may create an env with the same resource requests and limits as mentioned above.

**Expected result**

Ideally the limits should be greater than or equal to request

**Actual result**
Request is greater than limit

**Comment by soharab-ic** [comment]
The poolmgr deployment contains two containers: `env` and `fetcher`.
With K8s, We can mention the requests and limits for each containers individually. The above command sets the requests and limits for `environment` container but not for `fetcher` container.

If you account for fetcher container resource requests then the total requests will match the request value shown on K8s node. However, It is weird that K8s is not taking note of `fetcher` container's limits until explicitly mentioned in definition.

If you edit the deployment and set limits for `fetcher` container resources then K8s will take note of these limits too.

```
Containers:
   go:
    Image:       fission/go-env-1.20
    Ports:       8000/TCP, 8888/TCP
    Host Ports:  0/TCP, 0/TCP
    Limits:
      cpu:     256m
      memory:  256Mi
    Requests:
      cpu:        256m
      memory:     256Mi
    Environment:  <none>
    Mounts:
      /configs from configmaps (rw)
      /etc/podinfo from podinfo (rw)
      /secrets from secrets (rw)
      /userfunc from userfunc (rw)
   fetcher:
    Image:      localhost:5001/fetcher:v1.20.2-17-g9f9975b5@sha256:6b531832004218bd0d06e6198d3350859c92c7e9ff220f6f24f949f03c903b4c
    Port:       <none>
    Host Port:  <none>
    Command:
      /fetcher
      -secret-dir
      /secrets
      -cfgmap-dir
      /configs
      /userfunc
    Requests:
      cpu:      10m
      memory:   16Mi
    Liveness:   http-get http://:8000/healthz delay=1s timeout=1s period=5s #success=1 #failure=3
    Readiness:  http-get http://:8000/readiness-healthz delay=1s timeout=1s period=1s #success=1 #failure=30
    Environment:
      OTEL_EXPORTER_OTLP_ENDPOINT:  
      OTEL_PROPAGATORS:             tracecontext,baggage
      OTEL_TRACES_SAMPLER_ARG:      0.1
      OTEL_EXPORTER_OTLP_INSECURE:  true
      OTEL_TRACES_SAMPLER:          parentbased_traceidratio
    Mounts:
      /configs from configmaps (rw)
      /etc/podinfo from podinfo (rw)
      /secrets from secrets (rw)
      /userfunc from userfunc (rw)
```
