### ISSUE TITLE
Fission is strongly required to provide system configuration guidelines, especially the K8s helm-based deployment mode.

### ISSUE THREAD

**Issue by QWQyyy** [fission/fission#2818]
I strongly request fission to provide system configuration guide, especially the mode based on K8s helm deployment.
For other serverless frameworks such as openwhisk, their K8s deployment tools provide configuration guidelines for key components, such as controller, Invoker, and scheduler. We can set the jvm memory size of these components through the values.yaml file of helm to adjust the system performance.
For example:
![image](https://github.com/fission/fission/assets/54056797/785a450e-db2e-4f2a-b2ba-0dfeefce2ce6)
Therefore, I think it is necessary to make some configuration guides for some key components of fission. I can only know how to configure some resource limitations of the fetcher in the Pod. I don’t understand what the key configurations of components such as executor are, and values.yaml What is the corresponding meaning in .
so, I hope the fission team can provide more information on the configuration of the system, thanks!

**Comment by reinbach** [comment]
The following provides a well commented `values.yaml` file, does that maybe help?

```
helm repo add fission-charts https://fission.github.io/fission-charts/
helm repo update
helm show values fission-charts/fission-all > values.yaml
```
