### ISSUE TITLE
Environment pods do not show up when environment is created in another namespace

### ISSUE THREAD

**Issue by martel100jn** [fission/fission#2822]
**Fission/Kubernetes version**

<pre>
$ fission version

client/server:
  fission/core:
    Version: v1.19.0

$ kubectl version

Client Version: v1.27.2
Kustomize Version: v5.0.1
Server Version: v1.27.3

</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

kind v0.20.0 (under MacOS)

**Describe the bug**

When I create a namespace test, and run:

> fission env create --name nodejs --image fission/node-env -n test

I don't see any pods showing up.

The nodejs environment is created though:

<pre>

NAME   IMAGE            BUILDER_IMAGE POOLSIZE MINCPU MAXCPU MINMEMORY MAXMEMORY EXTNET GRACETIME NAMESPACE
nodejs fission/node-env               3        0      0      0         0         false  0         test

</pre>

<br>

I experimented with different sort of settings:
* by setting the NAMESPACE environment variables (using the export command)
* by updating the NAMESPACE settings in values.yaml
* by using: kubectl config set-context --current  --namespace=test

but none of that seems to have effect.

<br>
    
I also tried Microk8s instead of kind, but I get the same results.

<br>

**To Reproduce**

> kubectl create namespace test
> fission env create --name nodejs --image fission/node-env -n test
> kubect get pods -A

**Expected result**

When I follow the standard nodejs example, and run:

> fission env create --name nodejs --image fission/node-env
> kubect get pods -A

I see the following environment pods:

default       poolmgr-nodejs-default-5261-6cc484b9b7-5xsfd   2/2     Running   0          72s
default       poolmgr-nodejs-default-5261-6cc484b9b7-j4c85   2/2     Running   0          72s
default       poolmgr-nodejs-default-5261-6cc484b9b7-52sqw   2/2     Running   0          72s

<br>

I expect the same result when I create the environment in a namespace test:

test       poolmgr-nodejs-default-5261-6cc484b9b7-5xsfd   2/2     Running   0          72s
test       poolmgr-nodejs-default-5261-6cc484b9b7-j4c85   2/2     Running   0          72s
test       poolmgr-nodejs-default-5261-6cc484b9b7-52sqw   2/2     Running   0          72s

**Actual result**

I don't see any pods showing up.

**Comment by martel100jn** [comment]
We managed to solve the issue.

This adaptation in the install script was needed:

```
# helm install --version v1.19.0 --namespace $FISSION_NAMESPACE fission --set serviceType=NodePort,routerServiceType=NodePort fission-charts/fission-all
  helm install --version v1.19.0 --namespace $FISSION_NAMESPACE fission --set serviceType=NodePort,routerServiceType=NodePort  --set "additionalFissionNamespaces={test}" fission-charts/fission-all
```
<br>
The additionalFissionNamespaces setting is mentioned in the release notes:

https://fission.io/docs/releases/v1.18.0/#fission-cli-changes

Fission installation by default supports a single namespace defaultNamespace when installed. If you want to enable multiple namespaces, please set it via additionalFissionNamespaces in Helm values


Thank you Amjad Majid for pointing this out!

**Comment by fragsalat** [comment]
This is not very usable in my opinion. In my case we have a namespace per application. With every new application we would have to update the helm installation. Wouldn't it be possible to get informed by changed to resources on all namespaces? 
So when ever a namespace is used for an env, it is registered for the executor to inform for changes.

**Comment by soharab-ic** [comment]
It's a configuration issue. We need to mention the additional namespaces while installing fission.

**Comment by Stradivario** [comment]
@soharab-ic 

So how do we specify dinamically newly created namespaces ?
Previously in 1.15 version we could of specify namespace dynamically so in the end functions were working in a different namespaces without a problem. 

Right now using this approach means that if we do want to updated the namespaces we need to re-apply a helm chart which is strange.
