### ISSUE TITLE
Unable to successfully install and run examples

### ISSUE THREAD

**Issue by Peej11** [fission/fission#2831]
**Fission/Kubernetes version**
The cluster is an on-prem cluster running Cilium for CNI and SMB share for the volume mount.

<pre>
$ fission version - 1.19.0
$ kubectl version - 1.26.3
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
On-prem K8S cluster

**Describe the bug**
I'm unable to deploy Fission correctly and run the example functions. 

**To Reproduce**
- Install Fission with the attached spec
- Try to run an example

**Expected result**
Example should run successfully

**Actual result**
Example gave an error
```
Error: error creating resource: Internal error occurred: failed calling webhook "venvironment.fission.io": failed to call webhook: Post "https://webhook-service.fission.svc:443/validate-fission-io-v1-environment?timeout=10s": Bad Gateway
```

**Screenshots/Dump file**
<pre>
$ fission support dump
</pre>
[fission-dump_1693313310.zip](https://github.com/fission/fission/files/12464738/fission-dump_1693313310.zip)

<pre>
# fission version
client:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
server:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
</pre>

<pre>
# fission check
fission-services
--------------------
√ executor is running fine
√ router is running fine
√ storagesvc is running fine
√ webhook is running fine

fission-version
--------------------
√ fission is up-to-date
</pre>

**Additional context**

**Comment by soharab-ic** [comment]
Please try latest release `v1.20.4` and reopen if issue still remains.
