### ISSUE TITLE
how to set environment deployment params

### ISSUE THREAD

**Issue by BTYHunter** [fission/fission#2832]
**Is your feature request related to a problem? Please describe.**
Is there any approach to set environment params on environment deployment like `volumes` `volumeMounts` `nodeSelector`. For instance, I want to set `nodeSelector` to running function PODs on certain kubernetes nodes, and mount volumes on function PODS.

**Describe the solution you'd like**
My solution is to edit environment deployment yaml after the environment is created. But somehow the environment deployment may restart, and then all of my configrations will lost say `nodeSelector` `volumes`, and I must edit deployment again.
 
Can we make this feature by fission CLI say `fission env create --propery nodeSelector:noderole: ABC`

**Comment by soharab-ic** [comment]
FIxed in PR https://github.com/fission/fission/pull/3033.
Edit environment manifest file and update `podSpec` for `builder` and `runtime` deployments.
