### ISSUE TITLE
error sending request to function%: minikube and docker-desktop

### ISSUE THREAD

**Issue by rkochar** [fission/fission#2841]
**Fission/Kubernetes version**
```
> fission version
client:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
server:
  fission/core:
    BuildDate: "2023-05-18T12:33:09Z"
    GitCommit: f955d118
    Version: v1.19.0
```

```
> kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.25.9
```

`OS: macOS 13.5.2 22G91 arm64`

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker desktop and minikube

**Describe the bug**
Not able to complete the tutorial of "HTTP Headers" on [Go](https://fission.io/docs/usage/languages/go/) or [Python](https://fission.io/docs/usage/languages/python/). The first one, hello world works because it is `fission fn test`. It also works with a `curl $FISSION_ROUTER/hello`. The following code examples don't work.

**To Reproduce**
Install on Docker desktop or Minikube with instructions from fission documentation. Go to [Go](https://fission.io/docs/usage/languages/go/) or [Python](https://fission.io/docs/usage/languages/python/) tutorial page and create the sample code and execute them as instructed.

**Expected result**
```
> curl -H "X-My-Header: Hello" $FISSION_ROUTER/headers
The header's value is 'Hello'
```

**Actual result**
```
> curl -H "X-My-Header: Hello" $FISSION_ROUTER/headers
error sending request to function%
```

```
> fission route list
NAME                                 METHOD URL      FUNCTION(s) INGRESS HOST PATH     TLS ANNOTATIONS NAMESPACE
402b5f7a-01aa-4b0b-9976-6dd0b931a0d6 [GET]  /hello   hello       false   *    /hello                   default
4ff82d88-c5e9-403f-bd1b-55658fba8b81 [GET]  /headers headers     false   *    /headers                 default
```

```
> fission fn test --name headers
Warning: The environment variable FISSION_ROUTER is no longer supported for this command

...

Error: error executing HTTP request: Get "http://127.0.0.1:52516/fission-function/headers": context deadline exceeded
```

Since this problem is repeatable on 2 different languages on minikube and on docker-desktop, hello world works for both languages on minikube and docker-desktop, I am a little confused on what might be causing this. It could be arm64. Do you know if fission works on it?

**Comment by braumzhu** [comment]
The reason is that the IP address of Minikube in Docker on Mac is not reachable. You can try pinging $FISSION_ROUTER locally.

**Comment by soharab-ic** [comment]
Please try latest release `v1.20.4` and reopen if issue still remains.
