### ISSUE TITLE
Allow Keycloak issuer

### ISSUE THREAD

**Issue by HWiese1980** [fission/fission#2865]
**Describe the solution you'd like**
I have a Keycloak authentication service running in my K8s cluster and would like to use that to authenticate fission calls

**Describe alternatives you've considered**
It might be possible to use some middleware to make Fission work with Keycloak

**Additional context**
I'm also using Traefik as ingress controller. My other services that run on my K8s cluster are secured using mesosphere/traefik-forward-auth. That works like a charm. But that's for websites with a frontend where users can log in. That wouldn't work for RESTful APIs where no human user can user enter credentials.

**Comment by sanketsudake** [comment]
@HWiese1980 If you are already using traefix ingress and auth you can just route traffic from router via traffic ingress and use auth you are already using.

Other way is using any [oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/) which sits in front of fission router.

As of now Fission router supports basic auth, we may extend it to support for consuming OIDC provider in future. But I don't think we can do beyond that.
