### ISSUE TITLE
About Kubernetes Version

### ISSUE THREAD

**Issue by shaoyifeng1013** [fission/fission#2897]
How can I get the supported Kubernetes version ranges for each version of Fission ？

**Comment by sanketsudake** [comment]
@shaoyifeng1013 We can refer here https://fission.io/docs/installation/#kubernetes-cluster
We support Kubernetes 1.23 in latest release. 
Also adding contraint in helm chart for minimal supported version.

**Comment by sanketsudake** [comment]
Added in PR as helm chart constraint.
https://github.com/fission/fission/pull/2901
