### ISSUE TITLE
client version and server version not match

### ISSUE THREAD

**Issue by xiangpingjiang** [fission/fission#2904]
**Fission/Kubernetes version**

<pre>
$ fission version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
kind
**Describe the bug**

follow the guide https://fission.io/docs/installation/#without-helm  to install v1.20.1, 
I got 
<img width="684" alt="Screenshot 2024-01-18 at 16 18 09" src="https://github.com/fission/fission/assets/45722758/1fe6e3b6-197d-4111-9e65-6d069bb6d282">

**To Reproduce**

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by sanketsudake** [comment]
We have updated docker image version to 1.20.0 to 1.20.1 in all YAML files attached in a release.

https://github.com/fission/fission/releases/tag/v1.20.1

Feel free reopen issue if not solved.

@xiangpingjiang
