### ISSUE TITLE
[help] how to build fission-bundle image

### ISSUE THREAD

**Issue by BTYHunter** [fission/fission#2910]
Base on `v1.17-rc2` I changed the `pkg/mqtrigger/messageQueue/kafka.go` to support Kafka SASL (only for certain USER and PASSWORD). My question is how to build fission-bundle image, is there any tutorial or README file?

On `fission/cmd` directory, I run `docker build -t registry.test/fission/fission-bundle:test1 -f ./fission-bundle/Dockerfile.fission-bundle .` and I found this built image only `8.53MB` huge different from `ghcr.io/fission/fission-bundle:v1.20.1` that is `57MB`.
There must be someting wrong in my practise.

Thanks for your reply.

**Comment by soharab-ic** [comment]
1. Run `make skaffold-prebuild` which will generate all binaries and Dockerfile in `dist/` directory.
2. Cd into fission-bundle directory
```
$ cd dist/fission-bundle_linux_amd64_v1/
$ ls
Dockerfile  fission-bundle
```
3. Run the docker build command
```
$ docker build -t USER/fission-bundle .
```
