### ISSUE TITLE
Fission helm conflicts with Rancher

### ISSUE THREAD

**Issue by sergeykorablin** [fission/fission#2920]
**Fission/Kubernetes version**

<pre>
$ fission version

$ kubectl version
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.27.11+k3s1
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**

**Describe the bug**

```sh
$ helm install --version v1.20.1 --namespace $FISSION_NAMESPACE fission fission-charts/fission-all
            
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. 
Unable to continue with install: MutatingWebhookConfiguration "mutating-webhook-configuration" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata;
label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm";
annotation validation error: missing key "meta.helm.sh/release-name": must be set to "fission";
annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "fission"
```

https://github.com/rancher/rancher/blob/268d751c68b264e6f50a23d360d4699ca131768d/pkg/crds/provisioningv2/capi-webhooks.yaml#L6 
uses the same name for MutatingWebhookConfiguration

**To Reproduce**

1. Install Rancher 
```sh
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=rancher.homelab.local \
  --set replicas=1 \
  --set bootstrapPassword=admin
```
2. Try to install Fission
```sh
helm install --version v1.20.1 --namespace fission fission fission-charts/fission-all
```

**Expected result**

**Actual result**

**Screenshots/Dump file**

<pre>
$ fission support dump
</pre>

**Additional context**

**Comment by robert-cronin** [comment]
This should just be a simple matter of choosing a unique name for the mutating webhook
