### ISSUE TITLE
fission package build stuck in running

### ISSUE THREAD

**Issue by rohanatxcaliber** [fission/fission#2926]
**Fission/Kubernetes version**
v1.29

<pre>
$ fission version
v1.20.1
$ kubectl version
v1.25
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Amazon EKS

**Describe the bug**

The packages are getting stuck in the running state, and there are no logs available for the packages.
I tried below things:
1. I attempted to create a package out of a simple .py file, but it also became stuck in a running state.
2. I tried deleting everything, including the environment, routes, and all packages, and then created a new package, but the issue persists.
3. The fission check shows everything is functioning correctly, and all pods are operational.
4. I verified the AWS keys in the deployment configuration as well. I checked the logs of the executor and StorageSVC pod, but there are no error logs available to debug this issue. [Using S3 as storage]
5. Tried rollout restarting the whole fission deployments.

**To Reproduce**

fission pkg create --sourcearchive new-test.zip --env nodejs --name node-sample-test

**Expected result**
NAME                  BUILD_STATUS ENV    LASTUPDATEDAT       NAMESPACE
node-sample-test      succeeded nodejs 03 Apr 24 12:44 IST default

**Actual result**
NAME                  BUILD_STATUS ENV    LASTUPDATEDAT       NAMESPACE
node-sample-test      running      nodejs 03 Apr 24 12:44 IST default
**Screenshots/Dump file**

[fission-dump_1712129393.zip](https://github.com/fission/fission/files/14848595/fission-dump_1712129393.zip)

<pre>
$ fission support dump
</pre>

**Additional context**

fission pkg info --name function-name doesn't show any logs while it is running state, it will only show the logs if the pkg is failed or succeeded.

**Comment by soharab-ic** [comment]
Please follow this the readme for nodejs [examples](https://github.com/fission/examples/tree/main/nodejs)
Please check following points:
1.  Use builder while creating nodejs environment
```
$ fission env create --name nodeenv --image fission/node-env:latest --builder fission/node-builder:latest
```
2. Provide an entry point while creating the function
```
$ fission fn create --name hello --pkg [pkgname] --entrypoint "hello"
```
