### ISSUE TITLE
How can we provide the dependencies along with function code in the source zip ?

### ISSUE THREAD

**Issue by prajinkhadka** [fission/fission#2980]
**Fission/Kubernetes version**
client:
  fission/core:
    BuildDate: "2024-01-14T15:43:35Z"
    GitCommit: 7e8d5dd7
    Version: v1.20.1
server:
  fission/core:
    BuildDate: "2024-01-14T15:43:35Z"
    GitCommit: 7e8d5dd7
    Version: v1.20.1

<pre>
$ fission version
$ kubectl version
</pre>

**Kubernetes platform (e.g. Google Kubernetes Engine)**
Docker application on Mac OS ( M1 2020 Air )

**Describe the bug**
I am trying to create the fission function or package by providing a source zip ( that contains both the dependencies and function code ). 
For example in Python, 
pip3 install pyyaml -t . will install dependencies in the current directory. 

and build.sh script contains:
cp -r ${SRC_PKG} ${DEPLOY_PKG}

The files in the directory are: 

.
├── build.sh
├── function.py
└── lib
    └── site-packages
        ├── Crypto
        │   ├── Cipher
        │   │   ├── AES.py
        │   │   ├── AES.pyi
        │   │   ├── ARC2.py
        │   │   ├── ARC2.pyi
        │   │   ├── ARC4.py
        │   │   ├── ARC4.pyi
        │   │   ├── Blowfish.py
        │   │   ├── Blowfish.pyi
        │   │   ├── CAST.py

I create the zip src of this directory with:
zip -r demo-src-pkg.zip .

and use this zip file to create the package:

I get this error:
Name:        demo-src-pkg-zip-uufr
Environment: python
Status:      failed
Build Logs:
error fetching source package: Invalid argument - failed to download url : Get "http://127.0.0.1:53812/v1/archive?id=%2Ffission%2Ffission-functions%2F873a3796-39b8-4839-bf30-5d06119056f3": dial tcp 127.0.0.1:53812: connect: connection refused%

If I just zip without dependencies (just with the build.sh and function.py ) it works. 

How can I pass my dependencies? 

**To Reproduce**
touch function.py 
and just add :
def main():
    return "hello" 
    
touch build.sh 
#!/bin/sh
cp -r ${SRC_PKG} ${DEPLOY_PKG}

pip3 install pyyaml -t . will install dependencies in the current directory. 

Create Package:  
fission package create --sourcearchive demo-src-pkg.zip --env python --buildcmd "./build.sh" 

**Expected result**
I reckon Fission will just unzip this zip file and copy it to the deploy package directory.

**Comment by soharab-ic** [comment]
@prajinkhadka Please follow this example for [packaging source code](https://fission.io/docs/usage/function/package/). Source files are incomplete in this example. Please use these source [files](https://github.com/fission/examples/tree/main/python/sourcepkg).

**Comment by prajinkhadka** [comment]
@soharab-ic  Thank you for the reply. 

Yes, I followed your suggestions.

Here I have attached two folders. 
One is what you mentioned. 
The second one is what I am trying to do. 
In the first one, while creating the package fission installs the dependencies provided in the requirements.txt file as suggested by you. 
I want to skip this step. I want to provide my dependencies and use them. I do not want fission to install anything. 
So, If I add my dependencies and create the package. I get this error:
Name:        demo-src-pkg-zip-u9pu
Environment: pythonsrc
Status:      failed
Build Logs:
error fetching source package: Invalid argument - failed to download url : Get "http://127.0.0.1:51862/v1/archive?id=%2Ffission%2Ffission-functions%2F0ef2ca22-0a16-4832-b7a6-c54f7a895424": dial tcp 127.0.0.1:51862: connect: connection refused%

How can I do that? 

To reproduce:
1. Download two folders. 

2. Inside originial: `chmod +x build.sh` `zip -jr demo-src-pkg.zip .` and `fission package create --sourcearchive demo-src-pkg.zip --env pythonsrc --buildcmd "./build.sh"`

 3. Inside nodep: `chmod +x build.sh` `zip -r demo-src-pkg.zip`  and `fission package create --sourcearchive demo-src-pkg.zip --env pythonsrc --buildcmd "./build.sh"`

The issue is: that when I add other folders (dependencies that contain other python, .pyc files ) fission is not able to create the 
[original.zip](https://github.com/user-attachments/files/16336159/original.zip)
[trying.zip](https://github.com/user-attachments/files/16336162/trying.zip)
package.

**Comment by prajinkhadka** [comment]
Hi @soharab-ic Can you provide me the fission-cli build file for Mac OS M1 ( air 2020 )? 

I am having some problems to build the CLI ( the issue is with my machine )

**Comment by soharab-ic** [comment]
You can download the latest cli with curl.
```
curl -Lo fission https://github.com/fission/fission/releases/download/v1.20.2/fission-v1.20.2-linux-amd64
```

**Comment by prajinkhadka** [comment]
@soharab-ic thank you for the help. 
Your PR solved the issue for me. 
I am closing the issue.
