### ISSUE TITLE
Function not working when routerServiceType=ClusterIP.

### ISSUE THREAD

**Issue by Waqas-Shah-42** [fission/fission#2985]
**Fission/Kubernetes version**
fission: v1.20.2 (also tried with v1.20.1)
kubernetes version: v1.29.4-eks-036c24b

**Kubernetes platform (e.g. Google Kubernetes Engine)**
EKS

**Describe the bug**
I installed fission using helm chart with routerServiceType of type ClusterIP using the following command
`helm install --version v1.20.2 --namespace fission fission \
--set routerServiceType=ClusterIP \
fission-charts/fission-all`

Then I followed the example given after the helm installation which were as following (with namespace updated):- 
- fission env create --name nodejs --image fission/node-env --namespace fission
- curl https://raw.githubusercontent.com/fission/examples/master/nodejs/hello.js > hello.js
- fission function create --name hello --env nodejs --code hello.js --namespace fission
- fission function test --name hello --namespace fission

All the above commands ran successfully. However the following command failed
- fission function test --name hello --namespace fission

It gave the following output
`Error: calling function hello: 404; Please try again or fix the error: 404 page not found
Error: getting function logs: no active pods found for function in namespace fission. Try to get logs from log database.`
![image](https://github.com/user-attachments/assets/b53b0491-293f-4658-8180-3b0135f1bb54)

When I enter fission fn list it shows the function is deployed
![image](https://github.com/user-attachments/assets/86ba5915-df0a-43a5-863e-a08aeeea79ad)

**To Reproduce**

**Expected result**
The function to run as expected.

**Actual result**
The function does not run at all.

**Screenshots/Dump file**

![image](https://github.com/user-attachments/assets/90a2189d-514a-44f6-9962-b0488f398cc0)
![image](https://github.com/user-attachments/assets/7c0f820b-976e-47c3-8f0d-302e8d76bb2c)

<pre>
$ fission support dump
</pre>

**Additional context**
The helm installation was done with  routerServiceType of type ClusterIP using helm chart

**Comment by Waqas-Shah-42** [comment]
In my opinion this should be labelled as bug.

**Comment by soharab-ic** [comment]
@Waqas-Shah-42 Please use `default` namespace while creating fission resources. You have used release namespace `fission`.
```
fission env create --name nodejs --image fission/node-env --namespace default
curl https://raw.githubusercontent.com/fission/examples/master/nodejs/hello.js > hello.js
fission function create --name hello --env nodejs --code hello.js --namespace default
fission function test --name hello --namespace default
```
