### ISSUE TITLE
Feature Request: Support for Fission CLI to Utilize ServiceAccount in Cluster

### ISSUE THREAD

**Issue by yaguirre** [fission/fission#2994]
### **Is your feature request related to a problem? Please describe.**
I am currently developing an application that dynamically creates functions within a Kubernetes EKS environment using Fission. The application, packaged as a Docker image, includes the Fission CLI and is deployed in the EKS cluster. The ServiceAccount associated with this application has been bound with the necessary permissions to interact with cluster resources. However, I discovered that the Fission CLI does not support using the ServiceAccount for authentication and authorization. Instead, **it requires a KubeConfig file,** which complicates the deployment process and introduces security concerns, as embedding a KubeConfig in a Docker image is not ideal.

### **Describe the solution you'd like**
I would like the Fission CLI to support authentication via a ServiceAccount within the cluster. This feature would allow the Fission CLI to leverage the in-cluster configuration (inClusterConfig) for authentication, similar to how other Kubernetes tools like `kubectl` and `client-go` operate. That would enable seamless integration of Fission CLI within applications running within the Kubernetes cluster _**without needing to manage and distribute KubeConfig files.**_

### **Describe alternatives you've considered**
* **`Security Risk of KubeConfig in Containers:`** An alternative solution could involve manually creating and injecting a KubeConfig file into the application’s container, but this approach introduces security risks and adds complexity to the deployment process.

* **`Direct API Interaction:`** Another alternative might be to modify the application to bypass the Fission CLI and directly interact with Fission resources via the Kubernetes API, but this would require significant changes to the existing workflow.

### **Additional context**
This feature would greatly simplify the deployment and management of applications using Fission in a Kubernetes environment, particularly in scenarios where dynamic function creation is required. It would also align with Kubernetes best practices by utilizing the ServiceAccount for in-cluster authentication

**Comment by ansegura7** [comment]
Hi all,

I am encountering the same issue. I'm building an application where I need to use the `Fission CLI` from within a Docker container to dynamically create functions in a Kubernetes EKS environment. However, I want to use the `ServiceAccount` associated with the pod for authentication and authorization, instead of relying on a `KubeConfig` file.

It would definitely be ideal to have support for in-cluster configuration via ServiceAccount, as it would improve deployments for applications that require this kind of functionality.

Fission team, by any chance, do you plan to support this type of functionality in the near future?

**Comment by caladdd** [comment]
I have used _kubectl_, we also use _Fission CLI_, and we noticed that it uses a kubeConfig file for authentication. It has that security risk that _kubectl_ does not have. It could be a good feature.

**Comment by yaguirre** [comment]
@sanketsudake after merging this change how long would it take to reflect the new version of the CLI?

**Comment by ansegura7** [comment]
> @sanketsudake @soharab-ic after merging this change how long would it take to reflect the new version of the CLI?

The new release is now available, with this long awaited and useful feature. I have already tested it, and it works like a charm. Thanks Fission team!

https://github.com/fission/fission/releases/tag/v1.20.4
