### ISSUE TITLE
When we r updating from fission version from 1.20.1 to 1.20.3..we are seeing failure..in router pods.

### ISSUE THREAD

**Issue by rajat42059** [fission/fission#3022]
.. [ERR] POST http://executor.fission/v2/getServiceForFunction request failed

**Comment by sanketsudake** [comment]
Closing this issue as lacks details. 

Please add details to issue via template. 

https://github.com/fission/fission/issues/new?assignees=&labels=&projects=&template=bug_report.md&title=

Please attach fission specs and any additional details which would help in reproducing issue.
