### ISSUE TITLE
Error when running python function 

### ISSUE THREAD

**Issue by amnpandey** [fission/fission#3054]
Hello team,

I am getting the below error when running a pyhton function. I request your help on this. Thanks

```
~/fission
▶ oc get environments
NAME     AGE
python   23m


~/fission
▶ oc get functions
NAME       AGE
hello-py   50s


~/fission
▶ fission function test --name hello-py
Error: calling function hello-py: 500; Please try again or fix the error: error sending request to function
Error: getting function logs: no active pods found for function in namespace default. Try to get logs from log database.
```

env status:

```
~/fission                                                                                                                                                                ⍉
▶ fission check
fission-services
--------------------
√ executor is running fine
√ router is running fine
√ storagesvc is running fine
√ webhook is running fine

fission-version
--------------------
√ fission is up-to-date
```

pods in fission namespace:

```
~/fission                                                                                                                                                                ⍉
▶ oc get po -n fission
NAME                                        READY   STATUS      RESTARTS   AGE
buildermgr-74bbccdb88-xksnc                 1/1     Running     0          77m
executor-bd6b79f88-bt5p4                    1/1     Running     0          77m
fission-v1-20-5-fission-v1.20.5-047-qbm86   0/1     Completed   0          77m
fission-v1-20-5-fission-v1.20.5-633-w248f   0/1     Completed   0          77m
kubewatcher-6549d476b4-vh6gw                1/1     Running     0          77m
mqtrigger-keda-597545984d-zbd8s             1/1     Running     0          77m
router-8c7b87bd9-d5r5h                      1/1     Running     0          77m
storagesvc-f57ff6d9d-v6v4h                  1/1     Running     0          77m
timer-69f48bbccd-26jn2                      1/1     Running     0          77m
webhook-7b6bb7947-7gkz9                     1/1     Running     0          77m
```

// @soharab-ic

**Comment by soharab-ic** [comment]
@amnpandey When you create environment `python` in default namespce, it will create a deployment with 3 replicas
`poolmgr-python-*`, 
```
$ fission environment create --name python --image ghcr.io/fission/python-env
poolsize setting default to 3
environment 'python' created
```
Make sure that env and functions are created in `default` namespace.
```
$ fission env list
NAME   IMAGE                      BUILDER_IMAGE POOLSIZE MINCPU MAXCPU MINMEMORY MAXMEMORY EXTNET GRACETIME NAMESPACE
python ghcr.io/fission/python-env               3        0      0      0         0         false  0         default
```

You can also check respective logs in executor:
```
executor-bd6b79f88-gvq5h {"level":"info","ts":"2024-11-01T10:07:38.950Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp.go:114","msg":"creating pool","environment":{"namespace":"default","name":"python"}}                                                                                                                                                                                                
executor-bd6b79f88-gvq5h {"level":"info","ts":"2024-11-01T10:07:38.956Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/gp_deployment.go:246","msg":"deployment created","deployment":"poolmgr-python-default-8157504","ns":"default","environment":{"namespace":"default","name":"python"}}                                                                                                                   │
executor-bd6b79f88-gvq5h {"level":"info","ts":"2024-11-01T10:07:38.956Z","logger":"generic_pool_manager.generic_pool","caller":"poolmgr/readyPodController.go:49","msg":"readyPod controller started","env":"python","envID":"6cb6fc53-6253-4747-97d0-b2f18ebc87b7"}                                                                                                                                                          
executor-bd6b79f88-gvq5h {"level":"info","ts":"2024-11-01T10:07:38.956Z","logger":"generic_pool_manager.pool_pod_controller","caller":"poolmgr/poolpodcontroller.go:321","msg":"created pool for the environment","env":"python","namespace":"default"}
```

**Comment by amnpandey** [comment]
@soharab-ic  I have created functions and environments in default namespace only. Also, I can see,

```
▶ fission env list
NAME   IMAGE                      BUILDER_IMAGE POOLSIZE MINCPU MAXCPU MINMEMORY MAXMEMORY EXTNET GRACETIME NAMESPACE
python ghcr.io/fission/python-env               3        0      0      0         0         false  0         default

```

**Comment by amnpandey** [comment]
@soharab-ic  I see this error in executor pod:

>{"level":"error","ts":"2024-11-01T10:05:04.138Z","logger":"generic_pool_manager.pool_pod_controller","caller":"poolmgr/poolpodcontroller.go:383","msg":"error handling env from envInformer, max retries reached","key":"default/python","error":"deployments.apps \"poolmgr-python-default-56444583\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>","stacktrace":"github.com/fission/fission/pkg/executor/executortype/poolmgr.(*PoolPodController).envCreateUpdateQueueProcessFunc\n\tpkg/executor/executortype/poolmgr/poolpodcontroller.go:383\ngithub.com/fission/fission/pkg/executor/executortype/poolmgr.(*PoolPodController).Run.func1.(*PoolPodController).workerRun.1\n\tpkg/executor/executortype/poolmgr/poolpodcontroller.go:288\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/util/wait/backoff.go:226\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/util/wait/backoff.go:227\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/util/wait/backoff.go:204\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.31.1/pkg/util/wait/backoff.go:161\ngithub.com/fission/fission/pkg/executor/executortype/poolmgr.(*PoolPodController).Run.func1\n\tpkg/executor/executortype/poolmgr/poolpodcontroller.go:270\ngithub.com/fission/fission/pkg/utils/manager.(*GroupManager).Add.func1\n\tpkg/utils/manager/manager.go:42"}

**Comment by soharab-ic** [comment]
@amnpandey It seems an issue with openshift https://github.com/kubernetes-sigs/cluster-api/issues/4880. Please take a look at this issue and see if you can find a workaround.

**Workaround from Fission:**
- Download [openshift.yaml](https://github.com/fission/fission/releases/download/v1.20.5/fission-core-v1.20.5-openshift.yaml).
- Update the yaml and set the environment variable `DISABLE_OWNER_REFERENCES` in `executor` and `buildermgr` deployments to `true`.
- Use the updated yaml to install the Fission.

**Comment by amnpandey** [comment]
Thanks @soharab-ic for your input. It works now!

```
▶ fission function test --name hello-py
Hello, world!
```
