### ISSUE TITLE
fission package created but remains in running state

### ISSUE THREAD

**Issue by amnpandey** [fission/fission#3055]
Hello Team,

I created a fission package. When I check the status (even after few minutes), it is in `running` status and after sometime it failed with below error:

```
▶ fission pkg info --name demo-src-pkg-zip-oqgy
Name:        demo-src-pkg-zip-oqgy
Environment: python
Status:      failed
Build Logs:
Build timeout due to environment builder not ready%
```

Builermgr pod log:

`{"level":"error","ts":"2024-11-02T12:10:52.103Z","logger":"builder_manager.package_watcher","caller":"buildermgr/pkgwatcher.go:248","msg":"max retries exceeded in building source package, timeout due to environment builder not ready","package":"demo-src-pkg-zip-oqgy","namespace":"default","resource_version":"59171693","key":"fb2dbb6a-78ad-4feb-bc1c-442015d1bdf7_59171693","environment":"python","builder_namespace":"default","environment_namespace":"default","stacktrace":"github.com/fission/fission/pkg/buildermgr.(*packageWatcher).build\n\tpkg/buildermgr/pkgwatcher.go:248"}`

// @soharab-ic

**Comment by soharab-ic** [comment]
@amnpandey 
Provide builder image while creating the environment.
```
fission env create --name python --image ghcr.io/fission/python-env --builder ghcr.io/fission/python-builder
```

**Comment by amnpandey** [comment]
Thanks @soharab-ic , it works now!
