### ISSUE TITLE
Use fission cli to manage packages

### ISSUE THREAD

**Issue by life1347** [fission/fission#321]
In v0.2.1, fission separates package from the function. We need a new `package` command to manage packages.

```
fission package create/update/get/delete xxxxxx
```

And a package reference can be specified when function create/update.
```
fission function create/update --packageref=xxxxx
```

**Comment by erwinvaneyk** [comment]
Is it possible to avoid exposing the packages concept to the user? Although I have only superficially followed the package PRs, to me it seems like something that we can abstract away on the CLI level.  What use cases are there that require exposing the package concept on the CLI level?

**Comment by life1347** [comment]
A user may use the same package in multiple functions, it's better to have a `package` command for users to manage packages. 

Also if users want to update package content, they should use `package` command to update it rather than using `function` command to update it since a package may be used by multiple functions.
 (https://github.com/fission/fission/blob/master/fission/function.go L249 - L269) 

I think we can keep `function` command as simple as before. And provide a `package` command  for advanced usage.

**Comment by soamvasani** [comment]
@life1347 @erwinvaneyk yup we need the advanced command for use cases involving sharing packages between functions. For more common one-function-per-package use case the user can get by with just the `fission function` command.

**Comment by soamvasani** [comment]
Safe to close this now, we've had the package command for a while now
