### ISSUE TITLE
Invalid function name crashes fission

### ISSUE THREAD

**Issue by LittleFox94** [fission/fission#322]
I created a function named "mgr/ip" and added a route for it. After trying to call it, the router crashed and was not coming to life again.

When trying to list the functions (fission fn list), I got the following error:
```sh
$ fission fn list
Failed to list functions: Internal error - unexpected end of JSON input
```

The router also complained about not being able to get a list of functions.

**Comment by soamvasani** [comment]
@LittleFox94 which release? Latest release 0.2.1 has a name validation bugfix, can you try it?

```
fission fn create --name 'mgr/ip' --env nothing --code README.md
Failed to create package: Internal error - Name must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?'
```

**Comment by soamvasani** [comment]
I think it's fixed but please reopen if you can repro on the most recent version
