### ISSUE TITLE
Fission persistance

### ISSUE THREAD

**Issue by valentin2105** [fission/fission#323]
Hi,

I really like Fission, quick and easy serverless ;)

I got a small problem otherwise about Data persistance,

I created a PersistentVolume for Fission's ETCD but it seem that if all my cluster reboot, Fission have lost my functions (code, not name and routes). 

I have forget anything to put in persistant volume ? The controller ? 

It would be great if you integrate this small part in the documentation ?!

Thanks a lot,

**Comment by soamvasani** [comment]
Hi @valentin2105, we've solved this in the latest release :)  We now use Kubernetes third party resources and a persistent volume for our state.

Please follow these instructions: http://fission.io/docs/v0.2.1/install/

(I'll be updating fission.io and INSTALL.md to point to the new instructions)

**Comment by valentin2105** [comment]
Thanks @soamvasani  I will try this !
