### ISSUE TITLE
Missing environment images of the latest tag

### ISSUE THREAD

**Issue by y-taka-23** [fission/fission#328]
I found that the following environment images lack the `latest` tag:

* `fission/binary-env`
* `fission/php-env`
* `fission/perl-env`
* `fission/dotnet-env`

Especially speaking of `binary-env`,  the current [README.md](https://github.com/fission/fission/blob/85983c9/examples/binary/README.md) refers to the `latest` image as:

```
fission env create --name binary-env --image fission/binary-env
```

So I'm afraid that newbies who follow the document will stall here. Do you have any reasons to omit the `latest` tags?

**Comment by soamvasani** [comment]
Thanks @y-taka-23, this is indeed a bug in our release automation script.  

The fix would be to make hack/release.sh `build_and_push_env_image()` also tag and push the `latest` tag.

**Comment by y-taka-23** [comment]
Successfully deployed into Docker Hub.
