### ISSUE TITLE
etcd: use the etcd-operator

### ISSUE THREAD

**Issue by philips** [fission/fission#33]
Instead of deploying your own etcd use the [etcd operator](https://github.com/coreos/etcd-operator) to take advantage of scaling, upgrades, etc. 

cc @xiang90 @hongchaodeng

**Comment by soamvasani** [comment]
So is using etcd operator a matter of just replacing the current etcd Deployment with something like the example/deployment.yaml in the linked repo, and then connecting to the etcd-cluster-NNNN service?

I noticed this is in alpha -- is the usage or deployment expected to change? 

(For the longer term, we probably don't want fission deploying its own etcd, at least in a production environment.  The user would want to control precisely how it's deployed, and fission would just connect to it.  But we'll tackle that later as we get closer to 1.0.)

**Comment by kfox1111** [comment]
etcd-operator is very cool. But I'm wondering if etcd is really needed at all? K8s provides 3rd party objects and some basic atomic operations on them. Some systems that need etcd (such as calico) are starting to add an etcd'less mode where they store in k8s instead, using the underlying etcd indirectly.

**Comment by xiang90** [comment]
@kfox1111 if you only need a reliable small storage, then you do not really need to talk to etcd directly. if you need distributed coordinations, you need etcd.

**Comment by soamvasani** [comment]
@kfox1111 Yes, we're moving to k8s third party objects soon! Current work is on the `controller-tpr` branch.

So I might as well close this issue.

**Comment by philips** [comment]
Just keep in mind that Kubernetes TPRs are only useful for really small values base64'd. I think it is 512KB.

**Comment by soamvasani** [comment]
@philips Yes. To quickly summarize the design -- TPRs will be used for function metadata and a separate storage service will be used for functions and function packages. There will also be a special case for small functions that will be stored as a literal inside the metdata itself.

**Comment by kfox1111** [comment]
They are not the same max size as a configmap?
