### ISSUE TITLE
Fission integration with Istio

### ISSUE THREAD

**Issue by atiwari** [fission/fission#344]
https://istio.io
IMO, this will solve much of our problem e.g. security, Ops and Assurance.
We are starting this work soon and happy to contribute.

**Comment by soamvasani** [comment]
Did some quick testing with Istio.  The injection of sidecars into function pods works fine, however the envoy sidecars end up being configured not to accept any incoming traffic. 

I can't seem to find any istio docs about how it decides what listeners to configure in the envoy proxy sidecar. So this needs a bit more investigation.

Another issue to figure out will be how security policies work given the late binding of functions to pods, and how it affects cold-start performance.

**Comment by vishal-biyani** [comment]
Closing this for now @life1347 We should probably raise new once for additional feature requests.
