### ISSUE TITLE
Failed to create environment with nodejs example

### ISSUE THREAD

**Issue by VP2405** [fission/fission#358]
I've installed fission 0.2.1 on a kubernetes cluster (on a cloud provider), which is behind an HAproxy.

Typing `kubectl --namespace fission get -w svc` I get:

```
NAME             CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
controller       10.43.20.117    10.4.60.13    80:31313/TCP     1d
etcd             10.43.48.175    <none>        2379/TCP         1d
influxdb         10.43.49.236    <none>        8086/TCP         1d
nats-streaming   10.43.122.209   10.4.62.9     4222:31316/TCP   1d
poolmgr          10.43.27.242    <none>        80/TCP           1d
router           10.43.5.131     10.4.21.197   80:31314/TCP     1d
storagesvc       10.43.119.200   <none>        80/TCP           1d
```
so the services seem to be running correctly.

The HAProxy node is associated to `my.domain.com`, so I set

```
FISSION_URL=http://my.domain.com/furl
FISSION_ROUTER=http://my.domain.com/frouter
```

and modified the configuration of HAProxy with the following rules:
```

frontend http
  bind *:80
  reqadd X-Forwarded-Proto:\ http
  stats uri /haproxy?stats
  cookie SERVERID insert indirect nocache

  acl fissionurl path_end -i /furl
  use_backend fission if fissionurl

  acl fissionrouter path_end -i /frouter
  use_backend fission_router if fissionrouter	
  
  default_backend my_backend

...

backend fission
  server controller 10.4.60.13:80

backend fission_router
  server router 10.4.21.197:80 
```

But when i try to do `fission env create --name nodejs --image fission/node-env`
I get `Failed to create environment: unexpected end of JSON input`

Where is the problem?
Thanks.

**Comment by soamvasani** [comment]
Hi @VP2405, if you're still facing this problem, can you please use our slack http://slack.fission.io ? I'm @soamv on the slack, @ me there and I'll try to debug it with you.

**Comment by soamvasani** [comment]
Likely an issue with how the fission api is being exposed to the outside world. Please drop by the slack if you're still having this issue. 

(Also, suggested alternative to this setup: use kubectl port-forwarding into the controller pod.)
