### ISSUE TITLE
Fission env create fails silently when image repo inaccessible

### ISSUE THREAD

**Issue by cwbeitel** [fission/fission#368]
Maybe a low priority feature but just wanted to note that if one attempts to create an environment from an image that is not accessible

```bash
fission env create --name myenv --image quay.io/org/inaccessible-image
```
the fission CLI will still say

```bash
environment 'myenv' created
```

without providing feedback that the image could not be pulled.

**Comment by soamvasani** [comment]
Thanks. I agree that this is a bug and we should provide some sort of feedback here.

**Comment by vishal-biyani** [comment]
Duplicate of https://github.com/fission/fission/issues/181 Closing this and will track in 181
