### ISSUE TITLE
Add a README.md and icon for fission charts

### ISSUE THREAD

**Issue by vannrt** [fission/fission#370]
Monocular currently skips charts without a README: https://github.com/kubernetes-helm/monocular/issues/370 

Also, it would be nice to add an icon to the charts. Here's an example chart with an icon:https://github.com/kubernetes/charts/blob/master/stable/artifactory/Chart.yaml

**Comment by sanketsudake** [comment]
This is solved now. https://artifacthub.io/packages/helm/fission-charts/fission-all
