### ISSUE TITLE
Cant deploy on openshift

### ISSUE THREAD

**Issue by karmab** [fission/fission#374]
it's not possible to deploy fission on openshift.
i installed helm there and then run 

```
helm install --namespace fission --set openshift=true https://github.com/fission/fission/releases/download/v0.2.1/fission-core-v0.2.1.tgz
```
but the specific objects ( custom project and sa ) are not used by the fission deployment objects.
i believe those objects overlap anyway as the fission-svc sa should do the job.
yet, when i deploy with openshift==false, all pod except the controller ones go in crashloopback state

```
[root@helm ~]# oc get pod
NAME                          READY     STATUS             RESTARTS   AGE
controller-3987168683-m62qp   1/1       Running            0          31m
kubewatcher-820895975-gm408   0/1       CrashLoopBackOff   10         31m
poolmgr-2834558889-kkbxl      0/1       CrashLoopBackOff   10         31m
router-3693263282-pf8jf       0/1       CrashLoopBackOff   11         31m
timer-3795673973-kpqpx        0/1       Error              11         31m
```

logs of the pod show messages like this one:

```
Failed to get Kubernetes watch trigger list: the server could not find the requested resource (get kuberneteswatchtriggers.fission.io)
````

this initially indicates permission issues but the following command works correctly so issue is not with the SA
```
curl -k -H "Authorization: Bearer `oc sa get-token fission-svc`" https://127.0.0.1:8443/apis/extensions/v1beta1/thirdpartyresources/kuberneteswatchtrigger.fission.io
````

Actually , after a while, my openshift install goes kind of made, since oc run or oc get scc stop to work, giving me 

```
the server doesn't have a resource type "scc"
```

I believe something with the kubewatcher pod  gets in the way and ends up deleting some openshift endpoints

**Comment by karmab** [comment]
for what it s worth, i believe the problem is located in the configureClient in tpr/client.go

**Comment by karmab** [comment]
The issue has to do with third party resources used by fission beeing defined without stable in their name,  for instance , it should be environment.stable.fission.io instead of environment.fission.io

**Comment by soamvasani** [comment]
Thanks for the report, @karmab.

> The issue has to do with third party resources used by fission beeing defined without stable in their name, for instance , it should be environment.stable.fission.io instead of environment.fission.io

I wasn't aware of this constraint on openshift.  Would you mind pointing me at some further reading about it (docs/issues etc)?  Thanks!

**Comment by karmab** [comment]
not sure it s actually a constraint @soamvasani , but rather might be of the underlying kubernetes version in use (1.7.0).
I've opened https://github.com/openshift/origin/issues/16860 to keep track.
do you plan to move to crd, as tpr will be deprecated in kubernetes 1.8?

**Comment by karmab** [comment]
retried this today and worked fine now on openshift 3.7.0 and fission 0.4.0
will open a PR to remove the openshift related stuff in the helm chart
