### ISSUE TITLE
Release fission install YAMLs for users who don't use helm

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#383]
We've gotten occasional feedback from people who aren't using helm for one reason or another.

We should release plain-old-yamls for these users.  We can probably automate it by running `helm --dry-run` in the release script with some sensible defaults.  The user may need to edit the YAMLs for their particular use case, but the released ones would be a good starting point.

**Comment by mingfang** [comment]
+1000000
Please don't make helm a requirement.

**Comment by soamvasani** [comment]
Ok, let's get this into the next release.

**Comment by vishal-biyani** [comment]
For 0.8.0, we will generate and deliver YAMLs as part of release. The work needed for this will be taken up in 0.9.0

**Comment by mingfang** [comment]
@vishal-biyani Thank you!

**Comment by vishal-biyani** [comment]
Closed by #745
