### ISSUE TITLE
Error with Installation Process

### ISSUE THREAD

**Issue by rashoodkhan** [fission/fission#396]
I have Kubernetes 1.8.3 and when running the following line from the installation procedure:
```
$ kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller 
```

Raises the following error:

```
Error from server (Forbidden): clusterrolebindings.rbac.authorization.k8s.io "alice" is forbidden: attempt to grant extra privileges: [{[*] <nil> [*] [*] [] []} {[*] <nil> [] [] [] [*]}] user=&{minikube  [system:authenticated] map[]} ownerrules=[{[create] <nil> [authorization.k8s.io] [selfsubjectaccessreviews] [] []} {[get] <nil> [] [] [] [/version /api /api/* /apis /apis/*]}] ruleResolutionErrors=[]
```

Any help in getting Fission running would be appreciated.

**Comment by life1347** [comment]
Hi @rashoodkhan 
I think the problem is that the current user `alice` does not have permission to set up the cluster role binding. Please try the following command to grant permission: 
```
$ kubectl create clusterrolebinding cluster-admin-binding --clusterrole=cluster-admin --user=alice
```

**Comment by soamvasani** [comment]
BTW, we removed that `create clusterrolebinding` line from newer instructions. It seems helm doesn't need that workaround any more.
