### ISSUE TITLE
0.4.0rc and 0.4.0 don't seem to like routes

### ISSUE THREAD

**Issue by c0dyhi11** [fission/fission#404]
Hello Fission Team,

When I deploy either 0.4.0rc or 0.4.0, I can't create or list routes. I get the following errors:
```
$ fission route create --function fortunewhale --url fortunewhale
Failed to create HTTP trigger: Internal error - no kind "HttptriggerList" is registered for version "fission.io/v1"
```

```
$ fission route list
Failed to list HTTP triggers: Internal error - no kind "HttptriggerList" is registered for version "fission.io/v1"
```

I'm running on kubernetes v1.7.7 using the AWS cloud provider.

Also when I deploy 0.4.0rc or 0.4.0 I notice that the following deployments fail to create in the fission namespace:
```
kubewatcher
mqtrigger
timer
```
I'm deploying using helm via this command:
`helm install --namespace fission https://github.com/fission/fission/releases/download/0.4.0rc/fission-all-0.4.0rc.tgz`
OR
`helm install --namespace fission https://github.com/fission/fission/releases/download/0.4.0/fission-all-0.4.0.tgz`

All of this seems to work properly in 0.3.0

I hope this info helps on the release.

Thank you,
Cody Hill

**Comment by soamvasani** [comment]
Thanks Cody,

For the first one -- do you have the right CLI version? Fission 0.3.0 CLI won't work against 0.4.0. (We do need to make that error message a lot better.)

For the second issue -- could you share some logs from any one of the failed pods?

**Comment by c0dyhi11** [comment]
Hi Soam!

On the first one, yes sir. I've been downloading the correct cli version on each update. 

On the second here are some logs: 
```
kubewatcher:
2017/11/19 07:03:37 Failed to get Kubernetes watch trigger list: no kind "KuberneteswatchtriggerList" is registered for version "fission.io/v1"

mqtrigger
time="2017-11-19T07:04:19Z" level=fatal msg="Failed to read message queue trigger list: no kind "MessagequeuetriggerList" is registered for version "fission.io/v1"" 

timer:
2017/11/19 07:04:29 Failed get time trigger list: no kind "TimetriggerList" is registered for version "fission.io/v1"
```

Thank you,
Cody Hill

**Comment by soamvasani** [comment]
@c0dyhi11 can you upload full logs from the controller pod? (Or email them to me if you don't want them public).

@life1347 can you please take a look? This seems related to the TPR->CRD transition.

**Comment by c0dyhi11** [comment]
Hey Soam,
Very little on the controller pod...
```
time="2017-11-19T07:02:50Z" level=info msg="Server started" port=8888 
10.20.31.0 - - [19/Nov/2017:07:21:54 +0000] "GET / HTTP/1.1" 200 47
```

Thank you,
Cody Hill

**Comment by c0dyhi11** [comment]
Hello @soamvasani and @prithviramesh,

I was able to confirm the following cleared up the issue:

```
helm delete $NAME_OF_FISSION_DEPLOYMENT

kubectl delete namespace fission

kubectl --namespace default get thirdpartyresources| grep -v NAME| grep "fission.io"| awk '{print $1}'|xargs -I@ bash -c "kubectl --namespace default delete thirdpartyresources @" || true

kubectl --namespace default get crd| grep -v NAME| grep "fission.io"| awk '{print $1}'|xargs -I@ bash -c "kubectl --namespace default delete crd @"  || true
```
Thanks for the help from both of you!

Thank you,
Cody Hill

**Comment by CamelCaseNotation** [comment]
The above fix didn't work for me. The controller Pod logs show the server has started, but the router Pod logs show:

`E1121 06:29:49.285947       1 reflector.go:201] github.com/fission/fission/router/httpTriggers.go:204: Failed to list *crd.HTTPTrigger: the server could not find the requested resource (get httptriggers.fission.io)
`
