### ISSUE TITLE
Glide Update breaks fission-bundle compilation 

### ISSUE THREAD

**Issue by prithviramesh** [fission/fission#410]
Updating the nats-streaming-server package to the latest version causes the compilation to fail; the method "IsSubjectValid" in "github.com/nats-io/nats-streaming-server/util" is deprecated and is now called "IsChannelNameValid"

[change made in this commit to nats-streaming-server](https://github.com/nats-io/nats-streaming-server/commit/240a2c024e1ad2abb8387b157693df7fa0a10f00#diff-99f38c7c07bfcc03a528180716bafab5)

https://godoc.org/github.com/nats-io/nats-streaming-server/util

**Comment by life1347** [comment]
thanks @prithviramesh! I pushed a PR to solve this problem.

**Comment by prithviramesh** [comment]
Thanks @life1347 for your prompt solution!

**Comment by erwinvaneyk** [comment]
Fixed in #411
