### ISSUE TITLE
Expose controller proxy/extension configuration

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#412]
Currently we have a couple of extensions to fission that have a proxy in the controller. Unfortunately, these contain hard to change configurations (https://github.com/fission/fission/blob/master/controller/api.go#L56).

As fission is most likely deployed before any extension, we probably want to be able to update these locations at runtime. 

Maybe exposing the environment variables in the deployment as a ConfigMap, but I am not sure if that propagates updates to the ConfigMap to a running controller container. Alternatively, an endpoint could be added to have extensions register themselves.

**Comment by avinilcodes** [comment]
@erwinvaneyk hello, I am willing to contribute, can i take it up?

**Comment by sanketsudake** [comment]
Not targeting this as we have deprecated the controller and making all calls to the Kubernetes API server directly; for other services, we do port forwarding and make calls directly.
