### ISSUE TITLE
Build logs not saved on build error

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#423]
Hey @life1347, it looks like the buildermgr only updates pkg.Status.BuildLogs when the build succeeds -- it should also save them when the build fails (i.e. the build script exits with non-zero exit code)

**Comment by erwinvaneyk** [comment]
Fixed by #426 - @life1347 you can use "fixed <issue>" to automatically close issues on PR merges https://help.github.com/articles/closing-issues-using-keywords/
