### ISSUE TITLE
help Installing local version to minikube

### ISSUE THREAD

**Issue by roei712** [fission/fission#440]
hello everyone,
i've cloned fission-master and made couple of changes to the source code.
how can i install my changed version of fission to my minikube?

**Comment by erwinvaneyk** [comment]
Although this isn't the place to ask these kind of support questions (the [slack channel](http://slack.fission.io/)), you should follow the [development guide](https://github.com/fission/fission/blob/master/Compiling.md) to deploy your custom Fission version.

If you need any further help, hit me (or any of the helpful members) up on the slack channel. :)
