### ISSUE TITLE
Helm delete is not cleaning up 'fission-fission-all' job

### ISSUE THREAD

**Issue by agrahamlincoln** [fission/fission#443]
Issue: When removing Fission via helm, not all resources are cleaned up.

Steps to reproduce:

1. Deploy fission 0.4.0 on k8s 1.7.7 with the following command: 
helm install --namespace fission --name fission https://github.com/fission/fission/releases/download/0.4.0/fission-all-0.4.0.tgz --set serviceType=NodePort
2. Remove fission with:
helm delete --purge fission
3. Find the jobs still present:
kubectl get jobs -n fission
NAME                  DESIRED   SUCCESSFUL   AGE
fission-fission-all   1         1            5m

**Comment by soamvasani** [comment]
Looks like we need to define a `hook-delete-policy` annotation on the post-install job.  This tells helm to delete the job when it's done ([docs here](https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md))
