### ISSUE TITLE
Add build environments to hack/release.sh

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#459]
Currently the build environments aren't included in the release script, which makes them easier to forget. And we do indeed forget to update them:
- [python-builder](https://hub.docker.com/r/fission/python-builder/tags/) is currently at 0.4.0rc
- [go-build-env](https://hub.docker.com/r/fission/go-build-env/tags/) is currently at 20171206-2 or 0.4.3
- [go-builder](https://hub.docker.com/r/fission/go-builder/tags/) is at 1.8.0 (not sure which one is the right image)

All of them lack `latest` tags

Building these images should at least be as automated as the environment images to avoid inconsistent instructions and unexpected behavior.

**Comment by erwinvaneyk** [comment]
The just added `binary builder` (see #452) also needs to be added as well

**Comment by vishal-biyani** [comment]
Hey @erwinvaneyk Looks like this is already fixed by @life1347 as part of #494 and builder images were pushed with version and latest tag to dockerhub 14 days ago. Do you want to confirm?

**Comment by erwinvaneyk** [comment]
Yes it looks fixed - related issue https://github.com/fission/fission/issues/501 isn't yet
