### ISSUE TITLE
Push to fission-chart repository on release

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#460]
Currently there is a manual step in the release process, in which we have to push the helm packages of the new release to the [fission-charts repo](https://github.com/fission/fission-charts). As evident from the missing versions in that repo, it is easy to forget this step.

Proposed solution: automate the pushing of the charts to the fission-charts repo in hack/release

**Comment by sanketsudake** [comment]
This is being done as part of a release process regularly now. Though we need automation or move chart to fission-charts repo.

**Comment by sanketsudake** [comment]
Closing this for now. Not a big to pain to handle as of now. 
Need a better solution though for pushing to charts repo.
