### ISSUE TITLE
NewDeploy backend - update function 

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#465]
The newdeploy backend creates a deployment when a new function is created and deletes a deployment when the function is deleted. The update function implementation is ATM not implemented and has a few scenarios which need to be implemented:

1) Environment associated with the function changes
2) Resource requirements for the function change
3) InvokeStrategy of function is different as compared to earlier

Each of these cases involves replacing the existing deployment and creating a fresh one potentially.

**Comment by soamvasani** [comment]
Also, the actual source/deployment archives in the package may change, as well as the package reference itself.

**Comment by soamvasani** [comment]
I think we should just restart for secrets/configmaps changes.
