### ISSUE TITLE
Test Stabilisation and optimisation

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#472]
The tests have been a little flaky and we need to improve certain things. This issue is a placeholder for all issues devs have faced and  work can be split into multiple PRs potentially.

1) Port binding issues

There are instances where during installation of fission chart, the ports cannot be assigned which causes the build failures. It is not clear if this is the problem or side effect of some other problem but this has been seen multiple times across multiple PR builds.

```
 $ curl http://$FISSION_ROUTER/hello
  Hello, world!
E0113 14:11:02.968228   25185 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:38644: bind: cannot assign requested address
```
Sample failed build: https://travis-ci.org/fission/fission/builds/328236257 

2) Intermittant failures

Some tests fail intermittently - mostly because the operation expected at some time does not finish. Some samples:

https://travis-ci.org/fission/fission/builds/336053006
https://travis-ci.org/fission/fission/builds/335775155

3) Debugging info not available

In some cases, if a helm chart installation takes too long (More than 10 minutes) - the build fails. But this information is not sufficient to solve the probelm. The sample build below for example had a wrong image name and the helm chart installation kept waiting forever for the image to be pulled. But this information is only visible in tiller pod log. If there is a mechanism to tail some of the tiller pod logs into Travis build log, it will be helpful.

https://travis-ci.org/fission/fission/builds/335474547

4) Tiller logs not verbose about issues

In case of (2) above, even tiller logs were not verbose enough. I had to actually go to describe pod and then the problem was found. There could be potentially two ways we could enhance this. One is to increase the verbosity of the tiller in the CI cluster. Another option could be to describe all objects created as part of helm chart installation if there is a failure/timeout.

**Comment by vishal-biyani** [comment]
@life1347 @soamvasani @erwinvaneyk Please add if you see any other cases not covered in issue.

**Comment by soamvasani** [comment]
Thanks Vishal, this is a *great* start.

> E0113 14:11:02.968228   25185 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:38644: bind: cannot assign requested address

I think this error is usually harmless, e.g. from a successful `helm delete`:
```
E0201 13:39:34.135626   32029 portforward.go:212] Unable to create listener: Error listen tcp6 [::1]:45791: bind: cannot assign requested address
release "96ed08" deleted
namespace "f-96ed08" deleted
```

About logs from deleted pods: logs from all pods/all namespaces in the CI cluster are also available in Google Cloud's Stackdriver Logging.  I think it retains them for 2-3 days. I'll send out a link on the slack, that should help a bit with (3) and (4).

**Comment by smruthi2187** [comment]
Adding one more issue here, saw this today:

5. getsockopt : connection refused to the controller pod's PUBLIC IP.
Failed to get function: Get http://35.194.45.105/v2/functions/nodejs-logtest-517307168?namespace=default: dial tcp 35.194.45.105:80: getsockopt: connection refused 
https://travis-ci.org/fission/fission/builds/336329563
