### ISSUE TITLE
pod name hits limit of 63 chars if env name is > 17 chars

### ISSUE THREAD

**Issue by kphatak** [fission/fission#50]
pod name hits limit of 63 chars if env name is greater than 17 chars
may want to drop adding entire uid

`2016/12/09 06:42:23 eager-create pool failed: Deployment.extensions "fission-alpha9-mod-b20e9823-72a8-4cbd-8ecc-d6fbfef8dadb-hxyrtehs" is invalid: [spec.selector.matchLabels: Invalid value: "fission-alpha9-mod-b20e9823-72a8-4cbd-8ecc-d6fbfef8dadb-hxyrtehs": must be no more than 63 characters, spec.selector: Invalid value: {"matchLabels":{"pool":"fission-alpha9-mod-b20e9823-72a8-4cbd-8ecc-d6fbfef8dadb-hxyrtehs"}}: invalid label selector.]`

**Comment by life1347** [comment]
Solved by #975
