### ISSUE TITLE
poolsize environment attribute breaks upgrades

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#506]
The addition of the poolsize attribute to environment spec broke upgrades.  Here's why:

 1. New environment spec has a poolsize attribute
 1. But old environments don't have poolsize defined
 1. Reading old environments into the new env spec yields poolsize equal to zero
 1. Poolsize==0 causes functions using poolmgr to fail 

There's a lot of options on how to fix this:

 * Option 1: Use env versioning -- create a new environment version (3) and only read poolsize when version>=3. 
 * Option 2: Ignore poolsize==0 when functions exist that use poolmgr
 * Option 3: Dispatch functions to newdeploy executor backend when poolsize==0.

Option 1 seems cleanest to think about.

**Comment by vishal-biyani** [comment]
Closed by PR.

**Comment by soamvasani** [comment]
Wouldn't changing int to int* also be a compatiblity-breaking change?

**Comment by life1347** [comment]
yes, so we may need to add another field for this purpose.
