### ISSUE TITLE
Multitenancy part 1: namespacing for resources; narrowing down service account privileges

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#532]
fission function/package/env/trigger CLIs should all accept `--namespace` arguments in addition to the `--name` that they already accept.

**Comment by soamvasani** [comment]
Also ensure that Namespace: in spec YAMLs is correctly applied

**Comment by soamvasani** [comment]
This change is a bit bigger than we expected, because of service accounts/RBAC roles, as well as internal `/fission-function` routes.

**Comment by soamvasani** [comment]
Updated title to reflect what is now the scope of this change

**Comment by vishal-biyani** [comment]
Closing this as #655 is merged. Let's raise a new issue for Part 2 work.
