### ISSUE TITLE
Pod re-use for different functions

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#54]
There are use cases where it's safe to reuse pods for multiple functions.  In fact it's probably more common than cases where it's unsafe to do so.  

This issue is for (a) figuring out the API/UX change, if any, and (b) the implementation for loading and routing to multiple functions per pod.

**Comment by hjianhao** [comment]
I don't think reuse a pod is a good idea. How to clean the file's that last function generated for isolating reason? If you want totally unload last function, then you need to download the function code and start a runtime process again, so it's not worth to reuse a pod.

**Comment by soamvasani** [comment]
Reuse breaks isolation, but isolation isn't always needed -- for example, if the functions are part of the same "app".  In such a case, loading them simultaneously as multiple modules in the same process might work just fine.

**Comment by bgrant0607** [comment]
@soamvasani I commented on related issues here: https://github.com/bitnami/kubeless/issues/148#issuecomment-302222088

**Comment by vishal-biyani** [comment]
Closing this in favor of https://github.com/fission/fission/issues/1888
