### ISSUE TITLE
link to "examples" on docs page returns 404

### ISSUE THREAD

**Issue by kphatak** [fission/fission#549]
page: https://docs.fission.io/0.6.0/
link at the bottom "See the examples directory for more." (https://docs.fission.io/0.6.0/examples)
points to a 404 Page Not Found.

**Comment by vishal-biyani** [comment]
Seems to be working with latest one but had another small issue for which PR raised: https://github.com/fission/docs.fission.io/pull/13 Closing this one as we will track all documentation issues in the docs repo.
