### ISSUE TITLE
Structured logs

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#55]
This issue is for fission logs itself, not function logs; we've been undisciplined about using logrus properly.  We need to go over most log statements and change them to use the WithFields logging method.

**Comment by grounded042** [comment]
@soamvasani is this still something you'd like to see done? If we're still wanting logrus I'm willing to go around and clean up things to use logrus.

**Comment by soamvasani** [comment]
Yes, it would be *great* to have structured logs!  In the meantime [uber/zap](https://github.com/uber-go/zap) has emerged as a good structured logging option too -- it claims to be faster and may be worth switching to before writing a lot of logrus-specific calls.

**Comment by grounded042** [comment]
I'm somewhat familiar with zap as I've used it before. I'll go ahead and start working on getting zap set up and replacing logrus. Feel free to assign this issue to me.

**Comment by soamvasani** [comment]
Awesome, thanks for working on this!

**Comment by grounded042** [comment]
@soamvasani with the PR merge this issue should be done!

**Comment by soamvasani** [comment]
Thanks again for taking on this work, @grounded042! And thanks @vishal-biyani for the all the testing effort and merging.
