### ISSUE TITLE
How to import external golang package?

### ISSUE THREAD

**Issue by xiekeyang** [fission/fission#557]
I write golang function which need import external package, like:

```go
package main

import (
    "net/http"

   “github.com/namespace/project/package”
)

// Handler is the entry point for this fission function
func Handler(w http.ResponseWriter, r *http.Request) {
    msg := package.Message()
    w.Write([]byte(msg))
}
```

Where should I place the external package files, and how to config it in `function-hello.yaml`? Thanks

**Comment by soamvasani** [comment]
Missed this issue when you filed it, @xiekeyang.  Did you figure it out? Anyway, the answer is, you add a custom build script, add it to your source archive, and set `Package.Spec.BuildCommand`.  The build script can be any bash script, it has to build sources from $SRC_PKG and place them in $DEPLOY_PKG.  See the built-in [go build script as an example](https://github.com/fission/fission/blob/master/environments/go/builder/build.sh).

**Comment by xiekeyang** [comment]
@soamvasani Yes I've figured put, and thank you so much!
