### ISSUE TITLE
v2 send code with api

### ISSUE THREAD

**Issue by bahadircivelek** [fission/fission#558]
Hi, how can we send code parametre in v2 with api call ? 
normally in v1 version we could add the code like that;
 `{ metadata: { name: item.name }, environment: { name: item.environment }, code: item.code };`

**Comment by soamvasani** [comment]
The code is in `function.Spec.PackageRef.Package.Source.Literal` (or if it's larger than 256k, it's referenced with a URL and checksum from `function.Spec.PackageRef.Package.Source.URL`)
