### ISSUE TITLE
fission env create CLI overrides user-specified version

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#559]
When the user specifies a builder, we automatically set the environment version = 2.  Which is fine if the user didn't set it, but if the user set it to 3 (or above) we'd end up lowering the version, and losing v3 features, like poolsize.

**Comment by soamvasani** [comment]
@vishal-biyani can you take this one?

**Comment by vishal-biyani** [comment]
@soamvasani Sure will take a look at it.

**Comment by vishal-biyani** [comment]
@soamvasani , I have done changes but two questions:

1) If the builder is set and environment version is not set - we are setting env version to 2. Isn't it better to set it to latest env version (i.e.3)?

2) If builder and env version - both are not set then we are defaulting to env version 1. I think even in this case default to latest version might be better IMO. Thoughts?
