### ISSUE TITLE
Environment builder for Nodejs

### ISSUE THREAD

**Issue by life1347** [fission/fission#565]
Nodejs is popular for the serverless solution, it will be better if we have nodejs env builder.

**Comment by vbmade2000** [comment]
@life1347  In https://raw.githubusercontent.com/fission/fission/master/README.md I see example of nodejs env is supported. Is it something different than what you are asking for ?

**Comment by vbmade2000** [comment]
@vishal-biyani Thanks. I'll check.

**Comment by life1347** [comment]
We have one right now. Close.
