### ISSUE TITLE
Installation issue on GKE

### ISSUE THREAD

**Issue by JoHuang** [fission/fission#566]
I followed instructions

at this step:
`helm install --namespace fission https://github.com/fission/fission/releases/download/0.6.0/fission-all-0.6.0.tgz`

I got `Error: no available release name found`

Please help.
Thanks

**Comment by soamvasani** [comment]
This is a helm setup issue. You have to set up helm with a service account that has enough privileges to install things.  `helm init` does not seem to do this by default, unfortunately.

Try something like this (via [here](https://gist.github.com/mgoodness/bd887830cd5d483446cc4cd3cb7db09d)):
```
helm reset # removes your existing helm server (tiller) install

kubectl -n kube-system create sa tiller
kubectl create clusterrolebinding tiller --clusterrole cluster-admin --serviceaccount=kube-system:tiller
helm init --service-account tiller
```
And then try the `helm install` command again.
