### ISSUE TITLE
Minimize fission-function service account privileges

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#574]

**Comment by sanketsudake** [comment]
We have minimized lot of accesses in 1.18.0-rc2 release. 
https://github.com/fission/fission/blob/main/charts/fission-all/templates/_function-access-role.tpl

We still need to consider how we can get rid of secret/configmap permission given within a namespace to the pod.

**Comment by soharab-ic** [comment]
Please check out latest release `v1.20.4` and reopen if issue still remains.
