### ISSUE TITLE
Go functions can be created, but don't work at all

### ISSUE THREAD

**Issue by clee** [fission/fission#577]
Following the directions in the quickstart guide, I ran:

    helm install --namespace fission --set serviceType=NodePort https://github.com/fission/fission/releases/download/0.6.1/fission-all-0.6.1.tgz
    
    fission env create --name go --image fission/go-env:0.6.1 --builder fission/go-builder:0.6.1
    
    fission function create --name hello --env go --code ./handler.go --entrypoint Handler

My `handler.go` looks like:

```go
package main

import "net/http"

func Handler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("hello world"))
}
```

And when I try to run `fission function test --name hello`, I get:

```
Error calling function hello: 500 Internal server error (fission)
Listening on 8888 ...
Specializing ...
loading plugin from /userfunc/4ca8e021-2f4b-11e8-b4b2-0c6212a58808
2018/03/24 10:08:35 http: panic serving 172.17.0.16:39804: plugin.Open: /userfunc/4ca8e021-2f4b-11e8-b4b2-0c6212a58808: invalid ELF header
goroutine 5 [running]:
net/http.(*conn).serve.func1(0xc420078780)
	/usr/local/go/src/net/http/server.go:1697 +0xd0
panic(0x81a580, 0xc420010b10)
	/usr/local/go/src/runtime/panic.go:491 +0x283
main.loadPlugin(0xc42001a210, 0x2e, 0xc42001c520, 0x7, 0x0)
	/usr/src/github.com/fission/fission/environments/go/server.go:62 +0x61a
main.specializeHandlerV2(0xbf3fe0, 0xc4200121c0, 0xc4200e8400)
	/usr/src/github.com/fission/fission/environments/go/server.go:140 +0x27a
net/http.HandlerFunc.ServeHTTP(0x889948, 0xbf3fe0, 0xc4200121c0, 0xc4200e8400)
	/usr/local/go/src/net/http/server.go:1918 +0x44
net/http.(*ServeMux).ServeHTTP(0xc1eee0, 0xbf3fe0, 0xc4200121c0, 0xc4200e8400)
	/usr/local/go/src/net/http/server.go:2254 +0x130
net/http.serverHandler.ServeHTTP(0xc42006ec30, 0xbf3fe0, 0xc4200121c0, 0xc4200e8400)
	/usr/local/go/src/net/http/server.go:2619 +0xb4
net/http.(*conn).serve(0xc420078780, 0xbf4520, 0xc420058280)
	/usr/local/go/src/net/http/server.go:1801 +0x71d
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2720 +0x288
```

**Comment by soamvasani** [comment]
Hi @clee, 

That command should use `--src`, as follows:
```
fission function create --name hello --env go --src ./handler.go --entrypoint Handler
```

(The behaviour of the `--code` flag is a leftover from before we supported compiled languages. It caused fission to attempt to execute the source file itself, which is why you saw the "invalid ELF header" error.  We'll fix this weird behaviour in a future release.)

**Comment by clee** [comment]
@soamvasani Ahhhh! That's great, thanks for the information. It would be great if the documentation were updated to reflect this. I'll try to submit a PR sometime tonight to at least add some notes to the documentation.
