### ISSUE TITLE
Router starts before CRDs exist and causes test failures

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#585]
This is something which occurs relatively less frequently but I noticed in one of CI builds and needs to be fixed.

The router fails to start properly:
```
k -n f-54ef2f log router-89c87b54-fk9f9
2018/03/28 07:02:09 Starting router at port 8888 E0328 07:02:09.433805     1 reflector.go:201] 
src/github.com/fission/fission/router/httpTriggers.go:217:
Failed to list *crd.HTTPTrigger: the server could not find the requested resource 
(get httptriggers.fission.io)

E0328 07:02:09.445643       1 reflector.go:201] 
src/github.com/fission/fission/router/httpTriggers.go:217: 
Failed to list *crd.Function: the server could not find the requested 
resource (get functions.fission.io)
```
Also confirmed by pod status:
```
Readiness probe failed: Get http://10.52.2.163:8888/router-healthz: net/http: request canceled (Client.Timeout exceeded while awaiting headers)```
```
Strangely enough the pod is still assumed ready:
```
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	True 
  PodScheduled 	True
```
This causes all tests to fail as the router is not reachable. I think this happens when the router starts even before the CRD creation is completed. We should improve liveness probe so that it restarts the router in case of above error.

**Comment by soamvasani** [comment]
Can you please add a link the failed build?

**Comment by soamvasani** [comment]
The reason I'm asking for the failed build, is that this isn't necessarily the cause of any failures.  The controller.Run() runs in a loop (see httpTriggers.go:217), so this error, in theory, should be harmless.  Unless this error continuously appears forever; then that would be a problem. But if it's just the initial few seconds, it's probably not, by itself, the cause of any failures.

**Comment by vishal-biyani** [comment]
I think I restarted the build for that commit and can't locate in Travis anymore. The test log for all tests complained about not able to reach port 8888 though I don't recall entire line. Maybe close this for now and re-open when it appears next?
