### ISSUE TITLE
Error happen when try to run test function.

### ISSUE THREAD

**Issue by pl04351820** [fission/fission#586]
I see this several times. Is this the problem form fission or kubernetes?
Failed to execute HTTP request: Get http://192.168.99.100:31314/fission-function/hello: dial tcp 
192.168.99.100:31314: getsockopt: connection refused

**Comment by life1347** [comment]
Hi @pl04351820 ,
Would you mind to provide more information, such as the kubernetes version & fission version you tested with? But from the IP in the log message, I guess you run fission on minikube. If yes, please try to export the following environment variables. 
```
 $ export FISSION_URL=http://localhost:31313
 $ export FISSION_ROUTER=localhost:31314
```

**Comment by pl04351820** [comment]
Thanks for your reply! @life1347 
My minikube version is v0.25.2
Fission version is v0.6.0

I find the problem seems like 31314 is not the port minikube assign to me.  I find this number in old guidance, but for now, I run following command
```
kubectl -n fission get svc router -o jsonpath='{...nodePort}'
```
and It works!
