### ISSUE TITLE
Add X-Forwarded-For header in router 

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#588]

**Comment by life1347** [comment]
@soamvasani do you have more detail for what this issue for?
Looks like `X-Forwarded-For` is already present in current implementation.
```
---HEADERS---
Connection: close
User-Agent: Go-http-client/1.1
X-Forwarded-For: 172.17.0.1
X-Fission-Function-Resourceversion: 327296
X-Fission-Function-Namespace: default
Accept-Encoding: gzip
Host: 172.17.0.35:8888
X-Fission-Function-Uid: 20d07fca-b588-11e8-88ef-080027c3bbd5
Forwarded: host=192.168.99.100:31314
X-Fission-Function-Name: hv1
X-Forwarded-Host: 192.168.99.100:31314


--BODY--
b''
-----
```

**Comment by life1347** [comment]
Close due to aged. Feel free to reopen it.

**Comment by lionello** [comment]
`X-Forwarded-For` is used to see the IP of the original client (eg. browser) that sent the request, but from the looks of it, the IP that's in the header is from the router? Judging from `Host:`, it's an IP internal to the cluster.
```
X-Forwarded-For: 172.17.0.1
```
