### ISSUE TITLE
Trap aggregation in test scripts

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#606]
Some tests currently call `trap` more than once, but the way `trap` behaves only last one is effective ([Check this for reference](https://unix.stackexchange.com/questions/170409/bash-issuing-trap-twice)). We should have a `cleanup()` function which is called as a trap and does all the cleanup activity.

**Comment by soamvasani** [comment]
I had no idea!  So many of our tests do this 😱

**Comment by life1347** [comment]
Solved by #1128
