### ISSUE TITLE
Intermittently, the request to the executor service IP errors out with a dial tcp i/o timeout

### ISSUE THREAD

**Issue by smruthi2187** [fission/fission#608]
Issue summary : 
We've noticed that in a few of our CI runs, the http post request from router to executor results in a `dial tcp i/o timeout`. 
Sometimes, the failure is at dns name to ip resolution by kube-dns ([sample log](https://api.travis-ci.org/v3/job/359982757/log.txt)). 
At other times, the timeout happens due to tcp connection establishment timeout (hard to tell why exactly because the dial error message doesnt give any more details). 

Solution:
The solution can be just to retry the request from router to executor a couple of times before giving up.
If the problem was indeed due to a glitch in kube-dns, retrying will help us out.

**Comment by life1347** [comment]
Looks like we no longer hitting the same problem, close it.
