### ISSUE TITLE
Is there any way to change resource allocation for FISSION

### ISSUE THREAD

**Issue by pl04351820** [fission/fission#610]
I am trying to find ways to improve the performance on my load test.
Is there any way to change CPU or memory allocation for Fission?

**Comment by vishal-biyani** [comment]
@pl04351820 I am assuming you want to change the resources assigned to function? You can assign resources when creating an environment and override when creating the function, as described here: https://docs.fission.io/0.7.0/usage/environments/#create-an-environment

**Comment by pl04351820** [comment]
Yes, thanks for your fast reply!
