### ISSUE TITLE
Use given environment runtime instead of package's when user specified

### ISSUE THREAD

**Issue by life1347** [fission/fission#617]
If a function is created with an existing package, fission use package's environment runtime directly. 
```
# https://github.com/fission/fission/blob/master/fission/function.go#L161
envName = pkg.Spec.Environment.Name
```
But a use case is that a user may want to run a function with runtime which is different from package's. We should provide a way for users to specify what env runtime a function runs on instead of silently assign.

Code changes:
1. Use environment runtime if it's specified by CLI, use package's otherwise. Fatal if both are empty.
2. `fission pkg --env`: `--env` is only required when user create a package with non-empty source package.

**Comment by soamvasani** [comment]
> But a use case is that a user may want to run a function with runtime which is different from package's

Is this really a valid use case?  Even if it is, suppose for a moment we deprecate the environment ref from function spec.  Then if a user wants the same package in a different env they can duplicate the package object, keeping the Archives the same.

**Comment by life1347** [comment]
I agree it's not a strong use case for now. Close this issue.
