### ISSUE TITLE
Runtime environment for Go should be alpine or scratch

### ISSUE THREAD

**Issue by jgall** [fission/fission#624]
Hi, your current runtime images for go are very large - is there any chance that you could migrate the go runtimes to alpine or scratch so that there is less deployment overhead?

Thanks!

**Comment by jgall** [comment]
A solution to this could be using multistage Dockerfiles (I can't really think of a reason you wouldn't do this other than to support older versions of Docker).

**Comment by jgall** [comment]
I can PR this change in if you'd like.

**Comment by life1347** [comment]
Hi @jgall, PRs are definitely welcome!
It's a good idea to use multistage Dockefile for building the go-env image.
I suggest using `alpine as the base image just like other env, since we may need to go into an env container to do some debug.

**Comment by jgall** [comment]
Sounds good - I'll shoot a PR your way whenever I get around to doing this.
