### ISSUE TITLE
Separate out the kubewatcher service from fission 

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#63]
The `kubewatcher` service is pretty much independent of Fission.  Only the API is dependent on the fission.Watch type, which may as well be a K8s resource; then watchSync.go can be changed to a the usual K8s controller loop instead of watching the Fission API.

This issue will track the work of removing the fission-specific bits and moving to a K8s resource and controller.

**Comment by soharab-ic** [comment]
Closing as respective PR is merged.
