### ISSUE TITLE
How to invoke a function from another function in Fission?

### ISSUE THREAD

**Issue by pl04351820** [fission/fission#634]
Now I am trying to invoke one function from another function (In different pod). Is there any inside mechanism to achieve this?

**Comment by life1347** [comment]
Hi @pl04351820 , a function can access other function with url 
```
http://router.<fission router namespace>/<function>
```
For example, router is in `fission` namespace, and function name is `h1`, then url is 

```
http://router.fission/h1
```

**Comment by erwinvaneyk** [comment]
We might want to add the address of the router to the request header/metadata. With the current approach - the one @life1347 suggested here - we are tightly coupling the function to the specific structure of the Fission deployment.

**Comment by soamvasani** [comment]
We should deprecate those URLs in favor of a properly authenticated and authorized function call API, which is tracked in #632.

**Comment by pl04351820** [comment]
It works.
Thanks for your reply. 
@life1347 @erwinvaneyk @soamvasani
