### ISSUE TITLE
Showing empty while running a pod

### ISSUE THREAD

**Issue by meysam001** [fission/fission#639]
Hi
I'm trying to get a pod : 
```
fission fn list
#NAME  UID                                  ENV    EXECUTORTYPE MINSCALE MAXSCALE TARGETCPU
#hello d86dc291-4523-11e8-9901-ce0dcdd7b986 nodejs poolmgr      0        1        80

fission fn pods --name hello
#NAME
#
```
But It won't show anything. How to get a pod?

fission version:
```
Client Version: {"GitCommit":"0247ea488e7e2f4b23b46ec9757d7b381caccf81","BuildDate":"2018-04-02T22:54:21Z","Version":"0.7.0"}
Server Version: {"GitCommit":"0247ea488e7e2f4b23b46ec9757d7b381caccf81","BuildDate":"2018-04-02T22:54:21Z","Version":"0.7.0"}
```
helm version:
```
Client: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.7.0", GitCommit:"08c1144f5eb3e3b636d9775617287cc26e53dba4", GitTreeState:"clean"}
```
OS (kernel): `Linux srv 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u2 (2017-06-26) x86_64 GNU/Linux`

**Comment by life1347** [comment]
Hi,
The subcommand `fission fn pods` grabs pod information from functions logs. If there is no request it returns the empty list of pods. But this subcommand will be removed in 0.8.0 (not release yet). I suggest using the following command
```
kubectl -n fission-function get pod -l functionName=<fn name>
```

**Comment by vishal-biyani** [comment]
@meysam001 Function pods are cleaned up after an idle duration (Currently 3 minutes). So if you did not invoke a function within the last 3 minutes the function pod will disappear. 

So when there is no executing pod alive, you will see no pods

```
kubectl get pods -n fission-function -l functionName=hello
No resources found.
```
But if you ran a `fn test` command or used route to hit the function, you will see the function pod:

```
kubectl get pods -n fission-function -l functionName=hello
NAME                                                              READY     STATUS    RESTARTS   AGE
nodejs-a899715e-54f6-11e8-b537-42010aa0001f-5nwkvnyy-6d7f8f2twm   2/2       Running   0          2h
```

Lastly, to see the environment pods which are idle and are specialized during function invocation, you can use:

```
kubectl get pods -n fission-function --show-labels=true
```

I am closing this issue, for now, please raise another issue if you run into any other problem.
