### ISSUE TITLE
Ability to init function with some data on volume

### ISSUE THREAD

**Issue by medzin** [fission/fission#640]
**Summary:**
I need to run some code that will pre-download some confidential data for function, preferably once (something similar to k8s init containers). It would be cool if the data could be shared on volume.

**Context:**
I'm looking for a simple way to integrate Vault KV with functions. Using the Secrets API increases the complexity of the solution because it requires the synchronization of data between Kubernetes and Vault and adds the related problems, i.e. potential differences in stored configuration in both services and maintaining additional code. Ability to execute a simple init script adds a powerful integration possibilities.

**Comment by life1347** [comment]
Solved by #1106
