### ISSUE TITLE
Link to install fission is not working

### ISSUE THREAD

**Issue by vbmade2000** [fission/fission#643]
On page [Fission workflows](https://docs.fission.io/0.7.1/workflows/), in `Prerequisites` section `Fission’s installation guide` URL is not working. It points to [https://docs.fission.io/0.7.1/install](https://docs.fission.io/0.7.1/install) which is unavailable.

**Comment by vishal-biyani** [comment]
Fixed by https://github.com/fission/docs.fission.io/pull/24
