### ISSUE TITLE
Support for tolerations on function

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#644]
[Virtual Kubelet](https://github.com/virtual-kubelet/virtual-kubelet) opens up some interesting possibilities for scheduling containers on targets like ACI, Hyper.sh, Fargate etc. One of the things needed for pods to be scheduled on virtual kubelet provider is tolerations that match the provider's taints. Fission should enable tolerations on functions.

There are other aspects too for example what to do with services, HPA etc. but tolerations are a good first starting point.

**Comment by vishal-biyani** [comment]
There could be other use cases too, for example, running certain pods on nodes which have taints for the availability of GPUs

**Comment by life1347** [comment]
Solved with PodSpec. https://docs.fission.io/docs/spec/podspec/toleration/
