### ISSUE TITLE
Function fn update should keep existing resource & scale config

### ISSUE THREAD

**Issue by life1347** [fission/fission#654]
### What happened

https://github.com/fission/fission/blob/dec4a39c152c4706862fafa8c7b1a8853e95ed2f/fission/function.go#L472-L474

Currently, the `fn update` override function's resource & scale config directly even user not specifiy any flag related to the config. We should pass existing configs to functions to prevent this problem.

**Comment by vishal-biyani** [comment]
I will take this up.
