### ISSUE TITLE
Seeing this issue: (Invalid argument - Failed to download url : Get : unsupported protocol scheme "") in executor

### ISSUE THREAD

**Issue by smruthi2187** [fission/fission#659]
When executor tries to specialize a Pod, i notice this print in the executor logs 
(Invalid argument - Failed to download url : Get : unsupported protocol scheme "") 

Looking at the test scenario , my guess is that buildermgr hasnt finished the build yet and the deployment url is empty in the package spec, while fetcher is already trying to download the deploy package with empty url.

I'm yet to try to repro this issue and confirm if this is what is the issue. but one CI run of mine has this issue = https://api.travis-ci.org/v3/job/373173522/log.txt
Look for ""2018/04/30 19:15:53 [func3] calling fetcher to copy function with fetcher url: http://10.52.0.90:8000/"

**Comment by vishal-biyani** [comment]
Hi @smruthi2187 Can this be closed as indicated in PR?

**Comment by vishal-biyani** [comment]
Closing this as PR has been merged.
