### ISSUE TITLE
curl http://$FISSION_ROUTER/hello fail

### ISSUE THREAD

**Issue by sgpennebaker** [fission/fission#671]
`fission function test --name hello` successful, `curl http://$FISSION_ROUTER/hello` fails.  attached zip contains two scripts, `fission-minikube-start.sh` which sets up minikube / fission, and `hello-fission.sh` which runs the hello examples from the fission site.
[hello-fail.zip](https://github.com/fission/fission/files/1980916/hello-fail.zip)

hopefully i just messed up somewhere, thanks in advance.

**Comment by life1347** [comment]
Hi @sgpennebaker , please try with following helm command to install fission

After checking the `fission-minikube-start.sh`, I think the problem is due to nodePort of router service is changed. Please add  `routerServiceType=NodePort` when install fission, this should fix the problem.

```
$ helm install --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/0.7.2/fission-all-0.7.2.tgz
```

**Comment by soamvasani** [comment]
Docs fixed too :)  Thanks for bringing this up @sgpennebaker, and for the fix @life1347 .
