### ISSUE TITLE
Timer trigger doc & CLI 

### ISSUE THREAD

**Issue by life1347** [fission/fission#678]
The cron package fission used supports `Seconds` field. So the correct cron spec would be like

`0 */30 * * * *`

For example, the current time is `2018-04-24 15:01:45 +0800 CST`.

The function will be invoked at

```
2018-04-24 15:30:00 +0800 CST
2018-04-24 16:00:00 +0800 CST
2018-04-24 16:30:00 +0800 CST
2018-04-24 17:00:00 +0800 CST
... and so on
```

`@every 30m` is slightly different from `0 */30 * * * *`

The function will be invoked at

```2018-04-24 15:31:45 +0800 CST
2018-04-24 16:01:45 +0800 CST
2018-04-24 16:31:45 +0800 CST
2018-04-24 17:01:45 +0800 CST
... and so on
```

There are couple works need to be done:
1. Update the document for timer trigger usage.
2. Add a subcommand to CLI that can prints out the next execution time, it should be more easier for user to test/debug.

**Comment by vishal-biyani** [comment]
Closed by #680
