### ISSUE TITLE
Need trace id for log correlation

### ISSUE THREAD

**Issue by life1347** [fission/fission#693]
It will be very helpful if services print out logs with trace id. For example, router attaches a trace id to HTTP header of the request sent to other services, then we can correlate the log with same trace id for debugging. And it will be great for adopting [opentracing](http://opentracing.io/)  as well.

**Comment by jingb** [comment]
yes I have same confusion

**Comment by sanketsudake** [comment]
We have open telemetry support now in the Fission 1.15 release.
We add trace_id in logs in the context of request also `trace_id` is propagated now across Fission components.

We can search across logs with `trace_id`
