### ISSUE TITLE
Error calling function test1: 502 Listening on 8888 ...

### ISSUE THREAD

**Issue by umerm-work** [fission/fission#694]
I created the function using this command 

fission function create --name test1 --env go --src hello.go --entrypoint Handler

when I tested it using
fission fn test --name test1

it gives me **Error calling function test1: 502 Listening on 8888 ...** error

**Comment by soamvasani** [comment]
Hey @umerm-work, sorry you're having trouble. This kind of problem is better handled on our slack: would you please join slack.fission.io and ask there?

**Comment by vishal-biyani** [comment]
Hey @umerm-work closing this for now. If you face trouble again, please reach on slack or raise an issue. Thanks
