### ISSUE TITLE
More robust pod metadata update in poolmgr

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#719]
In #676, pod updates in poolmgr failed.  That occurred because poolmgr modifies the pod metadata by doing a get, a modification, and an update.  This works when the update sends back the same pod except for the metadata change. But because the K8s API had added some stuff to the PodSpec and fission was still using an older client, the client ignored some fields when deserializing the podspec.   When fission send the updated pod back, more than the metadata had changed: the new fields in the api had disappeared.  So the update failed.  We temporarily fixed this by upgrading the client, but this bug will just resurface every time something new is added to the PodSpec.

We need a more robust way to update pod metadata. Since we're only changing metadata, perhaps we don't even need to deserialize the full object.  client-go has the notion of a dynamic client.  Maybe we can use that.

**Comment by life1347** [comment]
We can use PATCH instead of UPDATE to prevent the problem.
