### ISSUE TITLE
Only support code pieces will not ready for production

### ISSUE THREAD

**Issue by hjianhao** [fission/fission#74]
Fission only support code pieces now, I think it's not good enough, because user may need to include the 3rd party libs needed to run the function, so ...

**Comment by soamvasani** [comment]
It supports modules today, but yes, a function is limited to a single file.  The current way to add dependencies is to rebuild the environment image and add it to fission; in practice this is a bit cumbersome initially but works ok. 

We're working on v2 of environments, which will address dependencies better than the current design.  I'll file a bug for that and document what we're doing, in a few days.

(BTW we're pretty clear about fission not yet being ready for production; it says so in the README.)

**Comment by hjianhao** [comment]
Yeah, I had read the README, I know it's on early stage, just think it's import for the real scene. :) 

Dependencies is not the only problem in real scene. User function often need some files that not the libs comes from public repositories. (for example the trans-code table used by function) 

There are two methods to do it. One is package all files in a compressed file and when specialized the Pod, it can download the file and uncompressed it to a specified directory, the user function's entrance file lies on  the root. But this may cost much time for transfer the file without some cache mechanism(It's not easy for serverless on k8s if you do not extend k8s' component)

Another method is to package the user function package to a docker image base on the generic image, using the docker image local cache to improve the file download time,  but it lose the generic pod features and the open-source docker image repositories is poor for delete images.

**Comment by soamvasani** [comment]
There's some ongoing work around environments, which will address this and a lot more. See [/Documentation/wip/environments-v2.md](https://github.com/fission/fission/blob/master/Documentation/wip/environments-v2.md); if you're interested in discussions on this topic please watch that doc or drop by the [slack](http://slack.fission.io).  Closing this issue in favor of moving the discussion over there.
