### ISSUE TITLE
Specialize URL in fetcher error prone

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#758]
The env version check in github.com/fission/fission/environments/fetcher/cmd/main.go can cause an issue for environment versions 3 and higher. It leads to `/specialize` URL if env version is 1 or 3 & higher. Ideally for env versions greater than 2, the URL should be `/v2/specialize`

```
if envVersion == 2 {
        contentType = "application/json"
        specializeURL = "http://localhost:8888/v2/specialize"
        reader = bytes.NewReader([]byte(*loadPayload))
    } else {
        contentType = "text/plain"
        specializeURL = "http://localhost:8888/specialize"
        reader = bytes.NewReader([]byte{})
    }
```

**Comment by thenamly** [comment]
I have just hit this. Just `envVersion >= 2` can be workaround but maybe later versions should have better versioned specialize urls like `/v3/`
