### ISSUE TITLE
Minikube setup doesn't work in China due to firewall

### ISSUE THREAD

**Issue by AaronWo** [fission/fission#76]
When I'm going to create a nodejs environment with tutorial, I get stuck.

`fission env create --name nodejs --image fission/node-env`

There is no response with my terminal. I'm using fission on Mac.

**Comment by soamvasani** [comment]
Did you set $FISSION_URL? Does `fission env list` work?

**Comment by AaronWo** [comment]
Yes, I've set $FISSION_URL
![2017-01-13 10 14 19](https://cloud.githubusercontent.com/assets/4988379/21916113/36767f3e-d979-11e6-9d2c-35cf8efbefa1.png)
Also, I cannot get any response with 'fission env list'.
Minikube has been started already. Is there anything wrong with my operations?

**Comment by soamvasani** [comment]
Sorry you're having trouble with this.  Can you check the status of the fission services and pods?

```
kubectl --namespace fission get services
kubectl --namespace fission get pods
```

Also, can you post the output of `kubectl --namespace fission logs controller-xxx-yyy | tail -50` where `controller-xxx-yyy` is the name of the controller pod from the previous command?  

BTW, if you want quicker help feel free to drop into the slack channel, http://slack.fission.io/

**Comment by AaronWo** [comment]
hi, here is the results for these commands
![2017-01-13 12 09 54](https://cloud.githubusercontent.com/assets/4988379/21918146/453c99b2-d989-11e6-85d7-2024ad4e8972.png)
I cannot get logs from the controller.

**Comment by soamvasani** [comment]
We spoke on slack, we found that `gcr.io` is blocked in China, and so the pause container image can't be pulled, so the pods never come up.

I don't know if there's a good workaround.  There's a github issue kubernetes/minikube#473, but I can't find instructions on exactly how to get around this.

**Comment by soamvasani** [comment]
If you can reach docker hub, try destroying your minikube setup with `minikube delete`, and then try `minikube start --extra-config=kubelet.PodInfraContainerImage=kubernetes/pause`.

**Comment by soamvasani** [comment]
Going to close this, the only useful thing we could do in fission is improve the error; filed issue #78 for that.  @AaronWo please reach out on slack if you still need any help with setup.
