### ISSUE TITLE
Provide an easier way to create archive for pkg

### ISSUE THREAD

**Issue by life1347** [fission/fission#769]
It will be nice to provide additional flags to create archive when creating function/pkg.

Solution 1. Add new flags
```
--sourcearchive value, --src value     Local path or URL for source archive
--deployarchive value, --deploy value  Local path or URL for binary archive
--sourcedir value, --srcdir value     Local path for source directory
--deploydir value, --deploydir value     Local path for deploy directory
```

Solution 2. Change behavior of current flag, and retired some flag alias.
```
--src value     Local path to source directory/archive or URL for source archive
--deploy value  Local path to deployment directory/archive or URL for deployment archive
```

**Comment by erwinvaneyk** [comment]
Agree fully with solving this issue. Though I am a bit worried that we degrade user experience if we keep adding parameters to the command. 

What about allowing users to simply input a directory for `--src` or `--deploy`, and let the CLI handle both cases based on whether the input is a file, glob or a directory?

**Comment by erwinvaneyk** [comment]
`--src hello.go` => build single file
`--src hello.go --src world.go` or `--src *.go` => build package from multiple files
`--src myFnDir/` => build package from directory

**Comment by life1347** [comment]
@erwinvaneyk Oh! You're absolutely right! In this way, we don't need to add more flags to CLI

**Comment by life1347** [comment]
But looks like we need to retire `sourcearchive` and `deployarchive` as well to avoid confusion.

**Comment by life1347** [comment]
Sorry, I missed the thread notification. Originally, I thought that the flag can only accept one parameter, but I noticed we can use `StringSlice` to solve the problem so the constraint I mentioned is no longer exists.

**Comment by vishal-biyani** [comment]
While working on this, I realized a few more cases/variations and I am documenting them here for future reference:

Following variations will work

```
--src hello.go => build single file 
--src hello.go --src world.go or --src "*.go" => build package from multiple files
--src myFnDir/ => build package from directory
--src pkg.zip => Source archive - should work as it works today

--deploy somedir/ => deployment package from a directory
--deploy pkg.zip => Deploy archive - should work as it works today

--src/--deploy http://someurl/somefile.js - this should work but no tests  currently
```

Following is not supported as of now:

```
--src dir1/ --src dir2/ => Multiple directory combinations
--deploy dir1/ --deploy dir2/ => Currently only single flag supported for deploy flag
```

**Comment by life1347** [comment]
Just wondering why `--src dir1/ --src dir2/` is not support.
Won't fetcher extracts them under the same directory like following?
```
. 
├── dir1
└── dir2
```

For example, 

```
kind: ArchiveUploadSpec
name: bank-go-zip
include:
  - "functions/*.go"
  - "functions/vendor"
```

The final directory structure will be:

```
<pkg-dir-name> 
├── *.go
└── vendor
```
