### ISSUE TITLE
Router override request url path

### ISSUE THREAD

**Issue by life1347** [fission/fission#795]
While writing sample application, notice that router override the request to `/` and caused function not be able to get the request path.

For exmaple, if a http trigger's path is `/account/` and when a request to `/account/foo` is sent to the function, the function can only see request path `/` instead of `/account/` nor `/account/foo`.

Root cause: 
https://github.com/fission/fission/blob/cc40d1ed2ec278833f8b07cca65beb8a7baacea7/router/functionHandler.go#L144-L151

The request path is import for RESTful api, I think we should leave it intact.

@smruthi2187 Any thoughs if we remove L150?

**Comment by smruthi2187** [comment]
Wow! I didn't know this. awesome catch!!! did you try out the use-case you pointed out by removing that line and did it work?

**Comment by life1347** [comment]
Yes, it works after removing it.

**Comment by smruthi2187** [comment]
may be we should get @soamvasani 's opinion too before making the change? looking at the comments, he seems to have some ideas for the future.

**Comment by soamvasani** [comment]
The request path is in one of the headers. Functions aren't supposed to care about the http path they were invoked with.  If you want url params you can get them with the X-Fission-Params headers.

**Comment by smruthi2187** [comment]
I see. makes sense.

**Comment by life1347** [comment]
Thanks for explanation Soam! More detailed test information, please visit: https://github.com/fission/fission/issues/796#issuecomment-405513540
