### ISSUE TITLE
Autoscaling for function pods

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#80]
We need a way to autoscale specialized function pods up (and down) based on load.  There are a few possible metrics to scale based upon (CPU usage, latency, queue depth) and there's some design work needed around how these metrics should be tracked, what component should make the autoscaling decision, and so on.

**Comment by seriousme** [comment]
Just came across a page discussing micro scaling which might inspire
http://blog.microscaling.com/2016/04/microscaling-with-nsq-queue.html

**Comment by yqf3139** [comment]
@soamvasani 
K8s [horizontal-pod-autoscaling](https://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/) seems is doing the right job to autoscale the pods based upon (CPU usage) and customed metrics. 

So in 22f8240, seems we are going to scale the pods on our own. I think we can implement it in two ways: one based on autoscaling provided by k8s HPA, which is easier, then we can control the pods number on our own for fine-grained control over pods.

**Comment by soamvasani** [comment]
@yqf3139 agree on those being the options.  With the work on the autoscaling branch both options remain open.  As you say HPA is simpler; we can even plug in our own metrics, such as req/sec.  A good next step would be to come up with a cpu-intensive workload and experiment with HPA on that workload.

**Comment by yqf3139** [comment]
@soamvasani 
Hi, I just started [fission-benchmark](https://github.com/yqf3139/fission-benchmark) to provide benchmark tools and multiple workloads for fission.

I make a simple workload on hello world function. The result is [here](https://github.com/yqf3139/fission-benchmark/blob/master/workloads/helloworld-workload/Result.md).

The result shows under low stress fission performs almost the same as baseline (k8s service as control group). However, under an unlimited qps, 500 request and 30 concurrence, fission returns eight `502` and slowest request is over 50 seconds. So the router seems to be a bottleneck.

I will add more workloads and test fission, k8s service baseline and k8s HPA baseline.

**Comment by Disturbing** [comment]
Any thoughts of using something lightweight like Linkerd to handle the autoscaling + metrics of when to scale/not?

It can be the "man in the middle" if between router <>service, Although would require the router to configure routes with linkerd for this so automatically work.

**Comment by yqf3139** [comment]
Thanks @Disturbing for your suggestions. I am going to take a look at linkerd. The router have to invoke poolmgr to create new instances for cold functions. I am not sure we can simply replace it with linkerd.
For now, we are using k8s service and auto scaling to do the job. The router is then pointed to a service of the target function. The default metric is CPU usage. The next step is to pull metrics collected by Prometheus and use these customized metrics such as QPS, memory usage, message queue length. I will try this method in k8s v1.7.
Router is the bottle neck, but it is stateless so we can scale it once the custom metrics are ready.

**Comment by byndcivilization** [comment]
Hi is there a sense of when this will be ready for release?

**Comment by rore** [comment]
What is the status of handling high scales in Fission? From what I get from this thread, there's quite a limit currently to the number of QPS Fission can handle. Is that still the case?

**Comment by soamvasani** [comment]
Hey folks, 

Thanks for your patience, I know this has been a long standing ask.  We're currently working on function pod autoscaling. Very quick overview of how that's going to work:

 1. FunctionSpec will have parameters on the desired scale
 2. Poolmgr service is renamed to an `executor` service, which is an abstraction with poolmgr as an executor "backend" (PR #384, merged).
 3. Executor will dispatch function requests to a new backend when FunctionSpec needs autoscaling. The "new deploy" backend of executor will create a Deployment, a Service, and a Horizontal Pod Autoscaler (HPA) for the function. This work is being done by @vishal-biyani in PR #387.
 5. That should give us the first cut of working autoscaling.  Then comes benchmarking, beta testing with some real use cases, fine tuning.

**Comment by ajbouh** [comment]
Have you thought about moving fission out of the critical path altogether? I think this is possible by using the nginx ingress's concept of a fallback service. This is a secondary service that requests are sent to if there are no pods in the service that would normally match the incoming request.

This approach would mean that fission machinery is technically only invoked for cold starts. You'd need slightly different bootup and specialization logic for the autoscaling codepath, but I think it would have much cleaner scaling properties.

Thoughts?

**Comment by soamvasani** [comment]
So there's two parts of the fission "machinery" -- router and poolmgr. The poolmgr is the heavier one. We've already removed poolmgr from the critical path in the autoscaling case.  Autoscaling uses the new backend of the executor, and uses the standard Kubernetes HPA.

The router is lightweight, stateless, and so it's quite easy to scale up.  It's also the thing that keeps track of which functions are idle and which aren't. So if we remove the router we have to have something else that tracks that, and exposes it in a way that fission can consume. We're integrating with istio/envoy right now, and maybe the envoy sidecar proxy can handle this for us. Alternatively the runtime environments themselves could handle it, but that's code that has to be written in each language runtime env, which is something we try to avoid.

**Comment by soamvasani** [comment]
We support autoscaling now (since 0.5.0, with improvements in 0.6.0 and future releases).
