### ISSUE TITLE
Improve fidelity of saving HTTP requests/responses in Protobuf message types

### ISSUE THREAD

**Issue by Amusement** [fission/fission#800]
Currently, for record-replay, we save incoming HTTP requests and responses in a custom Protobuf message type that saves only the most important fields needed to replay the request (headers, URL, etc.) Discarding the other fields may be problematic in some cases where users rely on them for their functions. We should improve fidelity by storing and replaying, as close as possible, exactly what was received. 

See the file ``spec.proto`` in the ``redis`` package.

**Comment by ajbouh** [comment]
Where can I learn more about the intended use cases for record-replay?

**Comment by ajbouh** [comment]
This seems neat! We've built something similar for machine learning workloads. Though in our use case, we keep indefinite records of the entire request and entire response. We've also found it valuable to track info about the function that it was first applied to.
