### ISSUE TITLE
Spec experience needs improvement

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#809]
When using `fission spec` if you create a object that depends on another object (For ex. a function depends on an environment) - the message shown on CLI seems like an error to user whereas it might just be warning. This is super confusing to someone new to Fission and needs to be improved.

```
$ fission spec init
Creating fission spec directory 'specs'

$ fission env create --spec --name nodejs --envns default --image fission/node-env
$ fission fn create --spec --name hello --env nodejs --code hello.js
Environment "nodejs" does not exist. Please create the environment before executing the function. 
For example: `fission env create --name nodejs --envns default --image <image>`
```
**HERE** user gets confused and thinks something is broken

```
$ fission route create --spec --method GET --url /gh/hello --function hello
function 'hello' does not exist, use 'fission function create --name hello ...' to create the function

$fission spec apply
$fission fn test --name hello
Hello, Fission!
```

**Comment by soamvasani** [comment]
Yes, thanks for filing this. The validator should check the specs, so these cases are not errors

**Comment by vishal-biyani** [comment]
This is the result of the slack conversation with @pierluigi

**Comment by life1347** [comment]
Found another issue need to be addressed.
```
$ fission fn create --name bank-web --env go --pkg web-pkg --entrypoint WebHanlder --spec
Failed to read package in 'web-pkg' in Namespace: default. Package needs to be present in the same namespace as function: Resource not found - NotFound
```
CLI refuse to create spec file due to package not exists yet, but somehow we just want to generate the spec file only.

**Comment by vishal-biyani** [comment]
@life1347 For the issue you reported, I am going to raise a separate issue - as it is slightly more involved and not same as other two warnings.

**Comment by life1347** [comment]
More issues: https://github.com/fission/fission/issues/951
