### ISSUE TITLE
Heapster to Metric Server switch

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#812]
Currently, Heapster is deployed based on user input to enable HPA for Autoscaling. Heapster is [deprecated in Kubernetes 1.11 and will be removed in 1.13](https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md). Fission needs to switch from Heapster to metric server and test that setup works on a Kubernetes setup.

**Comment by sanketsudake** [comment]
We need to get rid of heapster from helm chart.

**Comment by sanketsudake** [comment]
We have removed Heapster via https://github.com/fission/fission/pull/2256 .  Fission relies on metric-server now.
