### ISSUE TITLE
No flag to expose route via Ingress controller on function creation

### ISSUE THREAD

**Issue by mattroark** [fission/fission#813]
A flag should be added for `fission fn create` such that it allows for the subsequently-created route to be exposed via an Ingress controller, similar to `fission route create [...] --createingress`. 

Presently, by default, an associated route will be created upon specifying the `--url` flag for a function but the route won't be exposed externally. In this scenario, the route would have to be deleted and re-created if the user were to want to expose this endpoint.

**Comment by sanketsudake** [comment]
We have deprecated route creation via `fission fn create` command. Now, we have enabled route/httptrigger creation via `fission route create` command only to avoid maintenance overhead and avoid confusion for user.

Closing this issue.
