### ISSUE TITLE
Fission client for Windows 

### ISSUE THREAD

**Issue by seriousme** [fission/fission#82]
Hi,

The fission.io offers clients for Linux and Mac

Since minikube is available for Windows as well it might be convenient to provide a Windows client as well so people would not need to build one themselves.

I cloned the repo on my Windows machine, installed Go, build the client and it worked like a charm.

If no windows server is available to build one in a CI process then [cross compiling](https://github.com/golang/go/wiki/WindowsCrossCompiling) might be an option.

Cheers,
Hans

**Comment by soamvasani** [comment]
Thanks for testing it on windows!  Yes we should do this.  I've tried cross compiling it: would you mind testing it a bit and confirming that it works?  
```
http://fission.io/windows/fission.exe
```

**Comment by seriousme** [comment]
I tested it a bit and it works (as expected ;-))

To set the environment variables I use:
```
for /f "delims=" %%a in ('minikube ip') do @set minikube_ip=%%a
set FISSION_URL=http://%minikube_ip%:31313
set FISSION_ROUTER=%minikube_ip%:31314
```

Cheers,
Hans

**Comment by soamvasani** [comment]
Awesome, thanks for the env var snippet. I'll include that in instructions for windows.

**Comment by seriousme** [comment]
small addition, I adapted the demo instructions to run on Windows:

```
:: Add the stock NodeJS env to your Fission deployment
fission env create --name nodejs --image fission/node-env

:: A javascript one-liner that prints "hello world"
echo module.exports = function(context, callback) { callback(200, "Hello, world!\n"); } > hello.js

:: Upload your function code to fission
fission function create --name hello --env nodejs --code hello.js

:: Map GET /hello to your new function
fission route create --method GET --url /hello --function hello

:: Run the function in the default browser. This takes about 100msec the first time.
explorer http://%FISSION_ROUTER%/hello
:: Hello, world!
```

Changes: 
- comments use `::` instead of `"`
- `echo` does not use quotes, if you do it will add them to the content in the file
-  `curl` is not available but `explorer` will hand over URL's to the default browser

**Comment by soamvasani** [comment]
Thanks.  Let me just keep this issue open to track adding that to the instructions.
