### ISSUE TITLE
Q: nodejs environment function with packages?

### ISSUE THREAD

**Issue by nea** [fission/fission#826]
Hi

I read that I am able to create a custom node env Docker image and adapt the package.json or server.js. But that would affect the whole image.

Is it also possible to add a package.json to a single function deployment and have that being pulled upfront? I have seen examples for python but no nodejs.

Is it possible to e.g. do something like

```
fission fn create --name helloworld --env node --code hello.js --buildcmd "npm install"
```

or would it be missing the package.json then? Would it be possible to pack it up, deploy and then do the same but with a `--src`  flag?

Thanks a lot in advance

**Comment by nea** [comment]
Got support by @vishal-biyani on Slack. Thanks a lot for that!

**Comment by LyKos4** [comment]
Can you mention the actions that helped you solved your issue?

**Comment by nea** [comment]
Hey @LyKos4 I am sorry, but that is 6 years ago, I don't have any history of that anymore. And it probably works differently now anyways after such a timespan. Best open a question anew.

**Comment by 62316e** [comment]
Any updates on this one?
