### ISSUE TITLE
Use library for parsing time for records time filter

### ISSUE THREAD

**Issue by Amusement** [fission/fission#845]
Currently, to filter records in Redis by time, we define a small set of acceptable ways for the user to format the time interval (integer followed by s,m,h, or d, e.g `--from 90s --to 1m`) and do some custom validation on the input. The parsing/validation involved should be fulfilled by a more reliable library instead. Make sure to update relevant tests after changes. 

Refer to `redis/redisApi.go` and Go's time library.

**Comment by erwinvaneyk** [comment]
Did you try https://golang.org/pkg/time/#ParseDuration? If that is insufficient, could explain what needs to be changed/added specifically? :)

**Comment by Amusement** [comment]
This works, I made a small commit with this change 👍
