### ISSUE TITLE
fission/executor 

### ISSUE THREAD

**Issue by EricYqd** [fission/fission#846]
I want to run one  more  executor，but  i met  502

**Comment by vishal-biyani** [comment]
@EricYqd Can you please provide more info on what steps you followed and the logs and relevant information. Alternatively, please ping us on Slack in general channel and we can help. We are at: http://slack.fission.io/

**Comment by soamvasani** [comment]
The executor isn't currently designed to run multiple instances concurrently.  Can you describe your use case for wanting to run more instances?

**Comment by soamvasani** [comment]
Please feel free to reopen with a little more explanation if you're still convinced this is a bug.
