### ISSUE TITLE
Swagger API spec is incomplete/outdated

### ISSUE THREAD

**Issue by seriousme** [fission/fission#85]
Hi,

I noticed in https://github.com/fission/fission/blob/master/Documentation/Architecture.md that a swagger spec is mentioned.
However api/swagger.json does not exist (anymore ?)

In my view the project would benefit from formally specified API's between the components.
Say one would like to build a fission dashboard then having to go through the Go code to find the URL's is rather cumbersome. Its much easier to generate a javascript client from a swagger spec.

And if you would like to take it even further then its possible to generate a the server stubs, the client stubs and even the command-line client (e.g. using http://swagger.io/tools/ or https://goa.design/ )

Last but not least: formally specifying the API's increase security as it stops invalid inputs early in the process :-)

Cheers,
Hans

**Comment by soamvasani** [comment]
Totally agree with the need for an API spec. I started writing a swagger spec, but didn't finish it.  It's in the `swagger-api-spec` branch.

**Comment by seriousme** [comment]
Some inspiration:

The Apache openWhisk spec can be found  at:
https://github.com/openwhisk/openwhisk/blob/master/core/controller/src/main/resources/whiskswagger.json

Or if you prefer it more visually:
http://petstore.swagger.io/?url=https://raw.githubusercontent.com/openwhisk/openwhisk/master/core/controller/src/main/resources/whiskswagger.json



And the full reference at:
https://github.com/openwhisk/openwhisk/blob/master/docs/reference.md

**Comment by life1347** [comment]
The package`go-restful`, which is also used by kubernetes, that allows us to define RESTful API route and generate swagger.json from the code automatically. Since the controller APIs are stabilized, I put this issue into `1.5` milestone.
