### ISSUE TITLE
Fission spec missing in some commands/subcommands

### ISSUE THREAD

**Issue by vishal-biyani** [fission/fission#851]
Some of the commands do not support spec creation, for example, the package creation:
```
$ fission package create --spec --name test
Incorrect Usage: flag provided but not defined: -spec
```
The workaround for above is to use `--src/--deploy` flags in function creation but it would be nice to directly create specs from the package. 

Also not a big one but update function does not support spec - though I am not sure if that is intended.

**Comment by life1347** [comment]
Solved in 1.7.0. Close.
