### ISSUE TITLE
Binary not found

### ISSUE THREAD

**Issue by lunchboxav** [fission/fission#873]
Hi All,

I'm trying to run the binary example. I've followed the instructions in the example directory, however, every time I tried, I always got the message

`Function error: fork/exec /bin/userfunc: no such file or directory`

This only happens when I want to create function with he binary-env. Node runs fine though. Could it be that the shell script can't be read? Also, how to check that the function have been uploaded to fission? 

I tested this in Ubuntu 18.04 and I'm using GKE.

Thanks

**Comment by life1347** [comment]
Hi @lunchboxav , which example you test with for binary-env?  It worked for me for all example.
```
$ fission fn get --name <fn name>
```
You can get shell code script with command above.

**Comment by lunchboxav** [comment]
Hi @life1347 I used the following command to create the environment:

`fission env create --name binary --image fission/binary-env --builder fission/binary-builder`

I followed the example in https://github.com/fission/fission/tree/master/examples/binary just to run the hello.sh script

**Comment by vishal-biyani** [comment]
Hi @lunchboxav I followed following steps from [this directory]( https://github.com/fission/fission/tree/master/examples/binary) and it seems to work fine. If you still face issues, please reopen or ping us on slack.

```
$ cat hello.sh 
#!/bin/sh

echo "Hello World!"

$ fission env create --name binary-env --image fission/binary-env:0.10.0
environment 'binary-env' created
$ fission fn create --name btest --env binary-env --code hello.sh 
function 'btest' created

$ fission fn test --name btest
Hello World!

$ curl $FISSION_ROUTER/fission-function/btest
Hello World!
```
