### ISSUE TITLE
Support Image pull secrets for environments

### ISSUE THREAD

**Issue by LittleFox94** [fission/fission#874]
When creating a new environment, specifying image pull secrets must be supported.

This is required for any kind of private image, like customized environments with internal code added.

**Comment by morganlogue** [comment]
Figured out a workaround for the issue.  If you add the image pull secret to the fission-fetcher service account it is able to pull environment images from a private repo.

apiVersion: v1
kind: ServiceAccount
  name: fission-fetcher
  namespace: fission-function
imagePullSecrets:
- name: privatereposecret

**Comment by life1347** [comment]
In 1.7.0, you can use `fission env create --imagepullsecret` to add pull secret.
