### ISSUE TITLE
Placeholder method for `spec helm` command?

### ISSUE THREAD

**Issue by philwinder** [fission/fission#881]
I got quite excited when I saw `spec helm` in the cli. But when it didn't seem to do anything, I checked the code.

https://github.com/fission/fission/blob/master/fission/spec.go#L1031

It's mildly annoying to include it in the cli when it doesn't do anything. Like when your parents used to wrap up an empty box for Christmas and think it was funny.

Everything else is great!

**Comment by soamvasani** [comment]
OMG 😂  Sorry for the empty box :)  We'll remove it from the CLI for now.

**Comment by vishal-biyani** [comment]
Closed by #886
