### ISSUE TITLE
go panic when trying to get function logs

### ISSUE THREAD

**Issue by adriandolha** [fission/fission#884]
Hi,
I've created a python3 function and want to read the logs using:
**fission fn logs --name hellopy**
Unfortunately, it fails with the following error:
panic: interface conversion: interface {} is nil, not string

goroutine 13 [running]:
github.com/fission/fission/fission/logdb.InfluxDB.GetLogs(0xc4200140cc, 0x16, 0x0, 0x0, 0xc420163218, 0x8, 0xc420337770, 0x24, 0x0, 0xe7791f700, ...)
        /Users/soam/gopath/src/github.com/fission/fission/fission/logdb/influxdb.go:106 +0xc5e
github.com/fission/fission/fission/logdb.(*InfluxDB).GetLogs(0xc420472fa0, 0x0, 0x0, 0xc420163218, 0x8, 0xc420337770, 0x24, 0x0, 0xe7791f700, 0x1d61820, ...)
        <autogenerated>:1 +0x8f
main.fnLogs.func1(0x0, 0x0, 0xc4203b58c0, 0x1cefaa0, 0xc420472fa0, 0xc4201bfcc0, 0x1cf80e0, 0xc4200180d0, 0xc4200547e0, 0xc420054840)
        /Users/soam/gopath/src/github.com/fission/fission/fission/function.go:428 +0x675
created by main.fnLogs
        /Users/soam/gopath/src/github.com/fission/fission/fission/function.go:417 +0x35f
Am I missing anything?

**Comment by soamvasani** [comment]
Hey @adriandolha, you're not missing something, it looks like a bug in the cli.  Could you tell us which version you're using (run `fission --version`)?

**Comment by adriandolha** [comment]
Hi Soam,
 
I think it is version 0.3.0 running on ubuntu 18.04 with minikube latest, —vm-driver=none

**Comment by soamvasani** [comment]
That is a really old version!  Could you upgrade to something more recent?

**Comment by adriandolha** [comment]
I’m new to fission and was following a turorial which seems outdated. I’ll try a recent version. Is there a recommended version? Or should I just try the latest?

**Comment by soamvasani** [comment]
Ah I see.  Which tutorial, btw?

Yes, latest version would be best, thanks.

**Comment by adriandolha** [comment]
Here's the book:
https://www.safaribooksonline.com/library/view/kubernetes-for-serverless/9781788620376/e18e875b-13ff-4990-bec3-1dddf252e836.xhtml

**Comment by soamvasani** [comment]
Ah, nice, thanks!  Let us know if you have problems with recent versions.
