### ISSUE TITLE
Delete related packages when a function is deleted

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#893]
Currently packages of a deleted function are not deleted. This leads to a lot of unused packages piling up in the CRDs. Since the packages are linked to functions, they don't seem to have a reason to exist on their own (without an associated function). 

If there are (future) reasons for not deleting these, we should add an option to the fn delete command (akin to `--purge` in helm) to let Fission delete all associated packages.

**Comment by life1347** [comment]
The reason for not deleting package is because users may simply try to recreate the function but with the same package. Add option sounds a reasonable&good idea.

**Comment by erwinvaneyk** [comment]
Do we support that right now? How does that work?

**Comment by life1347** [comment]
I mean a user may delete and create a function later with the same package, so its ideal to delete related package automatically. An additional option is better.

**Comment by soamvasani** [comment]
Yes to adding a --delete-package option; it should only delete the package if it is orphaned after the function is deleted (i.e. there are no other functions using the package).

BTW, we have `fission package delete --orphan`, which will delete all orphaned packages.  And orphaned storage artifacts are garbage-collected in the background automatically by the storage svc.
