### ISSUE TITLE
Fission environment for PHP

### ISSUE THREAD

**Issue by dgoujard** [fission/fission#92]
Hi,

It's on the roadmap to add PHP in the environments ? I think it's easy, if it's not in the roadmap i will try to add it.

Thanks

**Comment by Marak** [comment]
@dgoujard -

If you are interested, https://github.com/Stackvana/microcule already has full support for streaming PHP services.

**Comment by soamvasani** [comment]
@dgoujard PHP environments would be awesome!  Nobody I know of is working on them right now -- so go ahead, it's all yours :) Feel free to reach out on [slack](http://slack.fission.io) if you need any help.  The [python environment](https://github.com/fission/fission/tree/master/environments/python3) is a good example to follow.

**Comment by dgoujard** [comment]
@soamvasani Done, i created a pull request https://github.com/fission/fission/pull/97
