### ISSUE TITLE
Change function_call_duration metric to be a histogram instead of a summary

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#920]
For one, summaries return NaN unintuitively: https://github.com/prometheus/prometheus/issues/860

Also, histograms allow querying arbitrary percentiles.  See https://prometheus.io/docs/practices/histograms/#quantiles

**Comment by MikeSpreitzer** [comment]
Even more importantly, histograms can be meaningfully aggregated!  That is, if you have several copies of a controller (e.g., in a ReplicaSet, or a DaemonSet), it is meaningful to add together their histograms.  It is not as meaningful to try to aggregate their Summaries.

**Comment by ng29** [comment]
Hey @vishal-biyani / @MikeSpreitzer 

Some more info on this will be highly appreciated so that i can work on this

**Comment by prithvijit-dasgupta** [comment]
@MikeSpreitzer I have recently faced a similar issue at my work where we had to switch to `histogram_quantiles` in PromOL queries. I see the place where the metric input is to be changed in `metrics.go`

```functionCallDuration = prometheus.NewSummaryVec(
		prometheus.SummaryOpts{
			Name:       "fission_function_duration_seconds",
			Help:       "Runtime duration of the Fission function.",
			Objectives: map[float64]float64{0.5: 0.05, 0.9: 0.01, 0.99: 0.001},
		},
		labelsStrings,
	)```

What should be the buckets for the histogram quantile, if the change is required? Seems a simple fix if @ng29 is not working on it.

**Comment by sanketsudake** [comment]
This metric was removed as part of PR https://github.com/fission/fission/pull/2398
we http requests duration captured instead at different fission service level.
