### ISSUE TITLE
Installation failures on Kubernetes 1.12

### ISSUE THREAD

**Issue by banfger** [fission/fission#922]
Hi, 

I'm not a pro in Kubernetes and stuff, but I got the job in school to try out Fission. The problem is I can't even install it and I don't know what to do. I followed the guide with minikube, and it failed with helm and without helm too. Now I'm trying to install fission on a kubernetes cluster in virtualbox, so I can at least step back too a snapshot and try again.
So now I don't have minikube, I have 1 master Ubuntu, and 2 Ubuntu slaves. 
The kubectl version is:
**Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", **GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}****

### The error message I get is this (without helm):
`kubectl apply -f https://github.com/fission/fission/releases/download/0.11.0/fission-all-0.11.0.yaml`

secret/influxdb created
configmap/fission-all-0.11.0-prometheus-alertmanager created
configmap/fission-all-0.11.0-prometheus-server created
persistentvolumeclaim/fission-all-0.11.0-prometheus-alertmanager created
persistentvolumeclaim/fission-all-0.11.0-prometheus-server created
persistentvolumeclaim/fission-storage-pvc created
serviceaccount/fission-all-0.11.0-prometheus-alertmanager created
serviceaccount/fission-all-0.11.0-prometheus-kube-state-metrics created
serviceaccount/fission-all-0.11.0-prometheus-node-exporter created
serviceaccount/fission-all-0.11.0-prometheus-pushgateway created
serviceaccount/fission-all-0.11.0-prometheus-server created
clusterrole.rbac.authorization.k8s.io/fission-all-0.11.0-prometheus-kube-state-metrics created
clusterrole.rbac.authorization.k8s.io/fission-all-0.11.0-prometheus-server created
clusterrolebinding.rbac.authorization.k8s.io/fission-all-0.11.0-prometheus-kube-state-metrics c                                                                                                               reated
clusterrolebinding.rbac.authorization.k8s.io/fission-all-0.11.0-prometheus-server created
service/redis created
statefulset.apps/redis created
service/router created
service/controller created
service/nats-streaming created
service/storagesvc created
daemonset.extensions/fission-all-0.11.0-prometheus-node-exporter created
deployment.extensions/fission-all-0.11.0-prometheus-alertmanager created
deployment.extensions/fission-all-0.11.0-prometheus-kube-state-metrics created
deployment.extensions/fission-all-0.11.0-prometheus-pushgateway created
deployment.extensions/fission-all-0.11.0-prometheus-server created
job.batch/fission-all-0.11.0-fissi-0.11.0 created
job.batch/fission-all-0.11.0-fissi-0.11.0-488 created
namespace/fission-function created
namespace/fission-builder created
clusterrole.rbac.authorization.k8s.io/secret-configmap-getter created
clusterrole.rbac.authorization.k8s.io/package-getter created
serviceaccount/fission-svc created
rolebinding.rbac.authorization.k8s.io/fission-admin created
clusterrolebinding.rbac.authorization.k8s.io/fission-crd created
serviceaccount/fission-fetcher created
serviceaccount/fission-builder created
deployment.extensions/controller created
deployment.extensions/router created
service/executor created
deployment.extensions/executor created
deployment.extensions/buildermgr created
deployment.extensions/kubewatcher created
service/influxdb created
Error from server (Invalid): error when creating "fission-all-0.11.0.yaml": Service "fission-al                                                                                                               l-0.11.0-prometheus-alertmanager" is invalid: metadata.name: Invalid value: "fission-all-0.11.0                                                                                                               -prometheus-alertmanager": a DNS-1035 label must consist of lower case alphanumeric characters                                                                                                                or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-na                                                                                                               me',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
Error from server (Invalid): error when creating "fission-all-0.11.0.yaml": Service "fission-al                                                                                                               l-0.11.0-prometheus-kube-state-metrics" is invalid: metadata.name: Invalid value: "fission-all-                                                                                                               0.11.0-prometheus-kube-state-metrics": a DNS-1035 label must consist of lower case alphanumeric                                                                                                                characters or '-', start with an alphabetic character, and end with an alphanumeric character                                                                                                                (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
Error from server (Invalid): error when creating "fission-all-0.11.0.yaml": Service "fission-al                                                                                                               l-0.11.0-prometheus-node-exporter" is invalid: metadata.name: Invalid value: "fission-all-0.11.                                                                                                               0-prometheus-node-exporter": a DNS-1035 label must consist of lower case alphanumeric character                                                                                                               s or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-                                                                                                               name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
Error from server (Invalid): error when creating "fission-all-0.11.0.yaml": Service "fission-al                                                                                                               l-0.11.0-prometheus-pushgateway" is invalid: metadata.name: Invalid value: "fission-all-0.11.0-                                                                                                               prometheus-pushgateway": a DNS-1035 label must consist of lower case alphanumeric characters or                                                                                                                '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name                                                                                                               ',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
Error from server (Invalid): error when creating "fission-all-0.11.0.yaml": Service "fission-al                                                                                                               l-0.11.0-prometheus-server" is invalid: metadata.name: Invalid value: "fission-all-0.11.0-prome                                                                                                               theus-server": a DNS-1035 label must consist of lower case alphanumeric characters or '-', star                                                                                                               t with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'ab                                                                                                               c-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
Error from server (Invalid): error when applying patch:
{"metadata":{"annotations":{"helm.sh/hook":"post-upgrade","kubectl.kubernetes.io/last-applied-c                                                                                                               onfiguration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadata\":{\"annotations\":{\"h                                                                                                               elm.sh/hook\":\"post-upgrade\",\"helm.sh/hook-delete-policy\":\"hook-succeeded\"},\"labels\":{\                                                                                                               "app\":\"fission-all\",\"chart\":\"fission-all-0.11.0\",\"release\":\"fission-all-0.11.0\"},\"n                                                                                                               ame\":\"fission-all-0.11.0-fissi-0.11.0\",\"namespace\":\"default\"},\"spec\":{\"template\":{\"                                                                                                               metadata\":{\"annotations\":null,\"labels\":{\"app\":\"fission-all\",\"release\":\"fission-all-                                                                                                               0.11.0\"},\"name\":\"fission-all-0.11.0-fissi\"},\"spec\":{\"containers\":[{\"command\":[\"sh\"                                                                                                               ,\"-c\",\"/usr/bin/curl -m 5 -H \\\"Content-Type: application/json\\\" -X POST -d '{\\\"type\\\                                                                                                               ": \\\"helm-post-upgrade\\\", \\\"chartName\\\": \\\"fission-all\\\", \\\"chartVersion\\\": \\\                                                                                                               "0.11.0\\\"}' https://g.fission.sh/analytics || true\"],\"image\":\"fission/alpinecurl\",\"name                                                                                                               \":\"post-upgrade-job\"}],\"restartPolicy\":\"Never\"}}}}\n"}},"spec":{"template":{"metadata":{                                                                                                               "annotations":null},"spec":{"$setElementOrder/containers":[{"name":"post-upgrade-job"}],"contai                                                                                                               ners":[{"command":["sh","-c","/usr/bin/curl -m 5 -H \"Content-Type: application/json\" -X POST                                                                                                                -d '{\"type\": \"helm-post-upgrade\", \"chartName\": \"fission-all\", \"chartVersion\": \"0.11.                                                                                                               0\"}' https://g.fission.sh/analytics || true"],"image":"fission/alpinecurl","name":"post-upgrad                                                                                                               e-job"},{"$patch":"delete","name":"post-install-job"}]}}}}
to:
Resource: "batch/v1, Resource=jobs", GroupVersionKind: "batch/v1, Kind=Job"
Name: "fission-all-0.11.0-fissi-0.11.0", Namespace: "default"
Object: &{map["kind":"Job" "apiVersion":"batch/v1" "metadata":map["uid":"be4cb4e6-c988-11e8-999                                                                                                               e-080027f8eb0e" "resourceVersion":"42947" "creationTimestamp":"2018-10-06T16:56:18Z" "labels":m                                                                                                               ap["app":"fission-all" "chart":"fission-all-0.11.0" "release":"fission-all-0.11.0"] "annotation                                                                                                               s":map["helm.sh/hook":"post-install" "helm.sh/hook-delete-policy":"hook-succeeded" "kubectl.kub                                                                                                               ernetes.io/last-applied-configuration":"{\"apiVersion\":\"batch/v1\",\"kind\":\"Job\",\"metadat                                                                                                               a\":{\"annotations\":{\"helm.sh/hook\":\"post-install\",\"helm.sh/hook-delete-policy\":\"hook-s                                                                                                               ucceeded\"},\"labels\":{\"app\":\"fission-all\",\"chart\":\"fission-all-0.11.0\",\"release\":\"                                                                                                               fission-all-0.11.0\"},\"name\":\"fission-all-0.11.0-fissi-0.11.0\",\"namespace\":\"default\"},\                                                                                                               "spec\":{\"template\":{\"metadata\":{\"annotations\":null,\"labels\":{\"app\":\"fission-all\",\                                                                                                               "release\":\"fission-all-0.11.0\"},\"name\":\"fission-all-0.11.0-fissi\"},\"spec\":{\"container                                                                                                               s\":[{\"command\":[\"sh\",\"-c\",\"/usr/bin/curl -m 5 -H \\\"Content-Type: application/json\\\"                                                                                                                -X POST -d '{\\\"type\\\": \\\"helm-post-install\\\", \\\"chartName\\\": \\\"fission-all\\\",                                                                                                                \\\"chartVersion\\\": \\\"0.11.0\\\"}' https://g.fission.sh/analytics || true\"],\"image\":\"fi                                                                                                               ssion/alpinecurl\",\"name\":\"post-install-job\"}],\"restartPolicy\":\"Never\"}}}}\n"] "name":"                                                                                                               fission-all-0.11.0-fissi-0.11.0" "namespace":"default" "selfLink":"/apis/batch/v1/namespaces/de                                                                                                               fault/jobs/fission-all-0.11.0-fissi-0.11.0"] "spec":map["parallelism":'\x01' "completions":'\x0                                                                                                               1' "backoffLimit":'\x06' "selector":map["matchLabels":map["controller-uid":"be4cb4e6-c988-11e8-                                                                                                               999e-080027f8eb0e"]] "template":map["metadata":map["name":"fission-all-0.11.0-fissi" "creationT                                                                                                               imestamp":<nil> "labels":map["release":"fission-all-0.11.0" "app":"fission-all" "controller-uid                                                                                                               ":"be4cb4e6-c988-11e8-999e-080027f8eb0e" "job-name":"fission-all-0.11.0-fissi-0.11.0"]] "spec":                                                                                                               map["containers":[map["terminationMessagePolicy":"File" "imagePullPolicy":"Always" "name":"post                                                                                                               -install-job" "image":"fission/alpinecurl" "command":["sh" "-c" "/usr/bin/curl -m 5 -H \"Conten                                                                                                               t-Type: application/json\" -X POST -d '{\"type\": \"helm-post-install\", \"chartName\": \"fissi                                                                                                               on-all\", \"chartVersion\": \"0.11.0\"}' https://g.fission.sh/analytics || true"] "resources":m                                                                                                               ap[] "terminationMessagePath":"/dev/termination-log"]] "restartPolicy":"Never" "terminationGrac                                                                                                               ePeriodSeconds":'\x1e' "dnsPolicy":"ClusterFirst" "securityContext":map[] "schedulerName":"defa                                                                                                               ult-scheduler"]]] "status":map[]]}
for: "fission-all-0.11.0.yaml": Job.batch "fission-all-0.11.0-fissi-0.11.0" is invalid: spec.te                                                                                                               mplate: Invalid value: core.PodTemplateSpec{ObjectMeta:v1.ObjectMeta{Name:"fission-all-0.11.0-f                                                                                                               issi", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, Cr                                                                                                               eationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTi                                                                                                               mestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"co                                                                                                               ntroller-uid":"be4cb4e6-c988-11e8-999e-080027f8eb0e", "job-name":"fission-all-0.11.0-fissi-0.11                                                                                                               .0", "release":"fission-all-0.11.0", "app":"fission-all"}, Annotations:map[string]string(nil),                                                                                                                OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]st                                                                                                               ring(nil), ClusterName:""}, Spec:core.PodSpec{Volumes:[]core.Volume(nil), InitContainers:[]core                                                                                                               .Container(nil), Containers:[]core.Container{core.Container{Name:"post-upgrade-job", Image:"fis                                                                                                               sion/alpinecurl", Command:[]string{"sh", "-c", "/usr/bin/curl -m 5 -H \"Content-Type: applicati                                                                                                               on/json\" -X POST -d '{\"type\": \"helm-post-upgrade\", \"chartName\": \"fission-all\", \"chart                                                                                                               Version\": \"0.11.0\"}' https://g.fission.sh/analytics || true"}, Args:[]string(nil), WorkingDi                                                                                                               r:"", Ports:[]core.ContainerPort(nil), EnvFrom:[]core.EnvFromSource(nil), Env:[]core.EnvVar(nil                                                                                                               ), Resources:core.ResourceRequirements{Limits:core.ResourceList(nil), Requests:core.ResourceLis                                                                                                               t(nil)}, VolumeMounts:[]core.VolumeMount(nil), VolumeDevices:[]core.VolumeDevice(nil), Liveness                                                                                                               Probe:(*core.Probe)(nil), ReadinessProbe:(*core.Probe)(nil), Lifecycle:(*core.Lifecycle)(nil),                                                                                                                TerminationMessagePath:"/dev/termination-log", TerminationMessagePolicy:"File", ImagePullPolicy                                                                                                               :"Always", SecurityContext:(*core.SecurityContext)(nil), Stdin:false, StdinOnce:false, TTY:fals                                                                                                               e}}, RestartPolicy:"Never", TerminationGracePeriodSeconds:(*int64)(0xc429bf17c8), ActiveDeadlin                                                                                                               eSeconds:(*int64)(nil), DNSPolicy:"ClusterFirst", NodeSelector:map[string]string(nil), ServiceA                                                                                                               ccountName:"", AutomountServiceAccountToken:(*bool)(nil), NodeName:"", SecurityContext:(*core.P                                                                                                               odSecurityContext)(0xc42a596930), ImagePullSecrets:[]core.LocalObjectReference(nil), Hostname:"                                                                                                               ", Subdomain:"", Affinity:(*core.Affinity)(nil), SchedulerName:"default-scheduler", Tolerations                                                                                                               :[]core.Toleration(nil), HostAliases:[]core.HostAlias(nil), PriorityClassName:"", Priority:(*in                                                                                                               t32)(nil), DNSConfig:(*core.PodDNSConfig)(nil), ReadinessGates:[]core.PodReadinessGate(nil), Ru                                                                                                               ntimeClassName:(*string)(nil)}}: field is immutable
error validating "fission-all-0.11.0.yaml": error validating data: ValidationError(DaemonSet):                                                                                                                unknown field "---apiVersion" in io.k8s.api.extensions.v1beta1.DaemonSet; if you choose to igno                                                                                                               re these errors, turn validation off with --validate=false

### And with helm:
`helm install --name fission --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/0.11.0/fission-all-0.11.0.tgz`

Error: error validating "": error validating data: field spec.dataSource for v1.PersistentVolumeClaimSpec is required

**Comment by soamvasani** [comment]
Looks like there are two separate bugs here:

 1. On 1.12 it looks like our PersistentVolumeClaimSpec is somehow invalid
 2. Our `helm template` generated YAMLs are invalid because they stick the version number into the chart name, which makes the service names invalid.

We'll treat this as pretty high priority, but for now @banfger you could work around by using helm and trying this on Kubernetes 1.11.  Feel free to reach out on slack.fission.io if you need help with either of those things :)

**Comment by banfger** [comment]
With this version I got the same error with simple kubectl apply, but with helm I could install it succesfully, thanks.
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.2", GitCommit:"bb9ffb1654d4a729bb4cec18ff088eacc153c239", GitTreeState:"clean", BuildDate:"2018-08-07T23:17:28Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T17:53:03Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by thienly** [comment]
do you have any update?

**Comment by soamvasani** [comment]
I was able to reproduce the failure on Kuberenetes 1.12 with Helm 2.7.  But then I upgraded to Helm 2.11 and the install worked.  Not quite sure what changed in helm.  I'll investigate some more.

**Comment by PLoecker** [comment]
I got the same error. 
When I use the helm installation I get a timeout for the condition.
![image](https://user-images.githubusercontent.com/11966379/47100430-bf573d80-d237-11e8-90b3-ae16ae3b4323.png)

With the yaml file, I get the same message like banfger.

I use a Kuberenetes cluster with 3 workers and 1 master.
kube version: 1.12.1
helm version:
  Client: 2.11
  Server: 2.11

I tried the fission-version 0.11 and 0.10. Same results.
Change the version of Kuberenetes is not really an option for me.

**Comment by soamvasani** [comment]
@PLoecker would you mind running that same command again with the `--debug` flag to helm, and pasting the output here?

**Comment by PLoecker** [comment]
@soamvasani, unfortunately, the same result. I have a checkpoint of a basic Kubernetes-cluster setup which I always reset before I start a new trial. So there are no leftover jobs.
Here the debug-logs:
![image](https://user-images.githubusercontent.com/11966379/47141510-253bd780-d2c1-11e8-91d9-6b680bb159fe.png)

**Comment by PLoecker** [comment]
@soamvasani, I found the problem. We found an internal network routing problem. This problem caused a low data transfer, which caused the timeout. Because the cluster is running in a separated network, I didn't realize the low data transfer.
Thanks for your support!

**Comment by soamvasani** [comment]
Thanks for the update @PLoecker.

That leaves this bug with only PR #939 and a doc update to use a newer helm version.

**Comment by soamvasani** [comment]
The [doc update is done too](https://github.com/fission/docs.fission.io/commit/b46ab66ba9896cda832e5cf387a861195830b1b3).

**Comment by jackie-onai** [comment]
encountering this exception during installation:

```
helm install --name fission --namespace fission --set serviceType=NodePort,routerServiceType=NodePort https://github.com/fission/fission/releases/download/1.4.1/fission-all-1.4.1.tgz --debug
[debug] Created tunnel using local port: '61790'

[debug] SERVER: "127.0.0.1:61790"

[debug] Original chart version: ""
[debug] Fetched https://github.com/fission/fission/releases/download/1.4.1/fission-all-1.4.1.tgz to /Users/jackie/.helm/cache/archive/fission-all-1.4.1.tgz

[debug] CHART PATH: /Users/jackie/.helm/cache/archive/fission-all-1.4.1.tgz

Error: validation failed: [unable to recognize "": no matches for kind "DaemonSet" in version "extensions/v1beta1", unable to recognize "": no matches for kind "Deployment" in version "extensions/v1beta1", unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"]
```

**Comment by life1347** [comment]
@jackie-onai what kubernetes version you tested with?
