### ISSUE TITLE
Add option to list functions in all namespaces 

### ISSUE THREAD

**Issue by erwinvaneyk** [fission/fission#924]
Currently, `fission function list` lists only the functions in the default namespace. To view function in a different namespace the user has to provide the ns `fission function list --fns my_ns`. However there is no option akin to kubernetes `--all-namespaces`.

1) For discoverability, it would help to have such an option, like `all-namespaces`

2) In combination with (1) it might also be useful to show the namespace of the function `my_ns/text2speech`. We can do this by default, or we can add a parameter for this.

**Comment by neha-Gupta1** [comment]
Added `--all-namespaces` flag. Added namespace info in list results.
![listoutput](https://user-images.githubusercontent.com/23420056/199404432-09d552f6-cd36-4129-af84-9c5bd52e5e35.png)
