### ISSUE TITLE
Updating environment doesn't update function deployment when using newdeploy

### ISSUE THREAD

**Issue by soamvasani** [fission/fission#929]
Updating an env should cause any existing functions deployed on the old env to be re-deployed onto the new ones, within some reasonable amount of time.

**Comment by vishal-biyani** [comment]
Hi, @soamvasani I noticed that even for pool manager if a function is already unmanaged/ specialized - then it points to the old version of the image even after updating the environment.  Do we want to consider that as part of change too?

**Comment by soamvasani** [comment]
With minscale the problem is that the function pod is more permanent... Poolmgr pods usually recycle at some point. But yes the problem does exist in both backends. I wonder if we could just kill the pod? Then the solution would be same for both backends?  Router already has retries for the case where the pod is dead.
