### ISSUE TITLE
Build Error: (pip) Target path exists but is not a directory

### ISSUE THREAD

**Issue by cmattoon** [fission/fission#949]
I was following the docs [here](https://docs.fission.io/0.11.0/usage/developer-workflow/) and got to `fission spec apply --wait` before getting the following error:
```
--- Build FAILED: ---
Error building deployment package: Internal error - {"artifactFilename":"calc-py-srak-xrdlti-vfjfpd","buildLogs":"ERROR: Target path exists but is not a directory, will not continue.\nYou are using pip version 18.0, however version 18.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\nError building source package: Error waiting for cmd 'build': exit status 1\n"}

------
--- Build FAILED: ---
Error building deployment package: Internal error - {"artifactFilename":"form-py-bex2-bfq1w7-7o7aky","buildLogs":"ERROR: Target path exists but is not a directory, will not continue.\nYou are using pip version 18.0, however version 18.1 is available.\nYou should consider upgrading via the 'pip install --upgrade pip' command.\nError building source package: Error waiting for cmd 'build': exit status 1\n"}
```
Which, at its core, appears to be a pip error:

```
ERROR: Target path exists but is not a directory, will not continue.
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Logs from the environment builder Pod can be found [here](https://pastebin.com/ecYgdwrN).

Version info:
```
fission --version
client:
  fission/core:
    gitcommit: 9129758f990d9a09e22388c9233c1902a63be51b
    builddate: 2018-10-01T17:05:58Z
    version: 0.11.0
server:
  fission/core:
    gitcommit: 9129758f990d9a09e22388c9233c1902a63be51b
    builddate: 2018-10-01T17:05:58Z
    version: 0.11.0
```

 Initially, I thought it might have been missing values for `SRC_PKG` and `DEPLOY_PKG`, but the logs have values for them.  I've tried using Docker tags `0.11.0` and `latest`. Both give me the same error. 

Any ideas?

**Comment by life1347** [comment]
@cmattoon Thanks for reporting!

I'm able to reproduce the same problem at my local machine.  Here are workaround to solve the problem.

```
$ mkdir fncode
$ mv *.py fncode
$ touch fncode/__init__.py
$ zip -jr demo-src-pkg.zip fncode/

$ fission function create --spec --name calc-eval --env python --deploy python-pkg-zip --entrypoint calc.main
$ fission function create --spec --name calc-form --env python --deploy python-pkg-zip --entrypoint form.main
```

If `fission spec validate` shows following error, please remove the duplicate `ArchiveUploadSpec` in `function-calc-eval.yaml` manually. (bug in `spec` command)
```
Failed to read specs: 1 error occurred:
	* specs/function-calc-form.yaml:1: Duplicate ArchiveUploadSpec 'python-pkg-zip', first defined in specs/function-calc-eval.yaml:1
```

And run `fission spec apply --wait` again.

We will update the document and fix bugs in spec command. Thanks

**Comment by cmattoon** [comment]
That worked, thanks! 

Does this mean the code just has to be in a module/package to use spec?

**Comment by life1347** [comment]
It depends. 
If your code has only one single python file & your env doesn't contain builder image, then you don't need to do that.

For example:
```
$ fission spec init
$ fission env create --spec --name python --image fission/python-env:0.11.0
$ fission fn create --spec --name py1 --env python --code form.py
$ fission route create --spec --method GET --url "/py1" --function py1
$ fission spec apply
$ fission fn test --name py1
```

I believe the reason for docs to create env with `--builder` is because there is a section `Add dependencies to the function`. And for most cases we will want to import 3rd party dependencies, for such situation the answer is yes we need to put code in a module like what we've done above.

**Comment by life1347** [comment]
@soamvasani would you mind taking a look at docs (https://docs.fission.io/0.11.0/usage/developer-workflow/) and revise it? Thanks

**Comment by serain** [comment]
@life1347 is this a typo, you zip `demo-src-pkg.zip` and then in the create function you put `--deploy python-pkg-zip`.

I'm also having problems getting specs working at all. Manually it all works smoothly.

**Comment by life1347** [comment]
oops @serain you’re right. it should be “demo-src-pkg.zip”

**Comment by life1347** [comment]
solved by fission/docs.fission.io#93
