### ISSUE TITLE
Router should reply meaningful message back to CLI when encountering environment error

### ISSUE THREAD

**Issue by life1347** [fission/fission#952]
If an environment is not ready, then executor may not be able to reply message to the router before timeout. Router will send following error message to the client which make no sense to them. We should provide more useful messages instead.

```
$ fission fn test --name calc-form
Error calling function calc-form: 500 Post http://executor.fission/v2/getServiceForFunction: dial tcp: i/o timeoutFailed to parse the base URL: parse 192.168.99.100:31313: first path segment in URL cannot contain colon
```

**Comment by life1347** [comment]
Possible solutions
1. Executor return retry status code and client should retry again
2. Check env is ready before sending requests.

**Comment by soamvasani** [comment]
@life1347 both sound like good things to do, I'd vote for doing (1) first.

**Comment by vishal-biyani** [comment]
Hi @life1347 

As of now at least I can't see same errors that are filed in the issue. I gave a wrong image for environment to reproduce the issue. I get errors which are more verbose describeing the issue in detail:

With new deployment executor
```
$ fission fn test --name pyfunc
Error calling function pyfunc: 500 Error updating service address entry for function pyfunc_default: Internal error - [pyfunc] Error creating service for function: error creating deployment pyfunc-newdeploy-default: failed to create deployment within timeout window
```

With pool manager executor
```
$ fission fn test --name pyfunc
Error calling function pyfunc: 500 Error updating service address entry for function pyfunc_default: Internal error - [pyfunc] Error creating service for function: Timeout: waited too long for pod of deployment python-poolmgr-default in namespace fission-function to be ready
```

**Comment by soamvasani** [comment]
Updating the issue from our zoom conversation -- though the error is detailed it doesn't help the user understand that (a) the image is not yet downloaded and (b) that a retry may work.  Also it would be good to have automated retries in `fission fn test` with some reasonable limits.

Here's an example of someone encountering this error-- https://medium.com/@bluszcz/serverless-microk8s-kubernetes-fcd6b875cd33 -- I'm not sure it's the same error, but retries might have helped in that case too.

**Comment by vishal-biyani** [comment]
This needs to be moved out of 1.0-RC2
