### ISSUE TITLE
How can I pass parameter in python? 

### ISSUE THREAD

**Issue by justinbuzzni** [fission/fission#962]
I can not find the documents.

I want to pass parameter when I calling the python function.

**Comment by justinbuzzni** [comment]
I find the solution 
https://tachingchen.com/blog/how-to-develop-a-serverless-application-with-fission-pt-2/

**Comment by life1347** [comment]
Hi @justinbuzzni 
In fact, there is a PR for how to access url params. I just merged it. 
You can check it here: https://docs.fission.io/0.12.0/usage/accessing-url-params/
