### ISSUE TITLE
Annotations on route Ingress

### ISSUE THREAD

**Issue by mitchellmaler** [fission/fission#989]
Currently we use cert-manager and externaldns operator for our nginx ingress which is setup by annotations. I am unable to find a way to specify extra ingress annotations when I create a route with the createingress option.

**Comment by vishal-biyani** [comment]
Hi, @mitchellmaler currently you can't add annotations to ingress created by route creation. I would like to understand a bit more about how many annotations you use and general use case details. We could potentially consider this in one of the upcoming releases.

**Comment by mitchellmaler** [comment]
@vishal-biyani Currently we use two annotation. One for cert manager which will automatically get a ssl certificate for the ingress and save it to the specified tls secret in the ingress spec. The other is for using the external-dns operator to provide it with the A Record to create. 

Initially it would be nice if these annotations could be passed to the route command. Then maybe would be even better to create defaults for all routes that are created so it wouldn't always need to be passed unless it needs customized from the defaults.

**Comment by vishal-biyani** [comment]
Design and initial thoughts have been added here: https://github.com/fission/fission/blob/master/Documentation/wip/annotations_design.md @mitchellmaler If you would like to do a PR, I would be happy to walk you through it.

**Comment by laurence-hudson-mindfoundry** [comment]
+1 to this idea. I have a use case around the `nginx.ingress.kubernetes.io/whitelist-source-range` annotation.
