### ISSUE TITLE
Limit resource usage per function

### ISSUE THREAD

**Issue by lfundaro** [fission/fission#99]
One should be able to limit resource usage (cpu, ram, etc) for a given function. This could be possibly specify through the CLI

**Comment by yqf3139** [comment]
@soamvasani 
This issue is related to auto scaling, because if it is auto scaled by k8s, we need to provide a resource limit.

Once the pod is created, the resource requests and limitations are mutable. A simple idea is that we set a limitations for the specific environment.

**Comment by soamvasani** [comment]
Fixed by #387 (FunctionSpec.Resources)
