### ISSUE TITLE
Make helm chart work for cluster without RBAC enabled

### ISSUE THREAD

**Issue by jPrest** [fission/fission#993]
The chart cannot be installed on clusters without RBAC, because the install fails when helm tries to create the RBAC objects. We can add a flag rbac.enabled=true|false in values.yaml to make the chart usable on these clusters aswell.

**Comment by sanketsudake** [comment]
RBAC is pretty standard in Kubernetes now. I am not sure if we have the bandwidth to support Fission install without RBAC.

I am closing this issue for now, as a quite an old issue and Kubernetes moved a lot of ground since then.

If you still see the need for this, feel free to reopen the issue.
