### ISSUE TITLE
Following the Development Workflow docs verbatim does not produce a working example

### ISSUE THREAD

**Issue by serain** [fission/fission#997]
The documentation for [Source Code Organization and Your Development Workflow](https://docs.fission.io/0.12.0/usage/developer-workflow/) does not produce a working example.

* There are no valid URLs for the `form.py` and `calc.py` that the docs propose fetching
* The `calc.py` snippet lacks `from flask import request`
* Following the tutorial verbatim up to `Apply: deploy your functions to Fission` produces the following output:

```$ fission spec apply --wait
1 environment created: python
2 packages created: calc-py-58se, form-py-yijo
2 functions created: calc-eval, calc-form
2 HTTPTriggers created: 741c000b-5d20-4e8f-8ac2-f6bd680c9c43, e38b7667-ee72-4b0f-b840-784504ba984f
--- Build FAILED: ---
Build timeout due to environment builder not ready
------
--- Build FAILED: ---
Build timeout due to environment builder not ready
------
```

This is one of the key documents to get right for people to actually start using Fission for their projects. It would be helpful to have a working version of this document.

**Comment by vishal-biyani** [comment]
Fix here: https://github.com/fission/docs.fission.io/pull/93

**Comment by life1347** [comment]
Please take a look at here before the docs commit merged: https://github.com/fission/fission/issues/949
